
/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file BookAttrTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using LibraryManagement.Domain;
using LibraryManagement.Dao;
using LibraryManagement.Dao.Bases;

#endregion

namespace LibraryManagement.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="BookAttr"/> objects (entity, collection and repository).
    /// </summary>
   public partial class BookAttrTest
    {
    	// the BookAttr instance used to test the repository.
		protected BookAttr mock;
		
		// the TList<BookAttr> instance used to test the repository.
		protected TList<BookAttr> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the BookAttr Entity with the {0} --", LibraryManagement.Dao.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock BookAttr entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.BookAttrProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.BookAttrProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all BookAttr objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.BookAttrProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.BookAttrProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.BookAttrProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all BookAttr children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.BookAttrProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.BookAttrProvider.DeepLoading += new EntityProviderBaseCore<BookAttr, BookAttrKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.BookAttrProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("BookAttr instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.BookAttrProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock BookAttr entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				BookAttr mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.BookAttrProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.BookAttrProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.BookAttrProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock BookAttr entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (BookAttr)CreateMockInstance(tm);
				DataRepository.BookAttrProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.BookAttrProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.BookAttrProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock BookAttr entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_BookAttr.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock BookAttr entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_BookAttr.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<BookAttr>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a BookAttr collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_BookAttrCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<BookAttr> mockCollection = new TList<BookAttr>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<BookAttr> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a BookAttr collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_BookAttrCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<BookAttr>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<BookAttr> mockCollection = (TList<BookAttr>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<BookAttr> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				BookAttr entity = CreateMockInstance(tm);
				bool result = DataRepository.BookAttrProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				BookAttr entity = CreateMockInstance(tm);
				bool result = DataRepository.BookAttrProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				BookAttr t0 = DataRepository.BookAttrProvider.GetByGoodsId(tm, entity.GoodsId);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				BookAttr entity = mock.Copy() as BookAttr;
				entity = (BookAttr)mock.Clone();
				Assert.IsTrue(BookAttr.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				BookAttr mock = CreateMockInstance(tm);
				bool result = DataRepository.BookAttrProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				BookAttrQuery query = new BookAttrQuery();
			
				query.AppendEquals(BookAttrColumn.GoodsId, mock.GoodsId.ToString());
				query.AppendEquals(BookAttrColumn.Author, mock.Author.ToString());
				query.AppendEquals(BookAttrColumn.Publish, mock.Publish.ToString());
				query.AppendEquals(BookAttrColumn.Translator, mock.Translator.ToString());
				query.AppendEquals(BookAttrColumn.FormType, mock.FormType.ToString());
				query.AppendEquals(BookAttrColumn.Language, mock.Language.ToString());
				query.AppendEquals(BookAttrColumn.PlMonth, mock.PlMonth.ToString());
				query.AppendEquals(BookAttrColumn.PlYear, mock.PlYear.ToString());
				query.AppendEquals(BookAttrColumn.Dimension, mock.Dimension.ToString());
				query.AppendEquals(BookAttrColumn.Weight, mock.Weight.ToString());
				query.AppendEquals(BookAttrColumn.Pages, mock.Pages.ToString());
				query.AppendEquals(BookAttrColumn.Introinfo, mock.Introinfo.ToString());
				
				TList<BookAttr> results = DataRepository.BookAttrProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed BookAttr Entity with mock values.
		///</summary>
		static public BookAttr CreateMockInstance_Generated(TransactionManager tm)
		{		
			BookAttr mock = new BookAttr();
						
			mock.GoodsId = TestUtility.Instance.RandomString(6, false);;
			mock.Author = TestUtility.Instance.RandomString(99, false);;
			mock.Publish = TestUtility.Instance.RandomString(99, false);;
			mock.Translator = TestUtility.Instance.RandomString(99, false);;
			mock.FormType = TestUtility.Instance.RandomNumber();
			mock.Language = TestUtility.Instance.RandomNumber();
			mock.PlMonth = TestUtility.Instance.RandomNumber();
			mock.PlYear = TestUtility.Instance.RandomNumber();
			mock.Dimension = TestUtility.Instance.RandomString(49, false);;
			mock.Weight = TestUtility.Instance.RandomNumber();
			mock.Pages = TestUtility.Instance.RandomNumber();
			mock.Introinfo = TestUtility.Instance.RandomString(499, false);;
			
		
			// create a temporary collection and add the item to it
			TList<BookAttr> tempMockCollection = new TList<BookAttr>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (BookAttr)mock;
		}
		
		
		///<summary>
		///  Update the Typed BookAttr Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, BookAttr mock)
		{
			mock.Author = TestUtility.Instance.RandomString(99, false);;
			mock.Publish = TestUtility.Instance.RandomString(99, false);;
			mock.Translator = TestUtility.Instance.RandomString(99, false);;
			mock.FormType = TestUtility.Instance.RandomNumber();
			mock.Language = TestUtility.Instance.RandomNumber();
			mock.PlMonth = TestUtility.Instance.RandomNumber();
			mock.PlYear = TestUtility.Instance.RandomNumber();
			mock.Dimension = TestUtility.Instance.RandomString(49, false);;
			mock.Weight = TestUtility.Instance.RandomNumber();
			mock.Pages = TestUtility.Instance.RandomNumber();
			mock.Introinfo = TestUtility.Instance.RandomString(499, false);;
			
		}
		#endregion
    }
}
