
/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file MofSysTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using LibraryManagement.Domain;
using LibraryManagement.Dao;
using LibraryManagement.Dao.Bases;

#endregion

namespace LibraryManagement.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="MofSys"/> objects (entity, collection and repository).
    /// </summary>
   public partial class MofSysTest
    {
    	// the MofSys instance used to test the repository.
		protected MofSys mock;
		
		// the TList<MofSys> instance used to test the repository.
		protected TList<MofSys> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the MofSys Entity with the {0} --", LibraryManagement.Dao.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock MofSys entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.MofSysProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.MofSysProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all MofSys objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.MofSysProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.MofSysProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.MofSysProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all MofSys children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.MofSysProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.MofSysProvider.DeepLoading += new EntityProviderBaseCore<MofSys, MofSysKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.MofSysProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("MofSys instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.MofSysProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock MofSys entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MofSys mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.MofSysProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.MofSysProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.MofSysProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock MofSys entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (MofSys)CreateMockInstance(tm);
				DataRepository.MofSysProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.MofSysProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.MofSysProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock MofSys entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MofSys.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock MofSys entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MofSys.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<MofSys>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a MofSys collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MofSysCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<MofSys> mockCollection = new TList<MofSys>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<MofSys> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a MofSys collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_MofSysCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<MofSys>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<MofSys> mockCollection = (TList<MofSys>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<MofSys> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MofSys entity = CreateMockInstance(tm);
				bool result = DataRepository.MofSysProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				MofSys entity = CreateMockInstance(tm);
				bool result = DataRepository.MofSysProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				MofSys t0 = DataRepository.MofSysProvider.GetById(tm, entity.Id);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				MofSys entity = mock.Copy() as MofSys;
				entity = (MofSys)mock.Clone();
				Assert.IsTrue(MofSys.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				MofSys mock = CreateMockInstance(tm);
				bool result = DataRepository.MofSysProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				MofSysQuery query = new MofSysQuery();
			
				query.AppendEquals(MofSysColumn.Id, mock.Id.ToString());
				query.AppendEquals(MofSysColumn.MofGl, mock.MofGl.ToString());
				if(mock.MofName != null)
					query.AppendEquals(MofSysColumn.MofName, mock.MofName.ToString());
				if(mock.MofNameb != null)
					query.AppendEquals(MofSysColumn.MofNameb, mock.MofNameb.ToString());
				if(mock.AcType != null)
					query.AppendEquals(MofSysColumn.AcType, mock.AcType.ToString());
				if(mock.Negative != null)
					query.AppendEquals(MofSysColumn.Negative, mock.Negative.ToString());
				if(mock.Master != null)
					query.AppendEquals(MofSysColumn.Master, mock.Master.ToString());
				if(mock.Glevel != null)
					query.AppendEquals(MofSysColumn.Glevel, mock.Glevel.ToString());
				query.AppendEquals(MofSysColumn.LastLevel, mock.LastLevel.ToString());
				if(mock.OtherEqui != null)
					query.AppendEquals(MofSysColumn.OtherEqui, mock.OtherEqui.ToString());
				
				TList<MofSys> results = DataRepository.MofSysProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed MofSys Entity with mock values.
		///</summary>
		static public MofSys CreateMockInstance_Generated(TransactionManager tm)
		{		
			MofSys mock = new MofSys();
						
			mock.MofGl = TestUtility.Instance.RandomString(4, false);;
			mock.MofName = TestUtility.Instance.RandomString(126, false);;
			mock.MofNameb = TestUtility.Instance.RandomString(99, false);;
			mock.AcType = TestUtility.Instance.RandomString(1, false);;
			mock.Negative = TestUtility.Instance.RandomString(1, false);;
			mock.Master = TestUtility.Instance.RandomBoolean();
			mock.Glevel = TestUtility.Instance.RandomNumber();
			mock.LastLevel = TestUtility.Instance.RandomBoolean();
			mock.OtherEqui = TestUtility.Instance.RandomString(126, false);;
			
		
			// create a temporary collection and add the item to it
			TList<MofSys> tempMockCollection = new TList<MofSys>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (MofSys)mock;
		}
		
		
		///<summary>
		///  Update the Typed MofSys Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, MofSys mock)
		{
			mock.MofGl = TestUtility.Instance.RandomString(4, false);;
			mock.MofName = TestUtility.Instance.RandomString(126, false);;
			mock.MofNameb = TestUtility.Instance.RandomString(99, false);;
			mock.AcType = TestUtility.Instance.RandomString(1, false);;
			mock.Negative = TestUtility.Instance.RandomString(1, false);;
			mock.Master = TestUtility.Instance.RandomBoolean();
			mock.Glevel = TestUtility.Instance.RandomNumber();
			mock.LastLevel = TestUtility.Instance.RandomBoolean();
			mock.OtherEqui = TestUtility.Instance.RandomString(126, false);;
			
		}
		#endregion
    }
}
