
/*
	File Generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file StaffTest.cs instead.
*/

#region Using directives

using System;
using System.Xml;
using System.Xml.Serialization;
using NUnit.Framework;
using LibraryManagement.Domain;
using LibraryManagement.Dao;
using LibraryManagement.Dao.Bases;

#endregion

namespace LibraryManagement.UnitTests
{
    /// <summary>
    /// Provides tests for the and <see cref="Staff"/> objects (entity, collection and repository).
    /// </summary>
   public partial class StaffTest
    {
    	// the Staff instance used to test the repository.
		protected Staff mock;
		
		// the TList<Staff> instance used to test the repository.
		protected TList<Staff> mockCollection;
		
		protected static TransactionManager CreateTransaction()
		{
			TransactionManager transactionManager = null;
			if (DataRepository.Provider.IsTransactionSupported)
			{
				transactionManager = DataRepository.Provider.CreateTransaction();
				transactionManager.BeginTransaction(System.Data.IsolationLevel.ReadCommitted);
			}			
			return transactionManager;
		}
		       
        /// <summary>
		/// This method is used to construct the test environment prior to running the tests.
		/// </summary>        
        static public void Init_Generated()
        {		
        	System.Console.WriteLine(new String('-', 75));
			System.Console.WriteLine("-- Testing the Staff Entity with the {0} --", LibraryManagement.Dao.DataRepository.Provider.Name);
			System.Console.WriteLine(new String('-', 75));
        }
    
    	/// <summary>
		/// This method is used to restore the environment after the tests are completed.
		/// </summary>
		static public void CleanUp_Generated()
        {   		
			System.Console.WriteLine("All Tests Completed");
			System.Console.WriteLine();
        }
    
    
		/// <summary>
		/// Inserts a mock Staff entity into the database.
		/// </summary>
		private void Step_01_Insert_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.StaffProvider.Insert(tm, mock), "Insert failed");
										
				System.Console.WriteLine("DataRepository.StaffProvider.Insert(mock):");			
				System.Console.WriteLine(mock);			
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Selects all Staff objects of the database.
		/// </summary>
		private void Step_02_SelectAll_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Find
				int count = -1;
				
				mockCollection = DataRepository.StaffProvider.Find(tm, null, "", 0, 10, out count );
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue Find Command.");
				
				System.Console.WriteLine("DataRepository.StaffProvider.Find():");			
				System.Console.WriteLine(mockCollection);
				
				// GetPaged
				count = -1;
				
				mockCollection = DataRepository.StaffProvider.GetPaged(tm, 0, 10, out count);
				Assert.IsTrue(count >= 0 && mockCollection != null, "Query Failed to issue GetPaged Command.");
				System.Console.WriteLine("#get paged count: " + count.ToString());
			}
		}
		
		
		
		
		/// <summary>
		/// Deep load all Staff children.
		/// </summary>
		private void Step_03_DeepLoad_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				int count = -1;
				mock =  CreateMockInstance(tm);
				mockCollection = DataRepository.StaffProvider.GetPaged(tm, 0, 10, out count);
			
				DataRepository.StaffProvider.DeepLoading += new EntityProviderBaseCore<Staff, StaffKey>.DeepLoadingEventHandler(
						delegate(object sender, DeepSessionEventArgs e)
						{
							if (e.DeepSession.Count > 3)
								e.Cancel = true;
						}
					);

				if (mockCollection.Count > 0)
				{
					
					DataRepository.StaffProvider.DeepLoad(tm, mockCollection[0]);
					System.Console.WriteLine("Staff instance correctly deep loaded at 1 level.");
									
					mockCollection.Add(mock);
					// DataRepository.StaffProvider.DeepSave(tm, mockCollection);
				}
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		/// <summary>
		/// Updates a mock Staff entity into the database.
		/// </summary>
		private void Step_04_Update_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Staff mock = CreateMockInstance(tm);
				Assert.IsTrue(DataRepository.StaffProvider.Insert(tm, mock), "Insert failed");
				
				UpdateMockInstance(tm, mock);
				Assert.IsTrue(DataRepository.StaffProvider.Update(tm, mock), "Update failed.");			
				
				System.Console.WriteLine("DataRepository.StaffProvider.Update(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		
		/// <summary>
		/// Delete the mock Staff entity into the database.
		/// </summary>
		private void Step_05_Delete_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  (Staff)CreateMockInstance(tm);
				DataRepository.StaffProvider.Insert(tm, mock);
			
				Assert.IsTrue(DataRepository.StaffProvider.Delete(tm, mock), "Delete failed.");
				System.Console.WriteLine("DataRepository.StaffProvider.Delete(mock):");			
				System.Console.WriteLine(mock);
				
				//normally one would commit here
				//tm.Commit();
				//IDisposable will Rollback Transaction since it's left uncommitted
			}
		}
		
		#region Serialization tests
		
		/// <summary>
		/// Serialize the mock Staff entity into a temporary file.
		/// </summary>
		private void Step_06_SerializeEntity_Generated()
		{	
			using (TransactionManager tm = CreateTransaction())
			{
				mock =  CreateMockInstance(tm);
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_Staff.xml");
			
				EntityHelper.SerializeXml(mock, fileName);
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock not found");
					
				System.Console.WriteLine("mock correctly serialized to a temporary file.");			
			}
		}
		
		/// <summary>
		/// Deserialize the mock Staff entity from a temporary file.
		/// </summary>
		private void Step_07_DeserializeEntity_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_Staff.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			using (System.IO.StreamReader sr = System.IO.File.OpenText(fileName))
			{
				object item = EntityHelper.DeserializeEntityXml<Staff>(sr.ReadToEnd());
				sr.Close();
			}
			System.IO.File.Delete(fileName);
			
			System.Console.WriteLine("mock correctly deserialized from a temporary file.");
		}
		
		/// <summary>
		/// Serialize a Staff collection into a temporary file.
		/// </summary>
		private void Step_08_SerializeCollection_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_StaffCollection.xml");
				
				mock = CreateMockInstance(tm);
				TList<Staff> mockCollection = new TList<Staff>();
				mockCollection.Add(mock);
			
				EntityHelper.SerializeXml(mockCollection, fileName);
				
				Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock collection not found");
				System.Console.WriteLine("TList<Staff> correctly serialized to a temporary file.");					
			}
		}
		
		
		/// <summary>
		/// Deserialize a Staff collection from a temporary file.
		/// </summary>
		private void Step_09_DeserializeCollection_Generated()
		{
			string fileName = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "temp_StaffCollection.xml");
			Assert.IsTrue(System.IO.File.Exists(fileName), "Serialized mock file not found to deserialize");
			
			XmlSerializer mySerializer = new XmlSerializer(typeof(TList<Staff>)); 
			using (System.IO.FileStream myFileStream = new System.IO.FileStream(fileName,  System.IO.FileMode.Open))
			{
				TList<Staff> mockCollection = (TList<Staff>) mySerializer.Deserialize(myFileStream);
				myFileStream.Close();
			}
			
			System.IO.File.Delete(fileName);
			System.Console.WriteLine("TList<Staff> correctly deserialized from a temporary file.");	
		}
		#endregion
		
		
		
		/// <summary>
		/// Check the foreign key dal methods.
		/// </summary>
		private void Step_10_FK_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Staff entity = CreateMockInstance(tm);
				bool result = DataRepository.StaffProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test FK, Insert Failed");
				
			}
		}
		
		
		/// <summary>
		/// Check the indexes dal methods.
		/// </summary>
		private void Step_11_IX_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				Staff entity = CreateMockInstance(tm);
				bool result = DataRepository.StaffProvider.Insert(tm, entity);
				
				Assert.IsTrue(result, "Could Not Test IX, Insert Failed");

			
				Staff t0 = DataRepository.StaffProvider.GetById(tm, entity.Id);
			}
		}
		
		/// <summary>
		/// Test methods exposed by the EntityHelper class.
		/// </summary>
		private void Step_20_TestEntityHelper_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				mock = CreateMockInstance(tm);
				
				Staff entity = mock.Copy() as Staff;
				entity = (Staff)mock.Clone();
				Assert.IsTrue(Staff.ValueEquals(entity, mock), "Clone is not working");
			}
		}
		
		/// <summary>
		/// Test Find using the Query class
		/// </summary>
		private void Step_30_TestFindByQuery_Generated()
		{
			using (TransactionManager tm = CreateTransaction())
			{
				//Insert Mock Instance
				Staff mock = CreateMockInstance(tm);
				bool result = DataRepository.StaffProvider.Insert(tm, mock);
				
				Assert.IsTrue(result, "Could Not Test FindByQuery, Insert Failed");

				StaffQuery query = new StaffQuery();
			
				query.AppendEquals(StaffColumn.Id, mock.Id.ToString());
				if(mock.Name != null)
					query.AppendEquals(StaffColumn.Name, mock.Name.ToString());
				if(mock.Depart != null)
					query.AppendEquals(StaffColumn.Depart, mock.Depart.ToString());
				if(mock.OpenDate != null)
					query.AppendEquals(StaffColumn.OpenDate, mock.OpenDate.ToString());
				if(mock.SalaryLevel != null)
					query.AppendEquals(StaffColumn.SalaryLevel, mock.SalaryLevel.ToString());
				if(mock.Address != null)
					query.AppendEquals(StaffColumn.Address, mock.Address.ToString());
				if(mock.Phone != null)
					query.AppendEquals(StaffColumn.Phone, mock.Phone.ToString());
				if(mock.PersonId != null)
					query.AppendEquals(StaffColumn.PersonId, mock.PersonId.ToString());
				if(mock.PersonIddate != null)
					query.AppendEquals(StaffColumn.PersonIddate, mock.PersonIddate.ToString());
				if(mock.Location != null)
					query.AppendEquals(StaffColumn.Location, mock.Location.ToString());
				if(mock.ContactPerson != null)
					query.AppendEquals(StaffColumn.ContactPerson, mock.ContactPerson.ToString());
				if(mock.Remark != null)
					query.AppendEquals(StaffColumn.Remark, mock.Remark.ToString());
				if(mock.Labelsprn != null)
					query.AppendEquals(StaffColumn.Labelsprn, mock.Labelsprn.ToString());
				if(mock.Status != null)
					query.AppendEquals(StaffColumn.Status, mock.Status.ToString());
				
				TList<Staff> results = DataRepository.StaffProvider.Find(tm, query);
				
				Assert.IsTrue(results.Count == 1, "Find is not working correctly.  Failed to find the mock instance");
			}
		}
						
		#region Mock Instance
		///<summary>
		///  Returns a Typed Staff Entity with mock values.
		///</summary>
		static public Staff CreateMockInstance_Generated(TransactionManager tm)
		{		
			Staff mock = new Staff();
						
			mock.Id = TestUtility.Instance.RandomString(7, false);;
			mock.Name = TestUtility.Instance.RandomString(24, false);;
			mock.Depart = TestUtility.Instance.RandomString(2, false);;
			mock.OpenDate = TestUtility.Instance.RandomDateTime();
			mock.SalaryLevel = (decimal)TestUtility.Instance.RandomShort();
			mock.Address = TestUtility.Instance.RandomString(99, false);;
			mock.Phone = TestUtility.Instance.RandomString(14, false);;
			mock.PersonId = TestUtility.Instance.RandomString(10, false);;
			mock.PersonIddate = TestUtility.Instance.RandomDateTime();
			mock.Location = TestUtility.Instance.RandomString(24, false);;
			mock.ContactPerson = TestUtility.Instance.RandomString(49, false);;
			mock.Remark = TestUtility.Instance.RandomString(99, false);;
			mock.Labelsprn = TestUtility.Instance.RandomString(6, false);;
			mock.Status = TestUtility.Instance.RandomNumber();
			
		
			// create a temporary collection and add the item to it
			TList<Staff> tempMockCollection = new TList<Staff>();
			tempMockCollection.Add(mock);
			tempMockCollection.Remove(mock);
			
		
		   return (Staff)mock;
		}
		
		
		///<summary>
		///  Update the Typed Staff Entity with modified mock values.
		///</summary>
		static public void UpdateMockInstance_Generated(TransactionManager tm, Staff mock)
		{
			mock.Name = TestUtility.Instance.RandomString(24, false);;
			mock.Depart = TestUtility.Instance.RandomString(2, false);;
			mock.OpenDate = TestUtility.Instance.RandomDateTime();
			mock.SalaryLevel = (decimal)TestUtility.Instance.RandomShort();
			mock.Address = TestUtility.Instance.RandomString(99, false);;
			mock.Phone = TestUtility.Instance.RandomString(14, false);;
			mock.PersonId = TestUtility.Instance.RandomString(10, false);;
			mock.PersonIddate = TestUtility.Instance.RandomDateTime();
			mock.Location = TestUtility.Instance.RandomString(24, false);;
			mock.ContactPerson = TestUtility.Instance.RandomString(49, false);;
			mock.Remark = TestUtility.Instance.RandomString(99, false);;
			mock.Labelsprn = TestUtility.Instance.RandomString(6, false);;
			mock.Status = TestUtility.Instance.RandomNumber();
			
		}
		#endregion
    }
}
