using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Mask;
using System;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Windows.Forms;

namespace LibraryManagement.App
{
    partial class FrmCsCard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.btn_Delete = new SimpleButton();
            this.groupBox1 = new GroupBox();
            this.btn_Exit = new SimpleButton();
            this.btn_Search = new SimpleButton();
            this.btn_Edit = new SimpleButton();
            this.btn_New = new SimpleButton();
            this.btn_Skip = new SimpleButton();
            this.btn_Save = new SimpleButton();
            this.GroupBox2 = new GroupBox();
            this.LabelControl3 = new LabelControl();
            this.LabelControl4 = new LabelControl();
            this.Txt_Status = new TextEdit();
            this.Txt_Id = new TextEdit();
            this.LabelControl2 = new LabelControl();
            this.LabelControl1 = new LabelControl();
            this.Txt_Phone = new TextEdit();
            this.Txt_Address = new TextEdit();
            this.LabelControl14 = new LabelControl();
            this.Txt_FullName = new TextEdit();
            this.Txt_OpenDate = new TextEdit();
            this.radioGroup1 = new RadioGroup();
            this.Txt_BirthDay = new TextEdit();
            this.labelControl5 = new LabelControl();
            this.labelControl6 = new LabelControl();
            this.Txt_PersonId = new TextEdit();
            this.labelControl7 = new LabelControl();
            this.Txt_DateOfIssue = new TextEdit();
            this.labelControl8 = new LabelControl();
            this.Txt_PlaceOfIssue = new TextEdit();
            this.pictureEdit1 = new PictureEdit();
            this.labelControl9 = new LabelControl();
            this.Txt_DueDate = new TextEdit();
            this.btnChoose = new SimpleButton();
            this.labelControl10 = new LabelControl();
            this.Txt_Remark = new TextEdit();
            this.xTveRubwQ = new CheckEdit();
            this.labelControl11 = new LabelControl();
            this.Txt_Email = new TextEdit();
            this.Txt_DiscPc = new TextEdit();
            this.labelControl12 = new LabelControl();
            this.openFileDialog_0 = new OpenFileDialog();
            this.Txt_BegMark = new TextEdit();
            this.labelControl13 = new LabelControl();
            this.Txt_Status.Properties.BeginInit();
            this.Txt_Id.Properties.BeginInit();
            this.Txt_Phone.Properties.BeginInit();
            this.Txt_Address.Properties.BeginInit();
            this.Txt_FullName.Properties.BeginInit();
            this.Txt_OpenDate.Properties.BeginInit();
            this.radioGroup1.Properties.BeginInit();
            this.Txt_BirthDay.Properties.BeginInit();
            this.Txt_PersonId.Properties.BeginInit();
            this.Txt_DateOfIssue.Properties.BeginInit();
            this.Txt_PlaceOfIssue.Properties.BeginInit();
            this.pictureEdit1.Properties.BeginInit();
            this.Txt_DueDate.Properties.BeginInit();
            this.Txt_Remark.Properties.BeginInit();
            this.xTveRubwQ.Properties.BeginInit();
            this.Txt_Email.Properties.BeginInit();
            this.Txt_DiscPc.Properties.BeginInit();
            this.Txt_BegMark.Properties.BeginInit();
            base.SuspendLayout();
            this.btn_Delete.Anchor = AnchorStyles.Bottom;
            this.btn_Delete.Location = new Point(0x14b, 370);
            this.btn_Delete.Name = "btn_Delete";
            this.btn_Delete.Size = new Size(0x4b, 0x17);
            this.btn_Delete.TabIndex = 15;
            this.btn_Delete.Text = "&X\x00f3a";
            this.btn_Delete.Click += new EventHandler(this.btn_Delete_Click);
            this.groupBox1.Anchor = AnchorStyles.Bottom;
            this.groupBox1.Location = new Point(-90, 0x163);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x2fa, 5);
            this.groupBox1.TabIndex = 0x18d;
            this.groupBox1.TabStop = false;
            this.btn_Exit.Anchor = AnchorStyles.Bottom;
            this.btn_Exit.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Exit.Location = new Point(0x1e1, 370);
            this.btn_Exit.Name = "btn_Exit";
            this.btn_Exit.Size = new Size(0x4b, 0x17);
            this.btn_Exit.TabIndex = 0x11;
            this.btn_Exit.Text = "&Tho\x00e1t";
            this.btn_Exit.Click += new EventHandler(this.btn_Exit_Click);
            this.btn_Search.Anchor = AnchorStyles.Bottom;
            this.btn_Search.Location = new Point(0x196, 370);
            this.btn_Search.Name = "btn_Search";
            this.btn_Search.Size = new Size(0x4b, 0x17);
            this.btn_Search.TabIndex = 0x10;
            this.btn_Search.Text = "T\x00ec&m";
            this.btn_Search.Click += new EventHandler(this.btn_Search_Click);
            this.btn_Edit.Anchor = AnchorStyles.Bottom;
            this.btn_Edit.Location = new Point(0x100, 370);
            this.btn_Edit.Name = "btn_Edit";
            this.btn_Edit.Size = new Size(0x4b, 0x17);
            this.btn_Edit.TabIndex = 14;
            this.btn_Edit.Text = "&Sửa";
            this.btn_Edit.Click += new EventHandler(this.btn_Edit_Click);
            this.btn_New.Anchor = AnchorStyles.Bottom;
            this.btn_New.Location = new Point(0xb5, 370);
            this.btn_New.Name = "btn_New";
            this.btn_New.Size = new Size(0x4b, 0x17);
            this.btn_New.TabIndex = 0;
            this.btn_New.Text = "Tạ&o";
            this.btn_New.Click += new EventHandler(this.btn_New_Click);
            this.btn_Skip.Anchor = AnchorStyles.Bottom;
            this.btn_Skip.Location = new Point(0x6a, 370);
            this.btn_Skip.Name = "btn_Skip";
            this.btn_Skip.Size = new Size(0x4b, 0x17);
            this.btn_Skip.TabIndex = 13;
            this.btn_Skip.Text = "&Bỏ qua";
            this.btn_Skip.Click += new EventHandler(this.btn_Skip_Click);
            this.btn_Save.Anchor = AnchorStyles.Bottom;
            this.btn_Save.Location = new Point(0x1f, 370);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.Size = new Size(0x4b, 0x17);
            this.btn_Save.TabIndex = 12;
            this.btn_Save.Text = "&Lưu";
            this.btn_Save.Click += new EventHandler(this.btn_Save_Click);
            this.GroupBox2.Location = new Point(-97, 0x5b);
            this.GroupBox2.Name = "GroupBox2";
            this.GroupBox2.Size = new Size(0x2fa, 5);
            this.GroupBox2.TabIndex = 410;
            this.GroupBox2.TabStop = false;
            this.LabelControl3.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl3.Location = new Point(0x170, 15);
            this.LabelControl3.Name = "LabelControl3";
            this.LabelControl3.Size = new Size(0x31, 13);
            this.LabelControl3.TabIndex = 0x199;
            this.LabelControl3.Text = "Trạng th\x00e1i";
            this.LabelControl4.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl4.Location = new Point(0x15, 15);
            this.LabelControl4.Name = "LabelControl4";
            this.LabelControl4.Size = new Size(0x3f, 13);
            this.LabelControl4.TabIndex = 0x198;
            this.LabelControl4.Text = "M\x00e3 số thẻ KH";
            this.Txt_Status.EnterMoveNextControl = true;
            this.Txt_Status.Location = new Point(0x1a8, 12);
            this.Txt_Status.Name = "Txt_Status";
            this.Txt_Status.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Status.Properties.Appearance.Options.UseFont = true;
            this.Txt_Status.Size = new Size(0x7c, 20);
            this.Txt_Status.TabIndex = 0x197;
            this.Txt_Id.EnterMoveNextControl = true;
            this.Txt_Id.Location = new Point(0x85, 12);
            this.Txt_Id.Name = "Txt_Id";
            this.Txt_Id.Properties.Appearance.BackColor = Color.Yellow;
            this.Txt_Id.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Id.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_Id.Properties.Appearance.Options.UseFont = true;
            this.Txt_Id.Properties.Mask.PlaceHolder = ' ';
            this.Txt_Id.Properties.MaxLength = 8;
            this.Txt_Id.Properties.ValidateOnEnterKey = true;
            this.Txt_Id.Size = new Size(0x6d, 20);
            this.Txt_Id.TabIndex = 0x196;
            this.Txt_Id.EditValueChanged += new EventHandler(this.Txt_Id_EditValueChanged);
            this.Txt_Id.KeyDown += new KeyEventHandler(this.Txt_Id_KeyDown);
            this.LabelControl2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl2.Location = new Point(0x15, 0x83);
            this.LabelControl2.Name = "LabelControl2";
            this.LabelControl2.Size = new Size(0x3e, 13);
            this.LabelControl2.TabIndex = 0x195;
            this.LabelControl2.Text = "Số điện thoại";
            this.LabelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl1.Location = new Point(0x15, 0x69);
            this.LabelControl1.Name = "LabelControl1";
            this.LabelControl1.Size = new Size(0x20, 13);
            this.LabelControl1.TabIndex = 0x194;
            this.LabelControl1.Text = "Địa chỉ";
            this.Txt_Phone.EnterMoveNextControl = true;
            this.Txt_Phone.Location = new Point(0x85, 0x80);
            this.Txt_Phone.Name = "Txt_Phone";
            this.Txt_Phone.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Phone.Properties.Appearance.Options.UseFont = true;
            this.Txt_Phone.Size = new Size(0x11c, 20);
            this.Txt_Phone.TabIndex = 4;
            this.Txt_Address.EnterMoveNextControl = true;
            this.Txt_Address.Location = new Point(0x85, 0x66);
            this.Txt_Address.Name = "Txt_Address";
            this.Txt_Address.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Address.Properties.Appearance.Options.UseFont = true;
            this.Txt_Address.Size = new Size(0x19f, 20);
            this.Txt_Address.TabIndex = 3;
            this.LabelControl14.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl14.Location = new Point(0x15, 0x29);
            this.LabelControl14.Name = "LabelControl14";
            this.LabelControl14.Size = new Size(0x4c, 13);
            this.LabelControl14.TabIndex = 0x192;
            this.LabelControl14.Text = "T\x00ean kh\x00e1ch h\x00e0ng";
            this.Txt_FullName.EnterMoveNextControl = true;
            this.Txt_FullName.Location = new Point(0x85, 0x26);
            this.Txt_FullName.Name = "Txt_FullName";
            this.Txt_FullName.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_FullName.Properties.Appearance.Options.UseFont = true;
            this.Txt_FullName.Size = new Size(0x11c, 20);
            this.Txt_FullName.TabIndex = 1;
            this.Txt_OpenDate.EnterMoveNextControl = true;
            this.Txt_OpenDate.Location = new Point(0x1a8, 0x26);
            this.Txt_OpenDate.Name = "Txt_OpenDate";
            this.Txt_OpenDate.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_OpenDate.Properties.Appearance.Options.UseFont = true;
            this.Txt_OpenDate.Properties.DisplayFormat.FormatString = "dd/MM/yyyy";
            this.Txt_OpenDate.Properties.DisplayFormat.FormatType = FormatType.DateTime;
            this.Txt_OpenDate.Properties.EditFormat.FormatString = "dd/MM/yyyy";
            this.Txt_OpenDate.Properties.EditFormat.FormatType = FormatType.DateTime;
            this.Txt_OpenDate.Properties.Mask.EditMask = "dd/MM/yyyy";
            this.Txt_OpenDate.Properties.Mask.MaskType = MaskType.DateTime;
            this.Txt_OpenDate.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_OpenDate.Size = new Size(0x7c, 20);
            this.Txt_OpenDate.TabIndex = 0x19b;
            this.radioGroup1.Location = new Point(0x85, 0x40);
            this.radioGroup1.Name = "radioGroup1";
            this.radioGroup1.Properties.Appearance.BackColor = Color.Transparent;
            this.radioGroup1.Properties.Appearance.Options.UseBackColor = true;
            this.radioGroup1.Properties.BorderStyle = BorderStyles.NoBorder;
            this.radioGroup1.Properties.Items.AddRange(new RadioGroupItem[] { new RadioGroupItem(null, "Nữ"), new RadioGroupItem(null, "Nam") });
            this.radioGroup1.Size = new Size(0xdf, 0x17);
            this.radioGroup1.TabIndex = 2;
            this.Txt_BirthDay.EditValue = new DateTime(0x76c, 1, 1, 15, 0x34, 0x39, 0);
            this.Txt_BirthDay.EnterMoveNextControl = true;
            this.Txt_BirthDay.Location = new Point(0x85, 180);
            this.Txt_BirthDay.Name = "Txt_BirthDay";
            this.Txt_BirthDay.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_BirthDay.Properties.Appearance.Options.UseFont = true;
            this.Txt_BirthDay.Properties.DisplayFormat.FormatString = "dd/MM/yyyy";
            this.Txt_BirthDay.Properties.DisplayFormat.FormatType = FormatType.DateTime;
            this.Txt_BirthDay.Properties.EditFormat.FormatString = "dd/MM/yyyy";
            this.Txt_BirthDay.Properties.EditFormat.FormatType = FormatType.DateTime;
            this.Txt_BirthDay.Properties.Mask.EditMask = "dd/MM/yyyy";
            this.Txt_BirthDay.Properties.Mask.MaskType = MaskType.DateTime;
            this.Txt_BirthDay.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_BirthDay.Size = new Size(0x11c, 20);
            this.Txt_BirthDay.TabIndex = 6;
            this.labelControl5.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl5.Location = new Point(0x15, 0xb5);
            this.labelControl5.Name = "labelControl5";
            this.labelControl5.Size = new Size(0x2f, 13);
            this.labelControl5.TabIndex = 0x19e;
            this.labelControl5.Text = "Ng\x00e0y sinh";
            this.labelControl6.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl6.Location = new Point(0x15, 0xcf);
            this.labelControl6.Name = "labelControl6";
            this.labelControl6.Size = new Size(0x5f, 13);
            this.labelControl6.TabIndex = 0x1a0;
            this.labelControl6.Text = "Số CMTND/Hộ chiếu";
            this.Txt_PersonId.EnterMoveNextControl = true;
            this.Txt_PersonId.Location = new Point(0x85, 0xce);
            this.Txt_PersonId.Name = "Txt_PersonId";
            this.Txt_PersonId.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_PersonId.Properties.Appearance.Options.UseFont = true;
            this.Txt_PersonId.Size = new Size(0x11c, 20);
            this.Txt_PersonId.TabIndex = 7;
            this.labelControl7.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl7.Location = new Point(0x15, 0xe9);
            this.labelControl7.Name = "labelControl7";
            this.labelControl7.Size = new Size(0x2d, 13);
            this.labelControl7.TabIndex = 0x1a2;
            this.labelControl7.Text = "Ng\x00e0y cấp";
            this.Txt_DateOfIssue.EditValue = new DateTime(0x76c, 1, 1, 15, 0x35, 0x13, 0);
            this.Txt_DateOfIssue.EnterMoveNextControl = true;
            this.Txt_DateOfIssue.Location = new Point(0x85, 0xe8);
            this.Txt_DateOfIssue.Name = "Txt_DateOfIssue";
            this.Txt_DateOfIssue.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_DateOfIssue.Properties.Appearance.Options.UseFont = true;
            this.Txt_DateOfIssue.Properties.DisplayFormat.FormatString = "dd/MM/yyyy";
            this.Txt_DateOfIssue.Properties.DisplayFormat.FormatType = FormatType.DateTime;
            this.Txt_DateOfIssue.Properties.EditFormat.FormatString = "dd/MM/yyyy";
            this.Txt_DateOfIssue.Properties.EditFormat.FormatType = FormatType.DateTime;
            this.Txt_DateOfIssue.Properties.Mask.EditMask = "dd/MM/yyyy";
            this.Txt_DateOfIssue.Properties.Mask.MaskType = MaskType.DateTime;
            this.Txt_DateOfIssue.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DateOfIssue.Size = new Size(0x11c, 20);
            this.Txt_DateOfIssue.TabIndex = 8;
            this.labelControl8.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl8.Location = new Point(0x15, 0x103);
            this.labelControl8.Name = "labelControl8";
            this.labelControl8.Size = new Size(0x23, 13);
            this.labelControl8.TabIndex = 420;
            this.labelControl8.Text = "Nơi cấp";
            this.Txt_PlaceOfIssue.EnterMoveNextControl = true;
            this.Txt_PlaceOfIssue.Location = new Point(0x85, 0x102);
            this.Txt_PlaceOfIssue.Name = "Txt_PlaceOfIssue";
            this.Txt_PlaceOfIssue.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_PlaceOfIssue.Properties.Appearance.Options.UseFont = true;
            this.Txt_PlaceOfIssue.Size = new Size(0x11c, 20);
            this.Txt_PlaceOfIssue.TabIndex = 9;
            this.pictureEdit1.Location = new Point(0x1c0, 130);
            this.pictureEdit1.Name = "pictureEdit1";
            this.pictureEdit1.Properties.SizeMode = PictureSizeMode.Stretch;
            this.pictureEdit1.Size = new Size(100, 0x73);
            this.pictureEdit1.TabIndex = 0x1a5;
            this.labelControl9.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl9.Location = new Point(0x15, 0x11f);
            this.labelControl9.Name = "labelControl9";
            this.labelControl9.Size = new Size(0x56, 13);
            this.labelControl9.TabIndex = 0x1a7;
            this.labelControl9.Text = "Hiệu lực đến ng\x00e0y";
            this.Txt_DueDate.EnterMoveNextControl = true;
            this.Txt_DueDate.Location = new Point(0x85, 0x11c);
            this.Txt_DueDate.Name = "Txt_DueDate";
            this.Txt_DueDate.Properties.Appearance.BackColor = Color.Bisque;
            this.Txt_DueDate.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_DueDate.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_DueDate.Properties.Appearance.Options.UseFont = true;
            this.Txt_DueDate.Properties.DisplayFormat.FormatString = "dd/MM/yyyy";
            this.Txt_DueDate.Properties.DisplayFormat.FormatType = FormatType.DateTime;
            this.Txt_DueDate.Properties.EditFormat.FormatString = "dd/MM/yyyy";
            this.Txt_DueDate.Properties.EditFormat.FormatType = FormatType.DateTime;
            this.Txt_DueDate.Properties.Mask.EditMask = "dd/MM/yyyy";
            this.Txt_DueDate.Properties.Mask.MaskType = MaskType.DateTime;
            this.Txt_DueDate.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DueDate.Size = new Size(0x60, 20);
            this.Txt_DueDate.TabIndex = 10;
            this.btnChoose.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnChoose.Appearance.Options.UseFont = true;
            this.btnChoose.Location = new Point(0x1cd, 0xfb);
            this.btnChoose.Name = "btnChoose";
            this.btnChoose.Size = new Size(0x4d, 0x17);
            this.btnChoose.TabIndex = 0x1a8;
            this.btnChoose.Text = "Chọn";
            this.btnChoose.Click += new EventHandler(this.btnChoose_Click);
            this.labelControl10.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl10.Location = new Point(0x15, 0x13a);
            this.labelControl10.Name = "labelControl10";
            this.labelControl10.Size = new Size(0x23, 13);
            this.labelControl10.TabIndex = 0x1aa;
            this.labelControl10.Text = "Ghi ch\x00fa";
            this.Txt_Remark.EnterMoveNextControl = true;
            this.Txt_Remark.Location = new Point(0x85, 310);
            this.Txt_Remark.Name = "Txt_Remark";
            this.Txt_Remark.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Remark.Properties.Appearance.Options.UseFont = true;
            this.Txt_Remark.Size = new Size(0x19f, 20);
            this.Txt_Remark.TabIndex = 11;
            this.xTveRubwQ.Location = new Point(0x1a8, 0x42);
            this.xTveRubwQ.Name = "chk_VIP";
            this.xTveRubwQ.Properties.Caption = "Kh\x00e1ch VIP";
            this.xTveRubwQ.Size = new Size(0x4b, 0x13);
            this.xTveRubwQ.TabIndex = 0x1ab;
            this.labelControl11.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl11.Location = new Point(0x15, 0x9b);
            this.labelControl11.Name = "labelControl11";
            this.labelControl11.Size = new Size(0x18, 13);
            this.labelControl11.TabIndex = 0x1ad;
            this.labelControl11.Text = "Email";
            this.Txt_Email.EnterMoveNextControl = true;
            this.Txt_Email.Location = new Point(0x85, 0x9a);
            this.Txt_Email.Name = "Txt_Email";
            this.Txt_Email.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Email.Properties.Appearance.Options.UseFont = true;
            this.Txt_Email.Size = new Size(0x11c, 20);
            this.Txt_Email.TabIndex = 5;
            int[] bits1 = new int[4];
            this.Txt_DiscPc.EditValue = new decimal(bits1);
            this.Txt_DiscPc.EnterMoveNextControl = true;
            this.Txt_DiscPc.Location = new Point(0x14b, 0x11c);
            this.Txt_DiscPc.Name = "Txt_DiscPc";
            this.Txt_DiscPc.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_DiscPc.Properties.Appearance.Options.UseFont = true;
            this.Txt_DiscPc.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_DiscPc.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_DiscPc.Properties.DisplayFormat.FormatString = "n2";
            this.Txt_DiscPc.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_DiscPc.Properties.EditFormat.FormatString = "n2";
            this.Txt_DiscPc.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_DiscPc.Properties.Mask.EditMask = "n2";
            this.Txt_DiscPc.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_DiscPc.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DiscPc.Size = new Size(0x40, 20);
            this.Txt_DiscPc.TabIndex = 430;
            this.labelControl12.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl12.Location = new Point(0x12a, 0x11f);
            this.labelControl12.Name = "labelControl12";
            this.labelControl12.Size = new Size(0x1b, 13);
            this.labelControl12.TabIndex = 0x1af;
            this.labelControl12.Text = "% CK";
            this.openFileDialog_0.FileName = "*.jpg";
            this.openFileDialog_0.FileOk += new CancelEventHandler(this.openFileDialog_0_FileOk);
            int[] bits2 = new int[4];
            this.Txt_BegMark.EditValue = new decimal(bits2);
            this.Txt_BegMark.EnterMoveNextControl = true;
            this.Txt_BegMark.Location = new Point(0x1e4, 0x11c);
            this.Txt_BegMark.Name = "Txt_BegMark";
            this.Txt_BegMark.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_BegMark.Properties.Appearance.Options.UseFont = true;
            this.Txt_BegMark.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_BegMark.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_BegMark.Properties.DisplayFormat.FormatString = "n0";
            this.Txt_BegMark.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_BegMark.Properties.EditFormat.FormatString = "n0";
            this.Txt_BegMark.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_BegMark.Properties.Mask.EditMask = "n0";
            this.Txt_BegMark.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_BegMark.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_BegMark.Size = new Size(0x40, 20);
            this.Txt_BegMark.TabIndex = 0x1b0;
            this.labelControl13.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl13.Location = new Point(0x196, 0x11f);
            this.labelControl13.Name = "labelControl13";
            this.labelControl13.Size = new Size(0x42, 13);
            this.labelControl13.TabIndex = 0x1b1;
            this.labelControl13.Text = "Điểm ban đầu";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.CancelButton = this.btn_Exit;
            base.ClientSize = new Size(0x247, 0x195);
            base.Controls.Add(this.Txt_BegMark);
            base.Controls.Add(this.labelControl13);
            base.Controls.Add(this.Txt_DiscPc);
            base.Controls.Add(this.labelControl12);
            base.Controls.Add(this.labelControl11);
            base.Controls.Add(this.Txt_Email);
            base.Controls.Add(this.xTveRubwQ);
            base.Controls.Add(this.labelControl10);
            base.Controls.Add(this.Txt_Remark);
            base.Controls.Add(this.btnChoose);
            base.Controls.Add(this.labelControl9);
            base.Controls.Add(this.Txt_DueDate);
            base.Controls.Add(this.pictureEdit1);
            base.Controls.Add(this.labelControl8);
            base.Controls.Add(this.Txt_PlaceOfIssue);
            base.Controls.Add(this.labelControl7);
            base.Controls.Add(this.Txt_DateOfIssue);
            base.Controls.Add(this.labelControl6);
            base.Controls.Add(this.Txt_PersonId);
            base.Controls.Add(this.labelControl5);
            base.Controls.Add(this.Txt_BirthDay);
            base.Controls.Add(this.radioGroup1);
            base.Controls.Add(this.Txt_OpenDate);
            base.Controls.Add(this.GroupBox2);
            base.Controls.Add(this.LabelControl3);
            base.Controls.Add(this.LabelControl4);
            base.Controls.Add(this.Txt_Status);
            base.Controls.Add(this.Txt_Id);
            base.Controls.Add(this.LabelControl2);
            base.Controls.Add(this.LabelControl1);
            base.Controls.Add(this.Txt_Phone);
            base.Controls.Add(this.Txt_Address);
            base.Controls.Add(this.LabelControl14);
            base.Controls.Add(this.Txt_FullName);
            base.Controls.Add(this.btn_Delete);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.btn_Exit);
            base.Controls.Add(this.btn_Search);
            base.Controls.Add(this.btn_Edit);
            base.Controls.Add(this.btn_New);
            base.Controls.Add(this.btn_Skip);
            base.Controls.Add(this.btn_Save);
            base.Name = "FrmCsCard";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmCsCard";
            base.Load += new EventHandler(this.FrmCsCard_Load);
            this.Txt_Status.Properties.EndInit();
            this.Txt_Id.Properties.EndInit();
            this.Txt_Phone.Properties.EndInit();
            this.Txt_Address.Properties.EndInit();
            this.Txt_FullName.Properties.EndInit();
            this.Txt_OpenDate.Properties.EndInit();
            this.radioGroup1.Properties.EndInit();
            this.Txt_BirthDay.Properties.EndInit();
            this.Txt_PersonId.Properties.EndInit();
            this.Txt_DateOfIssue.Properties.EndInit();
            this.Txt_PlaceOfIssue.Properties.EndInit();
            this.pictureEdit1.Properties.EndInit();
            this.Txt_DueDate.Properties.EndInit();
            this.Txt_Remark.Properties.EndInit();
            this.xTveRubwQ.Properties.EndInit();
            this.Txt_Email.Properties.EndInit();
            this.Txt_DiscPc.Properties.EndInit();
            this.Txt_BegMark.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
        private SimpleButton btn_Delete;
        private SimpleButton btn_Edit;
        private SimpleButton btn_Exit;
        private SimpleButton btn_New;
        private SimpleButton btn_Save;
        private SimpleButton btn_Search;
        private SimpleButton btn_Skip;
        internal SimpleButton btnChoose;
        internal GroupBox groupBox1;
        internal GroupBox GroupBox2;
        //private IContainer components;
        internal LabelControl LabelControl1;
        internal LabelControl labelControl10;
        internal LabelControl labelControl11;
        internal LabelControl labelControl12;
        internal LabelControl labelControl13;
        internal LabelControl LabelControl14;
        internal LabelControl LabelControl2;
        internal LabelControl LabelControl3;
        internal LabelControl LabelControl4;
        internal LabelControl labelControl5;
        internal LabelControl labelControl6;
        internal LabelControl labelControl7;
        internal LabelControl labelControl8;
        internal LabelControl labelControl9;
        private OleDbConnection oleDbConnection_0;
        private OleDbDataAdapter oleDbDataAdapter_0;
        internal OpenFileDialog openFileDialog_0;
        private PictureEdit pictureEdit1;
        private RadioGroup radioGroup1;
        private string string_0;
        private string string_1;
        internal TextEdit Txt_Address;
        internal TextEdit Txt_BegMark;
        internal TextEdit Txt_BirthDay;
        internal TextEdit Txt_DateOfIssue;
        internal TextEdit Txt_DiscPc;
        internal TextEdit Txt_DueDate;
        internal TextEdit Txt_Email;
        internal TextEdit Txt_FullName;
        internal TextEdit Txt_Id;
        internal TextEdit Txt_OpenDate;
        internal TextEdit Txt_PersonId;
        internal TextEdit Txt_Phone;
        internal TextEdit Txt_PlaceOfIssue;
        internal TextEdit Txt_Remark;
        internal TextEdit Txt_Status;
        private CheckEdit xTveRubwQ;

        #endregion
    }
}
