using DevExpress.XtraGrid.Views.Base;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Mask;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Columns;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Windows.Forms;

namespace LibraryManagement.App
{
    partial class FrmDiscInfo
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.gridControl1 = new GridControl();
            this.dataSet_0 = new DataSet();
            this.dataTable_0 = new DataTable();
            this.dataColumn_0 = new DataColumn();
            this.dataColumn_1 = new DataColumn();
            this.dataColumn_2 = new DataColumn();
            this.ddvqeXfa4 = new DataColumn();
            this.dataColumn_3 = new DataColumn();
            this.dataColumn_4 = new DataColumn();
            this.dataColumn_5 = new DataColumn();
            this.dataColumn_6 = new DataColumn();
            this.dataColumn_7 = new DataColumn();
            this.dataColumn_8 = new DataColumn();
            this.welftZbha = new DataColumn();
            this.dataColumn_9 = new DataColumn();
            this.dataColumn_10 = new DataColumn();
            this.dataColumn_11 = new DataColumn();
            this.dataColumn_12 = new DataColumn();
            this.dataColumn_13 = new DataColumn();
            this.gridView1 = new GridView();
            this.CwwJoLjYp = new GridColumn();
            this.colfull_name = new GridColumn();
            this.colmin_qty = new GridColumn();
            this.colmax_qty = new GridColumn();
            this.coldisc_pc = new GridColumn();
            this.coldisc_value = new GridColumn();
            this.colnew_price = new GridColumn();
            this.colgift_qty = new GridColumn();
            this.colfr_date = new GridColumn();
            this.colto_date = new GridColumn();
            this.colfr_hour = new GridColumn();
            this.colto_hour = new GridColumn();
            this.colneed_card = new GridColumn();
            this.colstatus = new GridColumn();
            this.repositoryItemDateEdit1 = new RepositoryItemDateEdit();
            this.repositoryItemTimeEdit1 = new RepositoryItemTimeEdit();
            this.repositoryItemTextEdit1 = new RepositoryItemTextEdit();
            this.repositoryItemSpinEdit1 = new RepositoryItemSpinEdit();
            this.repositoryItemPopupContainerEdit1 = new RepositoryItemPopupContainerEdit();
            this.repositoryItemButtonEdit1 = new RepositoryItemButtonEdit();
            this.btnSave = new SimpleButton();
            this.LabelControl1 = new LabelControl();
            this.Txt_GoodsId = new TextEdit();
            this.Lbl_Lastimppr = new LabelControl();
            this.labelControl8 = new LabelControl();
            this.Lbl_WsPrice = new LabelControl();
            this.labelControl6 = new LabelControl();
            this.Lbl_Rtprice = new LabelControl();
            this.labelControl2 = new LabelControl();
            this.TgwIjsrYqS = new LabelControl();
            this.LabelControl15 = new LabelControl();
            this.LabelControl4 = new LabelControl();
            this.Lbl_SuppName = new LabelControl();
            this.Lbl_GrpName = new LabelControl();
            this.Lbl_SuppId = new LabelControl();
            this.Lbl_MercName = new LabelControl();
            this.Lbl_GrpId = new LabelControl();
            this.PicGoods = new PictureEdit();
            this.groupControl1 = new GroupControl();
            this.labelControl19 = new LabelControl();
            this.txtSurplusPc = new TextEdit();
            this.labelControl14 = new LabelControl();
            this.labelControl13 = new LabelControl();
            this.txtRtprice = new TextEdit();
            this.labelControl12 = new LabelControl();
            this.txtGiftQty = new TextEdit();
            this.labelControl11 = new LabelControl();
            this.txtNewPrice = new TextEdit();
            this.labelControl10 = new LabelControl();
            this.labelControl9 = new LabelControl();
            this.txtMaxQty = new TextEdit();
            this.labelControl3 = new LabelControl();
            this.txtMinQty = new TextEdit();
            this.LabelControl22 = new LabelControl();
            this.LabelControl7 = new LabelControl();
            this.txtDiscValue = new TextEdit();
            this.LabelControl18 = new LabelControl();
            this.txtDiscPc = new TextEdit();
            this.panelControl1 = new PanelControl();
            this.btn_Move = new SimpleButton();
            this.btn_Add = new SimpleButton();
            this.txtFrDate = new TextEdit();
            this.LabelControl17 = new LabelControl();
            this.txtToDate = new TextEdit();
            this.LabelControl16 = new LabelControl();
            this.gridControl1.BeginInit();
            this.dataSet_0.BeginInit();
            this.dataTable_0.BeginInit();
            this.gridView1.BeginInit();
            this.repositoryItemDateEdit1.BeginInit();
            this.repositoryItemDateEdit1.VistaTimeProperties.BeginInit();
            this.repositoryItemTimeEdit1.BeginInit();
            this.repositoryItemTextEdit1.BeginInit();
            this.repositoryItemSpinEdit1.BeginInit();
            this.repositoryItemPopupContainerEdit1.BeginInit();
            this.repositoryItemButtonEdit1.BeginInit();
            this.Txt_GoodsId.Properties.BeginInit();
            this.PicGoods.Properties.BeginInit();
            this.groupControl1.BeginInit();
            this.groupControl1.SuspendLayout();
            this.txtSurplusPc.Properties.BeginInit();
            this.txtRtprice.Properties.BeginInit();
            this.txtGiftQty.Properties.BeginInit();
            this.txtNewPrice.Properties.BeginInit();
            this.txtMaxQty.Properties.BeginInit();
            this.txtMinQty.Properties.BeginInit();
            this.txtDiscValue.Properties.BeginInit();
            this.txtDiscPc.Properties.BeginInit();
            this.panelControl1.BeginInit();
            this.panelControl1.SuspendLayout();
            this.txtFrDate.Properties.BeginInit();
            this.txtToDate.Properties.BeginInit();
            base.SuspendLayout();
            this.gridControl1.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.gridControl1.DataMember = "DISCINFO";
            this.gridControl1.DataSource = this.dataSet_0;
            this.gridControl1.Location = new Point(12, 0x11c);
            this.gridControl1.MainView = this.gridView1;
            this.gridControl1.Name = "gridControl1";
            this.gridControl1.RepositoryItems.AddRange(new RepositoryItem[] { this.repositoryItemDateEdit1, this.repositoryItemTimeEdit1, this.repositoryItemTextEdit1, this.repositoryItemSpinEdit1, this.repositoryItemPopupContainerEdit1, this.repositoryItemButtonEdit1 });
            this.gridControl1.Size = new Size(0x2b1, 0xb5);
            this.gridControl1.TabIndex = 0;
            this.gridControl1.ViewCollection.AddRange(new BaseView[] { this.gridView1 });
            this.dataSet_0.DataSetName = "NewDataSet";
            this.dataSet_0.EnforceConstraints = false;
            this.dataSet_0.Tables.AddRange(new DataTable[] { this.dataTable_0 });
            this.dataTable_0.Columns.AddRange(new DataColumn[] { this.dataColumn_0, this.dataColumn_1, this.dataColumn_2, this.ddvqeXfa4, this.dataColumn_3, this.dataColumn_4, this.dataColumn_5, this.dataColumn_6, this.dataColumn_7, this.dataColumn_8, this.welftZbha, this.dataColumn_9, this.dataColumn_10, this.dataColumn_11, this.dataColumn_12, this.dataColumn_13 });
            this.dataTable_0.Constraints.AddRange(new Constraint[] { new UniqueConstraint("Constraint1", new string[] { "goods_id" }, false) });
            this.dataTable_0.TableName = "DISCINFO";
            this.dataColumn_0.ColumnName = "goods_id";
            this.dataColumn_0.MaxLength = 6;
            this.dataColumn_1.Caption = "T\x00ean h\x00e0ng";
            this.dataColumn_1.ColumnName = "full_name";
            this.dataColumn_1.DefaultValue = "''";
            this.dataColumn_2.Caption = "SL tối thiểu";
            this.dataColumn_2.ColumnName = "min_qty";
            this.dataColumn_2.DataType = typeof(double);
            this.dataColumn_2.DefaultValue = 0.0;
            this.dataColumn_2.ReadOnly = true;
            this.ddvqeXfa4.Caption = "SL tối đa";
            this.ddvqeXfa4.ColumnName = "max_qty";
            this.ddvqeXfa4.DataType = typeof(double);
            this.ddvqeXfa4.DefaultValue = 0.0;
            this.dataColumn_3.Caption = "Gi\x00e1 b\x00e1n lẻ";
            this.dataColumn_3.ColumnName = "rtprice";
            this.dataColumn_3.DataType = typeof(double);
            this.dataColumn_3.DefaultValue = 0.0;
            this.dataColumn_4.Caption = "% CK";
            this.dataColumn_4.ColumnName = "disc_pc";
            this.dataColumn_4.DataType = typeof(double);
            this.dataColumn_4.DefaultValue = 0.0;
            this.dataColumn_5.Caption = "Gi\x00e1 trị CK";
            this.dataColumn_5.ColumnName = "disc_value";
            this.dataColumn_5.DataType = typeof(double);
            this.dataColumn_5.DefaultValue = 0.0;
            this.dataColumn_6.Caption = "Gi\x00e1 b\x00e1n mới";
            this.dataColumn_6.ColumnName = "new_price";
            this.dataColumn_6.DataType = typeof(double);
            this.dataColumn_6.DefaultValue = 0.0;
            this.dataColumn_7.Caption = "Tặng h\x00e0ng";
            this.dataColumn_7.ColumnName = "gift_qty";
            this.dataColumn_7.DataType = typeof(double);
            this.dataColumn_7.DefaultValue = 0.0;
            this.dataColumn_8.Caption = "Gi\x00e1 b\x00e1n thực tế";
            this.dataColumn_8.ColumnName = "real_value";
            this.dataColumn_8.DataType = typeof(double);
            this.dataColumn_8.DefaultValue = 0.0;
            this.welftZbha.Caption = "Từ ng\x00e0y";
            this.welftZbha.ColumnName = "fr_date";
            this.welftZbha.DataType = typeof(DateTime);
            this.welftZbha.DefaultValue = new DateTime(0x76c, 1, 1, 0, 0, 0, 0);
            this.dataColumn_9.Caption = "Đến ng\x00e0y";
            this.dataColumn_9.ColumnName = "to_date";
            this.dataColumn_9.DataType = typeof(DateTime);
            this.dataColumn_9.DefaultValue = new DateTime(0x76c, 1, 1, 0, 0, 0, 0);
            this.dataColumn_10.Caption = "Từ giờ";
            this.dataColumn_10.ColumnName = "fr_hour";
            this.dataColumn_10.DefaultValue = "00:00";
            this.dataColumn_10.MaxLength = 5;
            this.dataColumn_11.Caption = "Đến giờ";
            this.dataColumn_11.ColumnName = "to_hour";
            this.dataColumn_11.DefaultValue = "23:59";
            this.dataColumn_11.MaxLength = 5;
            this.dataColumn_12.Caption = "Y\x00eau cầu thẻ";
            this.dataColumn_12.ColumnName = "need_card";
            this.dataColumn_12.DataType = typeof(bool);
            this.dataColumn_12.DefaultValue = false;
            this.dataColumn_13.Caption = "Trạng th\x00e1i";
            this.dataColumn_13.ColumnName = "status";
            this.dataColumn_13.DataType = typeof(bool);
            this.dataColumn_13.DefaultValue = false;
            this.gridView1.Appearance.FooterPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.gridView1.Appearance.FooterPanel.Options.UseFont = true;
            this.gridView1.Appearance.HeaderPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.gridView1.Appearance.HeaderPanel.Options.UseFont = true;
            this.gridView1.Columns.AddRange(new GridColumn[] { this.CwwJoLjYp, this.colfull_name, this.colmin_qty, this.colmax_qty, this.coldisc_pc, this.coldisc_value, this.colnew_price, this.colgift_qty, this.colfr_date, this.colto_date, this.colfr_hour, this.colto_hour, this.colneed_card, this.colstatus });
            this.gridView1.GridControl = this.gridControl1;
            this.gridView1.Name = "gridView1";
            this.gridView1.OptionsView.ColumnAutoWidth = false;
            this.gridView1.OptionsView.ShowFooter = true;
            this.gridView1.OptionsView.ShowGroupPanel = false;
            this.CwwJoLjYp.AppearanceCell.BackColor = Color.Gainsboro;
            this.CwwJoLjYp.AppearanceCell.Options.UseBackColor = true;
            this.CwwJoLjYp.Caption = "M\x00e3 h\x00e0ng";
            this.CwwJoLjYp.FieldName = "goods_id";
            this.CwwJoLjYp.Fixed = FixedStyle.Left;
            this.CwwJoLjYp.Name = "colgoods_id";
            this.CwwJoLjYp.Visible = true;
            this.CwwJoLjYp.VisibleIndex = 0;
            this.colfull_name.AppearanceCell.BackColor = Color.WhiteSmoke;
            this.colfull_name.AppearanceCell.Options.UseBackColor = true;
            this.colfull_name.Caption = "T\x00ean h\x00e0ng";
            this.colfull_name.FieldName = "full_name";
            this.colfull_name.Fixed = FixedStyle.Left;
            this.colfull_name.Name = "colfull_name";
            this.colfull_name.OptionsColumn.AllowEdit = false;
            this.colfull_name.Visible = true;
            this.colfull_name.VisibleIndex = 1;
            this.colmin_qty.AppearanceCell.BackColor = Color.Transparent;
            this.colmin_qty.AppearanceCell.Options.UseBackColor = true;
            this.colmin_qty.Caption = "SL tối thiểu";
            this.colmin_qty.FieldName = "min_qty";
            this.colmin_qty.Name = "colmin_qty";
            this.colmin_qty.OptionsColumn.ReadOnly = true;
            this.colmin_qty.Visible = true;
            this.colmin_qty.VisibleIndex = 2;
            this.colmax_qty.AppearanceCell.BackColor = Color.Transparent;
            this.colmax_qty.AppearanceCell.Options.UseBackColor = true;
            this.colmax_qty.Caption = "SL tối đa";
            this.colmax_qty.FieldName = "max_qty";
            this.colmax_qty.Name = "colmax_qty";
            this.colmax_qty.Visible = true;
            this.colmax_qty.VisibleIndex = 3;
            this.coldisc_pc.AppearanceCell.BackColor = Color.Transparent;
            this.coldisc_pc.AppearanceCell.Options.UseBackColor = true;
            this.coldisc_pc.Caption = "%CK";
            this.coldisc_pc.FieldName = "disc_pc";
            this.coldisc_pc.Name = "coldisc_pc";
            this.coldisc_pc.Visible = true;
            this.coldisc_pc.VisibleIndex = 4;
            this.coldisc_value.AppearanceCell.BackColor = Color.Transparent;
            this.coldisc_value.AppearanceCell.Options.UseBackColor = true;
            this.coldisc_value.Caption = "Gi\x00e1 trị CK";
            this.coldisc_value.FieldName = "disc_value";
            this.coldisc_value.Name = "coldisc_value";
            this.coldisc_value.Visible = true;
            this.coldisc_value.VisibleIndex = 5;
            this.colnew_price.AppearanceCell.BackColor = Color.Transparent;
            this.colnew_price.AppearanceCell.Options.UseBackColor = true;
            this.colnew_price.Caption = "Gi\x00e1 b\x00e1n mới";
            this.colnew_price.FieldName = "new_price";
            this.colnew_price.Name = "colnew_price";
            this.colnew_price.Visible = true;
            this.colnew_price.VisibleIndex = 6;
            this.colgift_qty.AppearanceCell.BackColor = Color.Transparent;
            this.colgift_qty.AppearanceCell.Options.UseBackColor = true;
            this.colgift_qty.Caption = "Tặng h\x00e0ng";
            this.colgift_qty.FieldName = "gift_qty";
            this.colgift_qty.Name = "colgift_qty";
            this.colgift_qty.Visible = true;
            this.colgift_qty.VisibleIndex = 7;
            this.colfr_date.AppearanceCell.BackColor = Color.Transparent;
            this.colfr_date.AppearanceCell.Options.UseBackColor = true;
            this.colfr_date.FieldName = "fr_date";
            this.colfr_date.Name = "colfr_date";
            this.colfr_date.Visible = true;
            this.colfr_date.VisibleIndex = 8;
            this.colto_date.AppearanceCell.BackColor = Color.Transparent;
            this.colto_date.AppearanceCell.Options.UseBackColor = true;
            this.colto_date.FieldName = "to_date";
            this.colto_date.Name = "colto_date";
            this.colto_date.Visible = true;
            this.colto_date.VisibleIndex = 9;
            this.colfr_hour.AppearanceCell.BackColor = Color.Transparent;
            this.colfr_hour.AppearanceCell.Options.UseBackColor = true;
            this.colfr_hour.FieldName = "fr_hour";
            this.colfr_hour.Name = "colfr_hour";
            this.colfr_hour.Visible = true;
            this.colfr_hour.VisibleIndex = 10;
            this.colto_hour.AppearanceCell.BackColor = Color.Transparent;
            this.colto_hour.AppearanceCell.Options.UseBackColor = true;
            this.colto_hour.FieldName = "to_hour";
            this.colto_hour.Name = "colto_hour";
            this.colto_hour.Visible = true;
            this.colto_hour.VisibleIndex = 11;
            this.colneed_card.AppearanceCell.BackColor = Color.Transparent;
            this.colneed_card.AppearanceCell.Options.UseBackColor = true;
            this.colneed_card.FieldName = "need_card";
            this.colneed_card.Name = "colneed_card";
            this.colneed_card.Visible = true;
            this.colneed_card.VisibleIndex = 12;
            this.colstatus.AppearanceCell.BackColor = Color.Transparent;
            this.colstatus.AppearanceCell.Options.UseBackColor = true;
            this.colstatus.FieldName = "status";
            this.colstatus.Name = "colstatus";
            this.colstatus.Visible = true;
            this.colstatus.VisibleIndex = 13;
            this.repositoryItemDateEdit1.AutoHeight = false;
            this.repositoryItemDateEdit1.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.repositoryItemDateEdit1.Name = "repositoryItemDateEdit1";
            this.repositoryItemDateEdit1.VistaTimeProperties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.repositoryItemTimeEdit1.AutoHeight = false;
            this.repositoryItemTimeEdit1.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.repositoryItemTimeEdit1.Name = "repositoryItemTimeEdit1";
            this.repositoryItemTextEdit1.AutoHeight = false;
            this.repositoryItemTextEdit1.Name = "repositoryItemTextEdit1";
            this.repositoryItemTextEdit1.CustomDisplayText += new CustomDisplayTextEventHandler(this.repositoryItemTextEdit1_CustomDisplayText);
            this.repositoryItemTextEdit1.KeyDown += new KeyEventHandler(this.repositoryItemTextEdit1_KeyDown);
            this.repositoryItemSpinEdit1.AutoHeight = false;
            this.repositoryItemSpinEdit1.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.repositoryItemSpinEdit1.Name = "repositoryItemSpinEdit1";
            this.repositoryItemPopupContainerEdit1.AutoHeight = false;
            this.repositoryItemPopupContainerEdit1.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.repositoryItemPopupContainerEdit1.Name = "repositoryItemPopupContainerEdit1";
            this.repositoryItemPopupContainerEdit1.QueryResultValue += new QueryResultValueEventHandler(this.repositoryItemPopupContainerEdit1_QueryResultValue);
            this.repositoryItemPopupContainerEdit1.QueryDisplayText += new QueryDisplayTextEventHandler(this.repositoryItemPopupContainerEdit1_QueryDisplayText);
            this.repositoryItemPopupContainerEdit1.QueryPopUp += new CancelEventHandler(this.repositoryItemPopupContainerEdit1_QueryPopUp);
            this.repositoryItemPopupContainerEdit1.ButtonClick += new ButtonPressedEventHandler(this.repositoryItemPopupContainerEdit1_ButtonClick);
            this.repositoryItemButtonEdit1.AutoHeight = false;
            this.repositoryItemButtonEdit1.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.repositoryItemButtonEdit1.Name = "repositoryItemButtonEdit1";
            this.repositoryItemButtonEdit1.ButtonClick += new ButtonPressedEventHandler(this.repositoryItemButtonEdit1_ButtonClick);
            this.repositoryItemButtonEdit1.CustomDisplayText += new CustomDisplayTextEventHandler(this.repositoryItemButtonEdit1_CustomDisplayText);
            this.btnSave.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.btnSave.Location = new Point(0x13f, 0x1d7);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new Size(0x4b, 0x17);
            this.btnSave.TabIndex = 1;
            this.btnSave.Text = "&Lưu";
            this.btnSave.Click += new EventHandler(this.btnSave_Click);
            this.LabelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl1.Appearance.Options.UseFont = true;
            this.LabelControl1.Location = new Point(30, 15);
            this.LabelControl1.Name = "LabelControl1";
            this.LabelControl1.Size = new Size(0x2c, 13);
            this.LabelControl1.TabIndex = 0x17e;
            this.LabelControl1.Text = "M\x00e3 h\x00e0ng ";
            this.Txt_GoodsId.EnterMoveNextControl = true;
            this.Txt_GoodsId.Location = new Point(0x8d, 12);
            this.Txt_GoodsId.Name = "Txt_GoodsId";
            this.Txt_GoodsId.Properties.Appearance.BackColor = Color.PapayaWhip;
            this.Txt_GoodsId.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_GoodsId.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_GoodsId.Properties.Appearance.Options.UseFont = true;
            this.Txt_GoodsId.Properties.Mask.PlaceHolder = ' ';
            this.Txt_GoodsId.Properties.MaxLength = 20;
            this.Txt_GoodsId.Properties.ValidateOnEnterKey = true;
            this.Txt_GoodsId.Size = new Size(0x7b, 20);
            this.Txt_GoodsId.TabIndex = 0x17d;
            this.Txt_GoodsId.ToolTip = "Ấn F5 để t\x00ecm kiếm";
            this.Txt_GoodsId.ToolTipIconType = ToolTipIconType.Information;
            this.Txt_GoodsId.ToolTipTitle = "Lưu \x00fd";
            this.Txt_GoodsId.KeyDown += new KeyEventHandler(this.Txt_GoodsId_KeyDown);
            this.Lbl_Lastimppr.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Lastimppr.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Lastimppr.Appearance.BorderColor = Color.White;
            this.Lbl_Lastimppr.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Lastimppr.Appearance.ForeColor = Color.Black;
            this.Lbl_Lastimppr.Appearance.Options.UseBackColor = true;
            this.Lbl_Lastimppr.Appearance.Options.UseBorderColor = true;
            this.Lbl_Lastimppr.Appearance.Options.UseFont = true;
            this.Lbl_Lastimppr.Appearance.Options.UseForeColor = true;
            this.Lbl_Lastimppr.Appearance.Options.UseTextOptions = true;
            this.Lbl_Lastimppr.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_Lastimppr.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Lastimppr.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Lastimppr.Location = new Point(0x8d, 0x77);
            this.Lbl_Lastimppr.Name = "Lbl_Lastimppr";
            this.Lbl_Lastimppr.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_Lastimppr.Size = new Size(100, 0x11);
            this.Lbl_Lastimppr.TabIndex = 0x18c;
            this.labelControl8.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl8.Appearance.Options.UseFont = true;
            this.labelControl8.Location = new Point(30, 0x7a);
            this.labelControl8.Name = "labelControl8";
            this.labelControl8.Size = new Size(0x51, 13);
            this.labelControl8.TabIndex = 0x18b;
            this.labelControl8.Text = "Gi\x00e1 nhập lần cuối";
            this.Lbl_WsPrice.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_WsPrice.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_WsPrice.Appearance.BorderColor = Color.White;
            this.Lbl_WsPrice.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_WsPrice.Appearance.ForeColor = Color.Black;
            this.Lbl_WsPrice.Appearance.Options.UseBackColor = true;
            this.Lbl_WsPrice.Appearance.Options.UseBorderColor = true;
            this.Lbl_WsPrice.Appearance.Options.UseFont = true;
            this.Lbl_WsPrice.Appearance.Options.UseForeColor = true;
            this.Lbl_WsPrice.Appearance.Options.UseTextOptions = true;
            this.Lbl_WsPrice.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_WsPrice.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_WsPrice.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_WsPrice.Location = new Point(0x174, 0x62);
            this.Lbl_WsPrice.Name = "Lbl_WsPrice";
            this.Lbl_WsPrice.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_WsPrice.Size = new Size(110, 0x11);
            this.Lbl_WsPrice.TabIndex = 0x18a;
            this.Lbl_WsPrice.Visible = false;
            this.labelControl6.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl6.Appearance.Options.UseFont = true;
            this.labelControl6.Location = new Point(0x129, 0x65);
            this.labelControl6.Name = "labelControl6";
            this.labelControl6.Size = new Size(0x3f, 13);
            this.labelControl6.TabIndex = 0x189;
            this.labelControl6.Text = "Gi\x00e1 b\x00e1n bu\x00f4n";
            this.labelControl6.Visible = false;
            this.Lbl_Rtprice.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Rtprice.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Rtprice.Appearance.BorderColor = Color.White;
            this.Lbl_Rtprice.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Rtprice.Appearance.ForeColor = Color.Black;
            this.Lbl_Rtprice.Appearance.Options.UseBackColor = true;
            this.Lbl_Rtprice.Appearance.Options.UseBorderColor = true;
            this.Lbl_Rtprice.Appearance.Options.UseFont = true;
            this.Lbl_Rtprice.Appearance.Options.UseForeColor = true;
            this.Lbl_Rtprice.Appearance.Options.UseTextOptions = true;
            this.Lbl_Rtprice.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_Rtprice.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Rtprice.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Rtprice.Location = new Point(0x8d, 0x62);
            this.Lbl_Rtprice.Name = "Lbl_Rtprice";
            this.Lbl_Rtprice.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_Rtprice.Size = new Size(100, 0x11);
            this.Lbl_Rtprice.TabIndex = 0x188;
            this.labelControl2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl2.Appearance.Options.UseFont = true;
            this.labelControl2.Location = new Point(30, 100);
            this.labelControl2.Name = "labelControl2";
            this.labelControl2.Size = new Size(0x2f, 13);
            this.labelControl2.TabIndex = 0x187;
            this.labelControl2.Text = "Gi\x00e1 b\x00e1n lẻ";
            this.TgwIjsrYqS.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.TgwIjsrYqS.Appearance.Options.UseFont = true;
            this.TgwIjsrYqS.Location = new Point(30, 0x3a);
            this.TgwIjsrYqS.Name = "LabelControl5";
            this.TgwIjsrYqS.Size = new Size(0x3a, 13);
            this.TgwIjsrYqS.TabIndex = 0x181;
            this.TgwIjsrYqS.Text = "Thuộc nh\x00f3m";
            this.LabelControl15.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl15.Appearance.Options.UseFont = true;
            this.LabelControl15.Location = new Point(30, 0x25);
            this.LabelControl15.Name = "LabelControl15";
            this.LabelControl15.Size = new Size(0x42, 13);
            this.LabelControl15.TabIndex = 0x17f;
            this.LabelControl15.Text = "T\x00ean h\x00e0ng h\x00f3a";
            this.LabelControl4.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl4.Appearance.Options.UseFont = true;
            this.LabelControl4.Location = new Point(30, 0x4f);
            this.LabelControl4.Name = "LabelControl4";
            this.LabelControl4.Size = new Size(0x41, 13);
            this.LabelControl4.TabIndex = 0x180;
            this.LabelControl4.Text = "Nh\x00e0 cung cấp";
            this.Lbl_SuppName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_SuppName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_SuppName.Appearance.BorderColor = Color.White;
            this.Lbl_SuppName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_SuppName.Appearance.ForeColor = Color.Black;
            this.Lbl_SuppName.Appearance.Options.UseBackColor = true;
            this.Lbl_SuppName.Appearance.Options.UseBorderColor = true;
            this.Lbl_SuppName.Appearance.Options.UseFont = true;
            this.Lbl_SuppName.Appearance.Options.UseForeColor = true;
            this.Lbl_SuppName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_SuppName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_SuppName.Location = new Point(0xe2, 0x4d);
            this.Lbl_SuppName.Name = "Lbl_SuppName";
            this.Lbl_SuppName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_SuppName.Size = new Size(0x100, 0x11);
            this.Lbl_SuppName.TabIndex = 0x182;
            this.Lbl_GrpName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_GrpName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_GrpName.Appearance.BorderColor = Color.White;
            this.Lbl_GrpName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_GrpName.Appearance.ForeColor = Color.Black;
            this.Lbl_GrpName.Appearance.Options.UseBackColor = true;
            this.Lbl_GrpName.Appearance.Options.UseBorderColor = true;
            this.Lbl_GrpName.Appearance.Options.UseFont = true;
            this.Lbl_GrpName.Appearance.Options.UseForeColor = true;
            this.Lbl_GrpName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_GrpName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_GrpName.Location = new Point(0xe2, 0x38);
            this.Lbl_GrpName.Name = "Lbl_GrpName";
            this.Lbl_GrpName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_GrpName.Size = new Size(0x100, 0x11);
            this.Lbl_GrpName.TabIndex = 0x183;
            this.Lbl_SuppId.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_SuppId.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_SuppId.Appearance.BorderColor = Color.White;
            this.Lbl_SuppId.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_SuppId.Appearance.ForeColor = Color.Black;
            this.Lbl_SuppId.Appearance.Options.UseBackColor = true;
            this.Lbl_SuppId.Appearance.Options.UseBorderColor = true;
            this.Lbl_SuppId.Appearance.Options.UseFont = true;
            this.Lbl_SuppId.Appearance.Options.UseForeColor = true;
            this.Lbl_SuppId.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_SuppId.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_SuppId.Location = new Point(0x8d, 0x4d);
            this.Lbl_SuppId.Name = "Lbl_SuppId";
            this.Lbl_SuppId.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_SuppId.Size = new Size(0x4f, 0x11);
            this.Lbl_SuppId.TabIndex = 390;
            this.Lbl_MercName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_MercName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_MercName.Appearance.BorderColor = Color.White;
            this.Lbl_MercName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_MercName.Appearance.ForeColor = Color.Black;
            this.Lbl_MercName.Appearance.Options.UseBackColor = true;
            this.Lbl_MercName.Appearance.Options.UseBorderColor = true;
            this.Lbl_MercName.Appearance.Options.UseFont = true;
            this.Lbl_MercName.Appearance.Options.UseForeColor = true;
            this.Lbl_MercName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_MercName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_MercName.Location = new Point(0x8d, 0x23);
            this.Lbl_MercName.Name = "Lbl_MercName";
            this.Lbl_MercName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_MercName.Size = new Size(0x155, 0x11);
            this.Lbl_MercName.TabIndex = 0x184;
            this.Lbl_GrpId.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_GrpId.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_GrpId.Appearance.BorderColor = Color.White;
            this.Lbl_GrpId.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_GrpId.Appearance.ForeColor = Color.Black;
            this.Lbl_GrpId.Appearance.Options.UseBackColor = true;
            this.Lbl_GrpId.Appearance.Options.UseBorderColor = true;
            this.Lbl_GrpId.Appearance.Options.UseFont = true;
            this.Lbl_GrpId.Appearance.Options.UseForeColor = true;
            this.Lbl_GrpId.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_GrpId.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_GrpId.Location = new Point(0x8d, 0x37);
            this.Lbl_GrpId.Name = "Lbl_GrpId";
            this.Lbl_GrpId.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_GrpId.Size = new Size(0x4f, 0x11);
            this.Lbl_GrpId.TabIndex = 0x185;
            this.PicGoods.Cursor = Cursors.Hand;
            this.PicGoods.Location = new Point(0x225, 15);
            this.PicGoods.Name = "PicGoods";
            this.PicGoods.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.PicGoods.Properties.Appearance.Options.UseFont = true;
            this.PicGoods.Properties.SizeMode = PictureSizeMode.Zoom;
            this.PicGoods.Size = new Size(0x74, 120);
            this.PicGoods.TabIndex = 0x18d;
            this.groupControl1.Controls.Add(this.labelControl19);
            this.groupControl1.Controls.Add(this.txtSurplusPc);
            this.groupControl1.Controls.Add(this.labelControl14);
            this.groupControl1.Controls.Add(this.labelControl13);
            this.groupControl1.Controls.Add(this.txtRtprice);
            this.groupControl1.Controls.Add(this.labelControl12);
            this.groupControl1.Controls.Add(this.txtGiftQty);
            this.groupControl1.Controls.Add(this.labelControl11);
            this.groupControl1.Controls.Add(this.txtNewPrice);
            this.groupControl1.Controls.Add(this.labelControl10);
            this.groupControl1.Controls.Add(this.labelControl9);
            this.groupControl1.Controls.Add(this.txtMaxQty);
            this.groupControl1.Controls.Add(this.labelControl3);
            this.groupControl1.Controls.Add(this.txtMinQty);
            this.groupControl1.Controls.Add(this.LabelControl22);
            this.groupControl1.Controls.Add(this.LabelControl7);
            this.groupControl1.Controls.Add(this.txtDiscValue);
            this.groupControl1.Controls.Add(this.LabelControl18);
            this.groupControl1.Controls.Add(this.txtDiscPc);
            this.groupControl1.Location = new Point(12, 0x8d);
            this.groupControl1.Name = "groupControl1";
            this.groupControl1.Size = new Size(0x2b1, 100);
            this.groupControl1.TabIndex = 0x191;
            this.groupControl1.Text = "Th\x00f4ng tin khuyến mại";
            this.labelControl19.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.labelControl19.Appearance.ForeColor = Color.SteelBlue;
            this.labelControl19.Appearance.Options.UseFont = true;
            this.labelControl19.Appearance.Options.UseForeColor = true;
            this.labelControl19.Location = new Point(0x1bb, 0x35);
            this.labelControl19.Name = "labelControl19";
            this.labelControl19.Size = new Size(0x2b, 13);
            this.labelControl19.TabIndex = 0x1a8;
            this.labelControl19.Text = "Tỷ lệ l\x00e3i";
            int[] bits1 = new int[4];
            this.txtSurplusPc.EditValue = new decimal(bits1);
            this.txtSurplusPc.EnterMoveNextControl = true;
            this.txtSurplusPc.Location = new Point(0x209, 50);
            this.txtSurplusPc.Name = "txtSurplusPc";
            this.txtSurplusPc.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtSurplusPc.Properties.Appearance.Options.UseFont = true;
            this.txtSurplusPc.Properties.Appearance.Options.UseTextOptions = true;
            this.txtSurplusPc.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.txtSurplusPc.Properties.DisplayFormat.FormatString = "P1";
            this.txtSurplusPc.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtSurplusPc.Properties.EditFormat.FormatString = "P1";
            this.txtSurplusPc.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.txtSurplusPc.Properties.Mask.EditMask = "P1";
            this.txtSurplusPc.Properties.Mask.MaskType = MaskType.Numeric;
            this.txtSurplusPc.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtSurplusPc.Size = new Size(0x59, 20);
            this.txtSurplusPc.TabIndex = 0x1a7;
            this.labelControl14.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl14.Appearance.Options.UseFont = true;
            this.labelControl14.Location = new Point(0x267, 0x20);
            this.labelControl14.Name = "labelControl14";
            this.labelControl14.Size = new Size(20, 13);
            this.labelControl14.TabIndex = 0x1a6;
            this.labelControl14.Text = "VND";
            this.labelControl14.Visible = false;
            this.labelControl13.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl13.Appearance.Options.UseFont = true;
            this.labelControl13.Location = new Point(0x179, 0x4c);
            this.labelControl13.Name = "labelControl13";
            this.labelControl13.Size = new Size(20, 13);
            this.labelControl13.TabIndex = 0x1a5;
            this.labelControl13.Text = "VND";
            this.labelControl13.Visible = false;
            this.txtRtprice.EditValue = "0";
            this.txtRtprice.EnterMoveNextControl = true;
            this.txtRtprice.Location = new Point(0x209, 0x1b);
            this.txtRtprice.Name = "txtRtprice";
            this.txtRtprice.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtRtprice.Properties.Appearance.Options.UseFont = true;
            this.txtRtprice.Properties.Appearance.Options.UseTextOptions = true;
            this.txtRtprice.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.txtRtprice.Properties.DisplayFormat.FormatString = "n2";
            this.txtRtprice.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtRtprice.Properties.EditFormat.FormatString = "n2";
            this.txtRtprice.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.txtRtprice.Properties.Mask.EditMask = "n2";
            this.txtRtprice.Properties.Mask.MaskType = MaskType.Numeric;
            this.txtRtprice.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtRtprice.Size = new Size(0x58, 20);
            this.txtRtprice.TabIndex = 420;
            this.labelControl12.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.labelControl12.Appearance.ForeColor = Color.SteelBlue;
            this.labelControl12.Appearance.Options.UseFont = true;
            this.labelControl12.Appearance.Options.UseForeColor = true;
            this.labelControl12.Location = new Point(0x1bb, 30);
            this.labelControl12.Name = "labelControl12";
            this.labelControl12.Size = new Size(0x3a, 13);
            this.labelControl12.TabIndex = 0x1a3;
            this.labelControl12.Text = "Gi\x00e1 sau CK";
            this.txtGiftQty.EditValue = "0";
            this.txtGiftQty.EnterMoveNextControl = true;
            this.txtGiftQty.Location = new Point(0x80, 0x49);
            this.txtGiftQty.Name = "txtGiftQty";
            this.txtGiftQty.Properties.Appearance.BackColor = Color.Aquamarine;
            this.txtGiftQty.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtGiftQty.Properties.Appearance.Options.UseBackColor = true;
            this.txtGiftQty.Properties.Appearance.Options.UseFont = true;
            this.txtGiftQty.Properties.Appearance.Options.UseTextOptions = true;
            this.txtGiftQty.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.txtGiftQty.Properties.DisplayFormat.FormatString = "n2";
            this.txtGiftQty.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtGiftQty.Properties.EditFormat.FormatString = "n2";
            this.txtGiftQty.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.txtGiftQty.Properties.Mask.EditMask = "n2";
            this.txtGiftQty.Properties.Mask.MaskType = MaskType.Numeric;
            this.txtGiftQty.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtGiftQty.Size = new Size(50, 20);
            this.txtGiftQty.TabIndex = 2;
            this.labelControl11.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl11.Appearance.Options.UseFont = true;
            this.labelControl11.Location = new Point(0x11, 0x4c);
            this.labelControl11.Name = "labelControl11";
            this.labelControl11.Size = new Size(0x33, 13);
            this.labelControl11.TabIndex = 0x1a2;
            this.labelControl11.Text = "Tặng h\x00e0ng";
            this.txtNewPrice.EditValue = "0";
            this.txtNewPrice.EnterMoveNextControl = true;
            this.txtNewPrice.Location = new Point(0x132, 0x49);
            this.txtNewPrice.Name = "txtNewPrice";
            this.txtNewPrice.Properties.Appearance.BackColor = Color.Aquamarine;
            this.txtNewPrice.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtNewPrice.Properties.Appearance.Options.UseBackColor = true;
            this.txtNewPrice.Properties.Appearance.Options.UseFont = true;
            this.txtNewPrice.Properties.Appearance.Options.UseTextOptions = true;
            this.txtNewPrice.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.txtNewPrice.Properties.DisplayFormat.FormatString = "n2";
            this.txtNewPrice.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtNewPrice.Properties.EditFormat.FormatString = "n2";
            this.txtNewPrice.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.txtNewPrice.Properties.Mask.EditMask = "n2";
            this.txtNewPrice.Properties.Mask.MaskType = MaskType.Numeric;
            this.txtNewPrice.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtNewPrice.Size = new Size(0x41, 20);
            this.txtNewPrice.TabIndex = 5;
            this.labelControl10.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl10.Appearance.Options.UseFont = true;
            this.labelControl10.Location = new Point(220, 0x4c);
            this.labelControl10.Name = "labelControl10";
            this.labelControl10.Size = new Size(0x37, 13);
            this.labelControl10.TabIndex = 0x1a0;
            this.labelControl10.Text = "Gi\x00e1 b\x00e1n mới";
            this.labelControl9.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl9.Appearance.Options.UseFont = true;
            this.labelControl9.Location = new Point(0x179, 0x35);
            this.labelControl9.Name = "labelControl9";
            this.labelControl9.Size = new Size(20, 13);
            this.labelControl9.TabIndex = 0x19e;
            this.labelControl9.Text = "VND";
            this.labelControl9.Visible = false;
            this.txtMaxQty.EditValue = "0";
            this.txtMaxQty.EnterMoveNextControl = true;
            this.txtMaxQty.Location = new Point(0x80, 50);
            this.txtMaxQty.Name = "txtMaxQty";
            this.txtMaxQty.Properties.Appearance.BackColor = Color.Aquamarine;
            this.txtMaxQty.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtMaxQty.Properties.Appearance.Options.UseBackColor = true;
            this.txtMaxQty.Properties.Appearance.Options.UseFont = true;
            this.txtMaxQty.Properties.Appearance.Options.UseTextOptions = true;
            this.txtMaxQty.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.txtMaxQty.Properties.DisplayFormat.FormatString = "n2";
            this.txtMaxQty.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtMaxQty.Properties.EditFormat.FormatString = "n2";
            this.txtMaxQty.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.txtMaxQty.Properties.Mask.EditMask = "n2";
            this.txtMaxQty.Properties.Mask.MaskType = MaskType.Numeric;
            this.txtMaxQty.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtMaxQty.Size = new Size(50, 20);
            this.txtMaxQty.TabIndex = 1;
            this.labelControl3.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl3.Appearance.Options.UseFont = true;
            this.labelControl3.Location = new Point(0x11, 0x35);
            this.labelControl3.Name = "labelControl3";
            this.labelControl3.Size = new Size(0x29, 13);
            this.labelControl3.TabIndex = 0x19d;
            this.labelControl3.Text = "SL tối đa";
            this.txtMinQty.EditValue = "0";
            this.txtMinQty.EnterMoveNextControl = true;
            this.txtMinQty.Location = new Point(0x80, 0x1b);
            this.txtMinQty.Name = "txtMinQty";
            this.txtMinQty.Properties.Appearance.BackColor = Color.Aquamarine;
            this.txtMinQty.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtMinQty.Properties.Appearance.Options.UseBackColor = true;
            this.txtMinQty.Properties.Appearance.Options.UseFont = true;
            this.txtMinQty.Properties.Appearance.Options.UseTextOptions = true;
            this.txtMinQty.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.txtMinQty.Properties.DisplayFormat.FormatString = "n2";
            this.txtMinQty.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtMinQty.Properties.EditFormat.FormatString = "n2";
            this.txtMinQty.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.txtMinQty.Properties.Mask.EditMask = "n2";
            this.txtMinQty.Properties.Mask.MaskType = MaskType.Numeric;
            this.txtMinQty.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtMinQty.Size = new Size(50, 20);
            this.txtMinQty.TabIndex = 0;
            this.LabelControl22.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl22.Appearance.Options.UseFont = true;
            this.LabelControl22.Location = new Point(0x11, 30);
            this.LabelControl22.Name = "LabelControl22";
            this.LabelControl22.Size = new Size(0x35, 13);
            this.LabelControl22.TabIndex = 0x19b;
            this.LabelControl22.Text = "SL tối thiểu";
            this.LabelControl7.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl7.Appearance.Options.UseFont = true;
            this.LabelControl7.Location = new Point(220, 0x35);
            this.LabelControl7.Name = "LabelControl7";
            this.LabelControl7.Size = new Size(0x4e, 13);
            this.LabelControl7.TabIndex = 0x198;
            this.LabelControl7.Text = "Giảm theo gi\x00e1 trị";
            this.txtDiscValue.EditValue = "";
            this.txtDiscValue.EnterMoveNextControl = true;
            this.txtDiscValue.Location = new Point(0x132, 50);
            this.txtDiscValue.Name = "txtDiscValue";
            this.txtDiscValue.Properties.Appearance.BackColor = Color.Aquamarine;
            this.txtDiscValue.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtDiscValue.Properties.Appearance.Options.UseBackColor = true;
            this.txtDiscValue.Properties.Appearance.Options.UseFont = true;
            this.txtDiscValue.Properties.Appearance.Options.UseTextOptions = true;
            this.txtDiscValue.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.txtDiscValue.Properties.DisplayFormat.FormatString = "n0";
            this.txtDiscValue.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtDiscValue.Properties.EditFormat.FormatString = "n0";
            this.txtDiscValue.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.txtDiscValue.Properties.Mask.EditMask = "n0";
            this.txtDiscValue.Properties.Mask.MaskType = MaskType.Numeric;
            this.txtDiscValue.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtDiscValue.Size = new Size(0x41, 20);
            this.txtDiscValue.TabIndex = 4;
            this.LabelControl18.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl18.Appearance.Options.UseFont = true;
            this.LabelControl18.Location = new Point(0xdd, 30);
            this.LabelControl18.Name = "LabelControl18";
            this.LabelControl18.Size = new Size(0x3e, 13);
            this.LabelControl18.TabIndex = 0x196;
            this.LabelControl18.Text = "Giảm theo %";
            int[] bits2 = new int[4];
            this.txtDiscPc.EditValue = new decimal(bits2);
            this.txtDiscPc.EnterMoveNextControl = true;
            this.txtDiscPc.Location = new Point(0x132, 0x1b);
            this.txtDiscPc.Name = "txtDiscPc";
            this.txtDiscPc.Properties.Appearance.BackColor = Color.Aquamarine;
            this.txtDiscPc.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtDiscPc.Properties.Appearance.Options.UseBackColor = true;
            this.txtDiscPc.Properties.Appearance.Options.UseFont = true;
            this.txtDiscPc.Properties.Appearance.Options.UseTextOptions = true;
            this.txtDiscPc.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.txtDiscPc.Properties.DisplayFormat.FormatString = "P1";
            this.txtDiscPc.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.txtDiscPc.Properties.EditFormat.FormatString = "P1";
            this.txtDiscPc.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.txtDiscPc.Properties.Mask.EditMask = "P1";
            this.txtDiscPc.Properties.Mask.MaskType = MaskType.Numeric;
            this.txtDiscPc.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtDiscPc.Size = new Size(0x41, 20);
            this.txtDiscPc.TabIndex = 3;
            this.panelControl1.BorderStyle = BorderStyles.Style3D;
            this.panelControl1.Controls.Add(this.btn_Move);
            this.panelControl1.Controls.Add(this.btn_Add);
            this.panelControl1.Controls.Add(this.txtFrDate);
            this.panelControl1.Controls.Add(this.LabelControl17);
            this.panelControl1.Controls.Add(this.txtToDate);
            this.panelControl1.Controls.Add(this.LabelControl16);
            this.panelControl1.Location = new Point(12, 0xf5);
            this.panelControl1.Name = "panelControl1";
            this.panelControl1.Size = new Size(0x2b1, 0x23);
            this.panelControl1.TabIndex = 0x19c;
            this.btn_Move.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btn_Move.Appearance.ForeColor = Color.OrangeRed;
            this.btn_Move.Appearance.Options.UseFont = true;
            this.btn_Move.Appearance.Options.UseForeColor = true;
            this.btn_Move.Location = new Point(530, 7);
            this.btn_Move.Name = "btn_Move";
            this.btn_Move.Size = new Size(0x4b, 20);
            this.btn_Move.TabIndex = 0x1a1;
            this.btn_Move.Text = "Loại bỏ";
            this.btn_Add.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btn_Add.Appearance.ForeColor = Color.Blue;
            this.btn_Add.Appearance.Options.UseFont = true;
            this.btn_Add.Appearance.Options.UseForeColor = true;
            this.btn_Add.Location = new Point(0x261, 7);
            this.btn_Add.Name = "btn_Add";
            this.btn_Add.Size = new Size(0x4b, 20);
            this.btn_Add.TabIndex = 0x19e;
            this.btn_Add.Text = "Th\x00eam";
            this.txtFrDate.EditValue = new DateTime(0x7d8, 4, 0x18, 13, 0x34, 0x2b, 0x1a5);
            this.txtFrDate.EnterMoveNextControl = true;
            this.txtFrDate.Location = new Point(0x11c, 7);
            this.txtFrDate.Name = "txtFrDate";
            this.txtFrDate.Properties.Appearance.BackColor = Color.PapayaWhip;
            this.txtFrDate.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtFrDate.Properties.Appearance.Options.UseBackColor = true;
            this.txtFrDate.Properties.Appearance.Options.UseFont = true;
            this.txtFrDate.Properties.DisplayFormat.FormatString = "dd/MM/yyyy";
            this.txtFrDate.Properties.DisplayFormat.FormatType = FormatType.DateTime;
            this.txtFrDate.Properties.EditFormat.FormatString = "dd/MM/yyyy";
            this.txtFrDate.Properties.EditFormat.FormatType = FormatType.DateTime;
            this.txtFrDate.Properties.Mask.EditMask = "dd/MM/yyyy";
            this.txtFrDate.Properties.Mask.MaskType = MaskType.DateTime;
            this.txtFrDate.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtFrDate.Size = new Size(70, 20);
            this.txtFrDate.TabIndex = 0x19c;
            this.LabelControl17.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.LabelControl17.Appearance.Options.UseFont = true;
            this.LabelControl17.Location = new Point(0xe1, 10);
            this.LabelControl17.Name = "LabelControl17";
            this.LabelControl17.Size = new Size(0x2e, 13);
            this.LabelControl17.TabIndex = 0x1a0;
            this.LabelControl17.Text = "Từ ng\x00e0y";
            this.txtToDate.EditValue = new DateTime(0x7d8, 4, 0x18, 13, 0x34, 0x2b, 0x1a5);
            this.txtToDate.EnterMoveNextControl = true;
            this.txtToDate.Location = new Point(0x1b9, 7);
            this.txtToDate.Name = "txtToDate";
            this.txtToDate.Properties.Appearance.BackColor = Color.PapayaWhip;
            this.txtToDate.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtToDate.Properties.Appearance.Options.UseBackColor = true;
            this.txtToDate.Properties.Appearance.Options.UseFont = true;
            this.txtToDate.Properties.DisplayFormat.FormatString = "dd/MM/yyyy";
            this.txtToDate.Properties.DisplayFormat.FormatType = FormatType.DateTime;
            this.txtToDate.Properties.EditFormat.FormatString = "dd/MM/yyyy";
            this.txtToDate.Properties.EditFormat.FormatType = FormatType.DateTime;
            this.txtToDate.Properties.Mask.EditMask = "dd/MM/yyyy";
            this.txtToDate.Properties.Mask.MaskType = MaskType.DateTime;
            this.txtToDate.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.txtToDate.Size = new Size(0x47, 20);
            this.txtToDate.TabIndex = 0x19d;
            this.LabelControl16.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.LabelControl16.Appearance.Options.UseFont = true;
            this.LabelControl16.Location = new Point(0x17d, 10);
            this.LabelControl16.Name = "LabelControl16";
            this.LabelControl16.Size = new Size(0x36, 13);
            this.LabelControl16.TabIndex = 0x19f;
            this.LabelControl16.Text = "Đến ng\x00e0y";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(0x2c9, 0x1f5);
            base.Controls.Add(this.panelControl1);
            base.Controls.Add(this.groupControl1);
            base.Controls.Add(this.PicGoods);
            base.Controls.Add(this.Lbl_Lastimppr);
            base.Controls.Add(this.labelControl8);
            base.Controls.Add(this.Lbl_WsPrice);
            base.Controls.Add(this.labelControl6);
            base.Controls.Add(this.Lbl_Rtprice);
            base.Controls.Add(this.labelControl2);
            base.Controls.Add(this.TgwIjsrYqS);
            base.Controls.Add(this.LabelControl15);
            base.Controls.Add(this.LabelControl4);
            base.Controls.Add(this.Lbl_SuppName);
            base.Controls.Add(this.Lbl_GrpName);
            base.Controls.Add(this.Lbl_SuppId);
            base.Controls.Add(this.Lbl_MercName);
            base.Controls.Add(this.Lbl_GrpId);
            base.Controls.Add(this.LabelControl1);
            base.Controls.Add(this.Txt_GoodsId);
            base.Controls.Add(this.btnSave);
            base.Controls.Add(this.gridControl1);
            base.Name = "FrmDiscInfo";
            this.Text = "FrmDiscInfo";
            base.Load += new EventHandler(this.FrmDiscInfo_Load);
            this.gridControl1.EndInit();
            this.dataSet_0.EndInit();
            this.dataTable_0.EndInit();
            this.gridView1.EndInit();
            this.repositoryItemDateEdit1.VistaTimeProperties.EndInit();
            this.repositoryItemDateEdit1.EndInit();
            this.repositoryItemTimeEdit1.EndInit();
            this.repositoryItemTextEdit1.EndInit();
            this.repositoryItemSpinEdit1.EndInit();
            this.repositoryItemPopupContainerEdit1.EndInit();
            this.repositoryItemButtonEdit1.EndInit();
            this.Txt_GoodsId.Properties.EndInit();
            this.PicGoods.Properties.EndInit();
            this.groupControl1.EndInit();
            this.groupControl1.ResumeLayout(false);
            this.groupControl1.PerformLayout();
            this.txtSurplusPc.Properties.EndInit();
            this.txtRtprice.Properties.EndInit();
            this.txtGiftQty.Properties.EndInit();
            this.txtNewPrice.Properties.EndInit();
            this.txtMaxQty.Properties.EndInit();
            this.txtMinQty.Properties.EndInit();
            this.txtDiscValue.Properties.EndInit();
            this.txtDiscPc.Properties.EndInit();
            this.panelControl1.EndInit();
            this.panelControl1.ResumeLayout(false);
            this.panelControl1.PerformLayout();
            this.txtFrDate.Properties.EndInit();
            this.txtToDate.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
        internal SimpleButton btn_Add;
        internal SimpleButton btn_Move;
        private SimpleButton btnSave;
        private GridColumn coldisc_pc;
        private GridColumn coldisc_value;
        private GridColumn colfr_date;
        private GridColumn colfr_hour;
        private GridColumn colfull_name;
        private GridColumn colgift_qty;
        private GridColumn colmax_qty;
        private GridColumn colmin_qty;
        private GridColumn colneed_card;
        private GridColumn colnew_price;
        private GridColumn colstatus;
        private GridColumn colto_date;
        private GridColumn colto_hour;
        private GridColumn CwwJoLjYp;
        private DataColumn dataColumn_0;
        private DataColumn dataColumn_1;
        private DataColumn dataColumn_10;
        private DataColumn dataColumn_11;
        private DataColumn dataColumn_12;
        private DataColumn dataColumn_13;
        private DataColumn dataColumn_2;
        private DataColumn dataColumn_3;
        private DataColumn dataColumn_4;
        private DataColumn dataColumn_5;
        private DataColumn dataColumn_6;
        private DataColumn dataColumn_7;
        private DataColumn dataColumn_8;
        private DataColumn dataColumn_9;
        private DataSet dataSet_0;
        private DataTable dataTable_0;
        private DataColumn ddvqeXfa4;
        private GridControl gridControl1;
        private GridView gridView1;
        private GroupControl groupControl1;
        //private IContainer components;
        internal LabelControl LabelControl1;
        internal LabelControl labelControl10;
        internal LabelControl labelControl11;
        internal LabelControl labelControl12;
        internal LabelControl labelControl13;
        internal LabelControl labelControl14;
        internal LabelControl LabelControl15;
        internal LabelControl LabelControl16;
        internal LabelControl LabelControl17;
        internal LabelControl LabelControl18;
        internal LabelControl labelControl19;
        internal LabelControl labelControl2;
        internal LabelControl LabelControl22;
        internal LabelControl labelControl3;
        internal LabelControl LabelControl4;
        internal LabelControl labelControl6;
        internal LabelControl LabelControl7;
        internal LabelControl labelControl8;
        internal LabelControl labelControl9;
        internal LabelControl Lbl_GrpId;
        internal LabelControl Lbl_GrpName;
        internal LabelControl Lbl_Lastimppr;
        internal LabelControl Lbl_MercName;
        internal LabelControl Lbl_Rtprice;
        internal LabelControl Lbl_SuppId;
        internal LabelControl Lbl_SuppName;
        internal LabelControl Lbl_WsPrice;
        private OleDbConnection oleDbConnection_0;
        private OleDbDataAdapter oleDbDataAdapter_0;
        private PanelControl panelControl1;
        internal PictureEdit PicGoods;
        private RepositoryItemButtonEdit repositoryItemButtonEdit1;
        private RepositoryItemDateEdit repositoryItemDateEdit1;
        private RepositoryItemPopupContainerEdit repositoryItemPopupContainerEdit1;
        private RepositoryItemSpinEdit repositoryItemSpinEdit1;
        private RepositoryItemTextEdit repositoryItemTextEdit1;
        private RepositoryItemTimeEdit repositoryItemTimeEdit1;
        private string string_0;
        internal LabelControl TgwIjsrYqS;
        internal TextEdit Txt_GoodsId;
        internal TextEdit txtDiscPc;
        internal TextEdit txtDiscValue;
        internal TextEdit txtFrDate;
        internal TextEdit txtGiftQty;
        internal TextEdit txtMaxQty;
        internal TextEdit txtMinQty;
        internal TextEdit txtNewPrice;
        internal TextEdit txtRtprice;
        internal TextEdit txtSurplusPc;
        internal TextEdit txtToDate;
        private DataColumn welftZbha;


        #endregion

    }
}
