using DevExpress.XtraGrid.Views.Base;
using DevExpress.Data;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Mask;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Windows.Forms;

namespace LibraryManagement.App
{
    partial class FrmMercMove
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private ComponentResourceManager manager;
        private void InitializeComponent()
        {
            this.components = new Container();
            manager = new ComponentResourceManager(typeof(FrmMercMove));
            this.GroupBox3 = new GroupBox();
            this.GroupBox4 = new GroupBox();
            this.LabelControl14 = new LabelControl();
            this.Txt_Remark = new TextEdit();
            this.Lbl_MercName = new LabelControl();
            this.Lbl_ImpName = new LabelControl();
            this.Lbl_ExpName = new LabelControl();
            this.Lbl_Date = new LabelControl();
            this.chkLabelPrn = new CheckEdit();
            this.Txt_TransNum = new TextEdit();
            this.LabelControl9 = new LabelControl();
            this.Txt_ExpID = new TextEdit();
            this.LabelControl17 = new LabelControl();
            this.LabelControl18 = new LabelControl();
            this.Txt_ImpID = new TextEdit();
            this.LabelControl1 = new LabelControl();
            this.Txt_GoodsId = new TextEdit();
            this.LabelControl2 = new LabelControl();
            this.Txt_Qty = new TextEdit();
            this.LabelControl22 = new LabelControl();
            this.Txt_Price = new TextEdit();
            this.LabelControl3 = new LabelControl();
            this.Cmb_Unit = new ComboBoxEdit();
            this.GrdTran = new GridControl();
            this.TransDetail = new GridView();
            this.btnAdd = new SimpleButton();
            this.imageList_0 = new ImageList(this.components);
            this.groupBox1 = new GroupBox();
            this.btn_Exit = new SimpleButton();
            this.btn_Search = new SimpleButton();
            this.btn_Edit = new SimpleButton();
            this.btn_New = new SimpleButton();
            this.btn_Skip = new SimpleButton();
            this.btn_Save = new SimpleButton();
            this.btn_Delete = new SimpleButton();
            this.labelControl7 = new LabelControl();
            this.Txt_EndQty = new TextEdit();
            this.Txt_Remark.Properties.BeginInit();
            this.chkLabelPrn.Properties.BeginInit();
            this.Txt_TransNum.Properties.BeginInit();
            this.Txt_ExpID.Properties.BeginInit();
            this.Txt_ImpID.Properties.BeginInit();
            this.Txt_GoodsId.Properties.BeginInit();
            this.Txt_Qty.Properties.BeginInit();
            this.Txt_Price.Properties.BeginInit();
            this.Cmb_Unit.Properties.BeginInit();
            this.GrdTran.BeginInit();
            this.TransDetail.BeginInit();
            this.Txt_EndQty.Properties.BeginInit();
            base.SuspendLayout();
            this.GroupBox3.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.GroupBox3.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.GroupBox3.Location = new Point(-10, 0x58);
            this.GroupBox3.Name = "GroupBox3";
            this.GroupBox3.Size = new Size(0x2b6, 5);
            this.GroupBox3.TabIndex = 0x17e;
            this.GroupBox3.TabStop = false;
            this.GroupBox4.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.GroupBox4.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.GroupBox4.Location = new Point(-10, 0x19);
            this.GroupBox4.Name = "GroupBox4";
            this.GroupBox4.Size = new Size(0x2c0, 5);
            this.GroupBox4.TabIndex = 0x17d;
            this.GroupBox4.TabStop = false;
            this.LabelControl14.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.LabelControl14.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl14.Appearance.Options.UseFont = true;
            this.LabelControl14.Location = new Point(0x15, 0x161);
            this.LabelControl14.Name = "LabelControl14";
            this.LabelControl14.Size = new Size(0x23, 13);
            this.LabelControl14.TabIndex = 0x176;
            this.LabelControl14.Text = "Ghi ch\x00fa";
            this.Txt_Remark.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.Txt_Remark.EnterMoveNextControl = true;
            this.Txt_Remark.Location = new Point(0x5f, 350);
            this.Txt_Remark.Name = "Txt_Remark";
            this.Txt_Remark.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Remark.Properties.Appearance.Options.UseFont = true;
            this.Txt_Remark.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_Remark.Size = new Size(0x20f, 20);
            this.Txt_Remark.TabIndex = 7;
            this.Lbl_MercName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_MercName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_MercName.Appearance.BorderColor = Color.White;
            this.Lbl_MercName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_MercName.Appearance.ForeColor = Color.Black;
            this.Lbl_MercName.Appearance.Options.UseBackColor = true;
            this.Lbl_MercName.Appearance.Options.UseBorderColor = true;
            this.Lbl_MercName.Appearance.Options.UseFont = true;
            this.Lbl_MercName.Appearance.Options.UseForeColor = true;
            this.Lbl_MercName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_MercName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_MercName.Location = new Point(0x15, 0x7f);
            this.Lbl_MercName.Name = "Lbl_MercName";
            this.Lbl_MercName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_MercName.Size = new Size(0x10a, 0x11);
            this.Lbl_MercName.TabIndex = 380;
            this.Lbl_ImpName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_ImpName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_ImpName.Appearance.BorderColor = Color.White;
            this.Lbl_ImpName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_ImpName.Appearance.ForeColor = Color.Black;
            this.Lbl_ImpName.Appearance.Options.UseBackColor = true;
            this.Lbl_ImpName.Appearance.Options.UseBorderColor = true;
            this.Lbl_ImpName.Appearance.Options.UseFont = true;
            this.Lbl_ImpName.Appearance.Options.UseForeColor = true;
            this.Lbl_ImpName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_ImpName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_ImpName.Location = new Point(0xcf, 0x41);
            this.Lbl_ImpName.Name = "Lbl_ImpName";
            this.Lbl_ImpName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_ImpName.Size = new Size(0x1bd, 0x11);
            this.Lbl_ImpName.TabIndex = 0x17b;
            this.Lbl_ExpName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_ExpName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_ExpName.Appearance.BorderColor = Color.White;
            this.Lbl_ExpName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_ExpName.Appearance.ForeColor = Color.Black;
            this.Lbl_ExpName.Appearance.Options.UseBackColor = true;
            this.Lbl_ExpName.Appearance.Options.UseBorderColor = true;
            this.Lbl_ExpName.Appearance.Options.UseFont = true;
            this.Lbl_ExpName.Appearance.Options.UseForeColor = true;
            this.Lbl_ExpName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_ExpName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_ExpName.Location = new Point(0xcf, 0x26);
            this.Lbl_ExpName.Name = "Lbl_ExpName";
            this.Lbl_ExpName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_ExpName.Size = new Size(0x1bd, 0x11);
            this.Lbl_ExpName.TabIndex = 0x17a;
            this.Lbl_Date.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Date.Appearance.Options.UseFont = true;
            this.Lbl_Date.Location = new Point(0x119, 6);
            this.Lbl_Date.Name = "Lbl_Date";
            this.Lbl_Date.Size = new Size(0x38, 13);
            this.Lbl_Date.TabIndex = 0x179;
            this.Lbl_Date.Text = "01/01/2008";
            this.chkLabelPrn.EditValue = true;
            this.chkLabelPrn.Location = new Point(0x1cb, 3);
            this.chkLabelPrn.Name = "chkLabelPrn";
            this.chkLabelPrn.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.chkLabelPrn.Properties.Appearance.Options.UseFont = true;
            this.chkLabelPrn.Properties.Caption = "Tạo danh s\x00e1ch in tem";
            this.chkLabelPrn.Size = new Size(0xa3, 0x12);
            this.chkLabelPrn.TabIndex = 0x178;
            this.chkLabelPrn.TabStop = false;
            this.chkLabelPrn.CheckedChanged += new EventHandler(this.chkLabelPrn_CheckedChanged);
            this.Txt_TransNum.EnterMoveNextControl = true;
            this.Txt_TransNum.Location = new Point(0x74, 3);
            this.Txt_TransNum.Name = "Txt_TransNum";
            this.Txt_TransNum.Properties.Appearance.BackColor = Color.Yellow;
            this.Txt_TransNum.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_TransNum.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_TransNum.Properties.Appearance.Options.UseFont = true;
            this.Txt_TransNum.Properties.CharacterCasing = CharacterCasing.Upper;
            this.Txt_TransNum.Properties.Mask.PlaceHolder = ' ';
            this.Txt_TransNum.Properties.MaxLength = 12;
            this.Txt_TransNum.Properties.ValidateOnEnterKey = true;
            this.Txt_TransNum.Size = new Size(0x68, 20);
            this.Txt_TransNum.TabIndex = 0x177;
            this.Txt_TransNum.EditValueChanged += new EventHandler(this.Txt_TransNum_EditValueChanged);
            this.Txt_TransNum.KeyDown += new KeyEventHandler(this.Txt_TransNum_KeyDown);
            this.LabelControl9.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.LabelControl9.Appearance.Options.UseFont = true;
            this.LabelControl9.Location = new Point(0x15, 6);
            this.LabelControl9.Name = "LabelControl9";
            this.LabelControl9.Size = new Size(0x43, 13);
            this.LabelControl9.TabIndex = 0x16b;
            this.LabelControl9.Text = "Số giao dịch";
            this.Txt_ExpID.EnterMoveNextControl = true;
            this.Txt_ExpID.Location = new Point(0x74, 0x25);
            this.Txt_ExpID.Name = "Txt_ExpID";
            this.Txt_ExpID.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_ExpID.Properties.Appearance.Options.UseFont = true;
            this.Txt_ExpID.Properties.MaxLength = 5;
            this.Txt_ExpID.Size = new Size(0x55, 20);
            this.Txt_ExpID.TabIndex = 1;
            this.Txt_ExpID.EditValueChanged += new EventHandler(this.Txt_ExpID_EditValueChanged);
            this.Txt_ExpID.KeyDown += new KeyEventHandler(this.Txt_ExpID_KeyDown);
            this.LabelControl17.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl17.Appearance.Options.UseFont = true;
            this.LabelControl17.Location = new Point(0x15, 40);
            this.LabelControl17.Name = "LabelControl17";
            this.LabelControl17.Size = new Size(0x43, 13);
            this.LabelControl17.TabIndex = 0x16d;
            this.LabelControl17.Text = "Nơi xuất h\x00e0ng";
            this.LabelControl18.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.LabelControl18.Appearance.Options.UseFont = true;
            this.LabelControl18.Location = new Point(0xed, 6);
            this.LabelControl18.Name = "LabelControl18";
            this.LabelControl18.Size = new Size(0x22, 13);
            this.LabelControl18.TabIndex = 0x16c;
            this.LabelControl18.Text = "Ng\x00e0y :";
            this.Txt_ImpID.EnterMoveNextControl = true;
            this.Txt_ImpID.Location = new Point(0x74, 0x3f);
            this.Txt_ImpID.Name = "Txt_ImpID";
            this.Txt_ImpID.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_ImpID.Properties.Appearance.Options.UseFont = true;
            this.Txt_ImpID.Properties.MaxLength = 5;
            this.Txt_ImpID.Size = new Size(0x55, 20);
            this.Txt_ImpID.TabIndex = 2;
            this.Txt_ImpID.EditValueChanged += new EventHandler(this.Txt_ImpID_EditValueChanged);
            this.Txt_ImpID.KeyDown += new KeyEventHandler(this.Txt_ImpID_KeyDown);
            this.LabelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl1.Appearance.Options.UseFont = true;
            this.LabelControl1.Location = new Point(0x15, 0x42);
            this.LabelControl1.Name = "LabelControl1";
            this.LabelControl1.Size = new Size(0x45, 13);
            this.LabelControl1.TabIndex = 0x16e;
            this.LabelControl1.Text = "Nơi nhập h\x00e0ng";
            this.Txt_GoodsId.EnterMoveNextControl = true;
            this.Txt_GoodsId.Location = new Point(0x74, 0x62);
            this.Txt_GoodsId.Name = "Txt_GoodsId";
            this.Txt_GoodsId.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_GoodsId.Properties.Appearance.Options.UseFont = true;
            this.Txt_GoodsId.Properties.KeyDown += new KeyEventHandler(this.method_5);
            this.Txt_GoodsId.Size = new Size(0x7b, 20);
            this.Txt_GoodsId.TabIndex = 3;
            this.Txt_GoodsId.EditValueChanged += new EventHandler(this.Txt_GoodsId_EditValueChanged);
            this.Txt_GoodsId.KeyDown += new KeyEventHandler(this.Txt_GoodsId_KeyDown);
            this.LabelControl2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.LabelControl2.Appearance.Options.UseFont = true;
            this.LabelControl2.Location = new Point(0x15, 0x65);
            this.LabelControl2.Name = "LabelControl2";
            this.LabelControl2.Size = new Size(0x30, 13);
            this.LabelControl2.TabIndex = 0x16f;
            this.LabelControl2.Text = "M\x00e3 h\x00e0ng";
            this.Txt_Qty.EnterMoveNextControl = true;
            this.Txt_Qty.Location = new Point(0x124, 0x62);
            this.Txt_Qty.Name = "Txt_Qty";
            this.Txt_Qty.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Qty.Properties.Appearance.Options.UseFont = true;
            this.Txt_Qty.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_Qty.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_Qty.Properties.DisplayFormat.FormatString = "n2";
            this.Txt_Qty.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_Qty.Properties.EditFormat.FormatString = "n2";
            this.Txt_Qty.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_Qty.Properties.Mask.EditMask = "n2";
            this.Txt_Qty.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_Qty.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_Qty.Size = new Size(0x35, 20);
            this.Txt_Qty.TabIndex = 4;
            this.LabelControl22.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl22.Appearance.Options.UseFont = true;
            this.LabelControl22.Location = new Point(0xf5, 0x65);
            this.LabelControl22.Name = "LabelControl22";
            this.LabelControl22.Size = new Size(0x2a, 13);
            this.LabelControl22.TabIndex = 0x170;
            this.LabelControl22.Text = "Số lượng";
            this.Txt_Price.EnterMoveNextControl = true;
            this.Txt_Price.Location = new Point(0x15f, 0x7d);
            this.Txt_Price.Name = "Txt_Price";
            this.Txt_Price.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Price.Properties.Appearance.Options.UseFont = true;
            this.Txt_Price.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_Price.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_Price.Properties.DisplayFormat.FormatString = "n2";
            this.Txt_Price.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_Price.Properties.EditFormat.FormatString = "n2";
            this.Txt_Price.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_Price.Properties.Mask.EditMask = "n2";
            this.Txt_Price.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_Price.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_Price.Size = new Size(0x66, 20);
            this.Txt_Price.TabIndex = 5;
            this.LabelControl3.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl3.Appearance.Options.UseFont = true;
            this.LabelControl3.Location = new Point(0x127, 0x81);
            this.LabelControl3.Name = "LabelControl3";
            this.LabelControl3.Size = new Size(0x24, 13);
            this.LabelControl3.TabIndex = 0x171;
            this.LabelControl3.Text = "Gi\x00e1 vốn";
            this.Cmb_Unit.Location = new Point(0x15f, 0x62);
            this.Cmb_Unit.Name = "Cmb_Unit";
            this.Cmb_Unit.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Cmb_Unit.Properties.Appearance.Options.UseFont = true;
            this.Cmb_Unit.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.Cmb_Unit.Size = new Size(0x34, 20);
            this.Cmb_Unit.TabIndex = 370;
            this.Cmb_Unit.TabStop = false;
            this.GrdTran.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.GrdTran.Location = new Point(15, 0x99);
            this.GrdTran.MainView = this.TransDetail;
            this.GrdTran.Name = "GrdTran";
            this.GrdTran.Size = new Size(0x27d, 0xbf);
            this.GrdTran.TabIndex = 0x174;
            this.GrdTran.ViewCollection.AddRange(new BaseView[] { this.TransDetail });
            this.GrdTran.Click += new EventHandler(this.GrdTran_Click);
            this.TransDetail.Appearance.FooterPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.TransDetail.Appearance.FooterPanel.Options.UseFont = true;
            this.TransDetail.Appearance.HeaderPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.TransDetail.Appearance.HeaderPanel.Options.UseFont = true;
            this.TransDetail.Appearance.Row.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.TransDetail.Appearance.Row.Options.UseFont = true;
            this.TransDetail.GridControl = this.GrdTran;
            this.TransDetail.Name = "TransDetail";
            this.TransDetail.OptionsView.ShowFooter = true;
            this.TransDetail.OptionsView.ShowGroupPanel = false;
            this.btnAdd.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnAdd.Appearance.Options.UseFont = true;
            this.btnAdd.ImageIndex = 0;
            this.btnAdd.ImageList = this.imageList_0;
            this.btnAdd.ImageLocation = ImageLocation.MiddleCenter;
            this.btnAdd.Location = new Point(0x1d1, 0x7c);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.Size = new Size(0x4b, 0x17);
            this.btnAdd.TabIndex = 6;
            this.btnAdd.Click += new EventHandler(this.btnAdd_Click);
            this.imageList_0.ImageStream = (ImageListStreamer)manager.GetObject("imageList1.ImageStream");
            this.imageList_0.TransparentColor = Color.Transparent;
            this.imageList_0.Images.SetKeyName(0, "arrow_down_blue.png");
            this.groupBox1.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom;
            this.groupBox1.Location = new Point(-55, 0x17a);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x318, 5);
            this.groupBox1.TabIndex = 0x185;
            this.groupBox1.TabStop = false;
            this.btn_Exit.Anchor = AnchorStyles.Bottom;
            this.btn_Exit.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Exit.Location = new Point(0x224, 390);
            this.btn_Exit.Name = "btn_Exit";
            this.btn_Exit.Size = new Size(0x4b, 0x17);
            this.btn_Exit.TabIndex = 13;
            this.btn_Exit.Text = "&Tho\x00e1t";
            this.btn_Exit.Click += new EventHandler(this.btn_Exit_Click);
            this.btn_Search.Anchor = AnchorStyles.Bottom;
            this.btn_Search.Location = new Point(0x1d1, 390);
            this.btn_Search.Name = "btn_Search";
            this.btn_Search.Size = new Size(0x4b, 0x17);
            this.btn_Search.TabIndex = 12;
            this.btn_Search.Text = "T\x00ec&m";
            this.btn_Search.Click += new EventHandler(this.btn_Search_Click);
            this.btn_Edit.Anchor = AnchorStyles.Bottom;
            this.btn_Edit.Location = new Point(0x12b, 390);
            this.btn_Edit.Name = "btn_Edit";
            this.btn_Edit.Size = new Size(0x4b, 0x17);
            this.btn_Edit.TabIndex = 10;
            this.btn_Edit.Text = "&Sửa";
            this.btn_Edit.Click += new EventHandler(this.btn_Edit_Click);
            this.btn_New.Anchor = AnchorStyles.Bottom;
            this.btn_New.Location = new Point(0xd8, 390);
            this.btn_New.Name = "btn_New";
            this.btn_New.Size = new Size(0x4b, 0x17);
            this.btn_New.TabIndex = 0;
            this.btn_New.Text = "Tạ&o";
            this.btn_New.Click += new EventHandler(this.btn_New_Click);
            this.btn_Skip.Anchor = AnchorStyles.Bottom;
            this.btn_Skip.Location = new Point(0x85, 390);
            this.btn_Skip.Name = "btn_Skip";
            this.btn_Skip.Size = new Size(0x4b, 0x17);
            this.btn_Skip.TabIndex = 9;
            this.btn_Skip.Text = "&Bỏ qua";
            this.btn_Skip.Click += new EventHandler(this.iWyIskLbe);
            this.btn_Save.Anchor = AnchorStyles.Bottom;
            this.btn_Save.Location = new Point(50, 390);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.Size = new Size(0x4b, 0x17);
            this.btn_Save.TabIndex = 8;
            this.btn_Save.Text = "&Lưu";
            this.btn_Save.Click += new EventHandler(this.btn_Save_Click);
            this.btn_Delete.Anchor = AnchorStyles.Bottom;
            this.btn_Delete.Location = new Point(0x17e, 390);
            this.btn_Delete.Name = "btn_Delete";
            this.btn_Delete.Size = new Size(0x4b, 0x17);
            this.btn_Delete.TabIndex = 11;
            this.btn_Delete.Text = "&X\x00f3a";
            this.btn_Delete.Click += new EventHandler(this.btn_Delete_Click);
            this.labelControl7.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl7.Appearance.Options.UseFont = true;
            this.labelControl7.Location = new Point(440, 0x65);
            this.labelControl7.Name = "labelControl7";
            this.labelControl7.Size = new Size(40, 13);
            this.labelControl7.TabIndex = 0x18a;
            this.labelControl7.Text = "Hiện tồn";
            this.Txt_EndQty.EnterMoveNextControl = true;
            this.Txt_EndQty.Location = new Point(490, 0x62);
            this.Txt_EndQty.Name = "Txt_EndQty";
            this.Txt_EndQty.Properties.Appearance.BackColor = Color.PaleTurquoise;
            this.Txt_EndQty.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_EndQty.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_EndQty.Properties.Appearance.Options.UseFont = true;
            this.Txt_EndQty.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_EndQty.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_EndQty.Properties.DisplayFormat.FormatString = "n2";
            this.Txt_EndQty.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_EndQty.Properties.EditFormat.FormatString = "n2";
            this.Txt_EndQty.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_EndQty.Properties.Mask.EditMask = "n2";
            this.Txt_EndQty.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_EndQty.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_EndQty.Size = new Size(50, 20);
            this.Txt_EndQty.TabIndex = 0x18b;
            this.Txt_EndQty.EditValueChanged += new EventHandler(this.Txt_EndQty_EditValueChanged);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(0x2a0, 0x1a7);
            base.Controls.Add(this.Txt_EndQty);
            base.Controls.Add(this.labelControl7);
            base.Controls.Add(this.btn_Delete);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.btn_Exit);
            base.Controls.Add(this.btn_Search);
            base.Controls.Add(this.btn_Edit);
            base.Controls.Add(this.btn_New);
            base.Controls.Add(this.btn_Skip);
            base.Controls.Add(this.btn_Save);
            base.Controls.Add(this.GroupBox3);
            base.Controls.Add(this.GroupBox4);
            base.Controls.Add(this.LabelControl14);
            base.Controls.Add(this.Txt_Remark);
            base.Controls.Add(this.Lbl_MercName);
            base.Controls.Add(this.Lbl_ImpName);
            base.Controls.Add(this.Lbl_ExpName);
            base.Controls.Add(this.Lbl_Date);
            base.Controls.Add(this.chkLabelPrn);
            base.Controls.Add(this.Txt_TransNum);
            base.Controls.Add(this.LabelControl9);
            base.Controls.Add(this.Txt_ExpID);
            base.Controls.Add(this.LabelControl17);
            base.Controls.Add(this.LabelControl18);
            base.Controls.Add(this.Txt_ImpID);
            base.Controls.Add(this.LabelControl1);
            base.Controls.Add(this.Txt_GoodsId);
            base.Controls.Add(this.LabelControl2);
            base.Controls.Add(this.Txt_Qty);
            base.Controls.Add(this.LabelControl22);
            base.Controls.Add(this.Txt_Price);
            base.Controls.Add(this.LabelControl3);
            base.Controls.Add(this.Cmb_Unit);
            base.Controls.Add(this.GrdTran);
            base.Controls.Add(this.btnAdd);
            base.Name = "FrmMercMove";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmMercMove";
            base.Load += new EventHandler(this.FrmMercMove_Load);
            base.FormClosing += new FormClosingEventHandler(this.FrmMercMove_FormClosing);
            this.Txt_Remark.Properties.EndInit();
            this.chkLabelPrn.Properties.EndInit();
            this.Txt_TransNum.Properties.EndInit();
            this.Txt_ExpID.Properties.EndInit();
            this.Txt_ImpID.Properties.EndInit();
            this.Txt_GoodsId.Properties.EndInit();
            this.Txt_Qty.Properties.EndInit();
            this.Txt_Price.Properties.EndInit();
            this.Cmb_Unit.Properties.EndInit();
            this.GrdTran.EndInit();
            this.TransDetail.EndInit();
            this.Txt_EndQty.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
        private SimpleButton btn_Delete;
        private SimpleButton btn_Edit;
        private SimpleButton btn_Exit;
        private SimpleButton btn_New;
        private SimpleButton btn_Save;
        private SimpleButton btn_Search;
        private SimpleButton btn_Skip;
        internal SimpleButton btnAdd;
        internal CheckEdit chkLabelPrn;
        internal ComboBoxEdit Cmb_Unit;
        internal GridControl GrdTran;
        internal GroupBox groupBox1;
        internal GroupBox GroupBox3;
        internal GroupBox GroupBox4;
        //private IContainer components;
        private ImageList imageList_0;
        internal LabelControl LabelControl1;
        internal LabelControl LabelControl14;
        internal LabelControl LabelControl17;
        internal LabelControl LabelControl18;
        internal LabelControl LabelControl2;
        internal LabelControl LabelControl22;
        internal LabelControl LabelControl3;
        internal LabelControl labelControl7;
        internal LabelControl LabelControl9;
        internal LabelControl Lbl_Date;
        internal LabelControl Lbl_ExpName;
        internal LabelControl Lbl_ImpName;
        internal LabelControl Lbl_MercName;
        private OleDbConnection oleDbConnection_0;
        private OleDbConnection oleDbConnection_1;
        private OleDbDataAdapter oleDbDataAdapter_0;
        private string string_0;
        private string string_1;
        private string string_2;
        private string string_3;
        private string string_4;
        internal GridView TransDetail;
        internal TextEdit Txt_EndQty;
        internal TextEdit Txt_ExpID;
        internal TextEdit Txt_GoodsId;
        internal TextEdit Txt_ImpID;
        internal TextEdit Txt_Price;
        internal TextEdit Txt_Qty;
        internal TextEdit Txt_Remark;
        internal TextEdit Txt_TransNum;

        #endregion

    }
}
