using DevExpress.XtraGrid.Views.Base;
using DevExpress.Data;
using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Mask;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Grid;
using System;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Windows.Forms;
namespace LibraryManagement.App
{
    partial class FrmPosSale
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private ComponentResourceManager manager;
        private void InitializeComponent()
        {
            this.components = new Container();
            this.GrdSale = new GridControl();
            this.Sales_View = new GridView();
            this.Lbl_MercName = new LabelControl();
            this.LabelControl17 = new LabelControl();
            this.Txt_TransNum = new TextEdit();
            this.labelControl1 = new LabelControl();
            this.Lbl_Date = new LabelControl();
            this.Txt_Barcode = new TextEdit();
            this.groupControl1 = new GroupControl();
            this.Txt_Qty = new TextEdit();
            this.btn_Exit = new SimpleButton();
            this.btn_New = new SimpleButton();
            this.btn_Save = new SimpleButton();
            this.Txt_Unit = new TextEdit();
            this.Lbl_PayAmt = new LabelControl();
            this.Lbl_Foreign = new LabelControl();
            this.labelControl3 = new LabelControl();
            this.Lbl_Exchange = new LabelControl();
            this.cnvLekth7 = new LabelControl();
            this.Lbl_CurrencyName = new LabelControl();
            this.LabelControl12 = new LabelControl();
            this.cboCurrency = new ComboBoxEdit();
            this.LabelControl8 = new LabelControl();
            this.LabelControl10 = new LabelControl();
            this.Lbl_LastAmount = new LabelControl();
            this.LabelControl5 = new LabelControl();
            this.LabelControl6 = new LabelControl();
            this.Lbl_Discount = new LabelControl();
            this.LabelControl4 = new LabelControl();
            this.labelControl7 = new LabelControl();
            this.Lbl_TotalAmount = new LabelControl();
            this.GroupBox2 = new GroupBox();
            this.btnSuspend = new SimpleButton();
            this.btn_Skip = new SimpleButton();
            this.labelControl2 = new LabelControl();
            this.labelControl9 = new LabelControl();
            this.Lbl_ReceivAmt = new LabelControl();
            this.labelControl13 = new LabelControl();
            this.labelControl15 = new LabelControl();
            this.Lbl_PaybackAmt = new LabelControl();
            this.Txt_MercSearch = new SimpleButton();
            this.btn_SuspendLst = new SimpleButton();
            this.labelControl11 = new LabelControl();
            this.Lbl_CurrencyCap = new LabelControl();
            this.Txt_Rtprice = new TextEdit();
            this.btnReprint = new SimpleButton();
            Timer timer = new Timer(this.components);
            this.GrdSale.BeginInit();
            this.Sales_View.BeginInit();
            this.Txt_TransNum.Properties.BeginInit();
            this.Txt_Barcode.Properties.BeginInit();
            this.groupControl1.BeginInit();
            this.Txt_Qty.Properties.BeginInit();
            this.Txt_Unit.Properties.BeginInit();
            this.cboCurrency.Properties.BeginInit();
            this.Txt_Rtprice.Properties.BeginInit();
            base.SuspendLayout();
            timer.Enabled = true;
            timer.Interval = 500;
            timer.Tick += new EventHandler(this.method_6);
            this.GrdSale.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.GrdSale.Location = new Point(12, 0x76);
            this.GrdSale.MainView = this.Sales_View;
            this.GrdSale.Name = "GrdSale";
            this.GrdSale.Size = new Size(0x335, 0x117);
            this.GrdSale.TabIndex = 0;
            this.GrdSale.ViewCollection.AddRange(new BaseView[] { this.Sales_View });
            this.GrdSale.Click += new EventHandler(this.GrdSale_Click);
            this.Sales_View.Appearance.HeaderPanel.Font = new Font("Tahoma", 11.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Sales_View.Appearance.HeaderPanel.Options.UseFont = true;
            this.Sales_View.Appearance.Row.Font = new Font("Tahoma", 11.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Sales_View.Appearance.Row.Options.UseFont = true;
            this.Sales_View.GridControl = this.GrdSale;
            this.Sales_View.Name = "Sales_View";
            this.Sales_View.OptionsView.ShowFooter = true;
            this.Sales_View.OptionsView.ShowGroupPanel = false;
            this.Lbl_MercName.Appearance.BackColor = Color.RoyalBlue;
            this.Lbl_MercName.Appearance.BackColor2 = Color.CornflowerBlue;
            this.Lbl_MercName.Appearance.BorderColor = Color.White;
            this.Lbl_MercName.Appearance.Font = new Font("Tahoma", 15.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_MercName.Appearance.ForeColor = Color.White;
            this.Lbl_MercName.Appearance.Options.UseBackColor = true;
            this.Lbl_MercName.Appearance.Options.UseBorderColor = true;
            this.Lbl_MercName.Appearance.Options.UseFont = true;
            this.Lbl_MercName.Appearance.Options.UseForeColor = true;
            this.Lbl_MercName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_MercName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_MercName.Location = new Point(12, 80);
            this.Lbl_MercName.Name = "Lbl_MercName";
            this.Lbl_MercName.Padding = new Padding(5, 0, 0, 0);
            this.Lbl_MercName.Size = new Size(0x223, 0x20);
            this.Lbl_MercName.TabIndex = 0x16b;
            this.Lbl_MercName.Text = "Nhẫn v\x00e0ng ta loại 1 chỉ";
            this.LabelControl17.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.LabelControl17.Appearance.Options.UseFont = true;
            this.LabelControl17.Location = new Point(12, 15);
            this.LabelControl17.Name = "LabelControl17";
            this.LabelControl17.Size = new Size(0x43, 13);
            this.LabelControl17.TabIndex = 0x16a;
            this.LabelControl17.Text = "Số giao dịch";
            this.Txt_TransNum.EnterMoveNextControl = true;
            this.Txt_TransNum.Location = new Point(0x61, 12);
            this.Txt_TransNum.Name = "Txt_TransNum";
            this.Txt_TransNum.Properties.Appearance.BackColor = Color.Yellow;
            this.Txt_TransNum.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_TransNum.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_TransNum.Properties.Appearance.Options.UseFont = true;
            this.Txt_TransNum.Properties.CharacterCasing = CharacterCasing.Upper;
            this.Txt_TransNum.Properties.MaxLength = 12;
            this.Txt_TransNum.Size = new Size(0x88, 20);
            this.Txt_TransNum.TabIndex = 0x169;
            this.Txt_TransNum.EditValueChanged += new EventHandler(this.Txt_TransNum_EditValueChanged);
            this.Txt_TransNum.KeyDown += new KeyEventHandler(this.Txt_TransNum_KeyDown);
            this.labelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.labelControl1.Appearance.Options.UseFont = true;
            this.labelControl1.Location = new Point(0x105, 15);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new Size(0x22, 13);
            this.labelControl1.TabIndex = 0x16c;
            this.labelControl1.Text = "Ng\x00e0y :";
            this.Lbl_Date.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_Date.Appearance.Options.UseFont = true;
            this.Lbl_Date.Location = new Point(0x12b, 15);
            this.Lbl_Date.Name = "Lbl_Date";
            this.Lbl_Date.Size = new Size(0x44, 13);
            this.Lbl_Date.TabIndex = 0x16d;
            this.Lbl_Date.Text = "22/10/2008";
            this.Txt_Barcode.EditValue = "89348936657412";
            this.Txt_Barcode.Location = new Point(12, 0x2f);
            this.Txt_Barcode.Name = "Txt_Barcode";
            this.Txt_Barcode.Properties.Appearance.Font = new Font("Tahoma", 15.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_Barcode.Properties.Appearance.Options.UseFont = true;
            this.Txt_Barcode.Size = new Size(0xe5, 0x20);
            this.Txt_Barcode.TabIndex = 0x16e;
            this.Txt_Barcode.EditValueChanged += new EventHandler(this.Txt_Barcode_EditValueChanged);
            this.Txt_Barcode.KeyDown += new KeyEventHandler(this.Txt_Barcode_KeyDown);
            this.groupControl1.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.groupControl1.BorderStyle = BorderStyles.Simple;
            this.groupControl1.Location = new Point(-8, 0x24);
            this.groupControl1.Name = "groupControl1";
            this.groupControl1.Size = new Size(860, 5);
            this.groupControl1.TabIndex = 0x16f;
            int[] bits = new int[4];
            this.Txt_Qty.EditValue = new decimal(bits);
            this.Txt_Qty.Location = new Point(0xf3, 0x2f);
            this.Txt_Qty.Name = "Txt_Qty";
            this.Txt_Qty.Properties.Appearance.Font = new Font("Tahoma", 15.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_Qty.Properties.Appearance.Options.UseFont = true;
            this.Txt_Qty.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_Qty.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_Qty.Properties.DisplayFormat.FormatString = "n2";
            this.Txt_Qty.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_Qty.Properties.EditFormat.FormatString = "n2";
            this.Txt_Qty.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_Qty.Properties.Mask.EditMask = "n2";
            this.Txt_Qty.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_Qty.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_Qty.Size = new Size(0x5b, 0x20);
            this.Txt_Qty.TabIndex = 0x170;
            this.Txt_Qty.KeyDown += new KeyEventHandler(this.Txt_Qty_KeyDown);
            this.btn_Exit.Anchor = AnchorStyles.Bottom;
            this.btn_Exit.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btn_Exit.Appearance.Options.UseFont = true;
            this.btn_Exit.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Exit.Location = new Point(0x298, 0x20b);
            this.btn_Exit.Name = "btn_Exit";
            this.btn_Exit.Size = new Size(0x69, 0x1a);
            this.btn_Exit.TabIndex = 0x177;
            this.btn_Exit.Text = "&Tho\x00e1t";
            this.btn_Exit.Click += new EventHandler(this.btn_Exit_Click);
            this.btn_New.Anchor = AnchorStyles.Bottom;
            this.btn_New.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btn_New.Appearance.Options.UseFont = true;
            this.btn_New.Location = new Point(0x1c0, 0x20b);
            this.btn_New.Name = "btn_New";
            this.btn_New.Size = new Size(0x69, 0x1a);
            this.btn_New.TabIndex = 0x174;
            this.btn_New.Text = "F2-Tạo";
            this.btn_New.Click += new EventHandler(this.btn_New_Click);
            this.btn_Save.Anchor = AnchorStyles.Bottom;
            this.btn_Save.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btn_Save.Appearance.Options.UseFont = true;
            this.btn_Save.Location = new Point(0x7c, 0x20b);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.Size = new Size(0x69, 0x1a);
            this.btn_Save.TabIndex = 370;
            this.btn_Save.Text = "F7-Lưu";
            this.btn_Save.Click += new EventHandler(this.btn_Save_Click);
            this.Txt_Unit.EditValue = "CAI";
            this.Txt_Unit.Location = new Point(0x150, 0x2f);
            this.Txt_Unit.Name = "Txt_Unit";
            this.Txt_Unit.Properties.Appearance.Font = new Font("Tahoma", 15.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_Unit.Properties.Appearance.Options.UseFont = true;
            this.Txt_Unit.Size = new Size(0x34, 0x20);
            this.Txt_Unit.TabIndex = 0x178;
            this.Lbl_PayAmt.Appearance.BackColor = Color.Black;
            this.Lbl_PayAmt.Appearance.BackColor2 = Color.Black;
            this.Lbl_PayAmt.Appearance.BorderColor = Color.White;
            this.Lbl_PayAmt.Appearance.Font = new Font("Times New Roman", 36f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_PayAmt.Appearance.ForeColor = Color.Cyan;
            this.Lbl_PayAmt.Appearance.Options.UseBackColor = true;
            this.Lbl_PayAmt.Appearance.Options.UseBorderColor = true;
            this.Lbl_PayAmt.Appearance.Options.UseFont = true;
            this.Lbl_PayAmt.Appearance.Options.UseForeColor = true;
            this.Lbl_PayAmt.Appearance.Options.UseTextOptions = true;
            this.Lbl_PayAmt.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_PayAmt.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_PayAmt.BorderStyle = BorderStyles.Style3D;
            this.Lbl_PayAmt.Location = new Point(0x235, 0x2f);
            this.Lbl_PayAmt.Name = "Lbl_PayAmt";
            this.Lbl_PayAmt.Padding = new Padding(0, 0, 10, 0);
            this.Lbl_PayAmt.Size = new Size(0x10c, 0x41);
            this.Lbl_PayAmt.TabIndex = 0x179;
            this.Lbl_PayAmt.Text = "0";
            this.Lbl_Foreign.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.Lbl_Foreign.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Foreign.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Foreign.Appearance.BorderColor = Color.White;
            this.Lbl_Foreign.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Foreign.Appearance.ForeColor = Color.Black;
            this.Lbl_Foreign.Appearance.Options.UseBackColor = true;
            this.Lbl_Foreign.Appearance.Options.UseBorderColor = true;
            this.Lbl_Foreign.Appearance.Options.UseFont = true;
            this.Lbl_Foreign.Appearance.Options.UseForeColor = true;
            this.Lbl_Foreign.Appearance.Options.UseTextOptions = true;
            this.Lbl_Foreign.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_Foreign.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Foreign.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Foreign.Location = new Point(0xb6, 0x1c0);
            this.Lbl_Foreign.Name = "Lbl_Foreign";
            this.Lbl_Foreign.Padding = new Padding(0, 0, 3, 0);
            this.Lbl_Foreign.Size = new Size(0x86, 0x11);
            this.Lbl_Foreign.TabIndex = 0x189;
            this.Lbl_Foreign.Text = "25.00";
            this.labelControl3.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.labelControl3.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl3.Appearance.Options.UseFont = true;
            this.labelControl3.Location = new Point(0x1b, 0x1c1);
            this.labelControl3.Name = "labelControl3";
            this.labelControl3.Size = new Size(0x41, 13);
            this.labelControl3.TabIndex = 0x188;
            this.labelControl3.Text = "Tương đương";
            this.Lbl_Exchange.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.Lbl_Exchange.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Exchange.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Exchange.Appearance.BorderColor = Color.White;
            this.Lbl_Exchange.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Exchange.Appearance.ForeColor = Color.Black;
            this.Lbl_Exchange.Appearance.Options.UseBackColor = true;
            this.Lbl_Exchange.Appearance.Options.UseBorderColor = true;
            this.Lbl_Exchange.Appearance.Options.UseFont = true;
            this.Lbl_Exchange.Appearance.Options.UseForeColor = true;
            this.Lbl_Exchange.Appearance.Options.UseTextOptions = true;
            this.Lbl_Exchange.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_Exchange.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Exchange.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Exchange.Location = new Point(0xb6, 0x1aa);
            this.Lbl_Exchange.Name = "Lbl_Exchange";
            this.Lbl_Exchange.Padding = new Padding(0, 0, 3, 0);
            this.Lbl_Exchange.Size = new Size(0x86, 0x11);
            this.Lbl_Exchange.TabIndex = 0x187;
            this.Lbl_Exchange.Text = "16,500";
            this.cnvLekth7.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.cnvLekth7.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cnvLekth7.Appearance.Options.UseFont = true;
            this.cnvLekth7.Location = new Point(0x1b, 0x1ab);
            this.cnvLekth7.Name = "LabelControl14";
            this.cnvLekth7.Size = new Size(0x1d, 13);
            this.cnvLekth7.TabIndex = 390;
            this.cnvLekth7.Text = "Tỷ gi\x00e1";
            this.Lbl_CurrencyName.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.Lbl_CurrencyName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_CurrencyName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_CurrencyName.Appearance.BorderColor = Color.White;
            this.Lbl_CurrencyName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_CurrencyName.Appearance.ForeColor = Color.Black;
            this.Lbl_CurrencyName.Appearance.Options.UseBackColor = true;
            this.Lbl_CurrencyName.Appearance.Options.UseBorderColor = true;
            this.Lbl_CurrencyName.Appearance.Options.UseFont = true;
            this.Lbl_CurrencyName.Appearance.Options.UseForeColor = true;
            this.Lbl_CurrencyName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_CurrencyName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_CurrencyName.Location = new Point(0xb6, 0x195);
            this.Lbl_CurrencyName.Name = "Lbl_CurrencyName";
            this.Lbl_CurrencyName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_CurrencyName.Size = new Size(0x86, 0x11);
            this.Lbl_CurrencyName.TabIndex = 0x185;
            this.LabelControl12.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.LabelControl12.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl12.Appearance.Options.UseFont = true;
            this.LabelControl12.Location = new Point(0x1b, 0x195);
            this.LabelControl12.Name = "LabelControl12";
            this.LabelControl12.Size = new Size(0x3d, 13);
            this.LabelControl12.TabIndex = 0x184;
            this.LabelControl12.Text = "Loại ngoại tệ";
            this.cboCurrency.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.cboCurrency.EnterMoveNextControl = true;
            this.cboCurrency.Location = new Point(0x72, 0x193);
            this.cboCurrency.Name = "cboCurrency";
            this.cboCurrency.Properties.Appearance.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.cboCurrency.Properties.Appearance.Options.UseFont = true;
            this.cboCurrency.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.cboCurrency.Size = new Size(0x3e, 0x15);
            this.cboCurrency.TabIndex = 0x183;
            this.cboCurrency.SelectedIndexChanged += new EventHandler(this.cboCurrency_SelectedIndexChanged);
            this.cboCurrency.TextChanged += new EventHandler(this.cboCurrency_TextChanged);
            this.LabelControl8.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.LabelControl8.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl8.Appearance.Options.UseFont = true;
            this.LabelControl8.Location = new Point(0x31c, 0x1c6);
            this.LabelControl8.Name = "LabelControl8";
            this.LabelControl8.Size = new Size(20, 13);
            this.LabelControl8.TabIndex = 0x182;
            this.LabelControl8.Text = "VND";
            this.LabelControl10.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.LabelControl10.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl10.Appearance.Options.UseFont = true;
            this.LabelControl10.Location = new Point(0x22f, 0x1c3);
            this.LabelControl10.Name = "LabelControl10";
            this.LabelControl10.Size = new Size(80, 13);
            this.LabelControl10.TabIndex = 0x181;
            this.LabelControl10.Text = "Tổng thanh to\x00e1n";
            this.Lbl_LastAmount.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.Lbl_LastAmount.Appearance.BackColor = Color.Gold;
            this.Lbl_LastAmount.Appearance.BackColor2 = Color.Yellow;
            this.Lbl_LastAmount.Appearance.BorderColor = Color.White;
            this.Lbl_LastAmount.Appearance.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_LastAmount.Appearance.ForeColor = Color.Black;
            this.Lbl_LastAmount.Appearance.Options.UseBackColor = true;
            this.Lbl_LastAmount.Appearance.Options.UseBorderColor = true;
            this.Lbl_LastAmount.Appearance.Options.UseFont = true;
            this.Lbl_LastAmount.Appearance.Options.UseForeColor = true;
            this.Lbl_LastAmount.Appearance.Options.UseTextOptions = true;
            this.Lbl_LastAmount.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_LastAmount.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_LastAmount.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_LastAmount.Location = new Point(0x2a1, 450);
            this.Lbl_LastAmount.Name = "Lbl_LastAmount";
            this.Lbl_LastAmount.Padding = new Padding(0, 0, 3, 0);
            this.Lbl_LastAmount.Size = new Size(0x75, 20);
            this.Lbl_LastAmount.TabIndex = 0x180;
            this.Lbl_LastAmount.Text = "1,000,000";
            this.LabelControl5.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.LabelControl5.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl5.Appearance.Options.UseFont = true;
            this.LabelControl5.Location = new Point(0x31c, 0x1ab);
            this.LabelControl5.Name = "LabelControl5";
            this.LabelControl5.Size = new Size(20, 13);
            this.LabelControl5.TabIndex = 0x17f;
            this.LabelControl5.Text = "VND";
            this.LabelControl6.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.LabelControl6.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl6.Appearance.Options.UseFont = true;
            this.LabelControl6.Location = new Point(0x22f, 0x1ac);
            this.LabelControl6.Name = "LabelControl6";
            this.LabelControl6.Size = new Size(0x4c, 13);
            this.LabelControl6.TabIndex = 0x17e;
            this.LabelControl6.Text = "Tổng chiết khấu";
            this.Lbl_Discount.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.Lbl_Discount.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Discount.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Discount.Appearance.BorderColor = Color.White;
            this.Lbl_Discount.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Discount.Appearance.ForeColor = Color.Black;
            this.Lbl_Discount.Appearance.Options.UseBackColor = true;
            this.Lbl_Discount.Appearance.Options.UseBorderColor = true;
            this.Lbl_Discount.Appearance.Options.UseFont = true;
            this.Lbl_Discount.Appearance.Options.UseForeColor = true;
            this.Lbl_Discount.Appearance.Options.UseTextOptions = true;
            this.Lbl_Discount.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_Discount.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Discount.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Discount.Location = new Point(0x2a1, 0x1ab);
            this.Lbl_Discount.Name = "Lbl_Discount";
            this.Lbl_Discount.Padding = new Padding(0, 0, 3, 0);
            this.Lbl_Discount.Size = new Size(0x75, 0x11);
            this.Lbl_Discount.TabIndex = 0x17d;
            this.Lbl_Discount.Text = "1,000,000";
            this.LabelControl4.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.LabelControl4.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl4.Appearance.Options.UseFont = true;
            this.LabelControl4.Location = new Point(0x31c, 0x194);
            this.LabelControl4.Name = "LabelControl4";
            this.LabelControl4.Size = new Size(20, 13);
            this.LabelControl4.TabIndex = 380;
            this.LabelControl4.Text = "VND";
            this.labelControl7.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.labelControl7.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl7.Appearance.Options.UseFont = true;
            this.labelControl7.Location = new Point(0x22f, 0x196);
            this.labelControl7.Name = "labelControl7";
            this.labelControl7.Size = new Size(0x42, 13);
            this.labelControl7.TabIndex = 0x17b;
            this.labelControl7.Text = "Tổng h\x00f3a đơn";
            this.Lbl_TotalAmount.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.Lbl_TotalAmount.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_TotalAmount.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_TotalAmount.Appearance.BorderColor = Color.White;
            this.Lbl_TotalAmount.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_TotalAmount.Appearance.ForeColor = Color.Black;
            this.Lbl_TotalAmount.Appearance.Options.UseBackColor = true;
            this.Lbl_TotalAmount.Appearance.Options.UseBorderColor = true;
            this.Lbl_TotalAmount.Appearance.Options.UseFont = true;
            this.Lbl_TotalAmount.Appearance.Options.UseForeColor = true;
            this.Lbl_TotalAmount.Appearance.Options.UseTextOptions = true;
            this.Lbl_TotalAmount.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_TotalAmount.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_TotalAmount.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_TotalAmount.Location = new Point(0x2a1, 0x194);
            this.Lbl_TotalAmount.Name = "Lbl_TotalAmount";
            this.Lbl_TotalAmount.Padding = new Padding(0, 0, 3, 0);
            this.Lbl_TotalAmount.Size = new Size(0x75, 0x11);
            this.Lbl_TotalAmount.TabIndex = 0x17a;
            this.Lbl_TotalAmount.Text = "1,000,000";
            this.GroupBox2.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom;
            this.GroupBox2.Location = new Point(-3, 0x1f9);
            this.GroupBox2.Name = "GroupBox2";
            this.GroupBox2.Size = new Size(0x354, 5);
            this.GroupBox2.TabIndex = 0x18a;
            this.GroupBox2.TabStop = false;
            this.btnSuspend.Anchor = AnchorStyles.Bottom;
            this.btnSuspend.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnSuspend.Appearance.Options.UseFont = true;
            this.btnSuspend.Location = new Point(340, 0x20b);
            this.btnSuspend.Name = "btnSuspend";
            this.btnSuspend.Size = new Size(0x69, 0x1a);
            this.btnSuspend.TabIndex = 0x18c;
            this.btnSuspend.TabStop = false;
            this.btnSuspend.Text = "F6-T\x00ecm";
            this.btnSuspend.Click += new EventHandler(this.btnSuspend_Click);
            this.btn_Skip.Anchor = AnchorStyles.Bottom;
            this.btn_Skip.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btn_Skip.Appearance.Options.UseFont = true;
            this.btn_Skip.Location = new Point(0x22c, 0x20b);
            this.btn_Skip.Name = "btn_Skip";
            this.btn_Skip.Size = new Size(0x69, 0x1a);
            this.btn_Skip.TabIndex = 0x18d;
            this.btn_Skip.Text = "&Bỏ qua";
            this.btn_Skip.Click += new EventHandler(this.btn_Skip_Click);
            this.labelControl2.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.labelControl2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl2.Appearance.Options.UseFont = true;
            this.labelControl2.Location = new Point(0x145, 0x1d9);
            this.labelControl2.Name = "labelControl2";
            this.labelControl2.Size = new Size(20, 13);
            this.labelControl2.TabIndex = 400;
            this.labelControl2.Text = "VND";
            this.labelControl9.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.labelControl9.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl9.Appearance.Options.UseFont = true;
            this.labelControl9.Location = new Point(0x1b, 0x1d7);
            this.labelControl9.Name = "labelControl9";
            this.labelControl9.Size = new Size(0x62, 13);
            this.labelControl9.TabIndex = 0x18f;
            this.labelControl9.Text = "Tiền nhận của kh\x00e1ch";
            this.Lbl_ReceivAmt.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.Lbl_ReceivAmt.Appearance.BackColor = Color.Gold;
            this.Lbl_ReceivAmt.Appearance.BackColor2 = Color.Yellow;
            this.Lbl_ReceivAmt.Appearance.BorderColor = Color.White;
            this.Lbl_ReceivAmt.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_ReceivAmt.Appearance.ForeColor = Color.Black;
            this.Lbl_ReceivAmt.Appearance.Options.UseBackColor = true;
            this.Lbl_ReceivAmt.Appearance.Options.UseBorderColor = true;
            this.Lbl_ReceivAmt.Appearance.Options.UseFont = true;
            this.Lbl_ReceivAmt.Appearance.Options.UseForeColor = true;
            this.Lbl_ReceivAmt.Appearance.Options.UseTextOptions = true;
            this.Lbl_ReceivAmt.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_ReceivAmt.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_ReceivAmt.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_ReceivAmt.Location = new Point(0xb6, 0x1d7);
            this.Lbl_ReceivAmt.Name = "Lbl_ReceivAmt";
            this.Lbl_ReceivAmt.Padding = new Padding(0, 0, 3, 0);
            this.Lbl_ReceivAmt.Size = new Size(0x86, 0x11);
            this.Lbl_ReceivAmt.TabIndex = 0x18e;
            this.Lbl_ReceivAmt.Text = "1,000,000";
            this.labelControl13.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.labelControl13.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl13.Appearance.Options.UseFont = true;
            this.labelControl13.Location = new Point(0x31c, 0x1de);
            this.labelControl13.Name = "labelControl13";
            this.labelControl13.Size = new Size(20, 13);
            this.labelControl13.TabIndex = 0x193;
            this.labelControl13.Text = "VND";
            this.labelControl15.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.labelControl15.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl15.Appearance.Options.UseFont = true;
            this.labelControl15.Location = new Point(0x22f, 0x1de);
            this.labelControl15.Name = "labelControl15";
            this.labelControl15.Size = new Size(50, 13);
            this.labelControl15.TabIndex = 0x192;
            this.labelControl15.Text = "Tiền trả lại";
            this.Lbl_PaybackAmt.Anchor = AnchorStyles.Right | AnchorStyles.Bottom;
            this.Lbl_PaybackAmt.Appearance.BackColor = Color.Blue;
            this.Lbl_PaybackAmt.Appearance.BackColor2 = Color.MediumBlue;
            this.Lbl_PaybackAmt.Appearance.BorderColor = Color.White;
            this.Lbl_PaybackAmt.Appearance.Font = new Font("Tahoma", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_PaybackAmt.Appearance.ForeColor = Color.White;
            this.Lbl_PaybackAmt.Appearance.Options.UseBackColor = true;
            this.Lbl_PaybackAmt.Appearance.Options.UseBorderColor = true;
            this.Lbl_PaybackAmt.Appearance.Options.UseFont = true;
            this.Lbl_PaybackAmt.Appearance.Options.UseForeColor = true;
            this.Lbl_PaybackAmt.Appearance.Options.UseTextOptions = true;
            this.Lbl_PaybackAmt.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_PaybackAmt.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_PaybackAmt.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_PaybackAmt.Location = new Point(0x2a1, 0x1dc);
            this.Lbl_PaybackAmt.Name = "Lbl_PaybackAmt";
            this.Lbl_PaybackAmt.Padding = new Padding(0, 0, 3, 0);
            this.Lbl_PaybackAmt.Size = new Size(0x75, 20);
            this.Lbl_PaybackAmt.TabIndex = 0x191;
            this.Lbl_PaybackAmt.Text = "1,000,000";
            this.Txt_MercSearch.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_MercSearch.Appearance.Options.UseFont = true;
            this.Txt_MercSearch.Location = new Point(390, 5);
            this.Txt_MercSearch.Name = "Txt_MercSearch";
            this.Txt_MercSearch.Size = new Size(0xa9, 0x20);
            this.Txt_MercSearch.TabIndex = 0x194;
            this.Txt_MercSearch.Text = "T\x00ecm kiếm h\x00e0ng h\x00f3a";
            this.Txt_MercSearch.Click += new EventHandler(this.Txt_MercSearch_Click);
            this.btn_SuspendLst.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.btn_SuspendLst.Appearance.Options.UseFont = true;
            this.btn_SuspendLst.Enabled = false;
            this.btn_SuspendLst.Location = new Point(0x235, 4);
            this.btn_SuspendLst.Name = "btn_SuspendLst";
            this.btn_SuspendLst.Size = new Size(0xa9, 0x20);
            this.btn_SuspendLst.TabIndex = 0x195;
            this.btn_SuspendLst.Text = "DS giao dịch ho\x00e3n";
            this.btn_SuspendLst.Click += new EventHandler(this.btn_SuspendLst_Click);
            this.labelControl11.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.labelControl11.Appearance.BackColor = Color.Transparent;
            this.labelControl11.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.labelControl11.Appearance.ForeColor = Color.Red;
            this.labelControl11.Appearance.Options.UseBackColor = true;
            this.labelControl11.Appearance.Options.UseFont = true;
            this.labelControl11.Appearance.Options.UseForeColor = true;
            this.labelControl11.Location = new Point(40, 0x178);
            this.labelControl11.Name = "labelControl11";
            this.labelControl11.Size = new Size(0x18a, 14);
            this.labelControl11.TabIndex = 0x196;
            this.labelControl11.Text = "F3-CK cả h\x00f3a đơn, F4-CK một mặt h\x00e0ng, F9-Tiền nhận của kh\x00e1ch";
            this.Lbl_CurrencyCap.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.Lbl_CurrencyCap.Location = new Point(0x145, 450);
            this.Lbl_CurrencyCap.Name = "Lbl_CurrencyCap";
            this.Lbl_CurrencyCap.Size = new Size(20, 13);
            this.Lbl_CurrencyCap.TabIndex = 0x197;
            this.Lbl_CurrencyCap.Text = "USD";
            int[] bits1 = new int[4];
            this.Txt_Rtprice.EditValue = new decimal(bits1);
            this.Txt_Rtprice.Location = new Point(390, 0x2f);
            this.Txt_Rtprice.Name = "Txt_Rtprice";
            this.Txt_Rtprice.Properties.Appearance.Font = new Font("Tahoma", 15.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_Rtprice.Properties.Appearance.Options.UseFont = true;
            this.Txt_Rtprice.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_Rtprice.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_Rtprice.Properties.DisplayFormat.FormatString = "n0";
            this.Txt_Rtprice.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_Rtprice.Properties.EditFormat.FormatString = "n0";
            this.Txt_Rtprice.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_Rtprice.Properties.Mask.EditMask = "n0";
            this.Txt_Rtprice.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_Rtprice.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_Rtprice.Size = new Size(0xa9, 0x20);
            this.Txt_Rtprice.TabIndex = 0x198;
            this.Txt_Rtprice.KeyDown += new KeyEventHandler(this.Txt_Rtprice_KeyDown);
            this.btnReprint.Anchor = AnchorStyles.Bottom;
            this.btnReprint.Appearance.Font = new Font("Tahoma", 9f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnReprint.Appearance.ForeColor = Color.Blue;
            this.btnReprint.Appearance.Options.UseFont = true;
            this.btnReprint.Appearance.Options.UseForeColor = true;
            this.btnReprint.Location = new Point(0xe8, 0x20b);
            this.btnReprint.Name = "btnReprint";
            this.btnReprint.Size = new Size(0x69, 0x1a);
            this.btnReprint.TabIndex = 0x199;
            this.btnReprint.TabStop = false;
            this.btnReprint.Text = "F4-In lại";
            this.btnReprint.Click += new EventHandler(this.btnReprint_Click);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(0x34d, 0x22f);
            base.Controls.Add(this.btnReprint);
            base.Controls.Add(this.Txt_Rtprice);
            base.Controls.Add(this.Lbl_CurrencyCap);
            base.Controls.Add(this.labelControl11);
            base.Controls.Add(this.btn_SuspendLst);
            base.Controls.Add(this.Txt_MercSearch);
            base.Controls.Add(this.labelControl13);
            base.Controls.Add(this.labelControl15);
            base.Controls.Add(this.Lbl_PaybackAmt);
            base.Controls.Add(this.labelControl2);
            base.Controls.Add(this.labelControl9);
            base.Controls.Add(this.Lbl_ReceivAmt);
            base.Controls.Add(this.btn_Skip);
            base.Controls.Add(this.btnSuspend);
            base.Controls.Add(this.GroupBox2);
            base.Controls.Add(this.Lbl_Foreign);
            base.Controls.Add(this.labelControl3);
            base.Controls.Add(this.Lbl_Exchange);
            base.Controls.Add(this.cnvLekth7);
            base.Controls.Add(this.Lbl_CurrencyName);
            base.Controls.Add(this.LabelControl12);
            base.Controls.Add(this.cboCurrency);
            base.Controls.Add(this.LabelControl8);
            base.Controls.Add(this.LabelControl10);
            base.Controls.Add(this.Lbl_LastAmount);
            base.Controls.Add(this.LabelControl5);
            base.Controls.Add(this.LabelControl6);
            base.Controls.Add(this.Lbl_Discount);
            base.Controls.Add(this.LabelControl4);
            base.Controls.Add(this.labelControl7);
            base.Controls.Add(this.Lbl_TotalAmount);
            base.Controls.Add(this.Lbl_PayAmt);
            base.Controls.Add(this.Txt_Unit);
            base.Controls.Add(this.btn_Exit);
            base.Controls.Add(this.btn_New);
            base.Controls.Add(this.btn_Save);
            base.Controls.Add(this.Txt_Qty);
            base.Controls.Add(this.groupControl1);
            base.Controls.Add(this.Txt_Barcode);
            base.Controls.Add(this.Lbl_Date);
            base.Controls.Add(this.labelControl1);
            base.Controls.Add(this.Lbl_MercName);
            base.Controls.Add(this.LabelControl17);
            base.Controls.Add(this.Txt_TransNum);
            base.Controls.Add(this.GrdSale);
            base.KeyPreview = true;
            base.Name = "FrmPosSale";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmPosSale";
            base.WindowState = FormWindowState.Maximized;
            base.Load += new EventHandler(this.FrmPosSale_Load);
            base.Activated += new EventHandler(this.FrmPosSale_Activated);
            base.FormClosing += new FormClosingEventHandler(this.FrmPosSale_FormClosing);
            base.KeyDown += new KeyEventHandler(this.FrmPosSale_KeyDown);
            this.GrdSale.EndInit();
            this.Sales_View.EndInit();
            this.Txt_TransNum.Properties.EndInit();
            this.Txt_Barcode.Properties.EndInit();
            this.groupControl1.EndInit();
            this.Txt_Qty.Properties.EndInit();
            this.Txt_Unit.Properties.EndInit();
            this.cboCurrency.Properties.EndInit();
            this.Txt_Rtprice.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private SimpleButton btn_Exit;
        private SimpleButton btn_New;
        private SimpleButton btn_Save;
        private SimpleButton btn_Skip;
        private SimpleButton btn_SuspendLst;
        private SimpleButton btnReprint;
        private SimpleButton btnSuspend;
        internal ComboBoxEdit cboCurrency;
        internal LabelControl cnvLekth7;
        private GridControl GrdSale;
        internal GroupBox GroupBox2;
        private GroupControl groupControl1;
        //private IContainer components;
        internal LabelControl labelControl1;
        internal LabelControl LabelControl10;
        internal LabelControl labelControl11;
        internal LabelControl LabelControl12;
        internal LabelControl labelControl13;
        internal LabelControl labelControl15;
        internal LabelControl LabelControl17;
        internal LabelControl labelControl2;
        internal LabelControl labelControl3;
        internal LabelControl LabelControl4;
        internal LabelControl LabelControl5;
        internal LabelControl LabelControl6;
        internal LabelControl labelControl7;
        internal LabelControl LabelControl8;
        internal LabelControl labelControl9;
        private LabelControl Lbl_CurrencyCap;
        internal LabelControl Lbl_CurrencyName;
        internal LabelControl Lbl_Date;
        internal LabelControl Lbl_Discount;
        internal LabelControl Lbl_Exchange;
        internal LabelControl Lbl_Foreign;
        internal LabelControl Lbl_LastAmount;
        internal LabelControl Lbl_MercName;
        internal LabelControl Lbl_PayAmt;
        internal LabelControl Lbl_PaybackAmt;
        internal LabelControl Lbl_ReceivAmt;
        internal LabelControl Lbl_TotalAmount;
        private OleDbConnection oleDbConnection_0;
        private OleDbDataAdapter oleDbDataAdapter_0;
        private GridView Sales_View;
        private string string_0;
        private string string_1;
        private string string_2;
        private TextEdit Txt_Barcode;
        private SimpleButton Txt_MercSearch;
        private TextEdit Txt_Qty;
        private TextEdit Txt_Rtprice;
        internal TextEdit Txt_TransNum;
        private TextEdit Txt_Unit;


        #endregion

    }
}
