using DevExpress.XtraPrinting;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraGrid;
using System.Data.OleDb;
using System.Windows.Forms;
using DevExpress.XtraTab;
using DevExpress.Utils;
using System.ComponentModel;
using System.Drawing;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraEditors.Controls;
using System;
namespace LibraryManagement.App
{
    partial class FrmAdjust_grp
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new Container();
            manager = new ComponentResourceManager(typeof(FrmAdjust_grp));
            this.XtraTabControl1 = new XtraTabControl();
            this.XtraTabPage1 = new XtraTabPage();
            this.GrdMercLst = new GridControl();
            this.GridView1 = new GridView();
            this.XtraTabPage3 = new XtraTabPage();
            this.GrdErrorId = new GridControl();
            this.ErrorView = new GridView();
            this.Lbl_StockName = new LabelControl();
            this.chk_ByStore = new CheckEdit();
            this.btn_Exit = new SimpleButton();
            this.btn_Correct = new SimpleButton();
            this.btn_Print = new SimpleButton();
            this.btnUpdate = new SimpleButton();
            this.btnClear = new SimpleButton();
            this.LabelControl1 = new LabelControl();
            this.LabelControl17 = new LabelControl();
            this.Txt_StockId = new TextEdit();
            this.Txt_TextFile = new ButtonEdit();
            this.panelControl1 = new PanelControl();
            this.Chk_mbc = new CheckEdit();
            this.printingSystem_0 = new PrintingSystem(this.components);
            this.printableComponentLink_0 = new PrintableComponentLink(this.components);
            this.openFileDialog_0 = new OpenFileDialog();
            this.timer_0 = new Timer(this.components);
            this.Lbl_Warning = new LabelControl();
            this.toolTipController_0 = new ToolTipController(this.components);
            this.XtraTabControl1.BeginInit();
            this.XtraTabControl1.SuspendLayout();
            this.XtraTabPage1.SuspendLayout();
            this.GrdMercLst.BeginInit();
            this.GridView1.BeginInit();
            this.XtraTabPage3.SuspendLayout();
            this.GrdErrorId.BeginInit();
            this.ErrorView.BeginInit();
            this.chk_ByStore.Properties.BeginInit();
            this.Txt_StockId.Properties.BeginInit();
            this.Txt_TextFile.Properties.BeginInit();
            this.panelControl1.BeginInit();
            this.panelControl1.SuspendLayout();
            this.Chk_mbc.Properties.BeginInit();
            ((ISupportInitialize)this.printingSystem_0).BeginInit();
            this.printableComponentLink_0.ImageCollection.BeginInit();
            base.SuspendLayout();
            this.XtraTabControl1.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.XtraTabControl1.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.XtraTabControl1.Location = new Point(0x11, 0x88);
            this.XtraTabControl1.Name = "XtraTabControl1";
            this.XtraTabControl1.SelectedTabPage = this.XtraTabPage1;
            this.XtraTabControl1.Size = new Size(0x260, 0xf1);
            this.XtraTabControl1.TabIndex = 0x16b;
            this.XtraTabControl1.TabPages.AddRange(new XtraTabPage[] { this.XtraTabPage1, this.XtraTabPage3 });
            this.XtraTabPage1.Appearance.Header.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.XtraTabPage1.Appearance.Header.Options.UseFont = true;
            this.XtraTabPage1.Controls.Add(this.GrdMercLst);
            this.XtraTabPage1.Name = "XtraTabPage1";
            this.XtraTabPage1.Size = new Size(0x259, 0xd4);
            this.XtraTabPage1.Text = "M\x00e3 h\x00e0ng chuẩn";
            this.GrdMercLst.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.GrdMercLst.Location = new Point(0, 3);
            this.GrdMercLst.MainView = this.GridView1;
            this.GrdMercLst.Name = "GrdMercLst";
            this.GrdMercLst.Size = new Size(0x25a, 0xd6);
            this.GrdMercLst.TabIndex = 0xf3;
            this.GrdMercLst.ViewCollection.AddRange(new BaseView[] { this.GridView1 });
            this.GridView1.Appearance.FooterPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.GridView1.Appearance.FooterPanel.Options.UseFont = true;
            this.GridView1.Appearance.HeaderPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.GridView1.Appearance.HeaderPanel.Options.UseFont = true;
            this.GridView1.Appearance.Row.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.GridView1.Appearance.Row.Options.UseFont = true;
            this.GridView1.GridControl = this.GrdMercLst;
            this.GridView1.Name = "GridView1";
            this.GridView1.OptionsView.ShowAutoFilterRow = true;
            this.GridView1.OptionsView.ShowFooter = true;
            this.GridView1.OptionsView.ShowGroupPanel = false;
            this.XtraTabPage3.Appearance.Header.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.XtraTabPage3.Appearance.Header.Options.UseFont = true;
            this.XtraTabPage3.Controls.Add(this.GrdErrorId);
            this.XtraTabPage3.Name = "XtraTabPage3";
            this.XtraTabPage3.Size = new Size(0x259, 0xd4);
            this.XtraTabPage3.Text = "M\x00e3 h\x00e0ng sai";
            this.GrdErrorId.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.GrdErrorId.Location = new Point(3, 3);
            this.GrdErrorId.MainView = this.ErrorView;
            this.GrdErrorId.Name = "GrdErrorId";
            this.GrdErrorId.Size = new Size(0x251, 0xe1);
            this.GrdErrorId.TabIndex = 0xf4;
            this.GrdErrorId.ViewCollection.AddRange(new BaseView[] { this.ErrorView });
            this.ErrorView.Appearance.FooterPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.ErrorView.Appearance.FooterPanel.Options.UseFont = true;
            this.ErrorView.Appearance.HeaderPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.ErrorView.Appearance.HeaderPanel.Options.UseFont = true;
            this.ErrorView.Appearance.Row.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ErrorView.Appearance.Row.Options.UseFont = true;
            this.ErrorView.GridControl = this.GrdErrorId;
            this.ErrorView.Name = "ErrorView";
            this.ErrorView.OptionsView.ShowAutoFilterRow = true;
            this.ErrorView.OptionsView.ShowFooter = true;
            this.ErrorView.OptionsView.ShowGroupPanel = false;
            this.Lbl_StockName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_StockName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_StockName.Appearance.BorderColor = Color.White;
            this.Lbl_StockName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_StockName.Appearance.ForeColor = Color.Black;
            this.Lbl_StockName.Appearance.Options.UseBackColor = true;
            this.Lbl_StockName.Appearance.Options.UseBorderColor = true;
            this.Lbl_StockName.Appearance.Options.UseFont = true;
            this.Lbl_StockName.Appearance.Options.UseForeColor = true;
            this.Lbl_StockName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_StockName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_StockName.Location = new Point(0xd8, 20);
            this.Lbl_StockName.Name = "Lbl_StockName";
            this.Lbl_StockName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_StockName.Size = new Size(0x16a, 0x11);
            this.Lbl_StockName.TabIndex = 360;
            this.chk_ByStore.Location = new Point(0x7f, 0x42);
            this.chk_ByStore.Name = "chk_ByStore";
            this.chk_ByStore.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.chk_ByStore.Properties.Appearance.Options.UseFont = true;
            this.chk_ByStore.Properties.Caption = "Hiệu chỉnh to\x00e0n bộ kho, quầy";
            this.chk_ByStore.Size = new Size(0xe1, 0x13);
            this.chk_ByStore.TabIndex = 0x167;
            this.chk_ByStore.TabStop = false;
            this.chk_ByStore.CheckedChanged += new EventHandler(this.chk_ByStore_CheckedChanged);
            this.chk_ByStore.MouseHover += new EventHandler(this.IjSwogAv6);
            this.btn_Exit.Anchor = AnchorStyles.Bottom;
            this.btn_Exit.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btn_Exit.Appearance.Options.UseFont = true;
            this.btn_Exit.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Exit.Location = new Point(0x189, 0x183);
            this.btn_Exit.Name = "btn_Exit";
            this.btn_Exit.Size = new Size(0x58, 0x17);
            this.btn_Exit.TabIndex = 0x162;
            this.btn_Exit.Text = "Tho\x00e1t";
            this.btn_Exit.Click += new EventHandler(this.btn_Exit_Click);
            this.btn_Correct.Anchor = AnchorStyles.Bottom;
            this.btn_Correct.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btn_Correct.Appearance.Options.UseFont = true;
            this.btn_Correct.Location = new Point(0xa1, 0x183);
            this.btn_Correct.Name = "btn_Correct";
            this.btn_Correct.Size = new Size(0x58, 0x17);
            this.btn_Correct.TabIndex = 0x160;
            this.btn_Correct.Text = "&Hiệu chỉnh";
            this.btn_Correct.Click += new EventHandler(this.btn_Correct_Click);
            this.btn_Print.Anchor = AnchorStyles.Bottom;
            this.btn_Print.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btn_Print.Appearance.Options.UseFont = true;
            this.btn_Print.Location = new Point(0x113, 0x183);
            this.btn_Print.Name = "btn_Print";
            this.btn_Print.Size = new Size(0x58, 0x17);
            this.btn_Print.TabIndex = 0x161;
            this.btn_Print.Text = "Ctrl+P In";
            this.btn_Print.Click += new EventHandler(this.btn_Print_Click);
            this.btnUpdate.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnUpdate.Appearance.Options.UseFont = true;
            this.btnUpdate.Location = new Point(0x1e6, 0x42);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.Size = new Size(0x5c, 0x17);
            this.btnUpdate.TabIndex = 3;
            this.btnUpdate.Text = "Cập nhật DS";
            this.btnUpdate.Click += new EventHandler(this.btnUpdate_Click);
            this.btnClear.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnClear.Appearance.Options.UseFont = true;
            this.btnClear.Location = new Point(0x184, 0x42);
            this.btnClear.Name = "btnClear";
            this.btnClear.Size = new Size(0x5c, 0x17);
            this.btnClear.TabIndex = 350;
            this.btnClear.TabStop = false;
            this.btnClear.Text = "L\x00e0m rỗng DS";
            this.btnClear.Click += new EventHandler(this.btnClear_Click);
            this.LabelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl1.Appearance.Options.UseFont = true;
            this.LabelControl1.Location = new Point(0x11, 0x2d);
            this.LabelControl1.Name = "LabelControl1";
            this.LabelControl1.Size = new Size(0x5b, 13);
            this.LabelControl1.TabIndex = 0x15d;
            this.LabelControl1.Text = "Tệp dữ liệu kiểm k\x00ea";
            this.LabelControl17.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl17.Appearance.Options.UseFont = true;
            this.LabelControl17.Location = new Point(0x11, 0x17);
            this.LabelControl17.Name = "LabelControl17";
            this.LabelControl17.Size = new Size(0x3d, 13);
            this.LabelControl17.TabIndex = 0x15b;
            this.LabelControl17.Text = "M\x00e3 kho h\x00e0ng";
            this.Txt_StockId.EnterMoveNextControl = true;
            this.Txt_StockId.Location = new Point(0x81, 0x11);
            this.Txt_StockId.Name = "Txt_StockId";
            this.Txt_StockId.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_StockId.Properties.Appearance.Options.UseFont = true;
            this.Txt_StockId.Properties.MaxLength = 5;
            this.Txt_StockId.Size = new Size(80, 20);
            this.Txt_StockId.TabIndex = 0;
            this.Txt_StockId.EditValueChanged += new EventHandler(this.Txt_StockId_EditValueChanged);
            this.Txt_StockId.KeyDown += new KeyEventHandler(this.Txt_StockId_KeyDown);
            this.Txt_TextFile.EnterMoveNextControl = true;
            this.Txt_TextFile.Location = new Point(0x81, 40);
            this.Txt_TextFile.Name = "Txt_TextFile";
            this.Txt_TextFile.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton() });
            this.Txt_TextFile.Size = new Size(0x1c1, 20);
            this.Txt_TextFile.TabIndex = 1;
            this.Txt_TextFile.ButtonClick += new ButtonPressedEventHandler(this.Txt_TextFile_ButtonClick);
            this.panelControl1.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.panelControl1.Controls.Add(this.Chk_mbc);
            this.panelControl1.Controls.Add(this.LabelControl1);
            this.panelControl1.Controls.Add(this.Txt_TextFile);
            this.panelControl1.Controls.Add(this.chk_ByStore);
            this.panelControl1.Controls.Add(this.Lbl_StockName);
            this.panelControl1.Controls.Add(this.btnUpdate);
            this.panelControl1.Controls.Add(this.btnClear);
            this.panelControl1.Controls.Add(this.LabelControl17);
            this.panelControl1.Controls.Add(this.Txt_StockId);
            this.panelControl1.Location = new Point(20, 12);
            this.panelControl1.Name = "panelControl1";
            this.panelControl1.Size = new Size(0x25d, 0x76);
            this.panelControl1.TabIndex = 0x16d;
            this.panelControl1.Paint += new PaintEventHandler(this.panelControl1_Paint);
            this.Chk_mbc.EditValue = true;
            this.Chk_mbc.Location = new Point(0x7f, 0x5b);
            this.Chk_mbc.Name = "Chk_mbc";
            this.Chk_mbc.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Chk_mbc.Properties.Appearance.Options.UseFont = true;
            this.Chk_mbc.Properties.Caption = "Kh\x00f4ng hiệu chỉnh h\x00e0ng tươi sống";
            this.Chk_mbc.Size = new Size(0xe1, 0x13);
            this.Chk_mbc.TabIndex = 0x169;
            this.Chk_mbc.TabStop = false;
            this.printingSystem_0.Links.AddRange(new object[] { this.printableComponentLink_0 });
            this.printableComponentLink_0.Component = this.GrdMercLst;
            this.printableComponentLink_0.ImageCollection.ImageStream = (ImageCollectionStreamer)manager.GetObject("printableComponentLink1.ImageCollection.ImageStream");
            this.printableComponentLink_0.PrintingSystem = this.printingSystem_0;
            this.printableComponentLink_0.PrintingSystemBase = this.printingSystem_0;
            this.printableComponentLink_0.CreateReportHeaderArea += new CreateAreaEventHandler(this.printableComponentLink_0_CreateReportHeaderArea);
            this.openFileDialog_0.FileName = "*.txt";
            this.openFileDialog_0.FileOk += new CancelEventHandler(this.openFileDialog_0_FileOk);
            this.timer_0.Enabled = true;
            this.timer_0.Tick += new EventHandler(this.timer_0_Tick);
            this.Lbl_Warning.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.Lbl_Warning.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.Lbl_Warning.Appearance.ForeColor = Color.Red;
            this.Lbl_Warning.Appearance.Options.UseFont = true;
            this.Lbl_Warning.Appearance.Options.UseForeColor = true;
            this.Lbl_Warning.Location = new Point(20, 0x189);
            this.Lbl_Warning.Name = "Lbl_Warning";
            this.Lbl_Warning.Size = new Size(0x58, 13);
            this.Lbl_Warning.TabIndex = 0x16f;
            this.Lbl_Warning.Text = "C\x00f3 1,000 m\x00e3 sai";
            this.toolTipController_0.Rounded = true;
            this.toolTipController_0.ToolTipType = ToolTipType.SuperTip;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.ClientSize = new Size(0x282, 0x1a7);
            base.Controls.Add(this.Lbl_Warning);
            base.Controls.Add(this.panelControl1);
            base.Controls.Add(this.XtraTabControl1);
            base.Controls.Add(this.btn_Exit);
            base.Controls.Add(this.btn_Correct);
            base.Controls.Add(this.btn_Print);
            base.KeyPreview = true;
            base.Name = "FrmAdjust_grp";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmAdjust";
            base.Load += new EventHandler(this.FrmAdjust_grp_Load);
            base.Activated += new EventHandler(this.FrmAdjust_grp_Activated);
            base.FormClosing += new FormClosingEventHandler(this.FrmAdjust_grp_FormClosing);
            base.KeyDown += new KeyEventHandler(this.FrmAdjust_grp_KeyDown);
            this.XtraTabControl1.EndInit();
            this.XtraTabControl1.ResumeLayout(false);
            this.XtraTabPage1.ResumeLayout(false);
            this.GrdMercLst.EndInit();
            this.GridView1.EndInit();
            this.XtraTabPage3.ResumeLayout(false);
            this.GrdErrorId.EndInit();
            this.ErrorView.EndInit();
            this.chk_ByStore.Properties.EndInit();
            this.Txt_StockId.Properties.EndInit();
            this.Txt_TextFile.Properties.EndInit();
            this.panelControl1.EndInit();
            this.panelControl1.ResumeLayout(false);
            this.panelControl1.PerformLayout();
            this.Chk_mbc.Properties.EndInit();
            ((ISupportInitialize)this.printingSystem_0).EndInit();
            this.printableComponentLink_0.ImageCollection.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        internal SimpleButton btn_Correct;
        internal SimpleButton btn_Exit;
        internal SimpleButton btn_Print;
        internal SimpleButton btnClear;
        internal SimpleButton btnUpdate;
        internal CheckEdit chk_ByStore;
        internal CheckEdit Chk_mbc;
        internal GridView ErrorView;
        internal GridControl GrdErrorId;
        internal GridControl GrdMercLst;
        internal GridView GridView1;
        internal LabelControl LabelControl1;
        internal LabelControl LabelControl17;
        internal LabelControl Lbl_StockName;
        internal LabelControl Lbl_Warning;
        private OleDbConnection oleDbConnection_0;
        private OleDbDataAdapter oleDbDataAdapter_0;
        internal OpenFileDialog openFileDialog_0;
        private PanelControl panelControl1;
        private PrintableComponentLink printableComponentLink_0;
        private PrintingSystem printingSystem_0;
        private string string_0;
        private string string_1;
        private Timer timer_0;
        private ToolTipController toolTipController_0;
        internal TextEdit Txt_StockId;
        private ButtonEdit Txt_TextFile;
        internal XtraTabControl XtraTabControl1;
        internal XtraTabPage XtraTabPage1;
        internal XtraTabPage XtraTabPage3;
        private ComponentResourceManager manager;
        #endregion
    }
}