using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraGrid;
using DevExpress.XtraGrid.Views.Base;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraPrinting;
using System;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Windows.Forms;


namespace LibraryManagement.App
{
    partial class FrmAtrList
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private ComponentResourceManager manager;
        private void InitializeComponent()
        {
            this.components = new Container();
            manager = new ComponentResourceManager(typeof(FrmAtrList));
            this.LabelControl7 = new LabelControl();
            this.Lbl_Remark = new LabelControl();
            this.LabelControl6 = new LabelControl();
            this.Lbl_UserName = new LabelControl();
            this.Lbl_TransName = new LabelControl();
            this.Lbl_TransNum = new LabelControl();
            this.Lbl_TranDate = new LabelControl();
            this.Lbl_TransCode = new LabelControl();
            this.Lbl_Voucher = new LabelControl();
            this.LabelControl4 = new LabelControl();
            this.LabelControl3 = new LabelControl();
            this.LabelControl1 = new LabelControl();
            this.btnExit = new SimpleButton();
            this.btnPrintInvoice = new SimpleButton();
            this.btnPrint = new SimpleButton();
            this.GrdTranDetail = new GridControl();
            this.DetailView = new GridView();
            this.GrdTransList = new GridControl();
            this.TransView = new GridView();
            this.GridView2 = new GridView();
            this.printingSystem_0 = new PrintingSystem(this.components);
            this.printableComponentLink_0 = new PrintableComponentLink(this.components);
            this.Lbl_duaration = new LabelControl();
            this.btnDelete = new SimpleButton();
            this.GrdTranDetail.BeginInit();
            this.DetailView.BeginInit();
            this.GrdTransList.BeginInit();
            this.TransView.BeginInit();
            this.GridView2.BeginInit();
            ((ISupportInitialize)this.printingSystem_0).BeginInit();
            this.printableComponentLink_0.ImageCollection.BeginInit();
            base.SuspendLayout();
            this.LabelControl7.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.LabelControl7.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl7.Appearance.Options.UseFont = true;
            this.LabelControl7.Location = new Point(0x20, 0x19b);
            this.LabelControl7.Name = "LabelControl7";
            this.LabelControl7.Size = new Size(0x23, 13);
            this.LabelControl7.TabIndex = 0x17f;
            this.LabelControl7.Text = "Ghi ch\x00fa";
            this.Lbl_Remark.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.Lbl_Remark.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Remark.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Remark.Appearance.BorderColor = Color.White;
            this.Lbl_Remark.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Remark.Appearance.ForeColor = Color.Black;
            this.Lbl_Remark.Appearance.Options.UseBackColor = true;
            this.Lbl_Remark.Appearance.Options.UseBorderColor = true;
            this.Lbl_Remark.Appearance.Options.UseFont = true;
            this.Lbl_Remark.Appearance.Options.UseForeColor = true;
            this.Lbl_Remark.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Remark.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Remark.Location = new Point(0x77, 0x197);
            this.Lbl_Remark.Name = "Lbl_Remark";
            this.Lbl_Remark.Size = new Size(0x1e4, 0x11);
            this.Lbl_Remark.TabIndex = 0x17e;
            this.LabelControl6.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl6.Appearance.Options.UseFont = true;
            this.LabelControl6.Location = new Point(0x20, 0xf3);
            this.LabelControl6.Name = "LabelControl6";
            this.LabelControl6.Size = new Size(0x45, 13);
            this.LabelControl6.TabIndex = 0x17d;
            this.LabelControl6.Text = "Người đăng k\x00fd";
            this.Lbl_UserName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_UserName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_UserName.Appearance.BorderColor = Color.White;
            this.Lbl_UserName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_UserName.Appearance.ForeColor = Color.Black;
            this.Lbl_UserName.Appearance.Options.UseBackColor = true;
            this.Lbl_UserName.Appearance.Options.UseBorderColor = true;
            this.Lbl_UserName.Appearance.Options.UseFont = true;
            this.Lbl_UserName.Appearance.Options.UseForeColor = true;
            this.Lbl_UserName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_UserName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_UserName.Location = new Point(0x77, 0xf2);
            this.Lbl_UserName.Name = "Lbl_UserName";
            this.Lbl_UserName.Padding = new Padding(5, 0, 0, 0);
            this.Lbl_UserName.Size = new Size(0x95, 0x11);
            this.Lbl_UserName.TabIndex = 380;
            this.Lbl_TransName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_TransName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_TransName.Appearance.BorderColor = Color.White;
            this.Lbl_TransName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_TransName.Appearance.ForeColor = Color.Black;
            this.Lbl_TransName.Appearance.Options.UseBackColor = true;
            this.Lbl_TransName.Appearance.Options.UseBorderColor = true;
            this.Lbl_TransName.Appearance.Options.UseFont = true;
            this.Lbl_TransName.Appearance.Options.UseForeColor = true;
            this.Lbl_TransName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_TransName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_TransName.Location = new Point(160, 0xdb);
            this.Lbl_TransName.Name = "Lbl_TransName";
            this.Lbl_TransName.Padding = new Padding(5, 0, 0, 0);
            this.Lbl_TransName.Size = new Size(0x1bb, 0x11);
            this.Lbl_TransName.TabIndex = 0x17b;
            this.Lbl_TransNum.Appearance.BackColor = Color.Yellow;
            this.Lbl_TransNum.Appearance.BackColor2 = Color.FromArgb(0xff, 0xff, 0xc0);
            this.Lbl_TransNum.Appearance.BorderColor = Color.White;
            this.Lbl_TransNum.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Lbl_TransNum.Appearance.ForeColor = Color.Black;
            this.Lbl_TransNum.Appearance.Options.UseBackColor = true;
            this.Lbl_TransNum.Appearance.Options.UseBorderColor = true;
            this.Lbl_TransNum.Appearance.Options.UseFont = true;
            this.Lbl_TransNum.Appearance.Options.UseForeColor = true;
            this.Lbl_TransNum.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_TransNum.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_TransNum.Location = new Point(0x77, 0xc4);
            this.Lbl_TransNum.Name = "Lbl_TransNum";
            this.Lbl_TransNum.Padding = new Padding(5, 0, 0, 0);
            this.Lbl_TransNum.Size = new Size(0x68, 0x11);
            this.Lbl_TransNum.TabIndex = 0x17a;
            this.Lbl_TransNum.TextChanged += new EventHandler(this.Lbl_TransNum_TextChanged);
            this.Lbl_TranDate.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_TranDate.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_TranDate.Appearance.BorderColor = Color.White;
            this.Lbl_TranDate.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_TranDate.Appearance.ForeColor = Color.Black;
            this.Lbl_TranDate.Appearance.Options.UseBackColor = true;
            this.Lbl_TranDate.Appearance.Options.UseBorderColor = true;
            this.Lbl_TranDate.Appearance.Options.UseFont = true;
            this.Lbl_TranDate.Appearance.Options.UseForeColor = true;
            this.Lbl_TranDate.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_TranDate.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_TranDate.Location = new Point(0xe5, 0xc4);
            this.Lbl_TranDate.Name = "Lbl_TranDate";
            this.Lbl_TranDate.Padding = new Padding(5, 0, 0, 0);
            this.Lbl_TranDate.Size = new Size(0x48, 0x11);
            this.Lbl_TranDate.TabIndex = 0x179;
            this.Lbl_TransCode.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_TransCode.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_TransCode.Appearance.BorderColor = Color.White;
            this.Lbl_TransCode.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_TransCode.Appearance.ForeColor = Color.Black;
            this.Lbl_TransCode.Appearance.Options.UseBackColor = true;
            this.Lbl_TransCode.Appearance.Options.UseBorderColor = true;
            this.Lbl_TransCode.Appearance.Options.UseFont = true;
            this.Lbl_TransCode.Appearance.Options.UseForeColor = true;
            this.Lbl_TransCode.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_TransCode.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_TransCode.Location = new Point(0x77, 0xdb);
            this.Lbl_TransCode.Name = "Lbl_TransCode";
            this.Lbl_TransCode.Padding = new Padding(5, 0, 0, 0);
            this.Lbl_TransCode.Size = new Size(0x23, 0x11);
            this.Lbl_TransCode.TabIndex = 0x178;
            this.Lbl_TransCode.TextChanged += new EventHandler(this.Lbl_TransCode_TextChanged);
            this.Lbl_Voucher.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Voucher.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Voucher.Appearance.BorderColor = Color.White;
            this.Lbl_Voucher.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Voucher.Appearance.ForeColor = Color.Black;
            this.Lbl_Voucher.Appearance.Options.UseBackColor = true;
            this.Lbl_Voucher.Appearance.Options.UseBorderColor = true;
            this.Lbl_Voucher.Appearance.Options.UseFont = true;
            this.Lbl_Voucher.Appearance.Options.UseForeColor = true;
            this.Lbl_Voucher.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Voucher.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Voucher.Location = new Point(0x1d5, 0xc4);
            this.Lbl_Voucher.Name = "Lbl_Voucher";
            this.Lbl_Voucher.Padding = new Padding(5, 0, 0, 0);
            this.Lbl_Voucher.Size = new Size(0x86, 0x11);
            this.Lbl_Voucher.TabIndex = 0x177;
            this.LabelControl4.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl4.Appearance.Options.UseFont = true;
            this.LabelControl4.Location = new Point(0x20, 0xdb);
            this.LabelControl4.Name = "LabelControl4";
            this.LabelControl4.Size = new Size(0x24, 13);
            this.LabelControl4.TabIndex = 0x173;
            this.LabelControl4.Text = "Loại GD";
            this.LabelControl3.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl3.Appearance.Options.UseFont = true;
            this.LabelControl3.Location = new Point(360, 0xc6);
            this.LabelControl3.Name = "LabelControl3";
            this.LabelControl3.Size = new Size(0x59, 13);
            this.LabelControl3.TabIndex = 370;
            this.LabelControl3.Text = "Chứng từ/h\x00f3a đơn";
            this.LabelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl1.Appearance.Options.UseFont = true;
            this.LabelControl1.Location = new Point(0x20, 0xc4);
            this.LabelControl1.Name = "LabelControl1";
            this.LabelControl1.Size = new Size(0x39, 13);
            this.LabelControl1.TabIndex = 0x170;
            this.LabelControl1.Text = "Số giao dịch";
            this.btnExit.Anchor = AnchorStyles.Bottom;
            this.btnExit.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnExit.Appearance.Options.UseFont = true;
            this.btnExit.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnExit.Location = new Point(0x1c0, 0x1b6);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new Size(0x58, 0x17);
            this.btnExit.TabIndex = 0x16f;
            this.btnExit.Text = "ESC-Tho\x00e1t";
            this.btnExit.Click += new EventHandler(this.btnExit_Click);
            this.btnPrintInvoice.Anchor = AnchorStyles.Bottom;
            this.btnPrintInvoice.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnPrintInvoice.Appearance.Options.UseFont = true;
            this.btnPrintInvoice.Location = new Point(0x88, 0x1b6);
            this.btnPrintInvoice.Name = "btnPrintInvoice";
            this.btnPrintInvoice.Size = new Size(0x58, 0x17);
            this.btnPrintInvoice.TabIndex = 0x16d;
            this.btnPrintInvoice.Text = "In giao dịch";
            this.btnPrintInvoice.Click += new EventHandler(this.btnPrintInvoice_Click);
            this.btnPrint.Anchor = AnchorStyles.Bottom;
            this.btnPrint.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnPrint.Appearance.Options.UseFont = true;
            this.btnPrint.Location = new Point(240, 0x1b6);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new Size(0x58, 0x17);
            this.btnPrint.TabIndex = 0x16e;
            this.btnPrint.Text = "In to\x00e0n bộ";
            this.btnPrint.Click += new EventHandler(this.btnPrint_Click);
            this.GrdTranDetail.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Bottom | AnchorStyles.Top;
            this.GrdTranDetail.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.GrdTranDetail.Location = new Point(13, 0x109);
            this.GrdTranDetail.MainView = this.DetailView;
            this.GrdTranDetail.Name = "GrdTranDetail";
            this.GrdTranDetail.Size = new Size(0x287, 0x88);
            this.GrdTranDetail.TabIndex = 0x16c;
            this.GrdTranDetail.ViewCollection.AddRange(new BaseView[] { this.DetailView });
            this.DetailView.Appearance.FooterPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.DetailView.Appearance.FooterPanel.Options.UseFont = true;
            this.DetailView.Appearance.GroupFooter.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.DetailView.Appearance.GroupFooter.Options.UseFont = true;
            this.DetailView.Appearance.HeaderPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.DetailView.Appearance.HeaderPanel.Options.UseFont = true;
            this.DetailView.Appearance.Row.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.DetailView.Appearance.Row.Options.UseFont = true;
            this.DetailView.GridControl = this.GrdTranDetail;
            this.DetailView.Name = "DetailView";
            this.DetailView.OptionsView.ShowGroupPanel = false;
            this.GrdTransList.Anchor = AnchorStyles.Right | AnchorStyles.Left | AnchorStyles.Top;
            this.GrdTransList.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.GrdTransList.Location = new Point(13, 0x1b);
            this.GrdTransList.MainView = this.TransView;
            this.GrdTransList.Name = "GrdTransList";
            this.GrdTransList.Size = new Size(0x287, 0xa2);
            this.GrdTransList.TabIndex = 0x16b;
            this.GrdTransList.ViewCollection.AddRange(new BaseView[] { this.TransView, this.GridView2 });
            this.GrdTransList.Click += new EventHandler(this.GrdTransList_Click);
            this.TransView.Appearance.FooterPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.TransView.Appearance.FooterPanel.Options.UseFont = true;
            this.TransView.Appearance.GroupPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.TransView.Appearance.GroupPanel.Options.UseFont = true;
            this.TransView.Appearance.HeaderPanel.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.TransView.Appearance.HeaderPanel.Options.UseFont = true;
            this.TransView.Appearance.Row.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.TransView.Appearance.Row.Options.UseFont = true;
            this.TransView.GridControl = this.GrdTransList;
            this.TransView.Name = "TransView";
            this.TransView.OptionsView.ShowAutoFilterRow = true;
            this.TransView.OptionsView.ShowGroupPanel = false;
            this.TransView.FocusedRowChanged += new FocusedRowChangedEventHandler(this.TransView_FocusedRowChanged);
            this.GridView2.GridControl = this.GrdTransList;
            this.GridView2.Name = "GridView2";
            this.printingSystem_0.Links.AddRange(new object[] { this.printableComponentLink_0 });
            this.printableComponentLink_0.Component = this.GrdTransList;
            this.printableComponentLink_0.ImageCollection.ImageStream = (ImageCollectionStreamer)manager.GetObject("printableComponentLink1.ImageCollection.ImageStream");
            this.printableComponentLink_0.PrintingSystem = this.printingSystem_0;
            this.printableComponentLink_0.PrintingSystemBase = this.printingSystem_0;
            this.printableComponentLink_0.CreateReportHeaderArea += new CreateAreaEventHandler(this.printableComponentLink_0_CreateReportHeaderArea);
            this.Lbl_duaration.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.Lbl_duaration.Appearance.ForeColor = Color.DarkBlue;
            this.Lbl_duaration.Appearance.Options.UseFont = true;
            this.Lbl_duaration.Appearance.Options.UseForeColor = true;
            this.Lbl_duaration.Location = new Point(13, 8);
            this.Lbl_duaration.Name = "Lbl_duaration";
            this.Lbl_duaration.Size = new Size(0xf3, 13);
            this.Lbl_duaration.TabIndex = 0x180;
            this.Lbl_duaration.Text = "Từ ng\x00e0y 20/01/2010 đến ng\x00e0y 30/01/2010";
            this.btnDelete.Anchor = AnchorStyles.Bottom;
            this.btnDelete.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.btnDelete.Appearance.Options.UseFont = true;
            this.btnDelete.Location = new Point(0x158, 0x1b6);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new Size(0x58, 0x17);
            this.btnDelete.TabIndex = 0x181;
            this.btnDelete.Text = "X\x00f3a GD";
            this.btnDelete.Click += new EventHandler(this.btnDelete_Click);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.CancelButton = this.btnExit;
            base.ClientSize = new Size(0x2a0, 0x1db);
            base.Controls.Add(this.btnDelete);
            base.Controls.Add(this.Lbl_duaration);
            base.Controls.Add(this.LabelControl7);
            base.Controls.Add(this.Lbl_Remark);
            base.Controls.Add(this.LabelControl6);
            base.Controls.Add(this.Lbl_UserName);
            base.Controls.Add(this.Lbl_TransName);
            base.Controls.Add(this.Lbl_TransNum);
            base.Controls.Add(this.Lbl_TranDate);
            base.Controls.Add(this.Lbl_TransCode);
            base.Controls.Add(this.Lbl_Voucher);
            base.Controls.Add(this.LabelControl4);
            base.Controls.Add(this.LabelControl3);
            base.Controls.Add(this.LabelControl1);
            base.Controls.Add(this.btnExit);
            base.Controls.Add(this.btnPrintInvoice);
            base.Controls.Add(this.btnPrint);
            base.Controls.Add(this.GrdTranDetail);
            base.Controls.Add(this.GrdTransList);
            base.Name = "FrmAtrList";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmAtrList";
            base.Load += new EventHandler(this.FrmAtrList_Load);
            base.Activated += new EventHandler(this.FrmAtrList_Activated);
            this.GrdTranDetail.EndInit();
            this.DetailView.EndInit();
            this.GrdTransList.EndInit();
            this.TransView.EndInit();
            this.GridView2.EndInit();
            ((ISupportInitialize)this.printingSystem_0).EndInit();
            this.printableComponentLink_0.ImageCollection.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        internal SimpleButton btnDelete;
        internal SimpleButton btnExit;
        internal SimpleButton btnPrint;
        internal SimpleButton btnPrintInvoice;
        internal GridView DetailView;
        internal GridControl GrdTranDetail;
        internal GridControl GrdTransList;
        internal GridView GridView2;
        internal LabelControl LabelControl1;
        internal LabelControl LabelControl3;
        internal LabelControl LabelControl4;
        internal LabelControl LabelControl6;
        internal LabelControl LabelControl7;
        private LabelControl Lbl_duaration;
        internal LabelControl Lbl_Remark;
        internal LabelControl Lbl_TranDate;
        internal LabelControl Lbl_TransCode;
        internal LabelControl Lbl_TransName;
        internal LabelControl Lbl_TransNum;
        internal LabelControl Lbl_UserName;
        internal LabelControl Lbl_Voucher;
        private OleDbConnection oleDbConnection_0;
        private OleDbDataAdapter oleDbDataAdapter_0;
        private PrintableComponentLink printableComponentLink_0;
        private PrintingSystem printingSystem_0;
        private string string_0;
        internal GridView TransView;


        #endregion

    }
}