using DevExpress.Utils;
using DevExpress.XtraPrinting;
using DevExpress.XtraReports.UI;
using System;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Drawing.Printing;

namespace LibraryManagement.App
{
    public class v_frsupp : XtraReport
    {
        private BottomMarginBand bottomMarginBand_0;
        private DetailBand detailBand_0;
        private XRTableCell ecgIrJiEyW;
        private XRLabel HygIsNcsnq;
        private IContainer icontainer_0;
        private string LvbIuIdVwC;
        private OleDbConnection oleDbConnection_0;
        private OleDbDataAdapter oleDbDataAdapter_0;
        private PageFooterBand pageFooterBand_0;
        private PageHeaderBand pageHeaderBand_0;
        private ReportFooterBand reportFooterBand_0;
        private ReportHeaderBand reportHeaderBand_0;
        private TopMarginBand topMarginBand_0;
        private XRLabel xrlabel_0;
        private XRLabel xrlabel_1;
        private XRLabel xrlabel_10;
        private XRLabel xrlabel_11;
        private XRLabel xrlabel_12;
        private XRLabel xrlabel_13;
        private XRLabel xrlabel_14;
        private XRLabel xrlabel_15;
        private XRLabel xrlabel_16;
        private XRLabel xrlabel_17;
        private XRLabel xrlabel_18;
        private XRLabel xrlabel_19;
        private XRLabel xrlabel_2;
        private XRLabel xrlabel_20;
        private XRLabel xrlabel_21;
        private XRLabel xrlabel_22;
        private XRLabel xrlabel_23;
        private XRLabel xrlabel_24;
        private XRLabel xrlabel_25;
        private XRLabel xrlabel_26;
        private XRLabel xrlabel_27;
        private XRLabel xrlabel_28;
        private XRLabel xrlabel_29;
        private XRLabel xrlabel_3;
        private XRLabel xrlabel_30;
        private XRLabel xrlabel_4;
        private XRLabel xrlabel_5;
        private XRLabel xrlabel_6;
        private XRLabel xrlabel_7;
        private XRLabel xrlabel_8;
        private XRLabel xrlabel_9;
        private XRLine xrline_0;
        private XRPageInfo xrpageInfo_0;
        private XRPageInfo xrpageInfo_1;
        private XRSummary xrsummary_0;
        private XRSummary xrsummary_1;
        private XRSummary xrsummary_2;
        private XRSummary xrsummary_3;
        private XRSummary xrsummary_4;
        private XRTable xrtable_0;
        private XRTable xrtable_1;
        private XRTable xrtable_2;
        private XRTableCell xrtableCell_0;
        private XRTableCell xrtableCell_1;
        private XRTableCell xrtableCell_10;
        private XRTableCell xrtableCell_11;
        private XRTableCell xrtableCell_12;
        private XRTableCell xrtableCell_13;
        private XRTableCell xrtableCell_14;
        private XRTableCell xrtableCell_15;
        private XRTableCell xrtableCell_16;
        private XRTableCell xrtableCell_17;
        private XRTableCell xrtableCell_18;
        private XRTableCell xrtableCell_19;
        private XRTableCell xrtableCell_2;
        private XRTableCell xrtableCell_20;
        private XRTableCell xrtableCell_21;
        private XRTableCell xrtableCell_22;
        private XRTableCell xrtableCell_23;
        private XRTableCell xrtableCell_24;
        private XRTableCell xrtableCell_25;
        private XRTableCell xrtableCell_3;
        private XRTableCell xrtableCell_4;
        private XRTableCell xrtableCell_5;
        private XRTableCell xrtableCell_6;
        private XRTableCell xrtableCell_7;
        private XRTableCell xrtableCell_8;
        private XRTableCell xrtableCell_9;
        private XRTableRow xrtableRow_0;
        private XRTableRow xrtableRow_1;
        private XRTableRow xrtableRow_2;
        private XRLabel xTveRubwQ;

        static v_frsupp()
        {
            Class15.smethod_5();
        }

        public v_frsupp()
        {
            Class17.smethod_0();
            this.icontainer_0 = null;
            this.oleDbConnection_0 = new OleDbConnection(Class7.string_5);
            this.LvbIuIdVwC = null;
            this.xrsummary_0 = new XRSummary();
            this.xrsummary_1 = new XRSummary();
            this.xrsummary_2 = new XRSummary();
            this.xrsummary_3 = new XRSummary();
            this.xrsummary_4 = new XRSummary();
            this.method_0();
        }

        private void detailBand_0_BeforePrint(object sender, PrintEventArgs e)
        {
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(disposing);
        }

        private void method_0()
        {
            XRSummary summary = new XRSummary();
            XRSummary summary2 = new XRSummary();
            XRSummary summary3 = new XRSummary();
            XRSummary summary4 = new XRSummary();
            XRSummary summary5 = new XRSummary();
            this.detailBand_0 = new DetailBand();
            this.xrtable_1 = new XRTable();
            this.xrtableRow_1 = new XRTableRow();
            this.xrtableCell_10 = new XRTableCell();
            this.xrtableCell_11 = new XRTableCell();
            this.xrtableCell_7 = new XRTableCell();
            this.xrtableCell_8 = new XRTableCell();
            this.xrtableCell_12 = new XRTableCell();
            this.xrtableCell_9 = new XRTableCell();
            this.xrtableCell_14 = new XRTableCell();
            this.xrtableCell_15 = new XRTableCell();
            this.xrtableCell_13 = new XRTableCell();
            this.pageHeaderBand_0 = new PageHeaderBand();
            this.xrtable_0 = new XRTable();
            this.xrtableRow_0 = new XRTableRow();
            this.xrtableCell_0 = new XRTableCell();
            this.xrtableCell_1 = new XRTableCell();
            this.xrtableCell_2 = new XRTableCell();
            this.xrtableCell_3 = new XRTableCell();
            this.xrtableCell_4 = new XRTableCell();
            this.xrtableCell_5 = new XRTableCell();
            this.xrtableCell_6 = new XRTableCell();
            this.xrtableCell_16 = new XRTableCell();
            this.xrtableCell_17 = new XRTableCell();
            this.pageFooterBand_0 = new PageFooterBand();
            this.xrpageInfo_1 = new XRPageInfo();
            this.xrlabel_17 = new XRLabel();
            this.xrpageInfo_0 = new XRPageInfo();
            this.reportHeaderBand_0 = new ReportHeaderBand();
            this.xrlabel_26 = new XRLabel();
            this.xrlabel_27 = new XRLabel();
            this.xrlabel_18 = new XRLabel();
            this.xrlabel_19 = new XRLabel();
            this.xrlabel_16 = new XRLabel();
            this.xrlabel_13 = new XRLabel();
            this.xrlabel_14 = new XRLabel();
            this.xTveRubwQ = new XRLabel();
            this.xrlabel_15 = new XRLabel();
            this.xrlabel_7 = new XRLabel();
            this.xrlabel_8 = new XRLabel();
            this.xrlabel_9 = new XRLabel();
            this.xrlabel_10 = new XRLabel();
            this.xrlabel_11 = new XRLabel();
            this.xrlabel_12 = new XRLabel();
            this.xrlabel_4 = new XRLabel();
            this.xrlabel_5 = new XRLabel();
            this.xrlabel_6 = new XRLabel();
            this.xrlabel_1 = new XRLabel();
            this.xrlabel_2 = new XRLabel();
            this.xrlabel_3 = new XRLabel();
            this.xrlabel_0 = new XRLabel();
            this.reportFooterBand_0 = new ReportFooterBand();
            this.xrlabel_24 = new XRLabel();
            this.xrlabel_25 = new XRLabel();
            this.xrlabel_21 = new XRLabel();
            this.xrlabel_22 = new XRLabel();
            this.xrlabel_23 = new XRLabel();
            this.xrlabel_20 = new XRLabel();
            this.xrtable_2 = new XRTable();
            this.xrtableRow_2 = new XRTableRow();
            this.ecgIrJiEyW = new XRTableCell();
            this.xrtableCell_18 = new XRTableCell();
            this.xrtableCell_19 = new XRTableCell();
            this.xrtableCell_20 = new XRTableCell();
            this.xrtableCell_21 = new XRTableCell();
            this.xrtableCell_22 = new XRTableCell();
            this.xrtableCell_23 = new XRTableCell();
            this.xrtableCell_24 = new XRTableCell();
            this.xrtableCell_25 = new XRTableCell();
            this.xrlabel_28 = new XRLabel();
            this.HygIsNcsnq = new XRLabel();
            this.xrline_0 = new XRLine();
            this.topMarginBand_0 = new TopMarginBand();
            this.bottomMarginBand_0 = new BottomMarginBand();
            this.xrlabel_30 = new XRLabel();
            this.xrlabel_29 = new XRLabel();
            this.xrtable_1.BeginInit();
            this.xrtable_0.BeginInit();
            this.xrtable_2.BeginInit();
            this.BeginInit();
            this.detailBand_0.Controls.AddRange(new XRControl[] { this.xrtable_1 });
            this.detailBand_0.HeightF = 25f;
            this.detailBand_0.Name = "Detail";
            this.detailBand_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.detailBand_0.TextAlignment = TextAlignment.TopLeft;
            this.detailBand_0.BeforePrint += new PrintEventHandler(this.detailBand_0_BeforePrint);
            this.xrtable_1.Borders = BorderSide.Right | BorderSide.Left;
            this.xrtable_1.LocationFloat = new PointFloat(0f, 0f);
            this.xrtable_1.Name = "xrTable2";
            this.xrtable_1.Rows.AddRange(new XRTableRow[] { this.xrtableRow_1 });
            this.xrtable_1.SizeF = new SizeF(784f, 25f);
            this.xrtable_1.StylePriority.UseBorders = false;
            this.xrtableRow_1.Cells.AddRange(new XRTableCell[] { this.xrtableCell_10, this.xrtableCell_11, this.xrtableCell_7, this.xrtableCell_8, this.xrtableCell_12, this.xrtableCell_9, this.xrtableCell_14, this.xrtableCell_15, this.xrtableCell_13 });
            this.xrtableRow_1.Name = "xrTableRow2";
            this.xrtableRow_1.StylePriority.UseTextAlignment = false;
            this.xrtableRow_1.TextAlignment = TextAlignment.MiddleLeft;
            this.xrtableRow_1.Weight = 3.0;
            this.xrtableCell_10.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_10.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_10.Name = "col_Index";
            this.xrtableCell_10.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_10.StylePriority.UseBorders = false;
            this.xrtableCell_10.StylePriority.UseFont = false;
            this.xrtableCell_10.StylePriority.UsePadding = false;
            this.xrtableCell_10.StylePriority.UseTextAlignment = false;
            this.xrtableCell_10.Text = "col_Index";
            this.xrtableCell_10.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_10.Weight = 0.046206894797840334;
            this.xrtableCell_10.WordWrap = false;
            this.xrtableCell_11.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_11.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_11.Name = "col_GoodsId";
            this.xrtableCell_11.Padding = new PaddingInfo(3, 0, 0, 0, 100f);
            this.xrtableCell_11.StylePriority.UseBorders = false;
            this.xrtableCell_11.StylePriority.UseFont = false;
            this.xrtableCell_11.StylePriority.UsePadding = false;
            this.xrtableCell_11.Text = "col_GoodsId";
            this.xrtableCell_11.Weight = 0.079310343073702425;
            this.xrtableCell_11.WordWrap = false;
            this.xrtableCell_7.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_7.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_7.Name = "col_MercName";
            this.xrtableCell_7.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
            this.xrtableCell_7.StylePriority.UseBorders = false;
            this.xrtableCell_7.StylePriority.UseFont = false;
            this.xrtableCell_7.StylePriority.UsePadding = false;
            this.xrtableCell_7.Text = "col_MercName";
            this.xrtableCell_7.Weight = 0.33517241028533579;
            this.xrtableCell_7.WordWrap = false;
            this.xrtableCell_8.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_8.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_8.Name = "col_Unit";
            this.xrtableCell_8.StylePriority.UseBorders = false;
            this.xrtableCell_8.StylePriority.UseFont = false;
            this.xrtableCell_8.StylePriority.UseTextAlignment = false;
            this.xrtableCell_8.Text = "col_Unit";
            this.xrtableCell_8.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_8.Weight = 0.044137932788366557;
            this.xrtableCell_8.WordWrap = false;
            this.xrtableCell_12.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_12.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_12.Name = "col_Price";
            this.xrtableCell_12.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_12.StylePriority.UseBorders = false;
            this.xrtableCell_12.StylePriority.UseFont = false;
            this.xrtableCell_12.StylePriority.UsePadding = false;
            this.xrtableCell_12.StylePriority.UseTextAlignment = false;
            this.xrtableCell_12.Text = "col_Price";
            this.xrtableCell_12.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_12.Weight = 0.11724138106422863;
            this.xrtableCell_12.WordWrap = false;
            this.xrtableCell_12.BeforePrint += new PrintEventHandler(this.xrtableCell_12_BeforePrint);
            this.xrtableCell_9.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_9.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_9.Name = "col_Qty";
            this.xrtableCell_9.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_9.StylePriority.UseBorders = false;
            this.xrtableCell_9.StylePriority.UseFont = false;
            this.xrtableCell_9.StylePriority.UsePadding = false;
            this.xrtableCell_9.StylePriority.UseTextAlignment = false;
            this.xrtableCell_9.Text = "col_Qty";
            this.xrtableCell_9.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_9.Weight = 0.06758620865043552;
            this.xrtableCell_9.WordWrap = false;
            this.xrtableCell_14.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_14.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_14.Name = "col_discount";
            this.xrtableCell_14.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_14.StylePriority.UseBorders = false;
            this.xrtableCell_14.StylePriority.UseFont = false;
            this.xrtableCell_14.StylePriority.UsePadding = false;
            this.xrtableCell_14.StylePriority.UseTextAlignment = false;
            this.xrtableCell_14.Text = "col_discount";
            this.xrtableCell_14.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_14.Weight = 0.13724137755646101;
            this.xrtableCell_14.WordWrap = false;
            this.xrtableCell_15.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_15.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_15.Name = "col_vatamt";
            this.xrtableCell_15.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_15.StylePriority.UseBorders = false;
            this.xrtableCell_15.StylePriority.UseFont = false;
            this.xrtableCell_15.StylePriority.UsePadding = false;
            this.xrtableCell_15.StylePriority.UseTextAlignment = false;
            this.xrtableCell_15.Text = "col_vatamt";
            this.xrtableCell_15.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_15.Weight = 0.10310344476809444;
            this.xrtableCell_15.WordWrap = false;
            this.xrtableCell_13.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_13.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_13.Name = "col_Amount";
            this.xrtableCell_13.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_13.StylePriority.UseBorders = false;
            this.xrtableCell_13.StylePriority.UseFont = false;
            this.xrtableCell_13.StylePriority.UsePadding = false;
            this.xrtableCell_13.StylePriority.UseTextAlignment = false;
            this.xrtableCell_13.Text = "col_Amount";
            this.xrtableCell_13.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_13.Weight = 0.15137931736036275;
            this.xrtableCell_13.WordWrap = false;
            this.xrtableCell_13.BeforePrint += new PrintEventHandler(this.xrtableCell_13_BeforePrint);
            this.pageHeaderBand_0.Controls.AddRange(new XRControl[] { this.xrtable_0 });
            this.pageHeaderBand_0.HeightF = 30f;
            this.pageHeaderBand_0.Name = "PageHeader";
            this.pageHeaderBand_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.pageHeaderBand_0.TextAlignment = TextAlignment.TopLeft;
            this.xrtable_0.BackColor = Color.Transparent;
            this.xrtable_0.BorderColor = Color.Black;
            this.xrtable_0.Borders = BorderSide.All;
            this.xrtable_0.BorderWidth = 2;
            this.xrtable_0.Font = new Font("Times New Roman", 12f, FontStyle.Bold);
            this.xrtable_0.LocationFloat = new PointFloat(0f, 0f);
            this.xrtable_0.Name = "xrTable1";
            this.xrtable_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.xrtable_0.Rows.AddRange(new XRTableRow[] { this.xrtableRow_0 });
            this.xrtable_0.SizeF = new SizeF(784f, 30f);
            this.xrtable_0.StylePriority.UseBackColor = false;
            this.xrtable_0.StylePriority.UseBorderColor = false;
            this.xrtable_0.TextAlignment = TextAlignment.TopLeft;
            this.xrtableRow_0.BackColor = Color.WhiteSmoke;
            this.xrtableRow_0.Cells.AddRange(new XRTableCell[] { this.xrtableCell_0, this.xrtableCell_1, this.xrtableCell_2, this.xrtableCell_3, this.xrtableCell_4, this.xrtableCell_5, this.xrtableCell_6, this.xrtableCell_16, this.xrtableCell_17 });
            this.xrtableRow_0.Font = new Font("Tahoma", 8.25f, FontStyle.Bold);
            this.xrtableRow_0.Name = "xrTableRow1";
            this.xrtableRow_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.xrtableRow_0.StylePriority.UseBackColor = false;
            this.xrtableRow_0.TextAlignment = TextAlignment.TopLeft;
            this.xrtableRow_0.Weight = 0.69767441860465107;
            this.xrtableCell_0.BorderWidth = 1;
            this.xrtableCell_0.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_0.Name = "xrTableCell5";
            this.xrtableCell_0.StylePriority.UseBorderWidth = false;
            this.xrtableCell_0.StylePriority.UseFont = false;
            this.xrtableCell_0.StylePriority.UseTextAlignment = false;
            this.xrtableCell_0.Text = "TT";
            this.xrtableCell_0.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_0.Weight = 0.051538461538461526;
            this.xrtableCell_1.BorderWidth = 1;
            this.xrtableCell_1.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_1.Name = "xrTableCell1";
            this.xrtableCell_1.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.xrtableCell_1.StylePriority.UseFont = false;
            this.xrtableCell_1.Text = "M\x00e3 h\x00e0ng";
            this.xrtableCell_1.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_1.Weight = 0.088461538461538466;
            this.xrtableCell_2.BorderWidth = 1;
            this.xrtableCell_2.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_2.Name = "xrTableCell4";
            this.xrtableCell_2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_2.StylePriority.UseFont = false;
            this.xrtableCell_2.Text = "T\x00ean h\x00e0ng h\x00f3a";
            this.xrtableCell_2.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_2.Weight = 0.37384615384615377;
            this.xrtableCell_3.BorderWidth = 1;
            this.xrtableCell_3.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_3.Name = "xrTableCell7";
            this.xrtableCell_3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_3.StylePriority.UseFont = false;
            this.xrtableCell_3.Text = "ĐV";
            this.xrtableCell_3.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_3.Weight = 0.049230769230769238;
            this.xrtableCell_4.BorderWidth = 1;
            this.xrtableCell_4.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_4.Name = "xrTableCell2";
            this.xrtableCell_4.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_4.StylePriority.UseFont = false;
            this.xrtableCell_4.Text = "Gi\x00e1 nhập";
            this.xrtableCell_4.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_4.Weight = 0.13076923076923078;
            this.xrtableCell_5.BorderWidth = 1;
            this.xrtableCell_5.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_5.Name = "xrTableCell13";
            this.xrtableCell_5.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_5.StylePriority.UseFont = false;
            this.xrtableCell_5.Text = "SL";
            this.xrtableCell_5.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_5.Weight = 0.0753846153846154;
            this.xrtableCell_6.BorderWidth = 1;
            this.xrtableCell_6.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_6.Name = "xrTableCell3";
            this.xrtableCell_6.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_6.StylePriority.UseFont = false;
            this.xrtableCell_6.Text = "Chiết khấu";
            this.xrtableCell_6.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_6.Weight = 0.15307692307692308;
            this.xrtableCell_16.BorderWidth = 1;
            this.xrtableCell_16.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_16.Name = "xrTableCell6";
            this.xrtableCell_16.StylePriority.UseBorderWidth = false;
            this.xrtableCell_16.StylePriority.UseFont = false;
            this.xrtableCell_16.StylePriority.UseTextAlignment = false;
            this.xrtableCell_16.Text = "Thuế VAT";
            this.xrtableCell_16.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_16.Weight = 0.11500000000000003;
            this.xrtableCell_17.BorderWidth = 1;
            this.xrtableCell_17.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_17.Name = "xrTableCell8";
            this.xrtableCell_17.StylePriority.UseBorderWidth = false;
            this.xrtableCell_17.StylePriority.UseFont = false;
            this.xrtableCell_17.StylePriority.UseTextAlignment = false;
            this.xrtableCell_17.Text = "Th\x00e0nh tiền";
            this.xrtableCell_17.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_17.Weight = 0.16884615384615387;
            this.pageFooterBand_0.Controls.AddRange(new XRControl[] { this.xrpageInfo_1, this.xrlabel_17, this.xrpageInfo_0 });
            this.pageFooterBand_0.HeightF = 27f;
            this.pageFooterBand_0.Name = "PageFooter";
            this.pageFooterBand_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.pageFooterBand_0.TextAlignment = TextAlignment.TopLeft;
            this.xrpageInfo_1.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrpageInfo_1.Format = "Ng\x00e0y in :{0:dd/MM/yyyy HH:mm}";
            this.xrpageInfo_1.LocationFloat = new PointFloat(533f, 0f);
            this.xrpageInfo_1.Name = "xrPageInfo2";
            this.xrpageInfo_1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrpageInfo_1.PageInfo = PageInfo.DateTime;
            this.xrpageInfo_1.SizeF = new SizeF(150f, 25f);
            this.xrpageInfo_1.StylePriority.UseFont = false;
            this.xrpageInfo_1.StylePriority.UseTextAlignment = false;
            this.xrpageInfo_1.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_17.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_17.LocationFloat = new PointFloat(0f, 0f);
            this.xrlabel_17.Name = "Lbl_TranName";
            this.xrlabel_17.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_17.SizeF = new SizeF(267f, 25f);
            this.xrlabel_17.StylePriority.UseFont = false;
            this.xrlabel_17.StylePriority.UseTextAlignment = false;
            this.xrlabel_17.Text = "Giao dịch nhập h\x00e0ng từ nh\x00e0 cung cấp";
            this.xrlabel_17.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_17.WordWrap = false;
            this.xrpageInfo_0.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrpageInfo_0.LocationFloat = new PointFloat(683f, 0f);
            this.xrpageInfo_0.Name = "xrPageInfo1";
            this.xrpageInfo_0.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrpageInfo_0.SizeF = new SizeF(100f, 25f);
            this.xrpageInfo_0.StylePriority.UseFont = false;
            this.xrpageInfo_0.StylePriority.UseTextAlignment = false;
            this.xrpageInfo_0.TextAlignment = TextAlignment.MiddleRight;
            this.reportHeaderBand_0.Controls.AddRange(new XRControl[] { 
                this.xrlabel_29, this.xrlabel_30, this.xrlabel_26, this.xrlabel_27, this.xrlabel_18, this.xrlabel_19, this.xrlabel_16, this.xrlabel_13, this.xrlabel_14, this.xTveRubwQ, this.xrlabel_15, this.xrlabel_7, this.xrlabel_8, this.xrlabel_9, this.xrlabel_10, this.xrlabel_11, 
                this.xrlabel_12, this.xrlabel_4, this.xrlabel_5, this.xrlabel_6, this.xrlabel_1, this.xrlabel_2, this.xrlabel_3, this.xrlabel_0
             });
            this.reportHeaderBand_0.HeightF = 208f;
            this.reportHeaderBand_0.Name = "ReportHeader";
            this.xrlabel_26.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_26.LocationFloat = new PointFloat(100f, 158f);
            this.xrlabel_26.Name = "Lbl_ImpId";
            this.xrlabel_26.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_26.SizeF = new SizeF(50f, 25f);
            this.xrlabel_26.StylePriority.UseFont = false;
            this.xrlabel_26.StylePriority.UseTextAlignment = false;
            this.xrlabel_26.Text = "Lbl_ImpId";
            this.xrlabel_26.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_26.WordWrap = false;
            this.xrlabel_27.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_27.LocationFloat = new PointFloat(100f, 133f);
            this.xrlabel_27.Name = "Lbl_ExpId";
            this.xrlabel_27.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_27.SizeF = new SizeF(50f, 25f);
            this.xrlabel_27.StylePriority.UseFont = false;
            this.xrlabel_27.StylePriority.UseTextAlignment = false;
            this.xrlabel_27.Text = "Lbl_ExpId";
            this.xrlabel_27.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_27.WordWrap = false;
            this.xrlabel_18.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_18.LocationFloat = new PointFloat(58f, 83f);
            this.xrlabel_18.Name = "Lbl_CompVatNumber";
            this.xrlabel_18.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_18.SizeF = new SizeF(142f, 25f);
            this.xrlabel_18.StylePriority.UseFont = false;
            this.xrlabel_18.StylePriority.UseTextAlignment = false;
            this.xrlabel_18.Text = "123546513213";
            this.xrlabel_18.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_18.WordWrap = false;
            this.xrlabel_19.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_19.LocationFloat = new PointFloat(0f, 83f);
            this.xrlabel_19.Name = "xrLabel16";
            this.xrlabel_19.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_19.SizeF = new SizeF(58f, 25f);
            this.xrlabel_19.StylePriority.UseFont = false;
            this.xrlabel_19.StylePriority.UseTextAlignment = false;
            this.xrlabel_19.Text = "MST :";
            this.xrlabel_19.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_19.WordWrap = false;
            this.xrlabel_16.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_16.LocationFloat = new PointFloat(57.99999f, 57.99999f);
            this.xrlabel_16.Name = "Lbl_CompPhone";
            this.xrlabel_16.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_16.SizeF = new SizeF(166.3333f, 25f);
            this.xrlabel_16.StylePriority.UseFont = false;
            this.xrlabel_16.StylePriority.UseTextAlignment = false;
            this.xrlabel_16.Text = "84-04-38226596/04-9437505";
            this.xrlabel_16.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_16.WordWrap = false;
            this.xrlabel_13.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_13.LocationFloat = new PointFloat(0f, 58f);
            this.xrlabel_13.Name = "xrLabel15";
            this.xrlabel_13.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_13.SizeF = new SizeF(58f, 25f);
            this.xrlabel_13.StylePriority.UseFont = false;
            this.xrlabel_13.StylePriority.UseTextAlignment = false;
            this.xrlabel_13.Text = "Đ.thoại :";
            this.xrlabel_13.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_13.WordWrap = false;
            this.xrlabel_14.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_14.LocationFloat = new PointFloat(0f, 33f);
            this.xrlabel_14.Name = "xrLabel14";
            this.xrlabel_14.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_14.SizeF = new SizeF(58f, 25f);
            this.xrlabel_14.StylePriority.UseFont = false;
            this.xrlabel_14.StylePriority.UseTextAlignment = false;
            this.xrlabel_14.Text = "Địa chỉ :";
            this.xrlabel_14.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_14.WordWrap = false;
            this.xTveRubwQ.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xTveRubwQ.LocationFloat = new PointFloat(58f, 33f);
            this.xTveRubwQ.Name = "Lbl_CompAddress";
            this.xTveRubwQ.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xTveRubwQ.SizeF = new SizeF(333f, 25f);
            this.xTveRubwQ.StylePriority.UseFont = false;
            this.xTveRubwQ.StylePriority.UseTextAlignment = false;
            this.xTveRubwQ.Text = "Số 30 Trần nh\x00e2n T\x00f4ng";
            this.xTveRubwQ.TextAlignment = TextAlignment.MiddleLeft;
            this.xTveRubwQ.WordWrap = false;
            this.xrlabel_15.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_15.LocationFloat = new PointFloat(0f, 8f);
            this.xrlabel_15.Name = "Lbl_CompName";
            this.xrlabel_15.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_15.SizeF = new SizeF(483f, 25f);
            this.xrlabel_15.StylePriority.UseFont = false;
            this.xrlabel_15.StylePriority.UseTextAlignment = false;
            this.xrlabel_15.Text = "C\x00d4NG TY V\x00c0NG BẠC Đ\x00c1 QU\x00dd PH\x00da QU\x00dd";
            this.xrlabel_15.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_15.WordWrap = false;
            this.xrlabel_7.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_7.LocationFloat = new PointFloat(150f, 158f);
            this.xrlabel_7.Name = "Lbl_ImpName";
            this.xrlabel_7.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_7.SizeF = new SizeF(275f, 25f);
            this.xrlabel_7.StylePriority.UseFont = false;
            this.xrlabel_7.StylePriority.UseTextAlignment = false;
            this.xrlabel_7.Text = "Quầy b\x00e1n lẻ trang sức số 12";
            this.xrlabel_7.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_7.WordWrap = false;
            this.xrlabel_7.BeforePrint += new PrintEventHandler(this.xrlabel_7_BeforePrint);
            this.xrlabel_8.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_8.LocationFloat = new PointFloat(0f, 158f);
            this.xrlabel_8.Name = "xrLabel10";
            this.xrlabel_8.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_8.SizeF = new SizeF(100f, 25f);
            this.xrlabel_8.StylePriority.UseFont = false;
            this.xrlabel_8.StylePriority.UseTextAlignment = false;
            this.xrlabel_8.Text = "Nơi nhận h\x00e0ng :";
            this.xrlabel_8.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_8.WordWrap = false;
            this.xrlabel_9.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_9.LocationFloat = new PointFloat(100f, 183f);
            this.xrlabel_9.Name = "Lbl_Remark";
            this.xrlabel_9.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_9.SizeF = new SizeF(392f, 25f);
            this.xrlabel_9.StylePriority.UseFont = false;
            this.xrlabel_9.StylePriority.UseTextAlignment = false;
            this.xrlabel_9.Text = "Lbl_Remark";
            this.xrlabel_9.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_9.WordWrap = false;
            this.xrlabel_10.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_10.LocationFloat = new PointFloat(150f, 133f);
            this.xrlabel_10.Name = "Lbl_ExpName";
            this.xrlabel_10.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_10.SizeF = new SizeF(275f, 25f);
            this.xrlabel_10.StylePriority.UseFont = false;
            this.xrlabel_10.StylePriority.UseTextAlignment = false;
            this.xrlabel_10.Text = "Kho chứa h\x00e0ng số 30 Trần nh\x00e2n T\x00f4ng";
            this.xrlabel_10.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_10.WordWrap = false;
            this.xrlabel_10.BeforePrint += new PrintEventHandler(this.xrlabel_10_BeforePrint);
            this.xrlabel_11.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_11.LocationFloat = new PointFloat(0f, 183f);
            this.xrlabel_11.Name = "xrLabel7";
            this.xrlabel_11.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_11.SizeF = new SizeF(100f, 25f);
            this.xrlabel_11.StylePriority.UseFont = false;
            this.xrlabel_11.StylePriority.UseTextAlignment = false;
            this.xrlabel_11.Text = "Diễn giải :";
            this.xrlabel_11.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_11.WordWrap = false;
            this.xrlabel_12.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_12.LocationFloat = new PointFloat(0f, 133f);
            this.xrlabel_12.Name = "xrLabel5";
            this.xrlabel_12.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_12.SizeF = new SizeF(100f, 25f);
            this.xrlabel_12.StylePriority.UseFont = false;
            this.xrlabel_12.StylePriority.UseTextAlignment = false;
            this.xrlabel_12.Text = "Nơi xuất h\x00e0ng :";
            this.xrlabel_12.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_12.WordWrap = false;
            this.xrlabel_4.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.xrlabel_4.LocationFloat = new PointFloat(625f, 158f);
            this.xrlabel_4.Name = "Lbl_TranTime";
            this.xrlabel_4.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_4.SizeF = new SizeF(117f, 25f);
            this.xrlabel_4.StylePriority.UseFont = false;
            this.xrlabel_4.StylePriority.UseTextAlignment = false;
            this.xrlabel_4.Text = "Lbl_TranTime";
            this.xrlabel_4.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_4.WordWrap = false;
            this.xrlabel_5.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_5.LocationFloat = new PointFloat(554.1667f, 158f);
            this.xrlabel_5.Name = "xrLabel4";
            this.xrlabel_5.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_5.SizeF = new SizeF(70.83331f, 25f);
            this.xrlabel_5.StylePriority.UseFont = false;
            this.xrlabel_5.StylePriority.UseTextAlignment = false;
            this.xrlabel_5.Text = "Giờ :";
            this.xrlabel_5.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_5.WordWrap = false;
            this.xrlabel_6.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.xrlabel_6.LocationFloat = new PointFloat(625f, 133f);
            this.xrlabel_6.Name = "Lbl_TranDate";
            this.xrlabel_6.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_6.SizeF = new SizeF(117f, 25f);
            this.xrlabel_6.StylePriority.UseFont = false;
            this.xrlabel_6.StylePriority.UseTextAlignment = false;
            this.xrlabel_6.Text = "Lbl_TranDate";
            this.xrlabel_6.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_6.WordWrap = false;
            this.xrlabel_1.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_1.LocationFloat = new PointFloat(366.5f, 108f);
            this.xrlabel_1.Name = "Lbl_TransNum";
            this.xrlabel_1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_1.SizeF = new SizeF(117f, 25f);
            this.xrlabel_1.StylePriority.UseFont = false;
            this.xrlabel_1.StylePriority.UseTextAlignment = false;
            this.xrlabel_1.Text = "Lbl_TransNum";
            this.xrlabel_1.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_1.WordWrap = false;
            this.xrlabel_2.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_2.LocationFloat = new PointFloat(554.1667f, 133f);
            this.xrlabel_2.Name = "xrLabel2";
            this.xrlabel_2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_2.SizeF = new SizeF(70.83331f, 25f);
            this.xrlabel_2.StylePriority.UseFont = false;
            this.xrlabel_2.StylePriority.UseTextAlignment = false;
            this.xrlabel_2.Text = "Ng\x00e0y :";
            this.xrlabel_2.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_2.WordWrap = false;
            this.xrlabel_3.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_3.LocationFloat = new PointFloat(333f, 108f);
            this.xrlabel_3.Name = "xrLabel1";
            this.xrlabel_3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_3.SizeF = new SizeF(33.49997f, 25.00001f);
            this.xrlabel_3.StylePriority.UseFont = false;
            this.xrlabel_3.StylePriority.UseTextAlignment = false;
            this.xrlabel_3.Text = "Số :";
            this.xrlabel_3.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_3.WordWrap = false;
            this.xrlabel_0.CanShrink = true;
            this.xrlabel_0.Font = new Font("Arial", 18f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_0.LocationFloat = new PointFloat(237.5f, 75f);
            this.xrlabel_0.Name = "Lbl_Title";
            this.xrlabel_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.xrlabel_0.SizeF = new SizeF(304.1667f, 33f);
            this.xrlabel_0.StylePriority.UseFont = false;
            this.xrlabel_0.StylePriority.UsePadding = false;
            this.xrlabel_0.StylePriority.UseTextAlignment = false;
            this.xrlabel_0.Text = "PHIẾU NHẬN H\x00c0NG";
            this.xrlabel_0.TextAlignment = TextAlignment.MiddleCenter;
            this.reportFooterBand_0.Controls.AddRange(new XRControl[] { this.xrlabel_24, this.xrlabel_25, this.xrlabel_21, this.xrlabel_22, this.xrlabel_23, this.xrlabel_20, this.xrtable_2, this.xrlabel_28, this.HygIsNcsnq, this.xrline_0 });
            this.reportFooterBand_0.HeightF = 171f;
            this.reportFooterBand_0.Name = "ReportFooter";
            this.xrlabel_24.Font = new Font("Arial", 9f, FontStyle.Italic, GraphicsUnit.Point, 0xa3);
            this.xrlabel_24.LocationFloat = new PointFloat(659f, 92f);
            this.xrlabel_24.Name = "xrLabel25";
            this.xrlabel_24.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_24.SizeF = new SizeF(50f, 25f);
            this.xrlabel_24.StylePriority.UseFont = false;
            this.xrlabel_24.StylePriority.UseTextAlignment = false;
            this.xrlabel_24.Text = "(K\x00fd t\x00ean)";
            this.xrlabel_24.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_24.WordWrap = false;
            this.xrlabel_25.Font = new Font("Arial", 9f, FontStyle.Italic, GraphicsUnit.Point, 0xa3);
            this.xrlabel_25.LocationFloat = new PointFloat(375f, 92f);
            this.xrlabel_25.Name = "xrLabel24";
            this.xrlabel_25.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_25.SizeF = new SizeF(50f, 25f);
            this.xrlabel_25.StylePriority.UseFont = false;
            this.xrlabel_25.StylePriority.UseTextAlignment = false;
            this.xrlabel_25.Text = "(K\x00fd t\x00ean)";
            this.xrlabel_25.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_25.WordWrap = false;
            this.xrlabel_21.Font = new Font("Arial", 9f, FontStyle.Italic, GraphicsUnit.Point, 0xa3);
            this.xrlabel_21.LocationFloat = new PointFloat(67f, 92f);
            this.xrlabel_21.Name = "xrLabel23";
            this.xrlabel_21.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_21.SizeF = new SizeF(50f, 25f);
            this.xrlabel_21.StylePriority.UseFont = false;
            this.xrlabel_21.StylePriority.UseTextAlignment = false;
            this.xrlabel_21.Text = "(K\x00fd t\x00ean)";
            this.xrlabel_21.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_21.WordWrap = false;
            this.xrlabel_22.Font = new Font("Arial", 9f, FontStyle.Italic | FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_22.LocationFloat = new PointFloat(33f, 75f);
            this.xrlabel_22.Name = "xrLabel21";
            this.xrlabel_22.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_22.SizeF = new SizeF(125f, 25f);
            this.xrlabel_22.StylePriority.UseFont = false;
            this.xrlabel_22.StylePriority.UseTextAlignment = false;
            this.xrlabel_22.Text = "Người nhận h\x00e0ng";
            this.xrlabel_22.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_22.WordWrap = false;
            this.xrlabel_23.Font = new Font("Arial", 9f, FontStyle.Italic | FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_23.LocationFloat = new PointFloat(617f, 75f);
            this.xrlabel_23.Name = "xrLabel20";
            this.xrlabel_23.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_23.SizeF = new SizeF(125f, 25f);
            this.xrlabel_23.StylePriority.UseFont = false;
            this.xrlabel_23.StylePriority.UseTextAlignment = false;
            this.xrlabel_23.Text = "Người lập phiếu";
            this.xrlabel_23.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_23.WordWrap = false;
            this.xrlabel_20.Font = new Font("Arial", 9f, FontStyle.Italic | FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_20.LocationFloat = new PointFloat(333f, 75f);
            this.xrlabel_20.Name = "xrLabel19";
            this.xrlabel_20.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_20.SizeF = new SizeF(125f, 25f);
            this.xrlabel_20.StylePriority.UseFont = false;
            this.xrlabel_20.StylePriority.UseTextAlignment = false;
            this.xrlabel_20.Text = "Người giao h\x00e0ng";
            this.xrlabel_20.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_20.WordWrap = false;
            this.xrtable_2.Borders = BorderSide.None;
            this.xrtable_2.LocationFloat = new PointFloat(0f, 8f);
            this.xrtable_2.Name = "xrTable3";
            this.xrtable_2.Rows.AddRange(new XRTableRow[] { this.xrtableRow_2 });
            this.xrtable_2.SizeF = new SizeF(784f, 25f);
            this.xrtable_2.StylePriority.UseBorders = false;
            this.xrtableRow_2.Cells.AddRange(new XRTableCell[] { this.ecgIrJiEyW, this.xrtableCell_18, this.xrtableCell_19, this.xrtableCell_20, this.xrtableCell_21, this.xrtableCell_22, this.xrtableCell_23, this.xrtableCell_24, this.xrtableCell_25 });
            this.xrtableRow_2.Name = "xrTableRow3";
            this.xrtableRow_2.StylePriority.UseTextAlignment = false;
            this.xrtableRow_2.TextAlignment = TextAlignment.MiddleLeft;
            this.xrtableRow_2.Weight = 3.0;
            this.ecgIrJiEyW.Borders = BorderSide.None;
            this.ecgIrJiEyW.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ecgIrJiEyW.Name = "xrTableCell11";
            this.ecgIrJiEyW.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.ecgIrJiEyW.StylePriority.UseBorders = false;
            this.ecgIrJiEyW.StylePriority.UseFont = false;
            this.ecgIrJiEyW.StylePriority.UsePadding = false;
            this.ecgIrJiEyW.StylePriority.UseTextAlignment = false;
            this.ecgIrJiEyW.TextAlignment = TextAlignment.MiddleRight;
            this.ecgIrJiEyW.Weight = 0.046091954022988504;
            this.ecgIrJiEyW.WordWrap = false;
            this.xrtableCell_18.Borders = BorderSide.None;
            this.xrtableCell_18.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.xrtableCell_18.Name = "xrTableCell12";
            this.xrtableCell_18.Padding = new PaddingInfo(3, 0, 0, 0, 100f);
            this.xrtableCell_18.StylePriority.UseBorders = false;
            this.xrtableCell_18.StylePriority.UseFont = false;
            this.xrtableCell_18.StylePriority.UsePadding = false;
            this.xrtableCell_18.Weight = 0.080574712643678173;
            this.xrtableCell_18.WordWrap = false;
            this.xrtableCell_19.Borders = BorderSide.None;
            this.xrtableCell_19.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.xrtableCell_19.Name = "xrTableCell14";
            this.xrtableCell_19.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
            this.xrtableCell_19.StylePriority.UseBorders = false;
            this.xrtableCell_19.StylePriority.UseFont = false;
            this.xrtableCell_19.StylePriority.UsePadding = false;
            this.xrtableCell_19.Weight = 0.33494252873563213;
            this.xrtableCell_19.WordWrap = false;
            this.xrtableCell_20.Borders = BorderSide.None;
            this.xrtableCell_20.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.xrtableCell_20.Name = "xrTableCell15";
            this.xrtableCell_20.StylePriority.UseBorders = false;
            this.xrtableCell_20.StylePriority.UseFont = false;
            this.xrtableCell_20.StylePriority.UseTextAlignment = false;
            this.xrtableCell_20.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_20.Weight = 0.043908045977011492;
            this.xrtableCell_20.WordWrap = false;
            this.xrtableCell_21.Borders = BorderSide.None;
            this.xrtableCell_21.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.xrtableCell_21.Name = "xrTableCell16";
            this.xrtableCell_21.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_21.StylePriority.UseBorders = false;
            this.xrtableCell_21.StylePriority.UseFont = false;
            this.xrtableCell_21.StylePriority.UsePadding = false;
            this.xrtableCell_21.StylePriority.UseTextAlignment = false;
            this.xrtableCell_21.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_21.Weight = 0.11701149425287356;
            this.xrtableCell_21.WordWrap = false;
            this.xrtableCell_22.Borders = BorderSide.None;
            this.xrtableCell_22.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_22.Name = "Txt_sumqty";
            this.xrtableCell_22.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_22.StylePriority.UseBorders = false;
            this.xrtableCell_22.StylePriority.UseFont = false;
            this.xrtableCell_22.StylePriority.UsePadding = false;
            this.xrtableCell_22.StylePriority.UseTextAlignment = false;
            summary.FormatString = "{0:n2}";
            summary.Running = SummaryRunning.Report;
            this.xrtableCell_22.Summary = summary;
            this.xrtableCell_22.Text = "Txt_sumqty";
            this.xrtableCell_22.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_22.Weight = 0.067356321839080455;
            this.xrtableCell_22.WordWrap = false;
            this.xrtableCell_23.Borders = BorderSide.None;
            this.xrtableCell_23.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_23.Name = "Txt_sumdisc";
            this.xrtableCell_23.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_23.StylePriority.UseBorders = false;
            this.xrtableCell_23.StylePriority.UseFont = false;
            this.xrtableCell_23.StylePriority.UsePadding = false;
            this.xrtableCell_23.StylePriority.UseTextAlignment = false;
            summary2.FormatString = "{0:n2}";
            summary2.Running = SummaryRunning.Report;
            this.xrtableCell_23.Summary = summary2;
            this.xrtableCell_23.Text = "Txt_sumdisc";
            this.xrtableCell_23.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_23.Weight = 0.13850574712643679;
            this.xrtableCell_23.WordWrap = false;
            this.xrtableCell_24.Borders = BorderSide.None;
            this.xrtableCell_24.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_24.Name = "Txt_sumvat";
            this.xrtableCell_24.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_24.StylePriority.UseBorders = false;
            this.xrtableCell_24.StylePriority.UseFont = false;
            this.xrtableCell_24.StylePriority.UsePadding = false;
            this.xrtableCell_24.StylePriority.UseTextAlignment = false;
            summary3.FormatString = "{0:n2}";
            summary3.Running = SummaryRunning.Report;
            this.xrtableCell_24.Summary = summary3;
            this.xrtableCell_24.Text = "Txt_sumvat";
            this.xrtableCell_24.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_24.Weight = 0.10304597701149423;
            this.xrtableCell_24.WordWrap = false;
            this.xrtableCell_25.Borders = BorderSide.None;
            this.xrtableCell_25.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_25.Name = "Txt_sumamt";
            this.xrtableCell_25.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_25.StylePriority.UseBorders = false;
            this.xrtableCell_25.StylePriority.UseFont = false;
            this.xrtableCell_25.StylePriority.UsePadding = false;
            this.xrtableCell_25.StylePriority.UseTextAlignment = false;
            summary4.FormatString = "{0:n2}";
            summary4.Running = SummaryRunning.Report;
            this.xrtableCell_25.Summary = summary4;
            this.xrtableCell_25.Text = "Txt_sumamt";
            this.xrtableCell_25.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_25.Weight = 0.14994252873563216;
            this.xrtableCell_25.WordWrap = false;
            this.xrlabel_28.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_28.LocationFloat = new PointFloat(675f, 42f);
            this.xrlabel_28.Name = "Txt_sumpay";
            this.xrlabel_28.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_28.SizeF = new SizeF(109f, 25f);
            this.xrlabel_28.StylePriority.UseFont = false;
            this.xrlabel_28.StylePriority.UseTextAlignment = false;
            summary5.FormatString = "{0:n2}";
            summary5.Running = SummaryRunning.Report;
            this.xrlabel_28.Summary = summary5;
            this.xrlabel_28.Text = "Txt_sumpay";
            this.xrlabel_28.TextAlignment = TextAlignment.MiddleRight;
            this.xrlabel_28.WordWrap = false;
            this.HygIsNcsnq.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.HygIsNcsnq.LocationFloat = new PointFloat(542f, 42f);
            this.HygIsNcsnq.Name = "xrLabel6";
            this.HygIsNcsnq.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.HygIsNcsnq.SizeF = new SizeF(133f, 25f);
            this.HygIsNcsnq.StylePriority.UseFont = false;
            this.HygIsNcsnq.StylePriority.UseTextAlignment = false;
            this.HygIsNcsnq.Text = "TỔNG THANH TO\x00c1N :";
            this.HygIsNcsnq.TextAlignment = TextAlignment.MiddleLeft;
            this.HygIsNcsnq.WordWrap = false;
            this.xrline_0.LocationFloat = new PointFloat(533f, 33f);
            this.xrline_0.Name = "xrLine1";
            this.xrline_0.SizeF = new SizeF(250f, 8f);
            this.topMarginBand_0.HeightF = 50f;
            this.topMarginBand_0.Name = "topMarginBand1";
            this.bottomMarginBand_0.HeightF = 50f;
            this.bottomMarginBand_0.Name = "bottomMarginBand1";
            this.xrlabel_30.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_30.LocationFloat = new PointFloat(554.1667f, 183f);
            this.xrlabel_30.Name = "xrLabel3";
            this.xrlabel_30.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_30.SizeF = new SizeF(70.83331f, 25f);
            this.xrlabel_30.StylePriority.UseFont = false;
            this.xrlabel_30.StylePriority.UseTextAlignment = false;
            this.xrlabel_30.Text = "Nh\x00e2n vi\x00ean :";
            this.xrlabel_30.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_30.WordWrap = false;
            this.xrlabel_29.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_29.LocationFloat = new PointFloat(625f, 183f);
            this.xrlabel_29.Name = "Lbl_UserName";
            this.xrlabel_29.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_29.SizeF = new SizeF(162f, 25f);
            this.xrlabel_29.StylePriority.UseFont = false;
            this.xrlabel_29.StylePriority.UseTextAlignment = false;
            this.xrlabel_29.Text = "KX00000008";
            this.xrlabel_29.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_29.WordWrap = false;
            base.Bands.AddRange(new Band[] { this.detailBand_0, this.pageHeaderBand_0, this.pageFooterBand_0, this.reportHeaderBand_0, this.reportFooterBand_0, this.topMarginBand_0, this.bottomMarginBand_0 });
            base.Margins = new Margins(20, 20, 50, 50);
            base.PageHeight = 0x491;
            base.PageWidth = 0x33b;
            base.PaperKind = PaperKind.A4;
            base.Version = "9.3";
            this.BeforePrint += new PrintEventHandler(this.v_frsupp_BeforePrint);
            this.xrtable_1.EndInit();
            this.xrtable_0.EndInit();
            this.xrtable_2.EndInit();
            this.EndInit();
        }

        private void method_1(object sender, PrintEventArgs e)
        {
        }

        private void method_2(object sender, PrintEventArgs e)
        {
        }

        private void method_3(object sender, PrintEventArgs e)
        {
        }

        private void v_frsupp_BeforePrint(object sender, PrintEventArgs e)
        {
            this.LvbIuIdVwC = "SELECT tr.tran_date, tr.tran_time, tr.trans_num, tr.trans_code, tr.voucher, tr.invoice, tr.post, tr.exp_id, tr.imp_id, tr.goods_id, tr.kit_qty, tr.kit_id, tr.qty, tr.unit_symb, tr.amount, tr.discount, tr.vat_amt, tr.surplus, tr.commis_amt, tr.forex_cys, tr.forex_rate, tr.user_id, tr.cs_id, tr.custax_id, tr.ref, tr.remark, tr.updated, tr.merc_type, tr.tax_code, tr.vat_incl, tr.discpervat, tr.disc_incl, tr.copies, tr.recnum, tr.card_id, tr.Shift, tr.Status, gs.grp_id, gs.short_name, gs.full_name, gs.supp_id, gsgrp.Description, us.name, (tr.amount + tr.surplus)/tr.qty as price, tr.amount/tr.qty as rtprice, tr.amount + tr.vat_amt AS amtandvat, tr.amount - tr.discount AS rtamount FROM  tblGoods AS gs INNER JOIN tblTransaction AS tr ON gs.goods_id = tr.goods_id INNER JOIN tblGoodsGrp AS gsgrp ON gs.grp_id = gsgrp.Id INNER JOIN tblUser AS us ON tr.user_id = us.ID WHERE tr.trans_num = '" + Class6.transNum + "' Order by tr.tran_date, tr.tran_time,tr.recnum ";
            this.oleDbDataAdapter_0 = new OleDbDataAdapter(this.LvbIuIdVwC, this.oleDbConnection_0);
            using (DataSet set = new DataSet())
            {
                this.oleDbDataAdapter_0.Fill(set);
                this.oleDbConnection_0.Close();
                base.DataAdapter = this.oleDbDataAdapter_0;
                base.DataSource = set.Tables[0];
                string str = string.Format("{0:dd/MM/yyy}", DateTime.Parse(set.Tables[0].Rows[0]["tran_date"].ToString()));
                this.xrlabel_6.Text = str;
                this.xrlabel_1.Text = set.Tables[0].Rows[0]["trans_num"].ToString();
                this.xrlabel_4.Text = set.Tables[0].Rows[0]["tran_time"].ToString();
                this.xrlabel_26.Text = set.Tables[0].Rows[0]["imp_id"].ToString();
                this.xrlabel_27.Text = set.Tables[0].Rows[0]["exp_id"].ToString();
                this.xrlabel_9.Text = set.Tables[0].Rows[0]["remark"].ToString();
                this.xrlabel_29.Text = set.Tables[0].Rows[0]["name"].ToString();
                if (set.Tables[0].Rows[0]["trans_code"].ToString() == "23")
                {
                    this.xrlabel_0.Text = "PHIẾU NHẬN H\x00c0NG (23)";
                }
            }
            this.xrtableCell_10.DataBindings.Add("Text", base.DataSource, "recnum", "{0:n0}");
            this.xrtableCell_11.DataBindings.Add("Text", base.DataSource, "goods_id", "");
            this.xrtableCell_7.DataBindings.Add("Text", base.DataSource, "full_name", "");
            this.xrtableCell_14.DataBindings.Add("Text", base.DataSource, "discount", "{0:n2}");
            this.xrtableCell_9.DataBindings.Add("Text", base.DataSource, "qty", "{0:n2}");
            this.xrtableCell_8.DataBindings.Add("Text", base.DataSource, "unit_symb", "");
            this.xrtableCell_13.DataBindings.Add("Text", base.DataSource, "amount", "{0:n2}");
            this.xrtableCell_15.DataBindings.Add("Text", base.DataSource, "vat_amt", "{0:n2}");
            this.xrtableCell_12.DataBindings.Add("Text", base.DataSource, "price", "{0:n2}");
            this.xrtableCell_25.DataBindings.Add("Text", base.DataSource, "amount", "{0:n2}");
            this.xrsummary_0.Running = SummaryRunning.Report;
            this.xrsummary_0.FormatString = "{0:n2}";
            this.xrtableCell_25.Summary = this.xrsummary_0;
            this.xrtableCell_23.DataBindings.Add("Text", base.DataSource, "discount", "{0:n2}");
            this.xrsummary_1.Running = SummaryRunning.Report;
            this.xrsummary_1.FormatString = "{0:n2}";
            this.xrtableCell_23.Summary = this.xrsummary_1;
            this.xrtableCell_22.DataBindings.Add("Text", base.DataSource, "qty", "{0:n2}");
            this.xrsummary_2.Running = SummaryRunning.Report;
            this.xrsummary_2.FormatString = "{0:n2}";
            this.xrtableCell_22.Summary = this.xrsummary_2;
            this.xrlabel_28.DataBindings.Add("Text", base.DataSource, "amtandvat", "{0:n2}");
            this.xrsummary_4.Running = SummaryRunning.Report;
            this.xrsummary_4.FormatString = "{0:n2}";
            this.xrlabel_28.Summary = this.xrsummary_4;
            this.xrtableCell_24.DataBindings.Add("Text", base.DataSource, "vat_amt", "{0:n2}");
            this.xrsummary_3.Running = SummaryRunning.Report;
            this.xrsummary_3.FormatString = "{0:n2}";
            this.xrtableCell_24.Summary = this.xrsummary_3;
            this.xrlabel_15.Text = Class13.smethod_1(Class7.smethod_14("m_name").ToString(), Class13.string_0);
            this.xTveRubwQ.Text = Class13.smethod_1(Class7.smethod_14("m_address").ToString(), Class13.string_0);
            this.xrlabel_16.Text = Class13.smethod_1(Class7.smethod_14("m_phone").ToString(), Class13.string_0);
            this.xrlabel_18.Text = Class13.smethod_1(Class7.smethod_14("m_vatnum").ToString(), Class13.string_0);
            this.xrlabel_17.Text = Class6.string_1;
        }

        private void xrlabel_10_BeforePrint(object sender, PrintEventArgs e)
        {
            string str = null;
            Class7.smethod_17("fullname", "tblStore", "Id", this.xrlabel_27.Text, "", Class7.oleDbConnection_1, ref str);
            this.xrlabel_10.Text = str;
        }

        private void xrlabel_7_BeforePrint(object sender, PrintEventArgs e)
        {
            string str = null;
            Class7.smethod_17("fullname", "tblStore", "Id", this.xrlabel_26.Text, "", Class7.oleDbConnection_1, ref str);
            this.xrlabel_7.Text = str;
        }

        private void xrtableCell_12_BeforePrint(object sender, PrintEventArgs e)
        {
        }

        private void xrtableCell_13_BeforePrint(object sender, PrintEventArgs e)
        {
        }
    }
}

