using DevExpress.Utils;
using DevExpress.XtraPrinting;
using DevExpress.XtraReports.UI;
using System;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Drawing.Printing;

namespace LibraryManagement.App
{
    public class v_tosupp : XtraReport
    {
        private BottomMarginBand bottomMarginBand_0;
        private DetailBand detailBand_0;
        private double double_0;
        private IContainer icontainer_0;
        private double kCnalMegv;
        private OleDbConnection oleDbConnection_0;
        private OleDbConnection oleDbConnection_1;
        private PageFooterBand pageFooterBand_0;
        private PageHeaderBand pageHeaderBand_0;
        private ReportFooterBand reportFooterBand_0;
        private ReportHeaderBand reportHeaderBand_0;
        private TopMarginBand topMarginBand_0;
        private XRLabel xrlabel_0;
        private XRLabel xrlabel_1;
        private XRLabel xrlabel_10;
        private XRLabel xrlabel_11;
        private XRLabel xrlabel_12;
        private XRLabel xrlabel_13;
        private XRLabel xrlabel_14;
        private XRLabel xrlabel_15;
        private XRLabel xrlabel_16;
        private XRLabel xrlabel_17;
        private XRLabel xrlabel_18;
        private XRLabel xrlabel_19;
        private XRLabel xrlabel_2;
        private XRLabel xrlabel_20;
        private XRLabel xrlabel_21;
        private XRLabel xrlabel_22;
        private XRLabel xrlabel_23;
        private XRLabel xrlabel_24;
        private XRLabel xrlabel_25;
        private XRLabel xrlabel_26;
        private XRLabel xrlabel_27;
        private XRLabel xrlabel_28;
        private XRLabel xrlabel_29;
        private XRLabel xrlabel_3;
        private XRLabel xrlabel_30;
        private XRLabel xrlabel_31;
        private XRLabel xrlabel_32;
        private XRLabel xrlabel_4;
        private XRLabel xrlabel_5;
        private XRLabel xrlabel_6;
        private XRLabel xrlabel_7;
        private XRLabel xrlabel_8;
        private XRLabel xrlabel_9;
        private XRPageInfo xrpageInfo_0;
        private XRPageInfo xrpageInfo_1;
        private XRSummary xrsummary_0;
        private XRSummary xrsummary_1;
        private XRTable xrtable_0;
        private XRTable xrtable_1;
        private XRTableCell xrtableCell_0;
        private XRTableCell xrtableCell_1;
        private XRTableCell xrtableCell_10;
        private XRTableCell xrtableCell_11;
        private XRTableCell xrtableCell_12;
        private XRTableCell xrtableCell_13;
        private XRTableCell xrtableCell_2;
        private XRTableCell xrtableCell_3;
        private XRTableCell xrtableCell_4;
        private XRTableCell xrtableCell_5;
        private XRTableCell xrtableCell_6;
        private XRTableCell xrtableCell_7;
        private XRTableCell xrtableCell_8;
        private XRTableCell xrtableCell_9;
        private XRTableRow xrtableRow_0;
        private XRTableRow xrtableRow_1;

        static v_tosupp()
        {
            Class15.smethod_5();
        }

        public v_tosupp()
        {
            Class17.smethod_0();
            this.xrsummary_0 = new XRSummary();
            this.xrsummary_1 = new XRSummary();
            this.oleDbConnection_0 = new OleDbConnection(Class7.string_5);
            this.oleDbConnection_1 = new OleDbConnection(Class7.string_4);
            this.kCnalMegv = 0.0;
            this.double_0 = 0.0;
            this.icontainer_0 = null;
            this.method_2();
        }

        private void detailBand_0_BeforePrint(object sender, PrintEventArgs e)
        {
            this.kCnalMegv += Class7.ParseDoubleValue(base.GetCurrentColumnValue("amount").ToString()) + Class7.ParseDoubleValue(base.GetCurrentColumnValue("discount").ToString());
            this.double_0 += Class7.ParseDoubleValue(base.GetCurrentColumnValue("amount").ToString());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.icontainer_0 != null))
            {
                this.icontainer_0.Dispose();
            }
            base.Dispose(disposing);
        }

        private void method_0(object sender, PrintEventArgs e)
        {
        }

        private void method_1(object sender, PrintEventArgs e)
        {
        }

        private void method_2()
        {
            this.detailBand_0 = new DetailBand();
            this.xrtable_1 = new XRTable();
            this.xrtableRow_1 = new XRTableRow();
            this.xrtableCell_10 = new XRTableCell();
            this.xrtableCell_11 = new XRTableCell();
            this.xrtableCell_7 = new XRTableCell();
            this.xrtableCell_8 = new XRTableCell();
            this.xrtableCell_12 = new XRTableCell();
            this.xrtableCell_9 = new XRTableCell();
            this.xrtableCell_13 = new XRTableCell();
            this.pageHeaderBand_0 = new PageHeaderBand();
            this.xrtable_0 = new XRTable();
            this.xrtableRow_0 = new XRTableRow();
            this.xrtableCell_0 = new XRTableCell();
            this.xrtableCell_1 = new XRTableCell();
            this.xrtableCell_2 = new XRTableCell();
            this.xrtableCell_3 = new XRTableCell();
            this.xrtableCell_4 = new XRTableCell();
            this.xrtableCell_5 = new XRTableCell();
            this.xrtableCell_6 = new XRTableCell();
            this.pageFooterBand_0 = new PageFooterBand();
            this.xrpageInfo_1 = new XRPageInfo();
            this.xrlabel_18 = new XRLabel();
            this.xrpageInfo_0 = new XRPageInfo();
            this.reportHeaderBand_0 = new ReportHeaderBand();
            this.xrlabel_27 = new XRLabel();
            this.xrlabel_28 = new XRLabel();
            this.xrlabel_19 = new XRLabel();
            this.xrlabel_20 = new XRLabel();
            this.xrlabel_17 = new XRLabel();
            this.xrlabel_13 = new XRLabel();
            this.xrlabel_14 = new XRLabel();
            this.xrlabel_15 = new XRLabel();
            this.xrlabel_16 = new XRLabel();
            this.xrlabel_7 = new XRLabel();
            this.xrlabel_8 = new XRLabel();
            this.xrlabel_9 = new XRLabel();
            this.xrlabel_10 = new XRLabel();
            this.xrlabel_11 = new XRLabel();
            this.xrlabel_12 = new XRLabel();
            this.xrlabel_4 = new XRLabel();
            this.xrlabel_5 = new XRLabel();
            this.xrlabel_6 = new XRLabel();
            this.xrlabel_1 = new XRLabel();
            this.xrlabel_2 = new XRLabel();
            this.xrlabel_3 = new XRLabel();
            this.xrlabel_0 = new XRLabel();
            this.reportFooterBand_0 = new ReportFooterBand();
            this.xrlabel_29 = new XRLabel();
            this.xrlabel_30 = new XRLabel();
            this.xrlabel_25 = new XRLabel();
            this.xrlabel_26 = new XRLabel();
            this.xrlabel_22 = new XRLabel();
            this.xrlabel_23 = new XRLabel();
            this.xrlabel_24 = new XRLabel();
            this.xrlabel_21 = new XRLabel();
            this.topMarginBand_0 = new TopMarginBand();
            this.bottomMarginBand_0 = new BottomMarginBand();
            this.xrlabel_32 = new XRLabel();
            this.xrlabel_31 = new XRLabel();
            this.xrtable_1.BeginInit();
            this.xrtable_0.BeginInit();
            this.BeginInit();
            this.detailBand_0.Controls.AddRange(new XRControl[] { this.xrtable_1 });
            this.detailBand_0.HeightF = 25f;
            this.detailBand_0.Name = "Detail";
            this.detailBand_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.detailBand_0.TextAlignment = TextAlignment.TopLeft;
            this.detailBand_0.BeforePrint += new PrintEventHandler(this.detailBand_0_BeforePrint);
            this.xrtable_1.Borders = BorderSide.Right | BorderSide.Left;
            this.xrtable_1.LocationFloat = new PointFloat(0f, 0f);
            this.xrtable_1.Name = "xrTable2";
            this.xrtable_1.Rows.AddRange(new XRTableRow[] { this.xrtableRow_1 });
            this.xrtable_1.SizeF = new SizeF(786.9999f, 25f);
            this.xrtable_1.StylePriority.UseBorders = false;
            this.xrtableRow_1.Cells.AddRange(new XRTableCell[] { this.xrtableCell_10, this.xrtableCell_11, this.xrtableCell_7, this.xrtableCell_8, this.xrtableCell_12, this.xrtableCell_9, this.xrtableCell_13 });
            this.xrtableRow_1.Name = "xrTableRow2";
            this.xrtableRow_1.StylePriority.UseTextAlignment = false;
            this.xrtableRow_1.TextAlignment = TextAlignment.MiddleLeft;
            this.xrtableRow_1.Weight = 3.0;
            this.xrtableCell_10.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_10.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_10.Name = "col_Index";
            this.xrtableCell_10.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_10.StylePriority.UseBorders = false;
            this.xrtableCell_10.StylePriority.UseFont = false;
            this.xrtableCell_10.StylePriority.UsePadding = false;
            this.xrtableCell_10.StylePriority.UseTextAlignment = false;
            this.xrtableCell_10.Text = "1";
            this.xrtableCell_10.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_10.Weight = 0.050158379214933546;
            this.xrtableCell_10.WordWrap = false;
            this.xrtableCell_11.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_11.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_11.Name = "col_GoodsId";
            this.xrtableCell_11.Padding = new PaddingInfo(3, 0, 0, 0, 100f);
            this.xrtableCell_11.StylePriority.UseBorders = false;
            this.xrtableCell_11.StylePriority.UseFont = false;
            this.xrtableCell_11.StylePriority.UsePadding = false;
            this.xrtableCell_11.Text = "000999";
            this.xrtableCell_11.Weight = 0.12651893703416844;
            this.xrtableCell_11.WordWrap = false;
            this.xrtableCell_7.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_7.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_7.Name = "col_MercName";
            this.xrtableCell_7.Padding = new PaddingInfo(5, 0, 0, 0, 100f);
            this.xrtableCell_7.StylePriority.UseBorders = false;
            this.xrtableCell_7.StylePriority.UseFont = false;
            this.xrtableCell_7.StylePriority.UsePadding = false;
            this.xrtableCell_7.Text = "D\x00e2y chuyền bi loại 45cm";
            this.xrtableCell_7.Weight = 0.38779160773617088;
            this.xrtableCell_7.WordWrap = false;
            this.xrtableCell_8.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_8.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_8.Name = "col_Unit";
            this.xrtableCell_8.StylePriority.UseBorders = false;
            this.xrtableCell_8.StylePriority.UseFont = false;
            this.xrtableCell_8.StylePriority.UseTextAlignment = false;
            this.xrtableCell_8.Text = "CAI";
            this.xrtableCell_8.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_8.Weight = 0.085344097970545985;
            this.xrtableCell_8.WordWrap = false;
            this.xrtableCell_12.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_12.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_12.Name = "col_Price";
            this.xrtableCell_12.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_12.StylePriority.UseBorders = false;
            this.xrtableCell_12.StylePriority.UseFont = false;
            this.xrtableCell_12.StylePriority.UsePadding = false;
            this.xrtableCell_12.StylePriority.UseTextAlignment = false;
            this.xrtableCell_12.Text = "200,000";
            this.xrtableCell_12.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_12.Weight = 0.12577024964080455;
            this.xrtableCell_12.WordWrap = false;
            this.xrtableCell_12.BeforePrint += new PrintEventHandler(this.xrtableCell_12_BeforePrint);
            this.xrtableCell_9.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_9.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_9.Name = "col_Qty";
            this.xrtableCell_9.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_9.StylePriority.UseBorders = false;
            this.xrtableCell_9.StylePriority.UseFont = false;
            this.xrtableCell_9.StylePriority.UsePadding = false;
            this.xrtableCell_9.StylePriority.UseTextAlignment = false;
            this.xrtableCell_9.Text = "100";
            this.xrtableCell_9.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_9.Weight = 0.092830459770114976;
            this.xrtableCell_9.WordWrap = false;
            this.xrtableCell_13.Borders = BorderSide.Bottom | BorderSide.Right | BorderSide.Left;
            this.xrtableCell_13.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_13.Name = "col_Amount";
            this.xrtableCell_13.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrtableCell_13.StylePriority.UseBorders = false;
            this.xrtableCell_13.StylePriority.UseFont = false;
            this.xrtableCell_13.StylePriority.UsePadding = false;
            this.xrtableCell_13.StylePriority.UseTextAlignment = false;
            this.xrtableCell_13.Text = "20,000,000";
            this.xrtableCell_13.TextAlignment = TextAlignment.MiddleRight;
            this.xrtableCell_13.Weight = 0.21710342582614942;
            this.xrtableCell_13.WordWrap = false;
            this.xrtableCell_13.BeforePrint += new PrintEventHandler(this.xrtableCell_13_BeforePrint);
            this.pageHeaderBand_0.Controls.AddRange(new XRControl[] { this.xrtable_0 });
            this.pageHeaderBand_0.HeightF = 29.99999f;
            this.pageHeaderBand_0.Name = "PageHeader";
            this.pageHeaderBand_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.pageHeaderBand_0.TextAlignment = TextAlignment.TopLeft;
            this.xrtable_0.BackColor = Color.Transparent;
            this.xrtable_0.BorderColor = Color.Black;
            this.xrtable_0.Borders = BorderSide.All;
            this.xrtable_0.BorderWidth = 2;
            this.xrtable_0.Font = new Font("Times New Roman", 12f, FontStyle.Bold);
            this.xrtable_0.LocationFloat = new PointFloat(0f, 0f);
            this.xrtable_0.Name = "xrTable1";
            this.xrtable_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.xrtable_0.Rows.AddRange(new XRTableRow[] { this.xrtableRow_0 });
            this.xrtable_0.SizeF = new SizeF(787f, 29.99999f);
            this.xrtable_0.StylePriority.UseBackColor = false;
            this.xrtable_0.StylePriority.UseBorderColor = false;
            this.xrtable_0.TextAlignment = TextAlignment.TopLeft;
            this.xrtableRow_0.BackColor = Color.WhiteSmoke;
            this.xrtableRow_0.Cells.AddRange(new XRTableCell[] { this.xrtableCell_0, this.xrtableCell_1, this.xrtableCell_2, this.xrtableCell_3, this.xrtableCell_4, this.xrtableCell_5, this.xrtableCell_6 });
            this.xrtableRow_0.Font = new Font("Tahoma", 8.25f, FontStyle.Bold);
            this.xrtableRow_0.Name = "xrTableRow1";
            this.xrtableRow_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.xrtableRow_0.StylePriority.UseBackColor = false;
            this.xrtableRow_0.TextAlignment = TextAlignment.TopLeft;
            this.xrtableRow_0.Weight = 0.69767441860465107;
            this.xrtableCell_0.BorderWidth = 1;
            this.xrtableCell_0.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_0.Name = "xrTableCell5";
            this.xrtableCell_0.StylePriority.UseBorderWidth = false;
            this.xrtableCell_0.StylePriority.UseFont = false;
            this.xrtableCell_0.StylePriority.UseTextAlignment = false;
            this.xrtableCell_0.Text = "TT";
            this.xrtableCell_0.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_0.Weight = 0.051538461538461526;
            this.xrtableCell_1.BorderWidth = 1;
            this.xrtableCell_1.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_1.Name = "xrTableCell1";
            this.xrtableCell_1.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.xrtableCell_1.StylePriority.UseFont = false;
            this.xrtableCell_1.Text = "M\x00e3 h\x00e0ng";
            this.xrtableCell_1.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_1.Weight = 0.13;
            this.xrtableCell_2.BorderWidth = 1;
            this.xrtableCell_2.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_2.Name = "xrTableCell4";
            this.xrtableCell_2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_2.StylePriority.UseFont = false;
            this.xrtableCell_2.Text = "T\x00ean h\x00e0ng h\x00f3a";
            this.xrtableCell_2.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_2.Weight = 0.39846153846153842;
            this.xrtableCell_3.BorderWidth = 1;
            this.xrtableCell_3.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_3.Name = "xrTableCell7";
            this.xrtableCell_3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_3.StylePriority.UseFont = false;
            this.xrtableCell_3.Text = "Đơn vị";
            this.xrtableCell_3.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_3.Weight = 0.087692307692307708;
            this.xrtableCell_4.BorderWidth = 1;
            this.xrtableCell_4.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_4.Name = "xrTableCell2";
            this.xrtableCell_4.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_4.StylePriority.UseFont = false;
            this.xrtableCell_4.Text = "Gi\x00e1 xuất";
            this.xrtableCell_4.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_4.Weight = 0.12923076923076926;
            this.xrtableCell_5.BorderWidth = 1;
            this.xrtableCell_5.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_5.Name = "xrTableCell13";
            this.xrtableCell_5.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_5.StylePriority.UseFont = false;
            this.xrtableCell_5.Text = "Số lượng";
            this.xrtableCell_5.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_5.Weight = 0.095384615384615387;
            this.xrtableCell_6.BorderWidth = 1;
            this.xrtableCell_6.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrtableCell_6.Name = "xrTableCell3";
            this.xrtableCell_6.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrtableCell_6.StylePriority.UseFont = false;
            this.xrtableCell_6.Text = "Th\x00e0nh tiền";
            this.xrtableCell_6.TextAlignment = TextAlignment.MiddleCenter;
            this.xrtableCell_6.Weight = 0.22307692307692312;
            this.pageFooterBand_0.Controls.AddRange(new XRControl[] { this.xrpageInfo_1, this.xrlabel_18, this.xrpageInfo_0 });
            this.pageFooterBand_0.HeightF = 27f;
            this.pageFooterBand_0.Name = "PageFooter";
            this.pageFooterBand_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.pageFooterBand_0.TextAlignment = TextAlignment.TopLeft;
            this.xrpageInfo_1.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrpageInfo_1.Format = "Ng\x00e0y in :{0:dd/MM/yyyy HH:mm}";
            this.xrpageInfo_1.LocationFloat = new PointFloat(536.9999f, 0f);
            this.xrpageInfo_1.Name = "xrPageInfo2";
            this.xrpageInfo_1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrpageInfo_1.PageInfo = PageInfo.DateTime;
            this.xrpageInfo_1.SizeF = new SizeF(150f, 25f);
            this.xrpageInfo_1.StylePriority.UseFont = false;
            this.xrpageInfo_1.StylePriority.UseTextAlignment = false;
            this.xrpageInfo_1.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_18.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_18.LocationFloat = new PointFloat(0f, 0f);
            this.xrlabel_18.Name = "Lbl_TranName";
            this.xrlabel_18.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_18.SizeF = new SizeF(267f, 25f);
            this.xrlabel_18.StylePriority.UseFont = false;
            this.xrlabel_18.StylePriority.UseTextAlignment = false;
            this.xrlabel_18.Text = "Giao dịch nhập h\x00e0ng từ nh\x00e0 cung cấp";
            this.xrlabel_18.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_18.WordWrap = false;
            this.xrpageInfo_0.Font = new Font("Arial", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrpageInfo_0.LocationFloat = new PointFloat(686.9999f, 0f);
            this.xrpageInfo_0.Name = "xrPageInfo1";
            this.xrpageInfo_0.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrpageInfo_0.SizeF = new SizeF(100f, 25f);
            this.xrpageInfo_0.StylePriority.UseFont = false;
            this.xrpageInfo_0.StylePriority.UseTextAlignment = false;
            this.xrpageInfo_0.TextAlignment = TextAlignment.MiddleRight;
            this.reportHeaderBand_0.Controls.AddRange(new XRControl[] { 
                this.xrlabel_31, this.xrlabel_32, this.xrlabel_27, this.xrlabel_28, this.xrlabel_19, this.xrlabel_20, this.xrlabel_17, this.xrlabel_13, this.xrlabel_14, this.xrlabel_15, this.xrlabel_16, this.xrlabel_7, this.xrlabel_8, this.xrlabel_9, this.xrlabel_10, this.xrlabel_11, 
                this.xrlabel_12, this.xrlabel_4, this.xrlabel_5, this.xrlabel_6, this.xrlabel_1, this.xrlabel_2, this.xrlabel_3, this.xrlabel_0
             });
            this.reportHeaderBand_0.HeightF = 208f;
            this.reportHeaderBand_0.Name = "ReportHeader";
            this.xrlabel_27.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_27.LocationFloat = new PointFloat(100f, 158f);
            this.xrlabel_27.Name = "Lbl_ImpId";
            this.xrlabel_27.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_27.SizeF = new SizeF(50f, 25f);
            this.xrlabel_27.StylePriority.UseFont = false;
            this.xrlabel_27.StylePriority.UseTextAlignment = false;
            this.xrlabel_27.Text = "(00003)";
            this.xrlabel_27.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_27.WordWrap = false;
            this.xrlabel_28.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_28.LocationFloat = new PointFloat(100f, 133f);
            this.xrlabel_28.Name = "Lbl_ExpId";
            this.xrlabel_28.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_28.SizeF = new SizeF(50f, 25f);
            this.xrlabel_28.StylePriority.UseFont = false;
            this.xrlabel_28.StylePriority.UseTextAlignment = false;
            this.xrlabel_28.Text = "(00003)";
            this.xrlabel_28.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_28.WordWrap = false;
            this.xrlabel_19.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_19.LocationFloat = new PointFloat(58f, 75f);
            this.xrlabel_19.Name = "Lbl_CompVatNumber";
            this.xrlabel_19.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_19.SizeF = new SizeF(142f, 25f);
            this.xrlabel_19.StylePriority.UseFont = false;
            this.xrlabel_19.StylePriority.UseTextAlignment = false;
            this.xrlabel_19.Text = "123546513213";
            this.xrlabel_19.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_19.WordWrap = false;
            this.xrlabel_20.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_20.LocationFloat = new PointFloat(0f, 75f);
            this.xrlabel_20.Name = "xrLabel16";
            this.xrlabel_20.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_20.SizeF = new SizeF(58f, 25f);
            this.xrlabel_20.StylePriority.UseFont = false;
            this.xrlabel_20.StylePriority.UseTextAlignment = false;
            this.xrlabel_20.Text = "MST :";
            this.xrlabel_20.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_20.WordWrap = false;
            this.xrlabel_17.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_17.LocationFloat = new PointFloat(58f, 50f);
            this.xrlabel_17.Name = "Lbl_CompPhone";
            this.xrlabel_17.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_17.SizeF = new SizeF(183f, 25f);
            this.xrlabel_17.StylePriority.UseFont = false;
            this.xrlabel_17.StylePriority.UseTextAlignment = false;
            this.xrlabel_17.Text = "84-04-38226596/04-9437505";
            this.xrlabel_17.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_17.WordWrap = false;
            this.xrlabel_13.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_13.LocationFloat = new PointFloat(0f, 50f);
            this.xrlabel_13.Name = "xrLabel15";
            this.xrlabel_13.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_13.SizeF = new SizeF(58f, 25f);
            this.xrlabel_13.StylePriority.UseFont = false;
            this.xrlabel_13.StylePriority.UseTextAlignment = false;
            this.xrlabel_13.Text = "Đ.thoại :";
            this.xrlabel_13.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_13.WordWrap = false;
            this.xrlabel_14.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_14.LocationFloat = new PointFloat(0f, 25f);
            this.xrlabel_14.Name = "xrLabel14";
            this.xrlabel_14.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_14.SizeF = new SizeF(58f, 25f);
            this.xrlabel_14.StylePriority.UseFont = false;
            this.xrlabel_14.StylePriority.UseTextAlignment = false;
            this.xrlabel_14.Text = "Địa chỉ :";
            this.xrlabel_14.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_14.WordWrap = false;
            this.xrlabel_15.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_15.LocationFloat = new PointFloat(58f, 25f);
            this.xrlabel_15.Name = "Lbl_CompAddress";
            this.xrlabel_15.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_15.SizeF = new SizeF(333f, 25f);
            this.xrlabel_15.StylePriority.UseFont = false;
            this.xrlabel_15.StylePriority.UseTextAlignment = false;
            this.xrlabel_15.Text = "Số 30 Trần nh\x00e2n T\x00f4ng";
            this.xrlabel_15.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_15.WordWrap = false;
            this.xrlabel_16.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_16.LocationFloat = new PointFloat(0f, 0f);
            this.xrlabel_16.Name = "Lbl_CompName";
            this.xrlabel_16.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_16.SizeF = new SizeF(483f, 25f);
            this.xrlabel_16.StylePriority.UseFont = false;
            this.xrlabel_16.StylePriority.UseTextAlignment = false;
            this.xrlabel_16.Text = "C\x00d4NG TY V\x00c0NG BẠC Đ\x00c1 QU\x00dd PH\x00da QU\x00dd";
            this.xrlabel_16.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_16.WordWrap = false;
            this.xrlabel_7.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_7.LocationFloat = new PointFloat(150f, 158f);
            this.xrlabel_7.Name = "Lbl_ImpName";
            this.xrlabel_7.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_7.SizeF = new SizeF(275f, 25f);
            this.xrlabel_7.StylePriority.UseFont = false;
            this.xrlabel_7.StylePriority.UseTextAlignment = false;
            this.xrlabel_7.Text = "Quầy b\x00e1n lẻ trang sức số 12";
            this.xrlabel_7.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_7.WordWrap = false;
            this.xrlabel_7.BeforePrint += new PrintEventHandler(this.xrlabel_7_BeforePrint);
            this.xrlabel_8.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_8.LocationFloat = new PointFloat(0f, 158f);
            this.xrlabel_8.Name = "xrLabel10";
            this.xrlabel_8.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_8.SizeF = new SizeF(100f, 25f);
            this.xrlabel_8.StylePriority.UseFont = false;
            this.xrlabel_8.StylePriority.UseTextAlignment = false;
            this.xrlabel_8.Text = "Nơi nhận h\x00e0ng :";
            this.xrlabel_8.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_8.WordWrap = false;
            this.xrlabel_9.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_9.LocationFloat = new PointFloat(100f, 183f);
            this.xrlabel_9.Name = "Lbl_Remark";
            this.xrlabel_9.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_9.SizeF = new SizeF(392f, 25f);
            this.xrlabel_9.StylePriority.UseFont = false;
            this.xrlabel_9.StylePriority.UseTextAlignment = false;
            this.xrlabel_9.Text = "Chuyển h\x00e0ng theo y\x00eau cầu của quầy";
            this.xrlabel_9.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_9.WordWrap = false;
            this.xrlabel_10.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_10.LocationFloat = new PointFloat(150f, 133f);
            this.xrlabel_10.Name = "Lbl_ExpName";
            this.xrlabel_10.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_10.SizeF = new SizeF(275f, 25f);
            this.xrlabel_10.StylePriority.UseFont = false;
            this.xrlabel_10.StylePriority.UseTextAlignment = false;
            this.xrlabel_10.Text = "Kho chứa h\x00e0ng số 30 Trần nh\x00e2n T\x00f4ng";
            this.xrlabel_10.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_10.WordWrap = false;
            this.xrlabel_10.BeforePrint += new PrintEventHandler(this.xrlabel_10_BeforePrint);
            this.xrlabel_11.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_11.LocationFloat = new PointFloat(0f, 183f);
            this.xrlabel_11.Name = "xrLabel7";
            this.xrlabel_11.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_11.SizeF = new SizeF(100f, 25f);
            this.xrlabel_11.StylePriority.UseFont = false;
            this.xrlabel_11.StylePriority.UseTextAlignment = false;
            this.xrlabel_11.Text = "Diễn giải :";
            this.xrlabel_11.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_11.WordWrap = false;
            this.xrlabel_12.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_12.LocationFloat = new PointFloat(0f, 133f);
            this.xrlabel_12.Name = "xrLabel5";
            this.xrlabel_12.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_12.SizeF = new SizeF(100f, 25f);
            this.xrlabel_12.StylePriority.UseFont = false;
            this.xrlabel_12.StylePriority.UseTextAlignment = false;
            this.xrlabel_12.Text = "Nơi xuất h\x00e0ng :";
            this.xrlabel_12.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_12.WordWrap = false;
            this.xrlabel_4.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_4.LocationFloat = new PointFloat(624.9999f, 158f);
            this.xrlabel_4.Name = "Lbl_TranTime";
            this.xrlabel_4.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_4.SizeF = new SizeF(142f, 25f);
            this.xrlabel_4.StylePriority.UseFont = false;
            this.xrlabel_4.StylePriority.UseTextAlignment = false;
            this.xrlabel_4.Text = "08:00";
            this.xrlabel_4.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_4.WordWrap = false;
            this.xrlabel_5.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_5.LocationFloat = new PointFloat(549.9999f, 158f);
            this.xrlabel_5.Name = "xrLabel4";
            this.xrlabel_5.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_5.SizeF = new SizeF(75.00006f, 25f);
            this.xrlabel_5.StylePriority.UseFont = false;
            this.xrlabel_5.StylePriority.UseTextAlignment = false;
            this.xrlabel_5.Text = "Giờ :";
            this.xrlabel_5.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_5.WordWrap = false;
            this.xrlabel_6.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_6.LocationFloat = new PointFloat(624.9999f, 133f);
            this.xrlabel_6.Name = "Lbl_TranDate";
            this.xrlabel_6.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_6.SizeF = new SizeF(142f, 25f);
            this.xrlabel_6.StylePriority.UseFont = false;
            this.xrlabel_6.StylePriority.UseTextAlignment = false;
            this.xrlabel_6.Text = "20/05/2009";
            this.xrlabel_6.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_6.WordWrap = false;
            this.xrlabel_1.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_1.LocationFloat = new PointFloat(375f, 96.54166f);
            this.xrlabel_1.Name = "Lbl_TransNum";
            this.xrlabel_1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_1.SizeF = new SizeF(142f, 25f);
            this.xrlabel_1.StylePriority.UseFont = false;
            this.xrlabel_1.StylePriority.UseTextAlignment = false;
            this.xrlabel_1.Text = "KX00000008";
            this.xrlabel_1.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_1.WordWrap = false;
            this.xrlabel_2.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_2.LocationFloat = new PointFloat(549.9999f, 133f);
            this.xrlabel_2.Name = "xrLabel2";
            this.xrlabel_2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_2.SizeF = new SizeF(75.00006f, 25f);
            this.xrlabel_2.StylePriority.UseFont = false;
            this.xrlabel_2.StylePriority.UseTextAlignment = false;
            this.xrlabel_2.Text = "Ng\x00e0y :";
            this.xrlabel_2.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_2.WordWrap = false;
            this.xrlabel_3.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_3.LocationFloat = new PointFloat(333f, 96.54166f);
            this.xrlabel_3.Name = "xrLabel1";
            this.xrlabel_3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_3.SizeF = new SizeF(42.00003f, 25f);
            this.xrlabel_3.StylePriority.UseFont = false;
            this.xrlabel_3.StylePriority.UseTextAlignment = false;
            this.xrlabel_3.Text = "Số :";
            this.xrlabel_3.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_3.WordWrap = false;
            this.xrlabel_0.CanShrink = true;
            this.xrlabel_0.Font = new Font("Arial", 14.25f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_0.LocationFloat = new PointFloat(259.375f, 75f);
            this.xrlabel_0.Name = "Lbl_Title";
            this.xrlabel_0.Padding = new PaddingInfo(0, 0, 0, 0, 100f);
            this.xrlabel_0.SizeF = new SizeF(271.875f, 33f);
            this.xrlabel_0.StylePriority.UseFont = false;
            this.xrlabel_0.StylePriority.UsePadding = false;
            this.xrlabel_0.StylePriority.UseTextAlignment = false;
            this.xrlabel_0.Text = "PHIẾU XUẤT TRẢ H\x00c0NG";
            this.xrlabel_0.TextAlignment = TextAlignment.MiddleCenter;
            this.reportFooterBand_0.Controls.AddRange(new XRControl[] { this.xrlabel_29, this.xrlabel_30, this.xrlabel_25, this.xrlabel_26, this.xrlabel_22, this.xrlabel_23, this.xrlabel_24, this.xrlabel_21 });
            this.reportFooterBand_0.HeightF = 162f;
            this.reportFooterBand_0.Name = "ReportFooter";
            this.xrlabel_29.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_29.LocationFloat = new PointFloat(504.6f, 0f);
            this.xrlabel_29.Name = "xrLabel13";
            this.xrlabel_29.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_29.SizeF = new SizeF(125f, 25f);
            this.xrlabel_29.StylePriority.UseFont = false;
            this.xrlabel_29.StylePriority.UseTextAlignment = false;
            this.xrlabel_29.Text = "Tổng xuất trả :";
            this.xrlabel_29.TextAlignment = TextAlignment.MiddleRight;
            this.xrlabel_29.WordWrap = false;
            this.xrlabel_30.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_30.LocationFloat = new PointFloat(629.6f, 0f);
            this.xrlabel_30.Name = "Lbl_TotalAmt";
            this.xrlabel_30.Padding = new PaddingInfo(0, 3, 0, 0, 100f);
            this.xrlabel_30.SizeF = new SizeF(157.4f, 25f);
            this.xrlabel_30.StylePriority.UseFont = false;
            this.xrlabel_30.StylePriority.UsePadding = false;
            this.xrlabel_30.StylePriority.UseTextAlignment = false;
            this.xrlabel_30.Text = "20,020,000";
            this.xrlabel_30.TextAlignment = TextAlignment.MiddleRight;
            this.xrlabel_30.WordWrap = false;
            this.xrlabel_25.Font = new Font("Arial", 9f, FontStyle.Italic, GraphicsUnit.Point, 0xa3);
            this.xrlabel_25.LocationFloat = new PointFloat(666.9999f, 58.33333f);
            this.xrlabel_25.Name = "xrLabel25";
            this.xrlabel_25.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_25.SizeF = new SizeF(50f, 25f);
            this.xrlabel_25.StylePriority.UseFont = false;
            this.xrlabel_25.StylePriority.UseTextAlignment = false;
            this.xrlabel_25.Text = "(K\x00fd t\x00ean)";
            this.xrlabel_25.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_25.WordWrap = false;
            this.xrlabel_26.Font = new Font("Arial", 9f, FontStyle.Italic, GraphicsUnit.Point, 0xa3);
            this.xrlabel_26.LocationFloat = new PointFloat(375f, 58.33333f);
            this.xrlabel_26.Name = "xrLabel24";
            this.xrlabel_26.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_26.SizeF = new SizeF(50f, 25f);
            this.xrlabel_26.StylePriority.UseFont = false;
            this.xrlabel_26.StylePriority.UseTextAlignment = false;
            this.xrlabel_26.Text = "(K\x00fd t\x00ean)";
            this.xrlabel_26.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_26.WordWrap = false;
            this.xrlabel_22.Font = new Font("Arial", 9f, FontStyle.Italic, GraphicsUnit.Point, 0xa3);
            this.xrlabel_22.LocationFloat = new PointFloat(67.00001f, 58.33333f);
            this.xrlabel_22.Name = "xrLabel23";
            this.xrlabel_22.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_22.SizeF = new SizeF(50f, 25f);
            this.xrlabel_22.StylePriority.UseFont = false;
            this.xrlabel_22.StylePriority.UseTextAlignment = false;
            this.xrlabel_22.Text = "(K\x00fd t\x00ean)";
            this.xrlabel_22.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_22.WordWrap = false;
            this.xrlabel_23.Font = new Font("Arial", 9f, FontStyle.Italic | FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_23.LocationFloat = new PointFloat(32.99999f, 41.33332f);
            this.xrlabel_23.Name = "xrLabel21";
            this.xrlabel_23.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_23.SizeF = new SizeF(125f, 25f);
            this.xrlabel_23.StylePriority.UseFont = false;
            this.xrlabel_23.StylePriority.UseTextAlignment = false;
            this.xrlabel_23.Text = "Người nhận h\x00e0ng";
            this.xrlabel_23.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_23.WordWrap = false;
            this.xrlabel_24.Font = new Font("Arial", 9f, FontStyle.Italic | FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_24.LocationFloat = new PointFloat(624.9999f, 41.33332f);
            this.xrlabel_24.Name = "xrLabel20";
            this.xrlabel_24.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_24.SizeF = new SizeF(125f, 25f);
            this.xrlabel_24.StylePriority.UseFont = false;
            this.xrlabel_24.StylePriority.UseTextAlignment = false;
            this.xrlabel_24.Text = "Người lập phiếu";
            this.xrlabel_24.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_24.WordWrap = false;
            this.xrlabel_21.Font = new Font("Arial", 9f, FontStyle.Italic | FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_21.LocationFloat = new PointFloat(333f, 41.33332f);
            this.xrlabel_21.Name = "xrLabel19";
            this.xrlabel_21.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_21.SizeF = new SizeF(125f, 25f);
            this.xrlabel_21.StylePriority.UseFont = false;
            this.xrlabel_21.StylePriority.UseTextAlignment = false;
            this.xrlabel_21.Text = "Người giao h\x00e0ng";
            this.xrlabel_21.TextAlignment = TextAlignment.MiddleCenter;
            this.xrlabel_21.WordWrap = false;
            this.topMarginBand_0.HeightF = 50f;
            this.topMarginBand_0.Name = "topMarginBand1";
            this.bottomMarginBand_0.HeightF = 50f;
            this.bottomMarginBand_0.Name = "bottomMarginBand1";
            this.xrlabel_32.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, 0xa3);
            this.xrlabel_32.LocationFloat = new PointFloat(624.9999f, 183f);
            this.xrlabel_32.Name = "Lbl_UserName";
            this.xrlabel_32.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_32.SizeF = new SizeF(162f, 25f);
            this.xrlabel_32.StylePriority.UseFont = false;
            this.xrlabel_32.StylePriority.UseTextAlignment = false;
            this.xrlabel_32.Text = "KX00000008";
            this.xrlabel_32.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_32.WordWrap = false;
            this.xrlabel_31.Font = new Font("Arial", 9f, FontStyle.Bold, GraphicsUnit.Point, 0xa3);
            this.xrlabel_31.LocationFloat = new PointFloat(549.9999f, 183f);
            this.xrlabel_31.Name = "xrLabel9";
            this.xrlabel_31.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrlabel_31.SizeF = new SizeF(75.00006f, 25f);
            this.xrlabel_31.StylePriority.UseFont = false;
            this.xrlabel_31.StylePriority.UseTextAlignment = false;
            this.xrlabel_31.Text = "Nh\x00e2n vi\x00ean :";
            this.xrlabel_31.TextAlignment = TextAlignment.MiddleLeft;
            this.xrlabel_31.WordWrap = false;
            base.Bands.AddRange(new Band[] { this.detailBand_0, this.pageHeaderBand_0, this.pageFooterBand_0, this.reportHeaderBand_0, this.reportFooterBand_0, this.topMarginBand_0, this.bottomMarginBand_0 });
            base.Margins = new Margins(20, 20, 50, 50);
            base.PageHeight = 0x491;
            base.PageWidth = 0x33b;
            base.PaperKind = PaperKind.A4;
            base.Version = "9.3";
            this.BeforePrint += new PrintEventHandler(this.v_tosupp_BeforePrint);
            this.xrtable_1.EndInit();
            this.xrtable_0.EndInit();
            this.EndInit();
        }

        private void v_tosupp_BeforePrint(object sender, PrintEventArgs e)
        {
            this.xrlabel_16.Text = Class13.smethod_1(Class7.smethod_14("m_name").ToString(), Class13.string_0);
            this.xrlabel_15.Text = Class13.smethod_1(Class7.smethod_14("m_address").ToString(), Class13.string_0);
            this.xrlabel_17.Text = Class13.smethod_1(Class7.smethod_14("m_phone").ToString(), Class13.string_0);
            this.xrlabel_19.Text = Class13.smethod_1(Class7.smethod_14("m_vatnum").ToString(), Class13.string_0);
            OleDbDataAdapter adapter = new OleDbDataAdapter("SELECT  stk.tran_date, stk.tran_time, stk.trans_num, stk.trans_code, stk.voucher, stk.invoice, stk.post, stk.exp_id, stk.imp_id, stk.goods_id, stk.qty, stk.unit_symb, stk.amount, stk.discount, stk.vat_amt,stk.surplus, stk.commis_amt, stk.forex_cys, stk.forex_rate, stk.expiry_dt, stk.user_id, stk.cs_id, stk.ref, stk.remark, stk.updated, stk.merc_type, stk.tax_code, stk.vat_incl, stk.discpervat, stk.disc_incl, stk.copies,stk.recnum, gs.full_name, pr.rtprice,pr.averimppr, pr.lastimppr, pr.wsprice, pr.prefprice,us.name FROM  tblTransaction AS stk INNER JOIN tblGoods AS gs ON stk.goods_id = gs.goods_id INNER JOIN tblPrice AS pr ON stk.goods_id = pr.goods_id INNER JOIN tblUser as us ON stk.user_id = us.id where stk.trans_num = '" + Class6.transNum + "' order by stk.recnum ", this.oleDbConnection_0);
            DataSet dataSet = new DataSet();
            adapter.Fill(dataSet);
            this.oleDbConnection_0.Close();
            base.DataAdapter = adapter;
            base.DataSource = dataSet.Tables[0];
            string str2 = string.Format("{0:dd/MM/yyy}", DateTime.Parse(dataSet.Tables[0].Rows[0]["tran_date"].ToString()));
            this.xrlabel_6.Text = str2;
            this.xrlabel_1.Text = dataSet.Tables[0].Rows[0]["trans_num"].ToString();
            this.xrlabel_4.Text = dataSet.Tables[0].Rows[0]["tran_time"].ToString();
            this.xrlabel_27.Text = dataSet.Tables[0].Rows[0]["imp_id"].ToString();
            this.xrlabel_28.Text = dataSet.Tables[0].Rows[0]["exp_id"].ToString();
            this.xrlabel_9.Text = dataSet.Tables[0].Rows[0]["remark"].ToString();
            this.xrlabel_32.Text = dataSet.Tables[0].Rows[0]["name"].ToString();
            this.xrtableCell_10.DataBindings.Add("Text", base.DataSource, "recnum", "{0:n0}");
            this.xrtableCell_11.DataBindings.Add("Text", base.DataSource, "goods_id", "");
            this.xrtableCell_7.DataBindings.Add("Text", base.DataSource, "full_name", "");
            this.xrtableCell_9.DataBindings.Add("Text", base.DataSource, "qty", "{0:n2}");
            this.xrtableCell_8.DataBindings.Add("Text", base.DataSource, "unit_symb", "");
            this.xrlabel_30.DataBindings.Add("Text", base.DataSource, "amount", "{0:n2}");
            this.xrsummary_0.Running = SummaryRunning.Report;
            this.xrsummary_0.FormatString = "{0:n2}";
            this.xrlabel_30.Summary = this.xrsummary_0;
            this.xrlabel_18.Text = Class6.string_1;
        }

        private void xrlabel_10_BeforePrint(object sender, PrintEventArgs e)
        {
            string str = null;
            Class7.smethod_17("fullname", "tblStore", "Id", this.xrlabel_28.Text, "", this.oleDbConnection_0, ref str);
            this.xrlabel_10.Text = str;
        }

        private void xrlabel_7_BeforePrint(object sender, PrintEventArgs e)
        {
            string str = null;
            Class7.smethod_17("fullname", "tblStore", "Id", this.xrlabel_27.Text, "", this.oleDbConnection_0, ref str);
            this.xrlabel_7.Text = str;
        }

        private void xrtableCell_12_BeforePrint(object sender, PrintEventArgs e)
        {
            this.xrtableCell_12.Text = string.Format("{0:n2}", (Class7.ParseDoubleValue(base.GetCurrentColumnValue("amount").ToString()) + Class7.ParseDoubleValue(base.GetCurrentColumnValue("discount").ToString())) / Class7.ParseDoubleValue(base.GetCurrentColumnValue("qty").ToString()));
        }

        private void xrtableCell_13_BeforePrint(object sender, PrintEventArgs e)
        {
            this.xrtableCell_13.Text = string.Format("{0:n2}", Class7.ParseDoubleValue(base.GetCurrentColumnValue("amount").ToString()) + Class7.ParseDoubleValue(base.GetCurrentColumnValue("discount").ToString()));
        }
    }
}

