using DevExpress.XtraEditors;
using System.Windows.Forms;
using System;
using System.Drawing;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Mask;
using DevExpress.Utils;
namespace LibraryManagement.App
{
    partial class FrmAccountInfo
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.Lbl_Name = new LabelControl();
            this.Txt_ShortName = new TextEdit();
            this.labelControl15 = new LabelControl();
            this.Txt_Account = new TextEdit();
            this.labelControl2 = new LabelControl();
            this.Lbl_DayDebit = new LabelControl();
            this.labelControl8 = new LabelControl();
            this.Lbl_BodAmt = new LabelControl();
            this.labelControl1 = new LabelControl();
            this.Lbl_Balance = new LabelControl();
            this.labelControl4 = new LabelControl();
            this.Lbl_DayCredit = new LabelControl();
            this.labelControl6 = new LabelControl();
            this.Lbl_MonthCredit = new LabelControl();
            this.Lbl_MonthDebit = new LabelControl();
            this.Lbl_BomAmt = new LabelControl();
            this.Lbl_YearCredit = new LabelControl();
            this.Lbl_YearDebit = new LabelControl();
            this.Lbl_BoyAmt = new LabelControl();
            this.GroupBox2 = new GroupBox();
            this.btn_Exit = new SimpleButton();
            this.btn_Search = new SimpleButton();
            this.btn_Detail = new SimpleButton();
            this.groupBox1 = new GroupBox();
            this.labelControl9 = new LabelControl();
            this.labelControl11 = new LabelControl();
            this.labelControl13 = new LabelControl();
            this.labelControl16 = new LabelControl();
            this.xTveRubwQ = new LabelControl();
            this.Lbl_Status = new LabelControl();
            this.Lbl_LatsDate = new LabelControl();
            this.groupBox3 = new GroupBox();
            this.Txt_ShortName.Properties.BeginInit();
            this.Txt_Account.Properties.BeginInit();
            base.SuspendLayout();
            this.Lbl_Name.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Name.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Name.Appearance.BorderColor = Color.White;
            this.Lbl_Name.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Name.Appearance.ForeColor = Color.Black;
            this.Lbl_Name.Appearance.Options.UseBackColor = true;
            this.Lbl_Name.Appearance.Options.UseBorderColor = true;
            this.Lbl_Name.Appearance.Options.UseFont = true;
            this.Lbl_Name.Appearance.Options.UseForeColor = true;
            this.Lbl_Name.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Name.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Name.Location = new Point(0x6a, 0x26);
            this.Lbl_Name.Name = "Lbl_Name";
            this.Lbl_Name.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_Name.Size = new Size(0x1a6, 0x11);
            this.Lbl_Name.TabIndex = 470;
            this.Txt_ShortName.EnterMoveNextControl = true;
            this.Txt_ShortName.Location = new Point(0x146, 12);
            this.Txt_ShortName.Name = "Txt_ShortName";
            this.Txt_ShortName.Properties.Appearance.Options.UseFont = true;
            this.Txt_ShortName.Properties.CharacterCasing = CharacterCasing.Upper;
            this.Txt_ShortName.Properties.MaxLength = 30;
            this.Txt_ShortName.Size = new Size(0xca, 20);
            this.Txt_ShortName.TabIndex = 0x1d3;
            this.labelControl15.Location = new Point(0x108, 15);
            this.labelControl15.Name = "labelControl15";
            this.labelControl15.Size = new Size(0x38, 13);
            this.labelControl15.TabIndex = 0x1d5;
            this.labelControl15.Text = "T\x00ean viết tắt";
            this.Txt_Account.EnterMoveNextControl = true;
            this.Txt_Account.Location = new Point(0x6a, 12);
            this.Txt_Account.Name = "Txt_Account";
            this.Txt_Account.Properties.Appearance.BackColor = Color.PapayaWhip;
            this.Txt_Account.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_Account.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_Account.Properties.Appearance.Options.UseFont = true;
            this.Txt_Account.Properties.Mask.EditMask = "####-#-####";
            this.Txt_Account.Properties.Mask.MaskType = MaskType.Simple;
            this.Txt_Account.Properties.Mask.PlaceHolder = ' ';
            this.Txt_Account.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_Account.Size = new Size(0x89, 20);
            this.Txt_Account.TabIndex = 0x1d2;
            this.Txt_Account.ToolTip = "Nhập số TK v\x00e0 Enter";
            this.Txt_Account.ToolTipIconType = ToolTipIconType.Warning;
            this.Txt_Account.ToolTipTitle = "Lưu \x00fd";
            this.Txt_Account.EditValueChanged += new EventHandler(this.Txt_Account_EditValueChanged);
            this.Txt_Account.KeyDown += new KeyEventHandler(this.Txt_Account_KeyDown);
            this.labelControl2.Location = new Point(15, 15);
            this.labelControl2.Name = "labelControl2";
            this.labelControl2.Size = new Size(0x3b, 13);
            this.labelControl2.TabIndex = 0x1d4;
            this.labelControl2.Text = "Số t\x00e0i khoản";
            this.Lbl_DayDebit.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_DayDebit.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_DayDebit.Appearance.BorderColor = Color.White;
            this.Lbl_DayDebit.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_DayDebit.Appearance.ForeColor = Color.Black;
            this.Lbl_DayDebit.Appearance.Options.UseBackColor = true;
            this.Lbl_DayDebit.Appearance.Options.UseBorderColor = true;
            this.Lbl_DayDebit.Appearance.Options.UseFont = true;
            this.Lbl_DayDebit.Appearance.Options.UseForeColor = true;
            this.Lbl_DayDebit.Appearance.Options.UseTextOptions = true;
            this.Lbl_DayDebit.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_DayDebit.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_DayDebit.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_DayDebit.Location = new Point(0x6a, 0x76);
            this.Lbl_DayDebit.Name = "Lbl_DayDebit";
            this.Lbl_DayDebit.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_DayDebit.Size = new Size(110, 0x11);
            this.Lbl_DayDebit.TabIndex = 0x1da;
            this.labelControl8.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl8.Appearance.Options.UseFont = true;
            this.labelControl8.Location = new Point(15, 0x79);
            this.labelControl8.Name = "labelControl8";
            this.labelControl8.Size = new Size(0x3b, 13);
            this.labelControl8.TabIndex = 0x1d9;
            this.labelControl8.Text = "Ph\x00e1t sinh nợ";
            this.Lbl_BodAmt.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_BodAmt.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_BodAmt.Appearance.BorderColor = Color.White;
            this.Lbl_BodAmt.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_BodAmt.Appearance.ForeColor = Color.Black;
            this.Lbl_BodAmt.Appearance.Options.UseBackColor = true;
            this.Lbl_BodAmt.Appearance.Options.UseBorderColor = true;
            this.Lbl_BodAmt.Appearance.Options.UseFont = true;
            this.Lbl_BodAmt.Appearance.Options.UseForeColor = true;
            this.Lbl_BodAmt.Appearance.Options.UseTextOptions = true;
            this.Lbl_BodAmt.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_BodAmt.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_BodAmt.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_BodAmt.Location = new Point(0x6a, 0x5f);
            this.Lbl_BodAmt.Name = "Lbl_BodAmt";
            this.Lbl_BodAmt.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_BodAmt.Size = new Size(110, 0x11);
            this.Lbl_BodAmt.TabIndex = 0x1d8;
            this.labelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl1.Appearance.Options.UseFont = true;
            this.labelControl1.Location = new Point(15, 0x63);
            this.labelControl1.Name = "labelControl1";
            this.labelControl1.Size = new Size(0x31, 13);
            this.labelControl1.TabIndex = 0x1d7;
            this.labelControl1.Text = "Số dư đầu";
            this.Lbl_Balance.Appearance.BackColor = Color.PapayaWhip;
            this.Lbl_Balance.Appearance.BackColor2 = Color.PapayaWhip;
            this.Lbl_Balance.Appearance.BorderColor = Color.White;
            this.Lbl_Balance.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Balance.Appearance.ForeColor = Color.Black;
            this.Lbl_Balance.Appearance.Options.UseBackColor = true;
            this.Lbl_Balance.Appearance.Options.UseBorderColor = true;
            this.Lbl_Balance.Appearance.Options.UseFont = true;
            this.Lbl_Balance.Appearance.Options.UseForeColor = true;
            this.Lbl_Balance.Appearance.Options.UseTextOptions = true;
            this.Lbl_Balance.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_Balance.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Balance.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Balance.Location = new Point(0x6a, 0xae);
            this.Lbl_Balance.Name = "Lbl_Balance";
            this.Lbl_Balance.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_Balance.Size = new Size(110, 0x11);
            this.Lbl_Balance.TabIndex = 0x1de;
            this.labelControl4.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl4.Appearance.Options.UseFont = true;
            this.labelControl4.Location = new Point(15, 0xb2);
            this.labelControl4.Name = "labelControl4";
            this.labelControl4.Size = new Size(0x48, 13);
            this.labelControl4.TabIndex = 0x1dd;
            this.labelControl4.Text = "Số dư hiện thời";
            this.Lbl_DayCredit.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_DayCredit.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_DayCredit.Appearance.BorderColor = Color.White;
            this.Lbl_DayCredit.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_DayCredit.Appearance.ForeColor = Color.Black;
            this.Lbl_DayCredit.Appearance.Options.UseBackColor = true;
            this.Lbl_DayCredit.Appearance.Options.UseBorderColor = true;
            this.Lbl_DayCredit.Appearance.Options.UseFont = true;
            this.Lbl_DayCredit.Appearance.Options.UseForeColor = true;
            this.Lbl_DayCredit.Appearance.Options.UseTextOptions = true;
            this.Lbl_DayCredit.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_DayCredit.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_DayCredit.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_DayCredit.Location = new Point(0x6a, 0x8d);
            this.Lbl_DayCredit.Name = "Lbl_DayCredit";
            this.Lbl_DayCredit.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_DayCredit.Size = new Size(110, 0x11);
            this.Lbl_DayCredit.TabIndex = 0x1dc;
            this.labelControl6.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl6.Appearance.Options.UseFont = true;
            this.labelControl6.Location = new Point(15, 0x91);
            this.labelControl6.Name = "labelControl6";
            this.labelControl6.Size = new Size(0x3a, 13);
            this.labelControl6.TabIndex = 0x1db;
            this.labelControl6.Text = "Ph\x00e1t sinh c\x00f3";
            this.Lbl_MonthCredit.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_MonthCredit.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_MonthCredit.Appearance.BorderColor = Color.White;
            this.Lbl_MonthCredit.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_MonthCredit.Appearance.ForeColor = Color.Black;
            this.Lbl_MonthCredit.Appearance.Options.UseBackColor = true;
            this.Lbl_MonthCredit.Appearance.Options.UseBorderColor = true;
            this.Lbl_MonthCredit.Appearance.Options.UseFont = true;
            this.Lbl_MonthCredit.Appearance.Options.UseForeColor = true;
            this.Lbl_MonthCredit.Appearance.Options.UseTextOptions = true;
            this.Lbl_MonthCredit.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_MonthCredit.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_MonthCredit.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_MonthCredit.Location = new Point(0xfd, 140);
            this.Lbl_MonthCredit.Name = "Lbl_MonthCredit";
            this.Lbl_MonthCredit.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_MonthCredit.Size = new Size(110, 0x11);
            this.Lbl_MonthCredit.TabIndex = 0x1e4;
            this.Lbl_MonthDebit.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_MonthDebit.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_MonthDebit.Appearance.BorderColor = Color.White;
            this.Lbl_MonthDebit.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_MonthDebit.Appearance.ForeColor = Color.Black;
            this.Lbl_MonthDebit.Appearance.Options.UseBackColor = true;
            this.Lbl_MonthDebit.Appearance.Options.UseBorderColor = true;
            this.Lbl_MonthDebit.Appearance.Options.UseFont = true;
            this.Lbl_MonthDebit.Appearance.Options.UseForeColor = true;
            this.Lbl_MonthDebit.Appearance.Options.UseTextOptions = true;
            this.Lbl_MonthDebit.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_MonthDebit.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_MonthDebit.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_MonthDebit.Location = new Point(0xfd, 0x75);
            this.Lbl_MonthDebit.Name = "Lbl_MonthDebit";
            this.Lbl_MonthDebit.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_MonthDebit.Size = new Size(110, 0x11);
            this.Lbl_MonthDebit.TabIndex = 0x1e2;
            this.Lbl_BomAmt.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_BomAmt.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_BomAmt.Appearance.BorderColor = Color.White;
            this.Lbl_BomAmt.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_BomAmt.Appearance.ForeColor = Color.Black;
            this.Lbl_BomAmt.Appearance.Options.UseBackColor = true;
            this.Lbl_BomAmt.Appearance.Options.UseBorderColor = true;
            this.Lbl_BomAmt.Appearance.Options.UseFont = true;
            this.Lbl_BomAmt.Appearance.Options.UseForeColor = true;
            this.Lbl_BomAmt.Appearance.Options.UseTextOptions = true;
            this.Lbl_BomAmt.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_BomAmt.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_BomAmt.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_BomAmt.Location = new Point(0xfd, 0x5e);
            this.Lbl_BomAmt.Name = "Lbl_BomAmt";
            this.Lbl_BomAmt.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_BomAmt.Size = new Size(110, 0x11);
            this.Lbl_BomAmt.TabIndex = 480;
            this.Lbl_YearCredit.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_YearCredit.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_YearCredit.Appearance.BorderColor = Color.White;
            this.Lbl_YearCredit.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_YearCredit.Appearance.ForeColor = Color.Black;
            this.Lbl_YearCredit.Appearance.Options.UseBackColor = true;
            this.Lbl_YearCredit.Appearance.Options.UseBorderColor = true;
            this.Lbl_YearCredit.Appearance.Options.UseFont = true;
            this.Lbl_YearCredit.Appearance.Options.UseForeColor = true;
            this.Lbl_YearCredit.Appearance.Options.UseTextOptions = true;
            this.Lbl_YearCredit.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_YearCredit.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_YearCredit.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_YearCredit.Location = new Point(0x18b, 140);
            this.Lbl_YearCredit.Name = "Lbl_YearCredit";
            this.Lbl_YearCredit.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_YearCredit.Size = new Size(110, 0x11);
            this.Lbl_YearCredit.TabIndex = 490;
            this.Lbl_YearDebit.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_YearDebit.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_YearDebit.Appearance.BorderColor = Color.White;
            this.Lbl_YearDebit.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_YearDebit.Appearance.ForeColor = Color.Black;
            this.Lbl_YearDebit.Appearance.Options.UseBackColor = true;
            this.Lbl_YearDebit.Appearance.Options.UseBorderColor = true;
            this.Lbl_YearDebit.Appearance.Options.UseFont = true;
            this.Lbl_YearDebit.Appearance.Options.UseForeColor = true;
            this.Lbl_YearDebit.Appearance.Options.UseTextOptions = true;
            this.Lbl_YearDebit.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_YearDebit.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_YearDebit.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_YearDebit.Location = new Point(0x18b, 0x75);
            this.Lbl_YearDebit.Name = "Lbl_YearDebit";
            this.Lbl_YearDebit.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_YearDebit.Size = new Size(110, 0x11);
            this.Lbl_YearDebit.TabIndex = 0x1e8;
            this.Lbl_BoyAmt.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_BoyAmt.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_BoyAmt.Appearance.BorderColor = Color.White;
            this.Lbl_BoyAmt.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_BoyAmt.Appearance.ForeColor = Color.Black;
            this.Lbl_BoyAmt.Appearance.Options.UseBackColor = true;
            this.Lbl_BoyAmt.Appearance.Options.UseBorderColor = true;
            this.Lbl_BoyAmt.Appearance.Options.UseFont = true;
            this.Lbl_BoyAmt.Appearance.Options.UseForeColor = true;
            this.Lbl_BoyAmt.Appearance.Options.UseTextOptions = true;
            this.Lbl_BoyAmt.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_BoyAmt.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_BoyAmt.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_BoyAmt.Location = new Point(0x18b, 0x5e);
            this.Lbl_BoyAmt.Name = "Lbl_BoyAmt";
            this.Lbl_BoyAmt.Padding = new Padding(3, 0, 3, 0);
            this.Lbl_BoyAmt.Size = new Size(110, 0x11);
            this.Lbl_BoyAmt.TabIndex = 0x1e6;
            this.GroupBox2.Anchor = AnchorStyles.Bottom;
            this.GroupBox2.Location = new Point(-108, 0xdd);
            this.GroupBox2.Name = "GroupBox2";
            this.GroupBox2.Size = new Size(0x2fa, 5);
            this.GroupBox2.TabIndex = 0x1f2;
            this.GroupBox2.TabStop = false;
            this.btn_Exit.Anchor = AnchorStyles.Bottom;
            this.btn_Exit.DialogResult = DialogResult.Cancel;
            this.btn_Exit.Location = new Point(0x143, 0xe9);
            this.btn_Exit.Name = "btn_Exit";
            this.btn_Exit.Size = new Size(0x4b, 0x17);
            this.btn_Exit.TabIndex = 0x1f1;
            this.btn_Exit.Text = "Th&o\x00e1t";
            this.btn_Exit.Click += new EventHandler(this.btn_Exit_Click);
            this.btn_Search.Anchor = AnchorStyles.Bottom;
            this.btn_Search.Location = new Point(0xed, 0xe9);
            this.btn_Search.Name = "btn_Search";
            this.btn_Search.Size = new Size(0x4b, 0x17);
            this.btn_Search.TabIndex = 0x1f0;
            this.btn_Search.Text = "T\x00ec&m";
            this.btn_Search.Click += new EventHandler(this.btn_Search_Click);
            this.btn_Detail.Anchor = AnchorStyles.Bottom;
            this.btn_Detail.DialogResult = DialogResult.Cancel;
            this.btn_Detail.Location = new Point(0x97, 0xe9);
            this.btn_Detail.Name = "btn_Detail";
            this.btn_Detail.Size = new Size(0x4b, 0x17);
            this.btn_Detail.TabIndex = 0x1ee;
            this.btn_Detail.Text = "&Chi tiết";
            this.btn_Detail.Click += new EventHandler(this.btn_Detail_Click);
            this.groupBox1.Location = new Point(-107, 0x39);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x2fa, 5);
            this.groupBox1.TabIndex = 0x1f3;
            this.groupBox1.TabStop = false;
            this.labelControl9.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl9.Appearance.Options.UseFont = true;
            this.labelControl9.Location = new Point(0x70, 0x4c);
            this.labelControl9.Name = "labelControl9";
            this.labelControl9.Size = new Size(0x37, 13);
            this.labelControl9.TabIndex = 500;
            this.labelControl9.Text = "Trong ng\x00e0y";
            this.labelControl11.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl11.Appearance.Options.UseFont = true;
            this.labelControl11.Location = new Point(0xfd, 0x4b);
            this.labelControl11.Name = "labelControl11";
            this.labelControl11.Size = new Size(0x3b, 13);
            this.labelControl11.TabIndex = 0x1f5;
            this.labelControl11.Text = "Trong th\x00e1ng";
            this.labelControl13.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl13.Appearance.Options.UseFont = true;
            this.labelControl13.Location = new Point(0x18b, 0x4b);
            this.labelControl13.Name = "labelControl13";
            this.labelControl13.Size = new Size(0x33, 13);
            this.labelControl13.TabIndex = 0x1f6;
            this.labelControl13.Text = "Trong năm";
            this.labelControl13.Click += new EventHandler(this.labelControl13_Click);
            this.labelControl16.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl16.Appearance.Options.UseFont = true;
            this.labelControl16.Location = new Point(0x11c, 0xaf);
            this.labelControl16.Name = "labelControl16";
            this.labelControl16.Size = new Size(0x5c, 13);
            this.labelControl16.TabIndex = 0x1f8;
            this.labelControl16.Text = "Ng\x00e0y giao dịch cuối";
            this.xTveRubwQ.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.xTveRubwQ.Appearance.Options.UseFont = true;
            this.xTveRubwQ.Location = new Point(0x11c, 0xc7);
            this.xTveRubwQ.Name = "labelControl18";
            this.xTveRubwQ.Size = new Size(0x60, 13);
            this.xTveRubwQ.TabIndex = 0x1f7;
            this.xTveRubwQ.Text = "Trạng th\x00e1i t\x00e0i khoản";
            this.Lbl_Status.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_Status.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_Status.Appearance.BorderColor = Color.White;
            this.Lbl_Status.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Status.Appearance.ForeColor = Color.Black;
            this.Lbl_Status.Appearance.Options.UseBackColor = true;
            this.Lbl_Status.Appearance.Options.UseBorderColor = true;
            this.Lbl_Status.Appearance.Options.UseFont = true;
            this.Lbl_Status.Appearance.Options.UseForeColor = true;
            this.Lbl_Status.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_Status.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_Status.Location = new Point(0x18b, 0xc4);
            this.Lbl_Status.Name = "Lbl_Status";
            this.Lbl_Status.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_Status.Size = new Size(110, 0x11);
            this.Lbl_Status.TabIndex = 0x1fa;
            this.Lbl_LatsDate.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_LatsDate.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_LatsDate.Appearance.BorderColor = Color.White;
            this.Lbl_LatsDate.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_LatsDate.Appearance.ForeColor = Color.Black;
            this.Lbl_LatsDate.Appearance.Options.UseBackColor = true;
            this.Lbl_LatsDate.Appearance.Options.UseBorderColor = true;
            this.Lbl_LatsDate.Appearance.Options.UseFont = true;
            this.Lbl_LatsDate.Appearance.Options.UseForeColor = true;
            this.Lbl_LatsDate.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_LatsDate.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_LatsDate.Location = new Point(0x18b, 0xae);
            this.Lbl_LatsDate.Name = "Lbl_LatsDate";
            this.Lbl_LatsDate.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_LatsDate.Size = new Size(110, 0x11);
            this.Lbl_LatsDate.TabIndex = 0x1f9;
            this.groupBox3.Location = new Point(-107, 0xa2);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x2fa, 5);
            this.groupBox3.TabIndex = 0x1fb;
            this.groupBox3.TabStop = false;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.CancelButton = this.btn_Exit;
            base.ClientSize = new Size(0x224, 0x109);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.labelControl16);
            base.Controls.Add(this.xTveRubwQ);
            base.Controls.Add(this.Lbl_Status);
            base.Controls.Add(this.Lbl_LatsDate);
            base.Controls.Add(this.labelControl13);
            base.Controls.Add(this.labelControl11);
            base.Controls.Add(this.labelControl9);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.GroupBox2);
            base.Controls.Add(this.btn_Exit);
            base.Controls.Add(this.btn_Search);
            base.Controls.Add(this.btn_Detail);
            base.Controls.Add(this.Lbl_YearCredit);
            base.Controls.Add(this.Lbl_YearDebit);
            base.Controls.Add(this.Lbl_BoyAmt);
            base.Controls.Add(this.Lbl_MonthCredit);
            base.Controls.Add(this.Lbl_MonthDebit);
            base.Controls.Add(this.Lbl_BomAmt);
            base.Controls.Add(this.Lbl_Balance);
            base.Controls.Add(this.labelControl4);
            base.Controls.Add(this.Lbl_DayCredit);
            base.Controls.Add(this.labelControl6);
            base.Controls.Add(this.Lbl_DayDebit);
            base.Controls.Add(this.labelControl8);
            base.Controls.Add(this.Lbl_BodAmt);
            base.Controls.Add(this.labelControl1);
            base.Controls.Add(this.Lbl_Name);
            base.Controls.Add(this.Txt_ShortName);
            base.Controls.Add(this.labelControl15);
            base.Controls.Add(this.Txt_Account);
            base.Controls.Add(this.labelControl2);
            base.FormBorderStyle = FormBorderStyle.FixedDialog;
            base.MaximizeBox = false;
            base.Name = "FrmAccountInfo";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmAccountInfo";
            base.Load += new EventHandler(this.FrmAccountInfo_Load);
            this.Txt_ShortName.Properties.EndInit();
            this.Txt_Account.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }


        private SimpleButton btn_Detail;
        private SimpleButton btn_Exit;
        private SimpleButton btn_Search;
        internal GroupBox groupBox1;
        internal GroupBox GroupBox2;
        internal GroupBox groupBox3;
        internal LabelControl labelControl1;
        internal LabelControl labelControl11;
        internal LabelControl labelControl13;
        private LabelControl labelControl15;
        internal LabelControl labelControl16;
        private LabelControl labelControl2;
        internal LabelControl labelControl4;
        internal LabelControl labelControl6;
        internal LabelControl labelControl8;
        internal LabelControl labelControl9;
        internal LabelControl Lbl_Balance;
        internal LabelControl Lbl_BodAmt;
        internal LabelControl Lbl_BomAmt;
        internal LabelControl Lbl_BoyAmt;
        internal LabelControl Lbl_DayCredit;
        internal LabelControl Lbl_DayDebit;
        internal LabelControl Lbl_LatsDate;
        internal LabelControl Lbl_MonthCredit;
        internal LabelControl Lbl_MonthDebit;
        internal LabelControl Lbl_Name;
        internal LabelControl Lbl_Status;
        internal LabelControl Lbl_YearCredit;
        internal LabelControl Lbl_YearDebit;

        private TextEdit Txt_Account;
        private TextEdit Txt_ShortName;
        internal LabelControl xTveRubwQ;

        #endregion
    }
}