using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Mask;
using System;
using System.ComponentModel;
using System.Data;
using System.Data.OleDb;
using System.Drawing;
using System.Windows.Forms;

namespace LibraryManagement.App
{
    partial class FrmCustomer
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.LabelControl11 = new LabelControl();
            this.Txt_Contactperson = new TextEdit();
            this.LabelControl7 = new LabelControl();
            this.Txt_Remark = new TextEdit();
            this.LabelControl6 = new LabelControl();
            this.Cmb_CustType = new ComboBoxEdit();
            this.Txt_OpenDate = new TextEdit();
            this.GroupBox2 = new GroupBox();
            this.LabelControl5 = new LabelControl();
            this.LabelControl10 = new LabelControl();
            this.LabelControl9 = new LabelControl();
            this.LabelControl8 = new LabelControl();
            this.ddvqeXfa4 = new TextEdit();
            this.Txt_BankName = new TextEdit();
            this.Txt_AccountId = new TextEdit();
            this.LabelControl3 = new LabelControl();
            this.LabelControl4 = new LabelControl();
            this.Txt_Status = new TextEdit();
            this.Txt_Id = new TextEdit();
            this.welftZbha = new TextEdit();
            this.LabelControl2 = new LabelControl();
            this.LabelControl1 = new LabelControl();
            this.Txt_Phone = new TextEdit();
            this.Txt_Address = new TextEdit();
            this.LabelControl15 = new LabelControl();
            this.CwwJoLjYp = new LabelControl();
            this.Txt_FullName = new TextEdit();
            this.Txt_ShortName = new TextEdit();
            this.groupBox1 = new GroupBox();
            this.btn_Exit = new SimpleButton();
            this.btn_Search = new SimpleButton();
            this.btn_Edit = new SimpleButton();
            this.btn_New = new SimpleButton();
            this.btn_Skip = new SimpleButton();
            this.btn_Save = new SimpleButton();
            this.btn_Delete = new SimpleButton();
            this.labelControl12 = new LabelControl();
            this.txtBankBranch = new TextEdit();
            this.Txt_Contactperson.Properties.BeginInit();
            this.Txt_Remark.Properties.BeginInit();
            this.Cmb_CustType.Properties.BeginInit();
            this.Txt_OpenDate.Properties.BeginInit();
            this.ddvqeXfa4.Properties.BeginInit();
            this.Txt_BankName.Properties.BeginInit();
            this.Txt_AccountId.Properties.BeginInit();
            this.Txt_Status.Properties.BeginInit();
            this.Txt_Id.Properties.BeginInit();
            this.welftZbha.Properties.BeginInit();
            this.Txt_Phone.Properties.BeginInit();
            this.Txt_Address.Properties.BeginInit();
            this.Txt_FullName.Properties.BeginInit();
            this.Txt_ShortName.Properties.BeginInit();
            this.txtBankBranch.Properties.BeginInit();
            base.SuspendLayout();
            this.LabelControl11.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl11.Appearance.Options.UseFont = true;
            this.LabelControl11.Location = new Point(0x1f, 0xb5);
            this.LabelControl11.Name = "LabelControl11";
            this.LabelControl11.Size = new Size(0x3e, 13);
            this.LabelControl11.TabIndex = 0x15f;
            this.LabelControl11.Text = "Người li\x00ean hệ";
            this.Txt_Contactperson.EnterMoveNextControl = true;
            this.Txt_Contactperson.Location = new Point(0x80, 0xb2);
            this.Txt_Contactperson.Name = "Txt_Contactperson";
            this.Txt_Contactperson.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Contactperson.Properties.Appearance.Options.UseFont = true;
            this.Txt_Contactperson.Size = new Size(0x19f, 20);
            this.Txt_Contactperson.TabIndex = 7;
            this.LabelControl7.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl7.Appearance.Options.UseFont = true;
            this.LabelControl7.Location = new Point(0x1f, 0x133);
            this.LabelControl7.Name = "LabelControl7";
            this.LabelControl7.Size = new Size(0x23, 13);
            this.LabelControl7.TabIndex = 350;
            this.LabelControl7.Text = "Ghi ch\x00fa";
            this.Txt_Remark.EnterMoveNextControl = true;
            this.Txt_Remark.Location = new Point(0x80, 0x130);
            this.Txt_Remark.Name = "Txt_Remark";
            this.Txt_Remark.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Remark.Properties.Appearance.Options.UseFont = true;
            this.Txt_Remark.Size = new Size(0x19f, 20);
            this.Txt_Remark.TabIndex = 13;
            this.LabelControl6.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl6.Appearance.Options.UseFont = true;
            this.LabelControl6.Location = new Point(0x1f, 0x119);
            this.LabelControl6.Name = "LabelControl6";
            this.LabelControl6.Size = new Size(0x29, 13);
            this.LabelControl6.TabIndex = 0x15d;
            this.LabelControl6.Text = "Quan hệ";
            this.Cmb_CustType.EnterMoveNextControl = true;
            this.Cmb_CustType.Location = new Point(0x80, 0x116);
            this.Cmb_CustType.Name = "Cmb_CustType";
            this.Cmb_CustType.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Cmb_CustType.Properties.Appearance.Options.UseFont = true;
            this.Cmb_CustType.Properties.Buttons.AddRange(new EditorButton[] { new EditorButton(ButtonPredefines.Combo) });
            this.Cmb_CustType.Properties.Items.AddRange(new object[] { "04 | Đại l\x00fd, kh\x00e1ch mua bu\x00f4n", "05 | Nh\x00e0 cung cấp h\x00e0ng h\x00f3a", "06 | Đại l\x00fd v\x00e0 nh\x00e0 cung cấp" });
            this.Cmb_CustType.Size = new Size(0x134, 20);
            this.Cmb_CustType.TabIndex = 11;
            this.Txt_OpenDate.EnterMoveNextControl = true;
            this.Txt_OpenDate.Location = new Point(0x1ba, 0x116);
            this.Txt_OpenDate.Name = "Txt_OpenDate";
            this.Txt_OpenDate.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_OpenDate.Properties.Appearance.Options.UseFont = true;
            this.Txt_OpenDate.Properties.DisplayFormat.FormatString = "dd/MM/yyyy";
            this.Txt_OpenDate.Properties.DisplayFormat.FormatType = FormatType.DateTime;
            this.Txt_OpenDate.Properties.EditFormat.FormatString = "dd/MM/yyyy";
            this.Txt_OpenDate.Properties.EditFormat.FormatType = FormatType.DateTime;
            this.Txt_OpenDate.Properties.Mask.EditMask = "dd/MM/yyyy";
            this.Txt_OpenDate.Properties.Mask.MaskType = MaskType.DateTime;
            this.Txt_OpenDate.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_OpenDate.Size = new Size(0x65, 20);
            this.Txt_OpenDate.TabIndex = 12;
            this.GroupBox2.Location = new Point(-102, 0x58);
            this.GroupBox2.Name = "GroupBox2";
            this.GroupBox2.Size = new Size(0x2fa, 5);
            this.GroupBox2.TabIndex = 0x15b;
            this.GroupBox2.TabStop = false;
            this.LabelControl5.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl5.Appearance.Options.UseFont = true;
            this.LabelControl5.Location = new Point(0x20, 0x9b);
            this.LabelControl5.Name = "LabelControl5";
            this.LabelControl5.Size = new Size(0x12, 13);
            this.LabelControl5.TabIndex = 0x15a;
            this.LabelControl5.Text = "Fax";
            this.LabelControl10.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl10.Appearance.Options.UseFont = true;
            this.LabelControl10.Location = new Point(0x14f, 0x9b);
            this.LabelControl10.Name = "LabelControl10";
            this.LabelControl10.Size = new Size(0x35, 13);
            this.LabelControl10.TabIndex = 0x159;
            this.LabelControl10.Text = "M\x00e3 số thuế";
            this.LabelControl9.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl9.Appearance.Options.UseFont = true;
            this.LabelControl9.Location = new Point(0x1f, 0xe9);
            this.LabelControl9.Name = "LabelControl9";
            this.LabelControl9.Size = new Size(0x34, 13);
            this.LabelControl9.TabIndex = 0x158;
            this.LabelControl9.Text = "Ng\x00e2n h\x00e0ng";
            this.LabelControl8.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl8.Appearance.Options.UseFont = true;
            this.LabelControl8.Location = new Point(0x1f, 0xcf);
            this.LabelControl8.Name = "LabelControl8";
            this.LabelControl8.Size = new Size(0x3b, 13);
            this.LabelControl8.TabIndex = 0x157;
            this.LabelControl8.Text = "Số t\x00e0i khoản";
            this.ddvqeXfa4.EnterMoveNextControl = true;
            this.ddvqeXfa4.Location = new Point(0x18f, 0x98);
            this.ddvqeXfa4.Name = "Txt_VatNumber";
            this.ddvqeXfa4.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ddvqeXfa4.Properties.Appearance.Options.UseFont = true;
            this.ddvqeXfa4.Size = new Size(0x90, 20);
            this.ddvqeXfa4.TabIndex = 6;
            this.Txt_BankName.EnterMoveNextControl = true;
            this.Txt_BankName.Location = new Point(0x80, 230);
            this.Txt_BankName.Name = "Txt_BankName";
            this.Txt_BankName.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_BankName.Properties.Appearance.Options.UseFont = true;
            this.Txt_BankName.Size = new Size(0x19f, 20);
            this.Txt_BankName.TabIndex = 9;
            this.Txt_AccountId.EnterMoveNextControl = true;
            this.Txt_AccountId.Location = new Point(0x80, 0xcc);
            this.Txt_AccountId.Name = "Txt_AccountId";
            this.Txt_AccountId.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_AccountId.Properties.Appearance.Options.UseFont = true;
            this.Txt_AccountId.Size = new Size(0x19f, 20);
            this.Txt_AccountId.TabIndex = 8;
            this.LabelControl3.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl3.Appearance.Options.UseFont = true;
            this.LabelControl3.Location = new Point(0x14f, 15);
            this.LabelControl3.Name = "LabelControl3";
            this.LabelControl3.Size = new Size(0x31, 13);
            this.LabelControl3.TabIndex = 0x156;
            this.LabelControl3.Text = "Trạng th\x00e1i";
            this.LabelControl4.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl4.Appearance.Options.UseFont = true;
            this.LabelControl4.Location = new Point(0x20, 15);
            this.LabelControl4.Name = "LabelControl4";
            this.LabelControl4.Size = new Size(0x1c, 13);
            this.LabelControl4.TabIndex = 0x155;
            this.LabelControl4.Text = "M\x00e3 số";
            this.Txt_Status.EnterMoveNextControl = true;
            this.Txt_Status.Location = new Point(0x1a3, 12);
            this.Txt_Status.Name = "Txt_Status";
            this.Txt_Status.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Status.Properties.Appearance.Options.UseFont = true;
            this.Txt_Status.Size = new Size(0x7c, 20);
            this.Txt_Status.TabIndex = 340;
            this.Txt_Id.EnterMoveNextControl = true;
            this.Txt_Id.Location = new Point(0x80, 12);
            this.Txt_Id.Name = "Txt_Id";
            this.Txt_Id.Properties.Appearance.BackColor = Color.PapayaWhip;
            this.Txt_Id.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Id.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_Id.Properties.Appearance.Options.UseFont = true;
            this.Txt_Id.Properties.Mask.PlaceHolder = ' ';
            this.Txt_Id.Properties.MaxLength = 6;
            this.Txt_Id.Properties.ValidateOnEnterKey = true;
            this.Txt_Id.Size = new Size(0x7b, 20);
            this.Txt_Id.TabIndex = 0x153;
            this.Txt_Id.EditValueChanged += new EventHandler(this.Txt_Id_EditValueChanged);
            this.Txt_Id.KeyDown += new KeyEventHandler(this.Txt_Id_KeyDown);
            this.welftZbha.EnterMoveNextControl = true;
            this.welftZbha.Location = new Point(0x80, 0x98);
            this.welftZbha.Name = "Txt_Fax";
            this.welftZbha.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.welftZbha.Properties.Appearance.Options.UseFont = true;
            this.welftZbha.Size = new Size(0xb7, 20);
            this.welftZbha.TabIndex = 5;
            this.LabelControl2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl2.Appearance.Options.UseFont = true;
            this.LabelControl2.Location = new Point(0x20, 0x81);
            this.LabelControl2.Name = "LabelControl2";
            this.LabelControl2.Size = new Size(0x3e, 13);
            this.LabelControl2.TabIndex = 0x152;
            this.LabelControl2.Text = "Số điện thoại";
            this.LabelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl1.Appearance.Options.UseFont = true;
            this.LabelControl1.Location = new Point(0x20, 0x67);
            this.LabelControl1.Name = "LabelControl1";
            this.LabelControl1.Size = new Size(0x20, 13);
            this.LabelControl1.TabIndex = 0x151;
            this.LabelControl1.Text = "Địa chỉ";
            this.Txt_Phone.EnterMoveNextControl = true;
            this.Txt_Phone.Location = new Point(0x80, 0x7e);
            this.Txt_Phone.Name = "Txt_Phone";
            this.Txt_Phone.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Phone.Properties.Appearance.Options.UseFont = true;
            this.Txt_Phone.Size = new Size(0x19f, 20);
            this.Txt_Phone.TabIndex = 4;
            this.Txt_Address.EnterMoveNextControl = true;
            this.Txt_Address.Location = new Point(0x80, 100);
            this.Txt_Address.Name = "Txt_Address";
            this.Txt_Address.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Address.Properties.Appearance.Options.UseFont = true;
            this.Txt_Address.Size = new Size(0x19f, 20);
            this.Txt_Address.TabIndex = 3;
            this.LabelControl15.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl15.Appearance.Options.UseFont = true;
            this.LabelControl15.Location = new Point(0x1f, 0x43);
            this.LabelControl15.Name = "LabelControl15";
            this.LabelControl15.Size = new Size(0x36, 13);
            this.LabelControl15.TabIndex = 0x150;
            this.LabelControl15.Text = "T\x00ean đầy đủ";
            this.CwwJoLjYp.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CwwJoLjYp.Appearance.Options.UseFont = true;
            this.CwwJoLjYp.Location = new Point(0x1f, 0x29);
            this.CwwJoLjYp.Name = "LabelControl14";
            this.CwwJoLjYp.Size = new Size(0x38, 13);
            this.CwwJoLjYp.TabIndex = 0x14f;
            this.CwwJoLjYp.Text = "T\x00ean viết tắt";
            this.Txt_FullName.EnterMoveNextControl = true;
            this.Txt_FullName.Location = new Point(0x80, 0x40);
            this.Txt_FullName.Name = "Txt_FullName";
            this.Txt_FullName.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_FullName.Properties.Appearance.Options.UseFont = true;
            this.Txt_FullName.Size = new Size(0x19f, 20);
            this.Txt_FullName.TabIndex = 2;
            this.Txt_ShortName.EnterMoveNextControl = true;
            this.Txt_ShortName.Location = new Point(0x80, 0x26);
            this.Txt_ShortName.Name = "Txt_ShortName";
            this.Txt_ShortName.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_ShortName.Properties.Appearance.Options.UseFont = true;
            this.Txt_ShortName.Properties.CharacterCasing = CharacterCasing.Upper;
            this.Txt_ShortName.Size = new Size(0x19f, 20);
            this.Txt_ShortName.TabIndex = 1;
            this.groupBox1.Location = new Point(-91, 0x14f);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x2fa, 5);
            this.groupBox1.TabIndex = 0x185;
            this.groupBox1.TabStop = false;
            this.btn_Exit.Anchor = AnchorStyles.Bottom;
            this.btn_Exit.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btn_Exit.Location = new Point(480, 0x15b);
            this.btn_Exit.Name = "btn_Exit";
            this.btn_Exit.Size = new Size(0x4b, 0x17);
            this.btn_Exit.TabIndex = 0x13;
            this.btn_Exit.Text = "&Tho\x00e1t";
            this.btn_Exit.Click += new EventHandler(this.btn_Exit_Click);
            this.btn_Search.Anchor = AnchorStyles.Bottom;
            this.btn_Search.Location = new Point(0x195, 0x15b);
            this.btn_Search.Name = "btn_Search";
            this.btn_Search.Size = new Size(0x4b, 0x17);
            this.btn_Search.TabIndex = 0x12;
            this.btn_Search.Text = "T\x00ec&m";
            this.btn_Search.Click += new EventHandler(this.btn_Search_Click);
            this.btn_Edit.Anchor = AnchorStyles.Bottom;
            this.btn_Edit.Location = new Point(0xff, 0x15b);
            this.btn_Edit.Name = "btn_Edit";
            this.btn_Edit.Size = new Size(0x4b, 0x17);
            this.btn_Edit.TabIndex = 0x10;
            this.btn_Edit.Text = "&Sửa";
            this.btn_Edit.Click += new EventHandler(this.btn_Edit_Click);
            this.btn_New.Anchor = AnchorStyles.Bottom;
            this.btn_New.Location = new Point(180, 0x15b);
            this.btn_New.Name = "btn_New";
            this.btn_New.Size = new Size(0x4b, 0x17);
            this.btn_New.TabIndex = 0;
            this.btn_New.Text = "Tạ&o";
            this.btn_New.Click += new EventHandler(this.btn_New_Click);
            this.btn_Skip.Anchor = AnchorStyles.Bottom;
            this.btn_Skip.Location = new Point(0x69, 0x15b);
            this.btn_Skip.Name = "btn_Skip";
            this.btn_Skip.Size = new Size(0x4b, 0x17);
            this.btn_Skip.TabIndex = 15;
            this.btn_Skip.Text = "&Bỏ qua";
            this.btn_Skip.Click += new EventHandler(this.btn_Skip_Click);
            this.btn_Save.Anchor = AnchorStyles.Bottom;
            this.btn_Save.Location = new Point(30, 0x15b);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.Size = new Size(0x4b, 0x17);
            this.btn_Save.TabIndex = 14;
            this.btn_Save.Text = "&Lưu";
            this.btn_Save.Click += new EventHandler(this.pfeZyQnoF);
            this.btn_Delete.Anchor = AnchorStyles.Bottom;
            this.btn_Delete.Location = new Point(330, 0x15b);
            this.btn_Delete.Name = "btn_Delete";
            this.btn_Delete.Size = new Size(0x4b, 0x17);
            this.btn_Delete.TabIndex = 0x11;
            this.btn_Delete.Text = "&X\x00f3a";
            this.btn_Delete.Click += new EventHandler(this.btn_Delete_Click);
            this.labelControl12.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl12.Appearance.Options.UseFont = true;
            this.labelControl12.Location = new Point(0x1f, 0x101);
            this.labelControl12.Name = "labelControl12";
            this.labelControl12.Size = new Size(0x30, 13);
            this.labelControl12.TabIndex = 0x187;
            this.labelControl12.Text = "Chi nh\x00e1nh";
            this.txtBankBranch.EnterMoveNextControl = true;
            this.txtBankBranch.Location = new Point(0x80, 0xfe);
            this.txtBankBranch.Name = "txtBankBranch";
            this.txtBankBranch.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.txtBankBranch.Properties.Appearance.Options.UseFont = true;
            this.txtBankBranch.Size = new Size(0x19f, 20);
            this.txtBankBranch.TabIndex = 10;
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            base.CancelButton = this.btn_Exit;
            base.ClientSize = new Size(0x249, 0x17e);
            base.Controls.Add(this.labelControl12);
            base.Controls.Add(this.txtBankBranch);
            base.Controls.Add(this.btn_Delete);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.btn_Exit);
            base.Controls.Add(this.btn_Search);
            base.Controls.Add(this.btn_Edit);
            base.Controls.Add(this.btn_New);
            base.Controls.Add(this.btn_Skip);
            base.Controls.Add(this.btn_Save);
            base.Controls.Add(this.LabelControl11);
            base.Controls.Add(this.Txt_Contactperson);
            base.Controls.Add(this.LabelControl7);
            base.Controls.Add(this.Txt_Remark);
            base.Controls.Add(this.LabelControl6);
            base.Controls.Add(this.Cmb_CustType);
            base.Controls.Add(this.Txt_OpenDate);
            base.Controls.Add(this.GroupBox2);
            base.Controls.Add(this.LabelControl5);
            base.Controls.Add(this.LabelControl10);
            base.Controls.Add(this.LabelControl9);
            base.Controls.Add(this.LabelControl8);
            base.Controls.Add(this.ddvqeXfa4);
            base.Controls.Add(this.Txt_BankName);
            base.Controls.Add(this.Txt_AccountId);
            base.Controls.Add(this.LabelControl3);
            base.Controls.Add(this.LabelControl4);
            base.Controls.Add(this.Txt_Status);
            base.Controls.Add(this.Txt_Id);
            base.Controls.Add(this.welftZbha);
            base.Controls.Add(this.LabelControl2);
            base.Controls.Add(this.LabelControl1);
            base.Controls.Add(this.Txt_Phone);
            base.Controls.Add(this.Txt_Address);
            base.Controls.Add(this.LabelControl15);
            base.Controls.Add(this.CwwJoLjYp);
            base.Controls.Add(this.Txt_FullName);
            base.Controls.Add(this.Txt_ShortName);
            base.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            base.MaximizeBox = false;
            base.Name = "FrmCustomer";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmCustomer";
            base.Load += new EventHandler(this.FrmCustomer_Load);
            this.Txt_Contactperson.Properties.EndInit();
            this.Txt_Remark.Properties.EndInit();
            this.Cmb_CustType.Properties.EndInit();
            this.Txt_OpenDate.Properties.EndInit();
            this.ddvqeXfa4.Properties.EndInit();
            this.Txt_BankName.Properties.EndInit();
            this.Txt_AccountId.Properties.EndInit();
            this.Txt_Status.Properties.EndInit();
            this.Txt_Id.Properties.EndInit();
            this.welftZbha.Properties.EndInit();
            this.Txt_Phone.Properties.EndInit();
            this.Txt_Address.Properties.EndInit();
            this.Txt_FullName.Properties.EndInit();
            this.Txt_ShortName.Properties.EndInit();
            this.txtBankBranch.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
        private SimpleButton btn_Delete;
        private SimpleButton btn_Edit;
        private SimpleButton btn_Exit;
        private SimpleButton btn_New;
        private SimpleButton btn_Save;
        private SimpleButton btn_Search;
        private SimpleButton btn_Skip;
        internal ComboBoxEdit Cmb_CustType;
        internal LabelControl CwwJoLjYp;
        internal TextEdit ddvqeXfa4;
        internal GroupBox groupBox1;
        internal GroupBox GroupBox2;
        //private IContainer components;
        internal LabelControl LabelControl1;
        internal LabelControl LabelControl10;
        internal LabelControl LabelControl11;
        internal LabelControl labelControl12;
        internal LabelControl LabelControl15;
        internal LabelControl LabelControl2;
        internal LabelControl LabelControl3;
        internal LabelControl LabelControl4;
        internal LabelControl LabelControl5;
        internal LabelControl LabelControl6;
        internal LabelControl LabelControl7;
        internal LabelControl LabelControl8;
        internal LabelControl LabelControl9;
        private OleDbConnection oleDbConnection_0;
        private OleDbDataAdapter oleDbDataAdapter_0;
        private string string_0;
        private string string_1;
        internal TextEdit Txt_AccountId;
        internal TextEdit Txt_Address;
        internal TextEdit Txt_BankName;
        internal TextEdit Txt_Contactperson;
        internal TextEdit Txt_FullName;
        internal TextEdit Txt_Id;
        internal TextEdit Txt_OpenDate;
        internal TextEdit Txt_Phone;
        internal TextEdit Txt_Remark;
        internal TextEdit Txt_ShortName;
        internal TextEdit Txt_Status;
        internal TextEdit txtBankBranch;
        internal TextEdit welftZbha;

        #endregion
    }
}
