using DevExpress.Utils;
using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Controls;
using DevExpress.XtraEditors.Mask;
using System;
using System.ComponentModel;
using System.Data.OleDb;
using System.Drawing;
using System.Windows.Forms;

namespace LibraryManagement.App
{
    partial class FrmTran_1_n
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.icontainer_0 = new Container();
            this.Lbl_Today = new LabelControl();
            this.GroupBox2 = new GroupBox();
            this.groupBox3 = new GroupBox();
            this.LabelControl20 = new LabelControl();
            this.LabelControl2 = new LabelControl();
            this.ddvqeXfa4 = new TextEdit();
            this.LabelControl3 = new LabelControl();
            this.Txt_Remark = new TextEdit();
            this.LabelControl4 = new LabelControl();
            this.btn_Delete = new SimpleButton();
            this.groupBox1 = new GroupBox();
            this.btn_Exit = new SimpleButton();
            this.welftZbha = new SimpleButton();
            this.btn_Edit = new SimpleButton();
            this.btn_New = new SimpleButton();
            this.btn_Skip = new SimpleButton();
            this.btn_Save = new SimpleButton();
            this.labelControl5 = new LabelControl();
            this.CwwJoLjYp = new LabelControl();
            this.Txt_Voucher = new TextEdit();
            this.timer_0 = new Timer(this.icontainer_0);
            this.Txt_TranDate = new TextEdit();
            this.LabelControl1 = new LabelControl();
            this.labelControl6 = new LabelControl();
            this.Lbl_TranCode = new LabelControl();
            this.Lbl_TranName = new LabelControl();
            this.Txt_DbAccId1 = new TextEdit();
            this.Lbl_DbAccName1 = new LabelControl();
            this.Txt_DbAmt1 = new TextEdit();
            this.labelControl7 = new LabelControl();
            this.Lbl_CreAccName = new LabelControl();
            this.Txt_CreAccId = new TextEdit();
            this.labelControl10 = new LabelControl();
            this.Lbl_DbAccName2 = new LabelControl();
            this.Txt_DbAccId2 = new TextEdit();
            this.labelControl11 = new LabelControl();
            this.Lbl_DbAccName3 = new LabelControl();
            this.Txt_DbAccId3 = new TextEdit();
            this.labelControl13 = new LabelControl();
            this.groupBox4 = new GroupBox();
            this.groupBox5 = new GroupBox();
            this.labelControl9 = new LabelControl();
            this.Txt_DbAmt2 = new TextEdit();
            this.labelControl12 = new LabelControl();
            this.labelControl14 = new LabelControl();
            this.Txt_DbAmt3 = new TextEdit();
            this.TgwIjsrYqS = new LabelControl();
            this.labelControl16 = new LabelControl();
            this.Lbl_CreditAmt = new LabelControl();
            this.labelControl18 = new LabelControl();
            this.GroupBox2.SuspendLayout();
            this.ddvqeXfa4.Properties.BeginInit();
            this.Txt_Remark.Properties.BeginInit();
            this.Txt_Voucher.Properties.BeginInit();
            this.Txt_TranDate.Properties.BeginInit();
            this.Txt_DbAccId1.Properties.BeginInit();
            this.Txt_DbAmt1.Properties.BeginInit();
            this.Txt_CreAccId.Properties.BeginInit();
            this.Txt_DbAccId2.Properties.BeginInit();
            this.Txt_DbAccId3.Properties.BeginInit();
            this.Txt_DbAmt2.Properties.BeginInit();
            this.Txt_DbAmt3.Properties.BeginInit();
            base.SuspendLayout();
            this.Lbl_Today.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_Today.Appearance.Options.UseFont = true;
            this.Lbl_Today.Location = new Point(0x109, 0x1d);
            this.Lbl_Today.Name = "Lbl_Today";
            this.Lbl_Today.Size = new Size(0x38, 13);
            this.Lbl_Today.TabIndex = 0xa9;
            this.Lbl_Today.Text = "01/01/2008";
            this.GroupBox2.Controls.Add(this.groupBox3);
            this.GroupBox2.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.GroupBox2.Location = new Point(-94, 0x34);
            this.GroupBox2.Name = "GroupBox2";
            this.GroupBox2.Size = new Size(0x338, 5);
            this.GroupBox2.TabIndex = 0xa5;
            this.GroupBox2.TabStop = false;
            this.groupBox3.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.groupBox3.Location = new Point(0, 0);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x338, 5);
            this.groupBox3.TabIndex = 0xa6;
            this.groupBox3.TabStop = false;
            this.LabelControl20.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl20.Appearance.Options.UseFont = true;
            this.LabelControl20.Location = new Point(0xe2, 0x1d);
            this.LabelControl20.Name = "LabelControl20";
            this.LabelControl20.Size = new Size(0x20, 13);
            this.LabelControl20.TabIndex = 160;
            this.LabelControl20.Text = "Ng\x00e0y :";
            this.LabelControl2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl2.Appearance.Options.UseFont = true;
            this.LabelControl2.Location = new Point(0x17, 0x1f);
            this.LabelControl2.Name = "LabelControl2";
            this.LabelControl2.Size = new Size(0x39, 13);
            this.LabelControl2.TabIndex = 0x9f;
            this.LabelControl2.Text = "Số giao dịch";
            this.ddvqeXfa4.Location = new Point(0x74, 0x1a);
            this.ddvqeXfa4.Name = "Txt_TransNum";
            this.ddvqeXfa4.Properties.Appearance.BackColor = Color.PapayaWhip;
            this.ddvqeXfa4.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ddvqeXfa4.Properties.Appearance.Options.UseBackColor = true;
            this.ddvqeXfa4.Properties.Appearance.Options.UseFont = true;
            this.ddvqeXfa4.Properties.CharacterCasing = CharacterCasing.Upper;
            this.ddvqeXfa4.Properties.MaxLength = 12;
            this.ddvqeXfa4.Properties.ReadOnly = true;
            this.ddvqeXfa4.Size = new Size(0x66, 20);
            this.ddvqeXfa4.TabIndex = 15;
            this.ddvqeXfa4.TabStop = false;
            this.ddvqeXfa4.KeyDown += new KeyEventHandler(this.pfeZyQnoF);
            this.LabelControl3.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl3.Appearance.Options.UseFont = true;
            this.LabelControl3.Location = new Point(0x17, 0x12d);
            this.LabelControl3.Name = "LabelControl3";
            this.LabelControl3.Size = new Size(40, 13);
            this.LabelControl3.TabIndex = 0xa7;
            this.LabelControl3.Text = "Diễn giải";
            this.Txt_Remark.EnterMoveNextControl = true;
            this.Txt_Remark.Location = new Point(0x74, 0x12a);
            this.Txt_Remark.Name = "Txt_Remark";
            this.Txt_Remark.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Remark.Properties.Appearance.Options.UseFont = true;
            this.Txt_Remark.Size = new Size(0x196, 20);
            this.Txt_Remark.TabIndex = 10;
            this.LabelControl4.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl4.Appearance.Options.UseFont = true;
            this.LabelControl4.Location = new Point(0x16, 0x7c);
            this.LabelControl4.Name = "LabelControl4";
            this.LabelControl4.Size = new Size(0x1c, 13);
            this.LabelControl4.TabIndex = 0xa4;
            this.LabelControl4.Text = "Gi\x00e1 trị";
            this.btn_Delete.Anchor = AnchorStyles.Bottom;
            this.btn_Delete.Location = new Point(0x131, 0x14f);
            this.btn_Delete.Name = "btn_Delete";
            this.btn_Delete.Size = new Size(0x4b, 0x17);
            this.btn_Delete.TabIndex = 14;
            this.btn_Delete.Text = "&X\x00f3a";
            this.groupBox1.Anchor = AnchorStyles.Bottom;
            this.groupBox1.Location = new Point(-114, 0x143);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x2fa, 5);
            this.groupBox1.TabIndex = 0x18d;
            this.groupBox1.TabStop = false;
            this.btn_Exit.Anchor = AnchorStyles.Bottom;
            this.btn_Exit.DialogResult = DialogResult.Cancel;
            this.btn_Exit.Location = new Point(0x1c7, 0x14f);
            this.btn_Exit.Name = "btn_Exit";
            this.btn_Exit.Size = new Size(0x4b, 0x17);
            this.btn_Exit.TabIndex = 0x10;
            this.btn_Exit.Text = "&Tho\x00e1t";
            this.btn_Exit.Click += new EventHandler(this.btn_Exit_Click);
            this.welftZbha.Anchor = AnchorStyles.Bottom;
            this.welftZbha.Location = new Point(380, 0x14f);
            this.welftZbha.Name = "btn_Search";
            this.welftZbha.Size = new Size(0x4b, 0x17);
            this.welftZbha.TabIndex = 15;
            this.welftZbha.Text = "T\x00ec&m";
            this.welftZbha.Click += new EventHandler(this.welftZbha_Click);
            this.btn_Edit.Anchor = AnchorStyles.Bottom;
            this.btn_Edit.Location = new Point(230, 0x14f);
            this.btn_Edit.Name = "btn_Edit";
            this.btn_Edit.Size = new Size(0x4b, 0x17);
            this.btn_Edit.TabIndex = 13;
            this.btn_Edit.Text = "&Sửa";
            this.btn_Edit.Click += new EventHandler(this.btn_Edit_Click);
            this.btn_New.Anchor = AnchorStyles.Bottom;
            this.btn_New.Location = new Point(0x9b, 0x14f);
            this.btn_New.Name = "btn_New";
            this.btn_New.Size = new Size(0x4b, 0x17);
            this.btn_New.TabIndex = 0;
            this.btn_New.Text = "Tạ&o";
            this.btn_New.Click += new EventHandler(this.btn_New_Click);
            this.btn_Skip.Anchor = AnchorStyles.Bottom;
            this.btn_Skip.Location = new Point(80, 0x14f);
            this.btn_Skip.Name = "btn_Skip";
            this.btn_Skip.Size = new Size(0x4b, 0x17);
            this.btn_Skip.TabIndex = 12;
            this.btn_Skip.Text = "&Bỏ qua";
            this.btn_Skip.Click += new EventHandler(this.btn_Skip_Click);
            this.btn_Save.Anchor = AnchorStyles.Bottom;
            this.btn_Save.Location = new Point(5, 0x14f);
            this.btn_Save.Name = "btn_Save";
            this.btn_Save.Size = new Size(0x4b, 0x17);
            this.btn_Save.TabIndex = 11;
            this.btn_Save.Text = "&Lưu";
            this.btn_Save.Click += new EventHandler(this.btn_Save_Click);
            this.labelControl5.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl5.Appearance.Options.UseFont = true;
            this.labelControl5.Location = new Point(0x17, 100);
            this.labelControl5.Name = "labelControl5";
            this.labelControl5.Size = new Size(0x57, 13);
            this.labelControl5.TabIndex = 400;
            this.labelControl5.Text = "T\x00e0i khoản ghi nợ 1";
            this.CwwJoLjYp.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.CwwJoLjYp.Appearance.Options.UseFont = true;
            this.CwwJoLjYp.Location = new Point(0x132, 0x42);
            this.CwwJoLjYp.Name = "labelControl8";
            this.CwwJoLjYp.Size = new Size(0x3b, 13);
            this.CwwJoLjYp.TabIndex = 0x192;
            this.CwwJoLjYp.Text = "Số chứng từ";
            this.Txt_Voucher.EnterMoveNextControl = true;
            this.Txt_Voucher.Location = new Point(0x17e, 0x3f);
            this.Txt_Voucher.Name = "Txt_Voucher";
            this.Txt_Voucher.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_Voucher.Properties.Appearance.Options.UseFont = true;
            this.Txt_Voucher.Properties.MaxLength = 10;
            this.Txt_Voucher.Size = new Size(140, 20);
            this.Txt_Voucher.TabIndex = 2;
            this.timer_0.Enabled = true;
            this.timer_0.Interval = 200;
            this.timer_0.Tick += new EventHandler(this.timer_0_Tick);
            this.Txt_TranDate.EditValue = new DateTime(0x7d8, 4, 0x18, 13, 0x34, 0x2b, 0x1a5);
            this.Txt_TranDate.EnterMoveNextControl = true;
            this.Txt_TranDate.Location = new Point(0x74, 0x3f);
            this.Txt_TranDate.Name = "Txt_TranDate";
            this.Txt_TranDate.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_TranDate.Properties.Appearance.Options.UseFont = true;
            this.Txt_TranDate.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_TranDate.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_TranDate.Properties.DisplayFormat.FormatString = "dd/MM/yyyy";
            this.Txt_TranDate.Properties.DisplayFormat.FormatType = FormatType.DateTime;
            this.Txt_TranDate.Properties.EditFormat.FormatString = "dd/MM/yyyy";
            this.Txt_TranDate.Properties.EditFormat.FormatType = FormatType.DateTime;
            this.Txt_TranDate.Properties.Mask.EditMask = "dd/MM/yyyy";
            this.Txt_TranDate.Properties.Mask.MaskType = MaskType.DateTime;
            this.Txt_TranDate.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_TranDate.Size = new Size(0x4f, 20);
            this.Txt_TranDate.TabIndex = 1;
            this.LabelControl1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.LabelControl1.Appearance.Options.UseFont = true;
            this.LabelControl1.Location = new Point(0x16, 0x42);
            this.LabelControl1.Name = "LabelControl1";
            this.LabelControl1.Size = new Size(0x41, 13);
            this.LabelControl1.TabIndex = 0x194;
            this.LabelControl1.Text = "Ng\x00e0y hiệu lực";
            this.labelControl6.Location = new Point(0x16, 5);
            this.labelControl6.Name = "labelControl6";
            this.labelControl6.Size = new Size(0x40, 13);
            this.labelControl6.TabIndex = 450;
            this.labelControl6.Text = "Loại giao dịch";
            this.Lbl_TranCode.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_TranCode.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_TranCode.Appearance.BorderColor = Color.White;
            this.Lbl_TranCode.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_TranCode.Appearance.ForeColor = Color.Black;
            this.Lbl_TranCode.Appearance.Options.UseBackColor = true;
            this.Lbl_TranCode.Appearance.Options.UseBorderColor = true;
            this.Lbl_TranCode.Appearance.Options.UseFont = true;
            this.Lbl_TranCode.Appearance.Options.UseForeColor = true;
            this.Lbl_TranCode.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_TranCode.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_TranCode.Location = new Point(0x74, 5);
            this.Lbl_TranCode.Name = "Lbl_TranCode";
            this.Lbl_TranCode.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_TranCode.Size = new Size(0x21, 15);
            this.Lbl_TranCode.TabIndex = 0x1c1;
            this.Lbl_TranCode.TextChanged += new EventHandler(this.Lbl_TranCode_TextChanged);
            this.Lbl_TranName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_TranName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_TranName.Appearance.BorderColor = Color.White;
            this.Lbl_TranName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_TranName.Appearance.ForeColor = Color.Black;
            this.Lbl_TranName.Appearance.Options.UseBackColor = true;
            this.Lbl_TranName.Appearance.Options.UseBorderColor = true;
            this.Lbl_TranName.Appearance.Options.UseFont = true;
            this.Lbl_TranName.Appearance.Options.UseForeColor = true;
            this.Lbl_TranName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_TranName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_TranName.Location = new Point(0x9b, 5);
            this.Lbl_TranName.Name = "Lbl_TranName";
            this.Lbl_TranName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_TranName.Size = new Size(0x16f, 15);
            this.Lbl_TranName.TabIndex = 0x1c3;
            this.Txt_DbAccId1.EnterMoveNextControl = true;
            this.Txt_DbAccId1.Location = new Point(0x74, 0x61);
            this.Txt_DbAccId1.Name = "Txt_DbAccId1";
            this.Txt_DbAccId1.Properties.Appearance.BackColor = Color.Transparent;
            this.Txt_DbAccId1.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_DbAccId1.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_DbAccId1.Properties.Appearance.Options.UseFont = true;
            this.Txt_DbAccId1.Properties.Mask.EditMask = "####-#-####";
            this.Txt_DbAccId1.Properties.Mask.MaskType = MaskType.Simple;
            this.Txt_DbAccId1.Properties.Mask.PlaceHolder = ' ';
            this.Txt_DbAccId1.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DbAccId1.Size = new Size(0x72, 20);
            this.Txt_DbAccId1.TabIndex = 3;
            this.Txt_DbAccId1.EditValueChanged += new EventHandler(this.Txt_DbAccId1_EditValueChanged);
            this.Txt_DbAccId1.KeyDown += new KeyEventHandler(this.Txt_DbAccId1_KeyDown);
            this.Lbl_DbAccName1.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_DbAccName1.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_DbAccName1.Appearance.BorderColor = Color.White;
            this.Lbl_DbAccName1.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_DbAccName1.Appearance.ForeColor = Color.Black;
            this.Lbl_DbAccName1.Appearance.Options.UseBackColor = true;
            this.Lbl_DbAccName1.Appearance.Options.UseBorderColor = true;
            this.Lbl_DbAccName1.Appearance.Options.UseFont = true;
            this.Lbl_DbAccName1.Appearance.Options.UseForeColor = true;
            this.Lbl_DbAccName1.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_DbAccName1.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_DbAccName1.Location = new Point(0xec, 0x65);
            this.Lbl_DbAccName1.Name = "Lbl_DbAccName1";
            this.Lbl_DbAccName1.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_DbAccName1.Size = new Size(0x11e, 15);
            this.Lbl_DbAccName1.TabIndex = 0x1c5;
            this.Txt_DbAmt1.EditValue = "0";
            this.Txt_DbAmt1.EnterMoveNextControl = true;
            this.Txt_DbAmt1.Location = new Point(0x74, 0x79);
            this.Txt_DbAmt1.Name = "Txt_DbAmt1";
            this.Txt_DbAmt1.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_DbAmt1.Properties.Appearance.Options.UseFont = true;
            this.Txt_DbAmt1.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_DbAmt1.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_DbAmt1.Properties.DisplayFormat.FormatString = "n2";
            this.Txt_DbAmt1.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_DbAmt1.Properties.EditFormat.FormatString = "n2";
            this.Txt_DbAmt1.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_DbAmt1.Properties.Mask.EditMask = "n2";
            this.Txt_DbAmt1.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_DbAmt1.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DbAmt1.Size = new Size(0x72, 20);
            this.Txt_DbAmt1.TabIndex = 4;
            this.labelControl7.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl7.Appearance.Options.UseFont = true;
            this.labelControl7.Location = new Point(0xec, 0x7c);
            this.labelControl7.Name = "labelControl7";
            this.labelControl7.Size = new Size(20, 13);
            this.labelControl7.TabIndex = 0x1c6;
            this.labelControl7.Text = "VND";
            this.Lbl_CreAccName.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_CreAccName.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_CreAccName.Appearance.BorderColor = Color.White;
            this.Lbl_CreAccName.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_CreAccName.Appearance.ForeColor = Color.Black;
            this.Lbl_CreAccName.Appearance.Options.UseBackColor = true;
            this.Lbl_CreAccName.Appearance.Options.UseBorderColor = true;
            this.Lbl_CreAccName.Appearance.Options.UseFont = true;
            this.Lbl_CreAccName.Appearance.Options.UseForeColor = true;
            this.Lbl_CreAccName.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_CreAccName.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_CreAccName.Location = new Point(0xec, 0x115);
            this.Lbl_CreAccName.Name = "Lbl_CreAccName";
            this.Lbl_CreAccName.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_CreAccName.Size = new Size(0x11e, 15);
            this.Lbl_CreAccName.TabIndex = 0x1c9;
            this.Txt_CreAccId.EnterMoveNextControl = true;
            this.Txt_CreAccId.Location = new Point(0x74, 0x111);
            this.Txt_CreAccId.Name = "Txt_CreAccId";
            this.Txt_CreAccId.Properties.Appearance.BackColor = Color.Transparent;
            this.Txt_CreAccId.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_CreAccId.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_CreAccId.Properties.Appearance.Options.UseFont = true;
            this.Txt_CreAccId.Properties.Mask.EditMask = "####-#-####";
            this.Txt_CreAccId.Properties.Mask.MaskType = MaskType.Simple;
            this.Txt_CreAccId.Properties.Mask.PlaceHolder = ' ';
            this.Txt_CreAccId.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_CreAccId.Size = new Size(0x72, 20);
            this.Txt_CreAccId.TabIndex = 9;
            this.Txt_CreAccId.EditValueChanged += new EventHandler(this.Txt_CreAccId_EditValueChanged);
            this.Txt_CreAccId.KeyDown += new KeyEventHandler(this.Txt_CreAccId_KeyDown);
            this.labelControl10.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl10.Appearance.Options.UseFont = true;
            this.labelControl10.Location = new Point(0x17, 0x114);
            this.labelControl10.Name = "labelControl10";
            this.labelControl10.Size = new Size(0x4d, 13);
            this.labelControl10.TabIndex = 0x1c8;
            this.labelControl10.Text = "T\x00e0i khoản ghi c\x00f3";
            this.Lbl_DbAccName2.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_DbAccName2.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_DbAccName2.Appearance.BorderColor = Color.White;
            this.Lbl_DbAccName2.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_DbAccName2.Appearance.ForeColor = Color.Black;
            this.Lbl_DbAccName2.Appearance.Options.UseBackColor = true;
            this.Lbl_DbAccName2.Appearance.Options.UseBorderColor = true;
            this.Lbl_DbAccName2.Appearance.Options.UseFont = true;
            this.Lbl_DbAccName2.Appearance.Options.UseForeColor = true;
            this.Lbl_DbAccName2.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_DbAccName2.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_DbAccName2.Location = new Point(0xec, 0x98);
            this.Lbl_DbAccName2.Name = "Lbl_DbAccName2";
            this.Lbl_DbAccName2.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_DbAccName2.Size = new Size(0x11e, 15);
            this.Lbl_DbAccName2.TabIndex = 460;
            this.Txt_DbAccId2.EnterMoveNextControl = true;
            this.Txt_DbAccId2.Location = new Point(0x74, 0x93);
            this.Txt_DbAccId2.Name = "Txt_DbAccId2";
            this.Txt_DbAccId2.Properties.Appearance.BackColor = Color.Transparent;
            this.Txt_DbAccId2.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_DbAccId2.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_DbAccId2.Properties.Appearance.Options.UseFont = true;
            this.Txt_DbAccId2.Properties.Mask.EditMask = "####-#-####";
            this.Txt_DbAccId2.Properties.Mask.MaskType = MaskType.Simple;
            this.Txt_DbAccId2.Properties.Mask.PlaceHolder = ' ';
            this.Txt_DbAccId2.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DbAccId2.Size = new Size(0x72, 20);
            this.Txt_DbAccId2.TabIndex = 5;
            this.Txt_DbAccId2.EditValueChanged += new EventHandler(this.Txt_DbAccId2_EditValueChanged);
            this.Txt_DbAccId2.KeyDown += new KeyEventHandler(this.Txt_DbAccId2_KeyDown);
            this.labelControl11.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl11.Appearance.Options.UseFont = true;
            this.labelControl11.Location = new Point(0x16, 150);
            this.labelControl11.Name = "labelControl11";
            this.labelControl11.Size = new Size(0x57, 13);
            this.labelControl11.TabIndex = 0x1cb;
            this.labelControl11.Text = "T\x00e0i khoản ghi nợ 2";
            this.Lbl_DbAccName3.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_DbAccName3.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_DbAccName3.Appearance.BorderColor = Color.White;
            this.Lbl_DbAccName3.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_DbAccName3.Appearance.ForeColor = Color.Black;
            this.Lbl_DbAccName3.Appearance.Options.UseBackColor = true;
            this.Lbl_DbAccName3.Appearance.Options.UseBorderColor = true;
            this.Lbl_DbAccName3.Appearance.Options.UseFont = true;
            this.Lbl_DbAccName3.Appearance.Options.UseForeColor = true;
            this.Lbl_DbAccName3.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_DbAccName3.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_DbAccName3.Location = new Point(0xec, 200);
            this.Lbl_DbAccName3.Name = "Lbl_DbAccName3";
            this.Lbl_DbAccName3.Padding = new Padding(3, 0, 0, 0);
            this.Lbl_DbAccName3.Size = new Size(0x11e, 15);
            this.Lbl_DbAccName3.TabIndex = 0x1cf;
            this.Txt_DbAccId3.EnterMoveNextControl = true;
            this.Txt_DbAccId3.Location = new Point(0x74, 0xc3);
            this.Txt_DbAccId3.Name = "Txt_DbAccId3";
            this.Txt_DbAccId3.Properties.Appearance.BackColor = Color.Transparent;
            this.Txt_DbAccId3.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Txt_DbAccId3.Properties.Appearance.Options.UseBackColor = true;
            this.Txt_DbAccId3.Properties.Appearance.Options.UseFont = true;
            this.Txt_DbAccId3.Properties.Mask.EditMask = "####-#-####";
            this.Txt_DbAccId3.Properties.Mask.MaskType = MaskType.Simple;
            this.Txt_DbAccId3.Properties.Mask.PlaceHolder = ' ';
            this.Txt_DbAccId3.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DbAccId3.Size = new Size(0x72, 20);
            this.Txt_DbAccId3.TabIndex = 7;
            this.Txt_DbAccId3.EditValueChanged += new EventHandler(this.Txt_DbAccId3_EditValueChanged);
            this.Txt_DbAccId3.KeyDown += new KeyEventHandler(this.Txt_DbAccId3_KeyDown);
            this.labelControl13.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl13.Appearance.Options.UseFont = true;
            this.labelControl13.Location = new Point(0x17, 0xc6);
            this.labelControl13.Name = "labelControl13";
            this.labelControl13.Size = new Size(0x57, 13);
            this.labelControl13.TabIndex = 0x1ce;
            this.labelControl13.Text = "T\x00e0i khoản ghi nợ 3";
            this.groupBox4.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.groupBox4.Location = new Point(-145, 0x58);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(0x338, 5);
            this.groupBox4.TabIndex = 0x1d0;
            this.groupBox4.TabStop = false;
            this.groupBox5.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.groupBox5.Location = new Point(-145, 0xf3);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(0x338, 5);
            this.groupBox5.TabIndex = 0x1d1;
            this.groupBox5.TabStop = false;
            this.labelControl9.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl9.Appearance.Options.UseFont = true;
            this.labelControl9.Location = new Point(0xec, 0xae);
            this.labelControl9.Name = "labelControl9";
            this.labelControl9.Size = new Size(20, 13);
            this.labelControl9.TabIndex = 0x1d4;
            this.labelControl9.Text = "VND";
            this.Txt_DbAmt2.EditValue = "0";
            this.Txt_DbAmt2.EnterMoveNextControl = true;
            this.Txt_DbAmt2.Location = new Point(0x74, 0xab);
            this.Txt_DbAmt2.Name = "Txt_DbAmt2";
            this.Txt_DbAmt2.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_DbAmt2.Properties.Appearance.Options.UseFont = true;
            this.Txt_DbAmt2.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_DbAmt2.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_DbAmt2.Properties.DisplayFormat.FormatString = "n2";
            this.Txt_DbAmt2.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_DbAmt2.Properties.EditFormat.FormatString = "n2";
            this.Txt_DbAmt2.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_DbAmt2.Properties.Mask.EditMask = "n2";
            this.Txt_DbAmt2.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_DbAmt2.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DbAmt2.Size = new Size(0x72, 20);
            this.Txt_DbAmt2.TabIndex = 6;
            this.Txt_DbAmt2.EditValueChanged += new EventHandler(this.Txt_DbAmt2_EditValueChanged);
            this.labelControl12.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl12.Appearance.Options.UseFont = true;
            this.labelControl12.Location = new Point(0x16, 0xae);
            this.labelControl12.Name = "labelControl12";
            this.labelControl12.Size = new Size(0x1c, 13);
            this.labelControl12.TabIndex = 0x1d3;
            this.labelControl12.Text = "Gi\x00e1 trị";
            this.labelControl14.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl14.Appearance.Options.UseFont = true;
            this.labelControl14.Location = new Point(0xec, 0xe0);
            this.labelControl14.Name = "labelControl14";
            this.labelControl14.Size = new Size(20, 13);
            this.labelControl14.TabIndex = 0x1d7;
            this.labelControl14.Text = "VND";
            this.Txt_DbAmt3.EditValue = "0";
            this.Txt_DbAmt3.EnterMoveNextControl = true;
            this.Txt_DbAmt3.Location = new Point(0x74, 0xdd);
            this.Txt_DbAmt3.Name = "Txt_DbAmt3";
            this.Txt_DbAmt3.Properties.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_DbAmt3.Properties.Appearance.Options.UseFont = true;
            this.Txt_DbAmt3.Properties.Appearance.Options.UseTextOptions = true;
            this.Txt_DbAmt3.Properties.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Txt_DbAmt3.Properties.DisplayFormat.FormatString = "n2";
            this.Txt_DbAmt3.Properties.DisplayFormat.FormatType = FormatType.Numeric;
            this.Txt_DbAmt3.Properties.EditFormat.FormatString = "n2";
            this.Txt_DbAmt3.Properties.EditFormat.FormatType = FormatType.Numeric;
            this.Txt_DbAmt3.Properties.Mask.EditMask = "n2";
            this.Txt_DbAmt3.Properties.Mask.MaskType = MaskType.Numeric;
            this.Txt_DbAmt3.Properties.Mask.UseMaskAsDisplayFormat = true;
            this.Txt_DbAmt3.Size = new Size(0x72, 20);
            this.Txt_DbAmt3.TabIndex = 8;
            this.TgwIjsrYqS.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.TgwIjsrYqS.Appearance.Options.UseFont = true;
            this.TgwIjsrYqS.Location = new Point(0x16, 0xe0);
            this.TgwIjsrYqS.Name = "labelControl15";
            this.TgwIjsrYqS.Size = new Size(0x1c, 13);
            this.TgwIjsrYqS.TabIndex = 470;
            this.TgwIjsrYqS.Text = "Gi\x00e1 trị";
            this.labelControl16.Location = new Point(0x16, 0xfc);
            this.labelControl16.Name = "labelControl16";
            this.labelControl16.Size = new Size(0x3b, 13);
            this.labelControl16.TabIndex = 0x1d9;
            this.labelControl16.Text = "Gi\x00e1 trị ghi c\x00f3";
            this.Lbl_CreditAmt.Appearance.BackColor = Color.MediumTurquoise;
            this.Lbl_CreditAmt.Appearance.BackColor2 = Color.PaleTurquoise;
            this.Lbl_CreditAmt.Appearance.BorderColor = Color.White;
            this.Lbl_CreditAmt.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Lbl_CreditAmt.Appearance.ForeColor = Color.Black;
            this.Lbl_CreditAmt.Appearance.Options.UseBackColor = true;
            this.Lbl_CreditAmt.Appearance.Options.UseBorderColor = true;
            this.Lbl_CreditAmt.Appearance.Options.UseFont = true;
            this.Lbl_CreditAmt.Appearance.Options.UseForeColor = true;
            this.Lbl_CreditAmt.Appearance.Options.UseTextOptions = true;
            this.Lbl_CreditAmt.Appearance.TextOptions.HAlignment = HorzAlignment.Far;
            this.Lbl_CreditAmt.AutoSizeMode = LabelAutoSizeMode.None;
            this.Lbl_CreditAmt.BorderStyle = BorderStyles.UltraFlat;
            this.Lbl_CreditAmt.Location = new Point(0x74, 0xfc);
            this.Lbl_CreditAmt.Name = "Lbl_CreditAmt";
            this.Lbl_CreditAmt.Padding = new Padding(0, 0, 3, 0);
            this.Lbl_CreditAmt.Size = new Size(0x72, 15);
            this.Lbl_CreditAmt.TabIndex = 0x1d8;
            this.labelControl18.Appearance.Font = new Font("Tahoma", 8.25f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.labelControl18.Appearance.Options.UseFont = true;
            this.labelControl18.Location = new Point(0xee, 0xfd);
            this.labelControl18.Name = "labelControl18";
            this.labelControl18.Size = new Size(20, 13);
            this.labelControl18.TabIndex = 0x1da;
            this.labelControl18.Text = "VND";
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            base.CancelButton = this.btn_Exit;
            base.ClientSize = new Size(0x216, 0x171);
            base.Controls.Add(this.labelControl18);
            base.Controls.Add(this.labelControl16);
            base.Controls.Add(this.Lbl_CreditAmt);
            base.Controls.Add(this.labelControl14);
            base.Controls.Add(this.Txt_DbAmt3);
            base.Controls.Add(this.TgwIjsrYqS);
            base.Controls.Add(this.labelControl9);
            base.Controls.Add(this.Txt_DbAmt2);
            base.Controls.Add(this.labelControl12);
            base.Controls.Add(this.groupBox5);
            base.Controls.Add(this.groupBox4);
            base.Controls.Add(this.Lbl_DbAccName3);
            base.Controls.Add(this.Txt_DbAccId3);
            base.Controls.Add(this.labelControl13);
            base.Controls.Add(this.Lbl_DbAccName2);
            base.Controls.Add(this.Txt_DbAccId2);
            base.Controls.Add(this.labelControl11);
            base.Controls.Add(this.Lbl_CreAccName);
            base.Controls.Add(this.Txt_CreAccId);
            base.Controls.Add(this.labelControl10);
            base.Controls.Add(this.labelControl7);
            base.Controls.Add(this.Txt_DbAmt1);
            base.Controls.Add(this.Lbl_DbAccName1);
            base.Controls.Add(this.Txt_DbAccId1);
            base.Controls.Add(this.Lbl_TranName);
            base.Controls.Add(this.labelControl6);
            base.Controls.Add(this.Lbl_TranCode);
            base.Controls.Add(this.Txt_TranDate);
            base.Controls.Add(this.LabelControl1);
            base.Controls.Add(this.CwwJoLjYp);
            base.Controls.Add(this.Txt_Voucher);
            base.Controls.Add(this.labelControl5);
            base.Controls.Add(this.btn_Delete);
            base.Controls.Add(this.groupBox1);
            base.Controls.Add(this.btn_Exit);
            base.Controls.Add(this.welftZbha);
            base.Controls.Add(this.btn_Edit);
            base.Controls.Add(this.btn_New);
            base.Controls.Add(this.btn_Skip);
            base.Controls.Add(this.btn_Save);
            base.Controls.Add(this.Lbl_Today);
            base.Controls.Add(this.GroupBox2);
            base.Controls.Add(this.LabelControl20);
            base.Controls.Add(this.LabelControl2);
            base.Controls.Add(this.ddvqeXfa4);
            base.Controls.Add(this.LabelControl3);
            base.Controls.Add(this.Txt_Remark);
            base.Controls.Add(this.LabelControl4);
            base.FormBorderStyle = FormBorderStyle.FixedSingle;
            base.MaximizeBox = false;
            base.Name = "FrmTran_1_n";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "Giao dịch một c\x00f3 nhiều nợ";
            base.Load += new EventHandler(this.FrmTran_1_n_Load);
            this.GroupBox2.ResumeLayout(false);
            this.ddvqeXfa4.Properties.EndInit();
            this.Txt_Remark.Properties.EndInit();
            this.Txt_Voucher.Properties.EndInit();
            this.Txt_TranDate.Properties.EndInit();
            this.Txt_DbAccId1.Properties.EndInit();
            this.Txt_DbAmt1.Properties.EndInit();
            this.Txt_CreAccId.Properties.EndInit();
            this.Txt_DbAccId2.Properties.EndInit();
            this.Txt_DbAccId3.Properties.EndInit();
            this.Txt_DbAmt2.Properties.EndInit();
            this.Txt_DbAmt3.Properties.EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
        private SimpleButton btn_Delete;
        private SimpleButton btn_Edit;
        private SimpleButton btn_Exit;
        private SimpleButton btn_New;
        private SimpleButton btn_Save;
        private SimpleButton btn_Skip;
        internal LabelControl CwwJoLjYp;
        internal TextEdit ddvqeXfa4;
        internal GroupBox groupBox1;
        internal GroupBox GroupBox2;
        internal GroupBox groupBox3;
        internal GroupBox groupBox4;
        internal GroupBox groupBox5;
        private IContainer icontainer_0;
        internal LabelControl LabelControl1;
        internal LabelControl labelControl10;
        internal LabelControl labelControl11;
        internal LabelControl labelControl12;
        internal LabelControl labelControl13;
        internal LabelControl labelControl14;
        private LabelControl labelControl16;
        internal LabelControl labelControl18;
        internal LabelControl LabelControl2;
        internal LabelControl LabelControl20;
        internal LabelControl LabelControl3;
        internal LabelControl LabelControl4;
        internal LabelControl labelControl5;
        private LabelControl labelControl6;
        internal LabelControl labelControl7;
        internal LabelControl labelControl9;
        internal LabelControl Lbl_CreAccName;
        internal LabelControl Lbl_CreditAmt;
        internal LabelControl Lbl_DbAccName1;
        internal LabelControl Lbl_DbAccName2;
        internal LabelControl Lbl_DbAccName3;
        internal LabelControl Lbl_Today;
        internal LabelControl Lbl_TranCode;
        internal LabelControl Lbl_TranName;
        private OleDbConnection oleDbConnection_0;
        private OleDbDataAdapter oleDbDataAdapter_0;
        private string string_0;
        private string string_1;
        internal LabelControl TgwIjsrYqS;
        private Timer timer_0;
        private TextEdit Txt_CreAccId;
        private TextEdit Txt_DbAccId1;
        private TextEdit Txt_DbAccId2;
        private TextEdit Txt_DbAccId3;
        internal TextEdit Txt_DbAmt1;
        internal TextEdit Txt_DbAmt2;
        internal TextEdit Txt_DbAmt3;
        internal TextEdit Txt_Remark;
        internal TextEdit Txt_TranDate;
        internal TextEdit Txt_Voucher;
        private SimpleButton welftZbha;

        #endregion

    }
}