
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file BookAttr.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using LibraryManagement.Domain.Validation;
#endregion

namespace LibraryManagement.Domain
{
	///<summary>
	/// An object representation of the 'tblBookAttr' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class BookAttrBase : EntityBase, IBookAttr, IEntityId<BookAttrKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private BookAttrEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private BookAttrEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private BookAttrEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<BookAttr> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BookAttrEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event BookAttrEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="BookAttrBase"/> instance.
		///</summary>
		public BookAttrBase()
		{
			this.entityData = new BookAttrEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="BookAttrBase"/> instance.
		///</summary>
		///<param name="_goodsId"></param>
		///<param name="_author"></param>
		///<param name="_publish"></param>
		///<param name="_translator"></param>
		///<param name="_formType"></param>
		///<param name="_language"></param>
		///<param name="_plMonth"></param>
		///<param name="_plYear"></param>
		///<param name="_dimension"></param>
		///<param name="_weight"></param>
		///<param name="_pages"></param>
		///<param name="_introinfo"></param>
		public BookAttrBase(System.String _goodsId, System.String _author, System.String _publish, 
			System.String _translator, System.Int32 _formType, System.Int32 _language, System.Int32 _plMonth, 
			System.Int32 _plYear, System.String _dimension, System.Int32 _weight, System.Int32 _pages, 
			System.String _introinfo)
		{
			this.entityData = new BookAttrEntityData();
			this.backupData = null;

			this.GoodsId = _goodsId;
			this.Author = _author;
			this.Publish = _publish;
			this.Translator = _translator;
			this.FormType = _formType;
			this.Language = _language;
			this.PlMonth = _plMonth;
			this.PlYear = _plYear;
			this.Dimension = _dimension;
			this.Weight = _weight;
			this.Pages = _pages;
			this.Introinfo = _introinfo;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="BookAttr"/> instance.
		///</summary>
		///<param name="_goodsId"></param>
		///<param name="_author"></param>
		///<param name="_publish"></param>
		///<param name="_translator"></param>
		///<param name="_formType"></param>
		///<param name="_language"></param>
		///<param name="_plMonth"></param>
		///<param name="_plYear"></param>
		///<param name="_dimension"></param>
		///<param name="_weight"></param>
		///<param name="_pages"></param>
		///<param name="_introinfo"></param>
		public static BookAttr CreateBookAttr(System.String _goodsId, System.String _author, System.String _publish, 
			System.String _translator, System.Int32 _formType, System.Int32 _language, System.Int32 _plMonth, 
			System.Int32 _plYear, System.String _dimension, System.Int32 _weight, System.Int32 _pages, 
			System.String _introinfo)
		{
			BookAttr newBookAttr = new BookAttr();
			newBookAttr.GoodsId = _goodsId;
			newBookAttr.Author = _author;
			newBookAttr.Publish = _publish;
			newBookAttr.Translator = _translator;
			newBookAttr.FormType = _formType;
			newBookAttr.Language = _language;
			newBookAttr.PlMonth = _plMonth;
			newBookAttr.PlYear = _plYear;
			newBookAttr.Dimension = _dimension;
			newBookAttr.Weight = _weight;
			newBookAttr.Pages = _pages;
			newBookAttr.Introinfo = _introinfo;
			return newBookAttr;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the GoodsId property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 6)]
		public virtual System.String GoodsId
		{
			get
			{
				return this.entityData.GoodsId; 
			}
			
			set
			{
				if (this.entityData.GoodsId == value)
					return;
				
                OnPropertyChanging("GoodsId");                    
				OnColumnChanging(BookAttrColumn.GoodsId, this.entityData.GoodsId);
				this.entityData.GoodsId = value;
				this.EntityId.GoodsId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.GoodsId, this.entityData.GoodsId);
				OnPropertyChanged("GoodsId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the goods_id property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the goods_id property.</remarks>
		/// <value>This type is nchar</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalGoodsId
		{
			get { return this.entityData.OriginalGoodsId; }
			set { this.entityData.OriginalGoodsId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the Author property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 200)]
		public virtual System.String Author
		{
			get
			{
				return this.entityData.Author; 
			}
			
			set
			{
				if (this.entityData.Author == value)
					return;
				
                OnPropertyChanging("Author");                    
				OnColumnChanging(BookAttrColumn.Author, this.entityData.Author);
				this.entityData.Author = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.Author, this.entityData.Author);
				OnPropertyChanged("Author");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Publish property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 200)]
		public virtual System.String Publish
		{
			get
			{
				return this.entityData.Publish; 
			}
			
			set
			{
				if (this.entityData.Publish == value)
					return;
				
                OnPropertyChanging("Publish");                    
				OnColumnChanging(BookAttrColumn.Publish, this.entityData.Publish);
				this.entityData.Publish = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.Publish, this.entityData.Publish);
				OnPropertyChanged("Publish");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Translator property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 200)]
		public virtual System.String Translator
		{
			get
			{
				return this.entityData.Translator; 
			}
			
			set
			{
				if (this.entityData.Translator == value)
					return;
				
                OnPropertyChanging("Translator");                    
				OnColumnChanging(BookAttrColumn.Translator, this.entityData.Translator);
				this.entityData.Translator = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.Translator, this.entityData.Translator);
				OnPropertyChanged("Translator");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FormType property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 FormType
		{
			get
			{
				return this.entityData.FormType; 
			}
			
			set
			{
				if (this.entityData.FormType == value)
					return;
				
                OnPropertyChanging("FormType");                    
				OnColumnChanging(BookAttrColumn.FormType, this.entityData.FormType);
				this.entityData.FormType = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.FormType, this.entityData.FormType);
				OnPropertyChanged("FormType");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Language property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Language
		{
			get
			{
				return this.entityData.Language; 
			}
			
			set
			{
				if (this.entityData.Language == value)
					return;
				
                OnPropertyChanging("Language");                    
				OnColumnChanging(BookAttrColumn.Language, this.entityData.Language);
				this.entityData.Language = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.Language, this.entityData.Language);
				OnPropertyChanged("Language");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PlMonth property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 PlMonth
		{
			get
			{
				return this.entityData.PlMonth; 
			}
			
			set
			{
				if (this.entityData.PlMonth == value)
					return;
				
                OnPropertyChanging("PlMonth");                    
				OnColumnChanging(BookAttrColumn.PlMonth, this.entityData.PlMonth);
				this.entityData.PlMonth = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.PlMonth, this.entityData.PlMonth);
				OnPropertyChanged("PlMonth");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the PlYear property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 PlYear
		{
			get
			{
				return this.entityData.PlYear; 
			}
			
			set
			{
				if (this.entityData.PlYear == value)
					return;
				
                OnPropertyChanging("PlYear");                    
				OnColumnChanging(BookAttrColumn.PlYear, this.entityData.PlYear);
				this.entityData.PlYear = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.PlYear, this.entityData.PlYear);
				OnPropertyChanged("PlYear");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Dimension property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 100)]
		public virtual System.String Dimension
		{
			get
			{
				return this.entityData.Dimension; 
			}
			
			set
			{
				if (this.entityData.Dimension == value)
					return;
				
                OnPropertyChanging("Dimension");                    
				OnColumnChanging(BookAttrColumn.Dimension, this.entityData.Dimension);
				this.entityData.Dimension = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.Dimension, this.entityData.Dimension);
				OnPropertyChanged("Dimension");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Weight property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Weight
		{
			get
			{
				return this.entityData.Weight; 
			}
			
			set
			{
				if (this.entityData.Weight == value)
					return;
				
                OnPropertyChanging("Weight");                    
				OnColumnChanging(BookAttrColumn.Weight, this.entityData.Weight);
				this.entityData.Weight = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.Weight, this.entityData.Weight);
				OnPropertyChanged("Weight");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Pages property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Pages
		{
			get
			{
				return this.entityData.Pages; 
			}
			
			set
			{
				if (this.entityData.Pages == value)
					return;
				
                OnPropertyChanging("Pages");                    
				OnColumnChanging(BookAttrColumn.Pages, this.entityData.Pages);
				this.entityData.Pages = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.Pages, this.entityData.Pages);
				OnPropertyChanged("Pages");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Introinfo property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 1500)]
		public virtual System.String Introinfo
		{
			get
			{
				return this.entityData.Introinfo; 
			}
			
			set
			{
				if (this.entityData.Introinfo == value)
					return;
				
                OnPropertyChanging("Introinfo");                    
				OnColumnChanging(BookAttrColumn.Introinfo, this.entityData.Introinfo);
				this.entityData.Introinfo = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(BookAttrColumn.Introinfo, this.entityData.Introinfo);
				OnPropertyChanged("Introinfo");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("GoodsId", "Goods Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("GoodsId", "Goods Id", 6));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Author", "Author"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Author", "Author", 200));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Publish", "Publish"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Publish", "Publish", 200));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Translator", "Translator"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Translator", "Translator", 200));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Dimension", "Dimension"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Dimension", "Dimension", 100));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Introinfo", "Introinfo"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Introinfo", "Introinfo", 1500));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblBookAttr"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"goods_id", "author", "publish", "translator", "form_type", "language", "pl_month", "pl_year", "dimension", "weight", "pages", "introinfo"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as BookAttrEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (BookAttr) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<BookAttr>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as BookAttr);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed BookAttr Entity 
		///</summary>
		protected virtual BookAttr Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			BookAttr copy = new BookAttr();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.GoodsId = this.GoodsId;
					copy.OriginalGoodsId = this.OriginalGoodsId;
				copy.Author = this.Author;
				copy.Publish = this.Publish;
				copy.Translator = this.Translator;
				copy.FormType = this.FormType;
				copy.Language = this.Language;
				copy.PlMonth = this.PlMonth;
				copy.PlYear = this.PlYear;
				copy.Dimension = this.Dimension;
				copy.Weight = this.Weight;
				copy.Pages = this.Pages;
				copy.Introinfo = this.Introinfo;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed BookAttr Entity 
		///</summary>
		public virtual BookAttr Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed BookAttr Entity which is a deep copy of the current entity.
		///</summary>
		public virtual BookAttr DeepCopy()
		{
			return EntityHelper.Clone<BookAttr>(this as BookAttr);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as BookAttrEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new BookAttrEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as BookAttrEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(BookAttrColumn column)
		{
			switch(column)
			{
					case BookAttrColumn.GoodsId:
					return entityData.GoodsId != _originalData.GoodsId;
					case BookAttrColumn.Author:
					return entityData.Author != _originalData.Author;
					case BookAttrColumn.Publish:
					return entityData.Publish != _originalData.Publish;
					case BookAttrColumn.Translator:
					return entityData.Translator != _originalData.Translator;
					case BookAttrColumn.FormType:
					return entityData.FormType != _originalData.FormType;
					case BookAttrColumn.Language:
					return entityData.Language != _originalData.Language;
					case BookAttrColumn.PlMonth:
					return entityData.PlMonth != _originalData.PlMonth;
					case BookAttrColumn.PlYear:
					return entityData.PlYear != _originalData.PlYear;
					case BookAttrColumn.Dimension:
					return entityData.Dimension != _originalData.Dimension;
					case BookAttrColumn.Weight:
					return entityData.Weight != _originalData.Weight;
					case BookAttrColumn.Pages:
					return entityData.Pages != _originalData.Pages;
					case BookAttrColumn.Introinfo:
					return entityData.Introinfo != _originalData.Introinfo;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< BookAttrColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.GoodsId != _originalData.GoodsId;
			result = result || entityData.Author != _originalData.Author;
			result = result || entityData.Publish != _originalData.Publish;
			result = result || entityData.Translator != _originalData.Translator;
			result = result || entityData.FormType != _originalData.FormType;
			result = result || entityData.Language != _originalData.Language;
			result = result || entityData.PlMonth != _originalData.PlMonth;
			result = result || entityData.PlYear != _originalData.PlYear;
			result = result || entityData.Dimension != _originalData.Dimension;
			result = result || entityData.Weight != _originalData.Weight;
			result = result || entityData.Pages != _originalData.Pages;
			result = result || entityData.Introinfo != _originalData.Introinfo;
			return result;
		}	
		
		///<summary>
		///  Returns a BookAttr Entity with the original data.
		///</summary>
		public BookAttr GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateBookAttr(
				_originalData.GoodsId,
				_originalData.Author,
				_originalData.Publish,
				_originalData.Translator,
				_originalData.FormType,
				_originalData.Language,
				_originalData.PlMonth,
				_originalData.PlYear,
				_originalData.Dimension,
				_originalData.Weight,
				_originalData.Pages,
				_originalData.Introinfo
				);
				
			return (BookAttr)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="BookAttrBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is BookAttrBase)
				return ValueEquals(this, (BookAttrBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="BookAttrBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.GoodsId.GetHashCode() ^ 
					this.Author.GetHashCode() ^ 
					this.Publish.GetHashCode() ^ 
					this.Translator.GetHashCode() ^ 
					this.FormType.GetHashCode() ^ 
					this.Language.GetHashCode() ^ 
					this.PlMonth.GetHashCode() ^ 
					this.PlYear.GetHashCode() ^ 
					this.Dimension.GetHashCode() ^ 
					this.Weight.GetHashCode() ^ 
					this.Pages.GetHashCode() ^ 
					this.Introinfo.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="BookAttrBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(BookAttrBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="BookAttrBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="BookAttrBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="BookAttrBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(BookAttrBase Object1, BookAttrBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.GoodsId != Object2.GoodsId)
				equal = false;
			if (Object1.Author != Object2.Author)
				equal = false;
			if (Object1.Publish != Object2.Publish)
				equal = false;
			if (Object1.Translator != Object2.Translator)
				equal = false;
			if (Object1.FormType != Object2.FormType)
				equal = false;
			if (Object1.Language != Object2.Language)
				equal = false;
			if (Object1.PlMonth != Object2.PlMonth)
				equal = false;
			if (Object1.PlYear != Object2.PlYear)
				equal = false;
			if (Object1.Dimension != Object2.Dimension)
				equal = false;
			if (Object1.Weight != Object2.Weight)
				equal = false;
			if (Object1.Pages != Object2.Pages)
				equal = false;
			if (Object1.Introinfo != Object2.Introinfo)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((BookAttrBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static BookAttrComparer GetComparer()
        {
            return new BookAttrComparer();
        }
        */

        // Comparer delegates back to BookAttr
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(BookAttr rhs, BookAttrColumn which)
        {
            switch (which)
            {
            	
            	
            	case BookAttrColumn.GoodsId:
            		return this.GoodsId.CompareTo(rhs.GoodsId);
            		
            		                 
            	
            	
            	case BookAttrColumn.Author:
            		return this.Author.CompareTo(rhs.Author);
            		
            		                 
            	
            	
            	case BookAttrColumn.Publish:
            		return this.Publish.CompareTo(rhs.Publish);
            		
            		                 
            	
            	
            	case BookAttrColumn.Translator:
            		return this.Translator.CompareTo(rhs.Translator);
            		
            		                 
            	
            	
            	case BookAttrColumn.FormType:
            		return this.FormType.CompareTo(rhs.FormType);
            		
            		                 
            	
            	
            	case BookAttrColumn.Language:
            		return this.Language.CompareTo(rhs.Language);
            		
            		                 
            	
            	
            	case BookAttrColumn.PlMonth:
            		return this.PlMonth.CompareTo(rhs.PlMonth);
            		
            		                 
            	
            	
            	case BookAttrColumn.PlYear:
            		return this.PlYear.CompareTo(rhs.PlYear);
            		
            		                 
            	
            	
            	case BookAttrColumn.Dimension:
            		return this.Dimension.CompareTo(rhs.Dimension);
            		
            		                 
            	
            	
            	case BookAttrColumn.Weight:
            		return this.Weight.CompareTo(rhs.Weight);
            		
            		                 
            	
            	
            	case BookAttrColumn.Pages:
            		return this.Pages.CompareTo(rhs.Pages);
            		
            		                 
            	
            	
            	case BookAttrColumn.Introinfo:
            		return this.Introinfo.CompareTo(rhs.Introinfo);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<BookAttrKey> Members
		
		// member variable for the EntityId property
		private BookAttrKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual BookAttrKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new BookAttrKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("BookAttr")
					.Append("|").Append( this.GoodsId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{13}{12}- GoodsId: {0}{12}- Author: {1}{12}- Publish: {2}{12}- Translator: {3}{12}- FormType: {4}{12}- Language: {5}{12}- PlMonth: {6}{12}- PlYear: {7}{12}- Dimension: {8}{12}- Weight: {9}{12}- Pages: {10}{12}- Introinfo: {11}{12}{14}", 
				this.GoodsId,
				this.Author,
				this.Publish,
				this.Translator,
				this.FormType,
				this.Language,
				this.PlMonth,
				this.PlYear,
				this.Dimension,
				this.Weight,
				this.Pages,
				this.Introinfo,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblBookAttr' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class BookAttrEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// goods_id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblBookAttr"</remarks>
		public System.String GoodsId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.String OriginalGoodsId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// author : 
		/// </summary>
		public System.String Author = string.Empty;
		
		/// <summary>
		/// publish : 
		/// </summary>
		public System.String Publish = string.Empty;
		
		/// <summary>
		/// translator : 
		/// </summary>
		public System.String Translator = string.Empty;
		
		/// <summary>
		/// form_type : 
		/// </summary>
		public System.Int32 FormType = (int)0;
		
		/// <summary>
		/// language : 
		/// </summary>
		public System.Int32 Language = (int)0;
		
		/// <summary>
		/// pl_month : 
		/// </summary>
		public System.Int32 PlMonth = (int)0;
		
		/// <summary>
		/// pl_year : 
		/// </summary>
		public System.Int32 PlYear = (int)0;
		
		/// <summary>
		/// dimension : 
		/// </summary>
		public System.String Dimension = string.Empty;
		
		/// <summary>
		/// weight : 
		/// </summary>
		public System.Int32 Weight = (int)0;
		
		/// <summary>
		/// pages : 
		/// </summary>
		public System.Int32 Pages = (int)0;
		
		/// <summary>
		/// introinfo : 
		/// </summary>
		public System.String Introinfo = string.Empty;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			BookAttrEntityData _tmp = new BookAttrEntityData();
						
			_tmp.GoodsId = this.GoodsId;
			_tmp.OriginalGoodsId = this.OriginalGoodsId;
			
			_tmp.Author = this.Author;
			_tmp.Publish = this.Publish;
			_tmp.Translator = this.Translator;
			_tmp.FormType = this.FormType;
			_tmp.Language = this.Language;
			_tmp.PlMonth = this.PlMonth;
			_tmp.PlYear = this.PlYear;
			_tmp.Dimension = this.Dimension;
			_tmp.Weight = this.Weight;
			_tmp.Pages = this.Pages;
			_tmp.Introinfo = this.Introinfo;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			BookAttrEntityData _tmp = new BookAttrEntityData();
						
			_tmp.GoodsId = this.GoodsId;
			_tmp.OriginalGoodsId = this.OriginalGoodsId;
			
			_tmp.Author = this.Author;
			_tmp.Publish = this.Publish;
			_tmp.Translator = this.Translator;
			_tmp.FormType = this.FormType;
			_tmp.Language = this.Language;
			_tmp.PlMonth = this.PlMonth;
			_tmp.PlYear = this.PlYear;
			_tmp.Dimension = this.Dimension;
			_tmp.Weight = this.Weight;
			_tmp.Pages = this.Pages;
			_tmp.Introinfo = this.Introinfo;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BookAttrColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(BookAttrColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BookAttrColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(BookAttrColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BookAttrColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(BookAttrColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				BookAttrEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new BookAttrEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="BookAttrColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(BookAttrColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				BookAttrEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new BookAttrEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region BookAttrEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="BookAttr"/> object.
	/// </remarks>
	public class BookAttrEventArgs : System.EventArgs
	{
		private BookAttrColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the BookAttrEventArgs class.
		///</summary>
		public BookAttrEventArgs(BookAttrColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the BookAttrEventArgs class.
		///</summary>
		public BookAttrEventArgs(BookAttrColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The BookAttrColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="BookAttrColumn" />
		public BookAttrColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all BookAttr related events.
	///</summary>
	public delegate void BookAttrEventHandler(object sender, BookAttrEventArgs e);
	
	#region BookAttrComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class BookAttrComparer : System.Collections.Generic.IComparer<BookAttr>
	{
		BookAttrColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:BookAttrComparer"/> class.
        /// </summary>
		public BookAttrComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:BookAttrComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public BookAttrComparer(BookAttrColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="BookAttr"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="BookAttr"/> to compare.</param>
        /// <param name="b">The second <c>BookAttr</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(BookAttr a, BookAttr b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(BookAttr entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(BookAttr a, BookAttr b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public BookAttrColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region BookAttrKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="BookAttr"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class BookAttrKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the BookAttrKey class.
		/// </summary>
		public BookAttrKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the BookAttrKey class.
		/// </summary>
		public BookAttrKey(BookAttrBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.GoodsId = entity.GoodsId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the BookAttrKey class.
		/// </summary>
		public BookAttrKey(System.String _goodsId)
		{
			#region Init Properties

			this.GoodsId = _goodsId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private BookAttrBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public BookAttrBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the GoodsId property
		private System.String _goodsId;
		
		/// <summary>
		/// Gets or sets the GoodsId property.
		/// </summary>
		public System.String GoodsId
		{
			get { return _goodsId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.GoodsId = value;
				
				_goodsId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				GoodsId = ( values["GoodsId"] != null ) ? (System.String) EntityUtil.ChangeType(values["GoodsId"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("GoodsId", GoodsId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("GoodsId: {0}{1}",
								GoodsId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region BookAttrColumn Enum
	
	/// <summary>
	/// Enumerate the BookAttr columns.
	/// </summary>
	[Serializable]
	public enum BookAttrColumn : int
	{
		/// <summary>
		/// GoodsId : 
		/// </summary>
		[EnumTextValue("Goods Id")]
		[ColumnEnum("goods_id", typeof(System.String), System.Data.DbType.StringFixedLength, true, false, false, 6)]
		GoodsId = 1,
		/// <summary>
		/// Author : 
		/// </summary>
		[EnumTextValue("Author")]
		[ColumnEnum("author", typeof(System.String), System.Data.DbType.String, false, false, false, 200)]
		Author = 2,
		/// <summary>
		/// Publish : 
		/// </summary>
		[EnumTextValue("Publish")]
		[ColumnEnum("publish", typeof(System.String), System.Data.DbType.String, false, false, false, 200)]
		Publish = 3,
		/// <summary>
		/// Translator : 
		/// </summary>
		[EnumTextValue("Translator")]
		[ColumnEnum("translator", typeof(System.String), System.Data.DbType.String, false, false, false, 200)]
		Translator = 4,
		/// <summary>
		/// FormType : 
		/// </summary>
		[EnumTextValue("Form Type")]
		[ColumnEnum("form_type", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		FormType = 5,
		/// <summary>
		/// Language : 
		/// </summary>
		[EnumTextValue("Language")]
		[ColumnEnum("language", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Language = 6,
		/// <summary>
		/// PlMonth : 
		/// </summary>
		[EnumTextValue("Pl Month")]
		[ColumnEnum("pl_month", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		PlMonth = 7,
		/// <summary>
		/// PlYear : 
		/// </summary>
		[EnumTextValue("Pl Year")]
		[ColumnEnum("pl_year", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		PlYear = 8,
		/// <summary>
		/// Dimension : 
		/// </summary>
		[EnumTextValue("Dimension")]
		[ColumnEnum("dimension", typeof(System.String), System.Data.DbType.String, false, false, false, 100)]
		Dimension = 9,
		/// <summary>
		/// Weight : 
		/// </summary>
		[EnumTextValue("Weight")]
		[ColumnEnum("weight", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Weight = 10,
		/// <summary>
		/// Pages : 
		/// </summary>
		[EnumTextValue("Pages")]
		[ColumnEnum("pages", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Pages = 11,
		/// <summary>
		/// Introinfo : 
		/// </summary>
		[EnumTextValue("Introinfo")]
		[ColumnEnum("introinfo", typeof(System.String), System.Data.DbType.String, false, false, false, 1500)]
		Introinfo = 12
	}//End enum

	#endregion BookAttrColumn Enum

} // end namespace
