using System;
using System.ComponentModel;

namespace LibraryManagement.Domain
{
	/// <summary>
	///		The data structure representation of the 'tblLoanTran' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ILoanTran 
	{
		/// <summary>			
		/// trans_num : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblLoanTran"</remarks>
		System.String TransNum { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalTransNum { get; set; }
			
		/// <summary>			
		/// goods_id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblLoanTran"</remarks>
		System.String GoodsId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.String OriginalGoodsId { get; set; }
			
		
		
		/// <summary>
		/// tran_date : 
		/// </summary>
		System.DateTime?  TranDate  { get; set; }
		
		/// <summary>
		/// trans_code : 
		/// </summary>
		System.String  TransCode  { get; set; }
		
		/// <summary>
		/// tran_time : 
		/// </summary>
		System.String  TranTime  { get; set; }
		
		/// <summary>
		/// exp_id : 
		/// </summary>
		System.String  ExpId  { get; set; }
		
		/// <summary>
		/// cs_id : 
		/// </summary>
		System.String  CsId  { get; set; }
		
		/// <summary>
		/// qty : 
		/// </summary>
		System.Decimal?  Qty  { get; set; }
		
		/// <summary>
		/// due_date : 
		/// </summary>
		System.DateTime?  DueDate  { get; set; }
		
		/// <summary>
		/// user_id : 
		/// </summary>
		System.Decimal?  UserId  { get; set; }
		
		/// <summary>
		/// corr_tran : 
		/// </summary>
		System.String  CorrTran  { get; set; }
		
		/// <summary>
		/// remark : 
		/// </summary>
		System.String  Remark  { get; set; }
		
		/// <summary>
		/// status : 
		/// </summary>
		System.Boolean?  Status  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


