using System;
using System.ComponentModel;

namespace LibraryManagement.Domain
{
	/// <summary>
	///		The data structure representation of the 'tblMenus' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IMenus 
	{
		/// <summary>			
		/// id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblMenus"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// subitem : 
		/// </summary>
		System.Int32?  Subitem  { get; set; }
		
		/// <summary>
		/// parent : 
		/// </summary>
		System.Int32?  Parent  { get; set; }
		
		/// <summary>
		/// menukey : 
		/// </summary>
		System.String  Menukey  { get; set; }
		
		/// <summary>
		/// prompt : 
		/// </summary>
		System.String  Prompt  { get; set; }
		
		/// <summary>
		/// type : 
		/// </summary>
		System.String  Type  { get; set; }
		
		/// <summary>
		/// procerdue : 
		/// </summary>
		System.String  Procerdue  { get; set; }
		
		/// <summary>
		/// imageidx : 
		/// </summary>
		System.Int32?  Imageidx  { get; set; }
		
		/// <summary>
		/// password : 
		/// </summary>
		System.Boolean?  Password  { get; set; }
		
		/// <summary>
		/// basicright : 
		/// </summary>
		System.Int32?  Basicright  { get; set; }
		
		/// <summary>
		/// depcode : 
		/// </summary>
		System.String  Depcode  { get; set; }
		
		/// <summary>
		/// skip : 
		/// </summary>
		System.Boolean?  Skip  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


