
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file MercLocation.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using LibraryManagement.Domain.Validation;
#endregion

namespace LibraryManagement.Domain
{
	///<summary>
	/// An object representation of the 'tblMercLocation' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class MercLocationBase : EntityBase, IMercLocation, IEntityId<MercLocationKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private MercLocationEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private MercLocationEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private MercLocationEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<MercLocation> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MercLocationEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MercLocationEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="MercLocationBase"/> instance.
		///</summary>
		public MercLocationBase()
		{
			this.entityData = new MercLocationEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="MercLocationBase"/> instance.
		///</summary>
		///<param name="_stkId"></param>
		///<param name="_locId"></param>
		///<param name="_goodsId"></param>
		///<param name="_check"></param>
		public MercLocationBase(System.String _stkId, System.String _locId, System.String _goodsId, 
			System.Boolean _check)
		{
			this.entityData = new MercLocationEntityData();
			this.backupData = null;

			this.StkId = _stkId;
			this.LocId = _locId;
			this.GoodsId = _goodsId;
			this.Check = _check;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="MercLocation"/> instance.
		///</summary>
		///<param name="_stkId"></param>
		///<param name="_locId"></param>
		///<param name="_goodsId"></param>
		///<param name="_check"></param>
		public static MercLocation CreateMercLocation(System.String _stkId, System.String _locId, System.String _goodsId, 
			System.Boolean _check)
		{
			MercLocation newMercLocation = new MercLocation();
			newMercLocation.StkId = _stkId;
			newMercLocation.LocId = _locId;
			newMercLocation.GoodsId = _goodsId;
			newMercLocation.Check = _check;
			return newMercLocation;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Idx property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Decimal Idx
		{
			get
			{
				return this.entityData.Idx; 
			}
			
			set
			{
				if (this.entityData.Idx == value)
					return;
				
                OnPropertyChanging("Idx");                    
				OnColumnChanging(MercLocationColumn.Idx, this.entityData.Idx);
				this.entityData.Idx = value;
				this.EntityId.Idx = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MercLocationColumn.Idx, this.entityData.Idx);
				OnPropertyChanged("Idx");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the StkId property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 5)]
		public virtual System.String StkId
		{
			get
			{
				return this.entityData.StkId; 
			}
			
			set
			{
				if (this.entityData.StkId == value)
					return;
				
                OnPropertyChanging("StkId");                    
				OnColumnChanging(MercLocationColumn.StkId, this.entityData.StkId);
				this.entityData.StkId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MercLocationColumn.StkId, this.entityData.StkId);
				OnPropertyChanged("StkId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the LocId property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 4)]
		public virtual System.String LocId
		{
			get
			{
				return this.entityData.LocId; 
			}
			
			set
			{
				if (this.entityData.LocId == value)
					return;
				
                OnPropertyChanging("LocId");                    
				OnColumnChanging(MercLocationColumn.LocId, this.entityData.LocId);
				this.entityData.LocId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MercLocationColumn.LocId, this.entityData.LocId);
				OnPropertyChanged("LocId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the GoodsId property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 6)]
		public virtual System.String GoodsId
		{
			get
			{
				return this.entityData.GoodsId; 
			}
			
			set
			{
				if (this.entityData.GoodsId == value)
					return;
				
                OnPropertyChanging("GoodsId");                    
				OnColumnChanging(MercLocationColumn.GoodsId, this.entityData.GoodsId);
				this.entityData.GoodsId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MercLocationColumn.GoodsId, this.entityData.GoodsId);
				OnPropertyChanged("GoodsId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Check property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Boolean Check
		{
			get
			{
				return this.entityData.Check; 
			}
			
			set
			{
				if (this.entityData.Check == value)
					return;
				
                OnPropertyChanging("Check");                    
				OnColumnChanging(MercLocationColumn.Check, this.entityData.Check);
				this.entityData.Check = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MercLocationColumn.Check, this.entityData.Check);
				OnPropertyChanged("Check");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("StkId", "Stk Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("StkId", "Stk Id", 5));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("LocId", "Loc Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("LocId", "Loc Id", 4));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("GoodsId", "Goods Id"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("GoodsId", "Goods Id", 6));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblMercLocation"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"idx", "stk_id", "loc_id", "goods_id", "check"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as MercLocationEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (MercLocation) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<MercLocation>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as MercLocation);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed MercLocation Entity 
		///</summary>
		protected virtual MercLocation Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			MercLocation copy = new MercLocation();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Idx = this.Idx;
				copy.StkId = this.StkId;
				copy.LocId = this.LocId;
				copy.GoodsId = this.GoodsId;
				copy.Check = this.Check;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed MercLocation Entity 
		///</summary>
		public virtual MercLocation Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed MercLocation Entity which is a deep copy of the current entity.
		///</summary>
		public virtual MercLocation DeepCopy()
		{
			return EntityHelper.Clone<MercLocation>(this as MercLocation);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as MercLocationEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new MercLocationEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as MercLocationEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(MercLocationColumn column)
		{
			switch(column)
			{
					case MercLocationColumn.Idx:
					return entityData.Idx != _originalData.Idx;
					case MercLocationColumn.StkId:
					return entityData.StkId != _originalData.StkId;
					case MercLocationColumn.LocId:
					return entityData.LocId != _originalData.LocId;
					case MercLocationColumn.GoodsId:
					return entityData.GoodsId != _originalData.GoodsId;
					case MercLocationColumn.Check:
					return entityData.Check != _originalData.Check;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< MercLocationColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Idx != _originalData.Idx;
			result = result || entityData.StkId != _originalData.StkId;
			result = result || entityData.LocId != _originalData.LocId;
			result = result || entityData.GoodsId != _originalData.GoodsId;
			result = result || entityData.Check != _originalData.Check;
			return result;
		}	
		
		///<summary>
		///  Returns a MercLocation Entity with the original data.
		///</summary>
		public MercLocation GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateMercLocation(
				_originalData.StkId,
				_originalData.LocId,
				_originalData.GoodsId,
				_originalData.Check
				);
				
			return (MercLocation)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="MercLocationBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is MercLocationBase)
				return ValueEquals(this, (MercLocationBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="MercLocationBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Idx.GetHashCode() ^ 
					this.StkId.GetHashCode() ^ 
					this.LocId.GetHashCode() ^ 
					this.GoodsId.GetHashCode() ^ 
					this.Check.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="MercLocationBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(MercLocationBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="MercLocationBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="MercLocationBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="MercLocationBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(MercLocationBase Object1, MercLocationBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Idx != Object2.Idx)
				equal = false;
			if (Object1.StkId != Object2.StkId)
				equal = false;
			if (Object1.LocId != Object2.LocId)
				equal = false;
			if (Object1.GoodsId != Object2.GoodsId)
				equal = false;
			if (Object1.Check != Object2.Check)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((MercLocationBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static MercLocationComparer GetComparer()
        {
            return new MercLocationComparer();
        }
        */

        // Comparer delegates back to MercLocation
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(MercLocation rhs, MercLocationColumn which)
        {
            switch (which)
            {
            	
            	
            	case MercLocationColumn.Idx:
            		return this.Idx.CompareTo(rhs.Idx);
            		
            		                 
            	
            	
            	case MercLocationColumn.StkId:
            		return this.StkId.CompareTo(rhs.StkId);
            		
            		                 
            	
            	
            	case MercLocationColumn.LocId:
            		return this.LocId.CompareTo(rhs.LocId);
            		
            		                 
            	
            	
            	case MercLocationColumn.GoodsId:
            		return this.GoodsId.CompareTo(rhs.GoodsId);
            		
            		                 
            	
            	
            	case MercLocationColumn.Check:
            		return this.Check.CompareTo(rhs.Check);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<MercLocationKey> Members
		
		// member variable for the EntityId property
		private MercLocationKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual MercLocationKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new MercLocationKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("MercLocation")
					.Append("|").Append( this.Idx.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- Idx: {0}{5}- StkId: {1}{5}- LocId: {2}{5}- GoodsId: {3}{5}- Check: {4}{5}{7}", 
				this.Idx,
				this.StkId,
				this.LocId,
				this.GoodsId,
				this.Check,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblMercLocation' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class MercLocationEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// idx : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblMercLocation"</remarks>
		public System.Decimal Idx;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// stk_id : 
		/// </summary>
		public System.String StkId = string.Empty;
		
		/// <summary>
		/// loc_id : 
		/// </summary>
		public System.String LocId = string.Empty;
		
		/// <summary>
		/// goods_id : 
		/// </summary>
		public System.String GoodsId = string.Empty;
		
		/// <summary>
		/// check : 
		/// </summary>
		public System.Boolean Check = true;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			MercLocationEntityData _tmp = new MercLocationEntityData();
						
			_tmp.Idx = this.Idx;
			
			_tmp.StkId = this.StkId;
			_tmp.LocId = this.LocId;
			_tmp.GoodsId = this.GoodsId;
			_tmp.Check = this.Check;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			MercLocationEntityData _tmp = new MercLocationEntityData();
						
			_tmp.Idx = this.Idx;
			
			_tmp.StkId = this.StkId;
			_tmp.LocId = this.LocId;
			_tmp.GoodsId = this.GoodsId;
			_tmp.Check = this.Check;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MercLocationColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(MercLocationColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MercLocationColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(MercLocationColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MercLocationColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(MercLocationColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				MercLocationEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new MercLocationEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MercLocationColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(MercLocationColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				MercLocationEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new MercLocationEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region MercLocationEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="MercLocation"/> object.
	/// </remarks>
	public class MercLocationEventArgs : System.EventArgs
	{
		private MercLocationColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the MercLocationEventArgs class.
		///</summary>
		public MercLocationEventArgs(MercLocationColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the MercLocationEventArgs class.
		///</summary>
		public MercLocationEventArgs(MercLocationColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The MercLocationColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="MercLocationColumn" />
		public MercLocationColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all MercLocation related events.
	///</summary>
	public delegate void MercLocationEventHandler(object sender, MercLocationEventArgs e);
	
	#region MercLocationComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class MercLocationComparer : System.Collections.Generic.IComparer<MercLocation>
	{
		MercLocationColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:MercLocationComparer"/> class.
        /// </summary>
		public MercLocationComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:MercLocationComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public MercLocationComparer(MercLocationColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="MercLocation"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="MercLocation"/> to compare.</param>
        /// <param name="b">The second <c>MercLocation</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(MercLocation a, MercLocation b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(MercLocation entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(MercLocation a, MercLocation b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public MercLocationColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region MercLocationKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="MercLocation"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class MercLocationKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the MercLocationKey class.
		/// </summary>
		public MercLocationKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the MercLocationKey class.
		/// </summary>
		public MercLocationKey(MercLocationBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Idx = entity.Idx;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the MercLocationKey class.
		/// </summary>
		public MercLocationKey(System.Decimal _idx)
		{
			#region Init Properties

			this.Idx = _idx;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private MercLocationBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public MercLocationBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Idx property
		private System.Decimal _idx;
		
		/// <summary>
		/// Gets or sets the Idx property.
		/// </summary>
		public System.Decimal Idx
		{
			get { return _idx; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Idx = value;
				
				_idx = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Idx = ( values["Idx"] != null ) ? (System.Decimal) EntityUtil.ChangeType(values["Idx"], typeof(System.Decimal)) : 0.0m;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Idx", Idx);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Idx: {0}{1}",
								Idx,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region MercLocationColumn Enum
	
	/// <summary>
	/// Enumerate the MercLocation columns.
	/// </summary>
	[Serializable]
	public enum MercLocationColumn : int
	{
		/// <summary>
		/// Idx : 
		/// </summary>
		[EnumTextValue("Idx")]
		[ColumnEnum("idx", typeof(System.Decimal), System.Data.DbType.Decimal, true, true, false)]
		Idx = 1,
		/// <summary>
		/// StkId : 
		/// </summary>
		[EnumTextValue("Stk Id")]
		[ColumnEnum("stk_id", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, false, 5)]
		StkId = 2,
		/// <summary>
		/// LocId : 
		/// </summary>
		[EnumTextValue("Loc Id")]
		[ColumnEnum("loc_id", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, false, 4)]
		LocId = 3,
		/// <summary>
		/// GoodsId : 
		/// </summary>
		[EnumTextValue("Goods Id")]
		[ColumnEnum("goods_id", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, false, 6)]
		GoodsId = 4,
		/// <summary>
		/// Check : 
		/// </summary>
		[EnumTextValue("Check")]
		[ColumnEnum("check", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, false)]
		Check = 5
	}//End enum

	#endregion MercLocationColumn Enum

} // end namespace
