
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file Trcode.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using LibraryManagement.Domain.Validation;
#endregion

namespace LibraryManagement.Domain
{
	///<summary>
	/// An object representation of the 'tblTrcode' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class TrcodeBase : EntityBase, ITrcode, IEntityId<TrcodeKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private TrcodeEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private TrcodeEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private TrcodeEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Trcode> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TrcodeEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event TrcodeEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="TrcodeBase"/> instance.
		///</summary>
		public TrcodeBase()
		{
			this.entityData = new TrcodeEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="TrcodeBase"/> instance.
		///</summary>
		///<param name="_trCode"></param>
		///<param name="_trName"></param>
		///<param name="_description"></param>
		///<param name="_trDepart"></param>
		///<param name="_frmCaption"></param>
		///<param name="_voucherFile"></param>
		///<param name="_voucherFile1"></param>
		///<param name="_voucherFile2"></param>
		///<param name="_status"></param>
		public TrcodeBase(System.String _trCode, System.String _trName, System.String _description, 
			System.String _trDepart, System.String _frmCaption, System.String _voucherFile, System.String _voucherFile1, 
			System.String _voucherFile2, System.Boolean? _status)
		{
			this.entityData = new TrcodeEntityData();
			this.backupData = null;

			this.TrCode = _trCode;
			this.TrName = _trName;
			this.Description = _description;
			this.TrDepart = _trDepart;
			this.FrmCaption = _frmCaption;
			this.VoucherFile = _voucherFile;
			this.VoucherFile1 = _voucherFile1;
			this.VoucherFile2 = _voucherFile2;
			this.Status = _status;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Trcode"/> instance.
		///</summary>
		///<param name="_trCode"></param>
		///<param name="_trName"></param>
		///<param name="_description"></param>
		///<param name="_trDepart"></param>
		///<param name="_frmCaption"></param>
		///<param name="_voucherFile"></param>
		///<param name="_voucherFile1"></param>
		///<param name="_voucherFile2"></param>
		///<param name="_status"></param>
		public static Trcode CreateTrcode(System.String _trCode, System.String _trName, System.String _description, 
			System.String _trDepart, System.String _frmCaption, System.String _voucherFile, System.String _voucherFile1, 
			System.String _voucherFile2, System.Boolean? _status)
		{
			Trcode newTrcode = new Trcode();
			newTrcode.TrCode = _trCode;
			newTrcode.TrName = _trName;
			newTrcode.Description = _description;
			newTrcode.TrDepart = _trDepart;
			newTrcode.FrmCaption = _frmCaption;
			newTrcode.VoucherFile = _voucherFile;
			newTrcode.VoucherFile1 = _voucherFile1;
			newTrcode.VoucherFile2 = _voucherFile2;
			newTrcode.Status = _status;
			return newTrcode;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the TrCode property. 
		///		
		/// </summary>
		/// <value>This type is char.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false, 2)]
		public virtual System.String TrCode
		{
			get
			{
				return this.entityData.TrCode; 
			}
			
			set
			{
				if (this.entityData.TrCode == value)
					return;
				
                OnPropertyChanging("TrCode");                    
				OnColumnChanging(TrcodeColumn.TrCode, this.entityData.TrCode);
				this.entityData.TrCode = value;
				this.EntityId.TrCode = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.TrCode, this.entityData.TrCode);
				OnPropertyChanged("TrCode");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the trCode property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the trCode property.</remarks>
		/// <value>This type is char</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.String OriginalTrCode
		{
			get { return this.entityData.OriginalTrCode; }
			set { this.entityData.OriginalTrCode = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the TrName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 200)]
		public virtual System.String TrName
		{
			get
			{
				return this.entityData.TrName; 
			}
			
			set
			{
				if (this.entityData.TrName == value)
					return;
				
                OnPropertyChanging("TrName");                    
				OnColumnChanging(TrcodeColumn.TrName, this.entityData.TrName);
				this.entityData.TrName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.TrName, this.entityData.TrName);
				OnPropertyChanged("TrName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
				
                OnPropertyChanging("Description");                    
				OnColumnChanging(TrcodeColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TrDepart property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1)]
		public virtual System.String TrDepart
		{
			get
			{
				return this.entityData.TrDepart; 
			}
			
			set
			{
				if (this.entityData.TrDepart == value)
					return;
				
                OnPropertyChanging("TrDepart");                    
				OnColumnChanging(TrcodeColumn.TrDepart, this.entityData.TrDepart);
				this.entityData.TrDepart = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.TrDepart, this.entityData.TrDepart);
				OnPropertyChanged("TrDepart");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FrmCaption property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String FrmCaption
		{
			get
			{
				return this.entityData.FrmCaption; 
			}
			
			set
			{
				if (this.entityData.FrmCaption == value)
					return;
				
                OnPropertyChanging("FrmCaption");                    
				OnColumnChanging(TrcodeColumn.FrmCaption, this.entityData.FrmCaption);
				this.entityData.FrmCaption = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.FrmCaption, this.entityData.FrmCaption);
				OnPropertyChanged("FrmCaption");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the VoucherFile property. 
		///		
		/// </summary>
		/// <value>This type is char.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String VoucherFile
		{
			get
			{
				return this.entityData.VoucherFile; 
			}
			
			set
			{
				if (this.entityData.VoucherFile == value)
					return;
				
                OnPropertyChanging("VoucherFile");                    
				OnColumnChanging(TrcodeColumn.VoucherFile, this.entityData.VoucherFile);
				this.entityData.VoucherFile = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.VoucherFile, this.entityData.VoucherFile);
				OnPropertyChanged("VoucherFile");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the VoucherFile1 property. 
		///		
		/// </summary>
		/// <value>This type is char.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String VoucherFile1
		{
			get
			{
				return this.entityData.VoucherFile1; 
			}
			
			set
			{
				if (this.entityData.VoucherFile1 == value)
					return;
				
                OnPropertyChanging("VoucherFile1");                    
				OnColumnChanging(TrcodeColumn.VoucherFile1, this.entityData.VoucherFile1);
				this.entityData.VoucherFile1 = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.VoucherFile1, this.entityData.VoucherFile1);
				OnPropertyChanged("VoucherFile1");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the VoucherFile2 property. 
		///		
		/// </summary>
		/// <value>This type is char.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 20)]
		public virtual System.String VoucherFile2
		{
			get
			{
				return this.entityData.VoucherFile2; 
			}
			
			set
			{
				if (this.entityData.VoucherFile2 == value)
					return;
				
                OnPropertyChanging("VoucherFile2");                    
				OnColumnChanging(TrcodeColumn.VoucherFile2, this.entityData.VoucherFile2);
				this.entityData.VoucherFile2 = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.VoucherFile2, this.entityData.VoucherFile2);
				OnPropertyChanged("VoucherFile2");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Status property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? Status
		{
			get
			{
				return this.entityData.Status; 
			}
			
			set
			{
				if (this.entityData.Status == value)
					return;
				
                OnPropertyChanging("Status");                    
				OnColumnChanging(TrcodeColumn.Status, this.entityData.Status);
				this.entityData.Status = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(TrcodeColumn.Status, this.entityData.Status);
				OnPropertyChanged("Status");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("TrCode", "Tr Code"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TrCode", "Tr Code", 2));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TrName", "Tr Name", 200));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Description", "Description"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("TrDepart", "Tr Depart", 1));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("FrmCaption", "Frm Caption", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("VoucherFile", "Voucher File", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("VoucherFile1", "Voucher File1", 20));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("VoucherFile2", "Voucher File2", 20));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblTrcode"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"trCode", "trName", "description", "trDepart", "frmCaption", "voucherFile", "voucherFile1", "voucherFile2", "Status"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as TrcodeEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Trcode) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Trcode>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Trcode);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Trcode Entity 
		///</summary>
		protected virtual Trcode Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Trcode copy = new Trcode();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.TrCode = this.TrCode;
					copy.OriginalTrCode = this.OriginalTrCode;
				copy.TrName = this.TrName;
				copy.Description = this.Description;
				copy.TrDepart = this.TrDepart;
				copy.FrmCaption = this.FrmCaption;
				copy.VoucherFile = this.VoucherFile;
				copy.VoucherFile1 = this.VoucherFile1;
				copy.VoucherFile2 = this.VoucherFile2;
				copy.Status = this.Status;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Trcode Entity 
		///</summary>
		public virtual Trcode Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Trcode Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Trcode DeepCopy()
		{
			return EntityHelper.Clone<Trcode>(this as Trcode);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as TrcodeEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new TrcodeEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as TrcodeEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(TrcodeColumn column)
		{
			switch(column)
			{
					case TrcodeColumn.TrCode:
					return entityData.TrCode != _originalData.TrCode;
					case TrcodeColumn.TrName:
					return entityData.TrName != _originalData.TrName;
					case TrcodeColumn.Description:
					return entityData.Description != _originalData.Description;
					case TrcodeColumn.TrDepart:
					return entityData.TrDepart != _originalData.TrDepart;
					case TrcodeColumn.FrmCaption:
					return entityData.FrmCaption != _originalData.FrmCaption;
					case TrcodeColumn.VoucherFile:
					return entityData.VoucherFile != _originalData.VoucherFile;
					case TrcodeColumn.VoucherFile1:
					return entityData.VoucherFile1 != _originalData.VoucherFile1;
					case TrcodeColumn.VoucherFile2:
					return entityData.VoucherFile2 != _originalData.VoucherFile2;
					case TrcodeColumn.Status:
					return entityData.Status != _originalData.Status;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< TrcodeColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.TrCode != _originalData.TrCode;
			result = result || entityData.TrName != _originalData.TrName;
			result = result || entityData.Description != _originalData.Description;
			result = result || entityData.TrDepart != _originalData.TrDepart;
			result = result || entityData.FrmCaption != _originalData.FrmCaption;
			result = result || entityData.VoucherFile != _originalData.VoucherFile;
			result = result || entityData.VoucherFile1 != _originalData.VoucherFile1;
			result = result || entityData.VoucherFile2 != _originalData.VoucherFile2;
			result = result || entityData.Status != _originalData.Status;
			return result;
		}	
		
		///<summary>
		///  Returns a Trcode Entity with the original data.
		///</summary>
		public Trcode GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateTrcode(
				_originalData.TrCode,
				_originalData.TrName,
				_originalData.Description,
				_originalData.TrDepart,
				_originalData.FrmCaption,
				_originalData.VoucherFile,
				_originalData.VoucherFile1,
				_originalData.VoucherFile2,
				_originalData.Status
				);
				
			return (Trcode)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="TrcodeBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is TrcodeBase)
				return ValueEquals(this, (TrcodeBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="TrcodeBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.TrCode.GetHashCode() ^ 
					((this.TrName == null) ? string.Empty : this.TrName.ToString()).GetHashCode() ^ 
					this.Description.GetHashCode() ^ 
					((this.TrDepart == null) ? string.Empty : this.TrDepart.ToString()).GetHashCode() ^ 
					((this.FrmCaption == null) ? string.Empty : this.FrmCaption.ToString()).GetHashCode() ^ 
					((this.VoucherFile == null) ? string.Empty : this.VoucherFile.ToString()).GetHashCode() ^ 
					((this.VoucherFile1 == null) ? string.Empty : this.VoucherFile1.ToString()).GetHashCode() ^ 
					((this.VoucherFile2 == null) ? string.Empty : this.VoucherFile2.ToString()).GetHashCode() ^ 
					((this.Status == null) ? string.Empty : this.Status.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="TrcodeBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(TrcodeBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="TrcodeBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="TrcodeBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="TrcodeBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(TrcodeBase Object1, TrcodeBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.TrCode != Object2.TrCode)
				equal = false;
			if ( Object1.TrName != null && Object2.TrName != null )
			{
				if (Object1.TrName != Object2.TrName)
					equal = false;
			}
			else if (Object1.TrName == null ^ Object2.TrName == null )
			{
				equal = false;
			}
			if (Object1.Description != Object2.Description)
				equal = false;
			if ( Object1.TrDepart != null && Object2.TrDepart != null )
			{
				if (Object1.TrDepart != Object2.TrDepart)
					equal = false;
			}
			else if (Object1.TrDepart == null ^ Object2.TrDepart == null )
			{
				equal = false;
			}
			if ( Object1.FrmCaption != null && Object2.FrmCaption != null )
			{
				if (Object1.FrmCaption != Object2.FrmCaption)
					equal = false;
			}
			else if (Object1.FrmCaption == null ^ Object2.FrmCaption == null )
			{
				equal = false;
			}
			if ( Object1.VoucherFile != null && Object2.VoucherFile != null )
			{
				if (Object1.VoucherFile != Object2.VoucherFile)
					equal = false;
			}
			else if (Object1.VoucherFile == null ^ Object2.VoucherFile == null )
			{
				equal = false;
			}
			if ( Object1.VoucherFile1 != null && Object2.VoucherFile1 != null )
			{
				if (Object1.VoucherFile1 != Object2.VoucherFile1)
					equal = false;
			}
			else if (Object1.VoucherFile1 == null ^ Object2.VoucherFile1 == null )
			{
				equal = false;
			}
			if ( Object1.VoucherFile2 != null && Object2.VoucherFile2 != null )
			{
				if (Object1.VoucherFile2 != Object2.VoucherFile2)
					equal = false;
			}
			else if (Object1.VoucherFile2 == null ^ Object2.VoucherFile2 == null )
			{
				equal = false;
			}
			if ( Object1.Status != null && Object2.Status != null )
			{
				if (Object1.Status != Object2.Status)
					equal = false;
			}
			else if (Object1.Status == null ^ Object2.Status == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((TrcodeBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static TrcodeComparer GetComparer()
        {
            return new TrcodeComparer();
        }
        */

        // Comparer delegates back to Trcode
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Trcode rhs, TrcodeColumn which)
        {
            switch (which)
            {
            	
            	
            	case TrcodeColumn.TrCode:
            		return this.TrCode.CompareTo(rhs.TrCode);
            		
            		                 
            	
            	
            	case TrcodeColumn.TrName:
            		return this.TrName.CompareTo(rhs.TrName);
            		
            		                 
            	
            	
            	case TrcodeColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            	
            	
            	case TrcodeColumn.TrDepart:
            		return this.TrDepart.CompareTo(rhs.TrDepart);
            		
            		                 
            	
            	
            	case TrcodeColumn.FrmCaption:
            		return this.FrmCaption.CompareTo(rhs.FrmCaption);
            		
            		                 
            	
            	
            	case TrcodeColumn.VoucherFile:
            		return this.VoucherFile.CompareTo(rhs.VoucherFile);
            		
            		                 
            	
            	
            	case TrcodeColumn.VoucherFile1:
            		return this.VoucherFile1.CompareTo(rhs.VoucherFile1);
            		
            		                 
            	
            	
            	case TrcodeColumn.VoucherFile2:
            		return this.VoucherFile2.CompareTo(rhs.VoucherFile2);
            		
            		                 
            	
            	
            	case TrcodeColumn.Status:
            		return this.Status.Value.CompareTo(rhs.Status.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<TrcodeKey> Members
		
		// member variable for the EntityId property
		private TrcodeKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual TrcodeKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new TrcodeKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Trcode")
					.Append("|").Append( this.TrCode.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{10}{9}- TrCode: {0}{9}- TrName: {1}{9}- Description: {2}{9}- TrDepart: {3}{9}- FrmCaption: {4}{9}- VoucherFile: {5}{9}- VoucherFile1: {6}{9}- VoucherFile2: {7}{9}- Status: {8}{9}{11}", 
				this.TrCode,
				(this.TrName == null) ? string.Empty : this.TrName.ToString(),
				this.Description,
				(this.TrDepart == null) ? string.Empty : this.TrDepart.ToString(),
				(this.FrmCaption == null) ? string.Empty : this.FrmCaption.ToString(),
				(this.VoucherFile == null) ? string.Empty : this.VoucherFile.ToString(),
				(this.VoucherFile1 == null) ? string.Empty : this.VoucherFile1.ToString(),
				(this.VoucherFile2 == null) ? string.Empty : this.VoucherFile2.ToString(),
				(this.Status == null) ? string.Empty : this.Status.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblTrcode' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class TrcodeEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// trCode : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblTrcode"</remarks>
		public System.String TrCode;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.String OriginalTrCode;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// trName : 
		/// </summary>
		public System.String TrName = null;
		
		/// <summary>
		/// description : 
		/// </summary>
		public System.String Description = string.Empty;
		
		/// <summary>
		/// trDepart : 
		/// </summary>
		public System.String TrDepart = null;
		
		/// <summary>
		/// frmCaption : 
		/// </summary>
		public System.String FrmCaption = null;
		
		/// <summary>
		/// voucherFile : 
		/// </summary>
		public System.String VoucherFile = null;
		
		/// <summary>
		/// voucherFile1 : 
		/// </summary>
		public System.String VoucherFile1 = null;
		
		/// <summary>
		/// voucherFile2 : 
		/// </summary>
		public System.String VoucherFile2 = null;
		
		/// <summary>
		/// Status : 
		/// </summary>
		public System.Boolean? Status = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			TrcodeEntityData _tmp = new TrcodeEntityData();
						
			_tmp.TrCode = this.TrCode;
			_tmp.OriginalTrCode = this.OriginalTrCode;
			
			_tmp.TrName = this.TrName;
			_tmp.Description = this.Description;
			_tmp.TrDepart = this.TrDepart;
			_tmp.FrmCaption = this.FrmCaption;
			_tmp.VoucherFile = this.VoucherFile;
			_tmp.VoucherFile1 = this.VoucherFile1;
			_tmp.VoucherFile2 = this.VoucherFile2;
			_tmp.Status = this.Status;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			TrcodeEntityData _tmp = new TrcodeEntityData();
						
			_tmp.TrCode = this.TrCode;
			_tmp.OriginalTrCode = this.OriginalTrCode;
			
			_tmp.TrName = this.TrName;
			_tmp.Description = this.Description;
			_tmp.TrDepart = this.TrDepart;
			_tmp.FrmCaption = this.FrmCaption;
			_tmp.VoucherFile = this.VoucherFile;
			_tmp.VoucherFile1 = this.VoucherFile1;
			_tmp.VoucherFile2 = this.VoucherFile2;
			_tmp.Status = this.Status;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TrcodeColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(TrcodeColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TrcodeColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(TrcodeColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TrcodeColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(TrcodeColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				TrcodeEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new TrcodeEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="TrcodeColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(TrcodeColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				TrcodeEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new TrcodeEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region TrcodeEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Trcode"/> object.
	/// </remarks>
	public class TrcodeEventArgs : System.EventArgs
	{
		private TrcodeColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the TrcodeEventArgs class.
		///</summary>
		public TrcodeEventArgs(TrcodeColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the TrcodeEventArgs class.
		///</summary>
		public TrcodeEventArgs(TrcodeColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The TrcodeColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="TrcodeColumn" />
		public TrcodeColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Trcode related events.
	///</summary>
	public delegate void TrcodeEventHandler(object sender, TrcodeEventArgs e);
	
	#region TrcodeComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class TrcodeComparer : System.Collections.Generic.IComparer<Trcode>
	{
		TrcodeColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:TrcodeComparer"/> class.
        /// </summary>
		public TrcodeComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:TrcodeComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public TrcodeComparer(TrcodeColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Trcode"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Trcode"/> to compare.</param>
        /// <param name="b">The second <c>Trcode</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Trcode a, Trcode b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Trcode entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Trcode a, Trcode b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public TrcodeColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region TrcodeKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Trcode"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class TrcodeKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the TrcodeKey class.
		/// </summary>
		public TrcodeKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the TrcodeKey class.
		/// </summary>
		public TrcodeKey(TrcodeBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.TrCode = entity.TrCode;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the TrcodeKey class.
		/// </summary>
		public TrcodeKey(System.String _trCode)
		{
			#region Init Properties

			this.TrCode = _trCode;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private TrcodeBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public TrcodeBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the TrCode property
		private System.String _trCode;
		
		/// <summary>
		/// Gets or sets the TrCode property.
		/// </summary>
		public System.String TrCode
		{
			get { return _trCode; }
			set
			{
				if ( this.Entity != null )
					this.Entity.TrCode = value;
				
				_trCode = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				TrCode = ( values["TrCode"] != null ) ? (System.String) EntityUtil.ChangeType(values["TrCode"], typeof(System.String)) : string.Empty;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("TrCode", TrCode);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("TrCode: {0}{1}",
								TrCode,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region TrcodeColumn Enum
	
	/// <summary>
	/// Enumerate the Trcode columns.
	/// </summary>
	[Serializable]
	public enum TrcodeColumn : int
	{
		/// <summary>
		/// TrCode : 
		/// </summary>
		[EnumTextValue("Tr Code")]
		[ColumnEnum("trCode", typeof(System.String), System.Data.DbType.AnsiStringFixedLength, true, false, false, 2)]
		TrCode = 1,
		/// <summary>
		/// TrName : 
		/// </summary>
		[EnumTextValue("Tr Name")]
		[ColumnEnum("trName", typeof(System.String), System.Data.DbType.String, false, false, true, 200)]
		TrName = 2,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("description", typeof(System.String), System.Data.DbType.String, false, false, false)]
		Description = 3,
		/// <summary>
		/// TrDepart : 
		/// </summary>
		[EnumTextValue("Tr Depart")]
		[ColumnEnum("trDepart", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, true, 1)]
		TrDepart = 4,
		/// <summary>
		/// FrmCaption : 
		/// </summary>
		[EnumTextValue("Frm Caption")]
		[ColumnEnum("frmCaption", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		FrmCaption = 5,
		/// <summary>
		/// VoucherFile : 
		/// </summary>
		[EnumTextValue("Voucher File")]
		[ColumnEnum("voucherFile", typeof(System.String), System.Data.DbType.AnsiStringFixedLength, false, false, true, 20)]
		VoucherFile = 6,
		/// <summary>
		/// VoucherFile1 : 
		/// </summary>
		[EnumTextValue("Voucher File1")]
		[ColumnEnum("voucherFile1", typeof(System.String), System.Data.DbType.AnsiStringFixedLength, false, false, true, 20)]
		VoucherFile1 = 7,
		/// <summary>
		/// VoucherFile2 : 
		/// </summary>
		[EnumTextValue("Voucher File2")]
		[ColumnEnum("voucherFile2", typeof(System.String), System.Data.DbType.AnsiStringFixedLength, false, false, true, 20)]
		VoucherFile2 = 8,
		/// <summary>
		/// Status : 
		/// </summary>
		[EnumTextValue("Status")]
		[ColumnEnum("Status", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		Status = 9
	}//End enum

	#endregion TrcodeColumn Enum

} // end namespace
